(() => {
  'use strict';
  const model=globalThis.ExtLinkSubmissionJournal;
  const box=document.createElement('section');box.className='submission-journal';box.id='submission-journal';
  box.innerHTML='<h2>我的站点 · 外链总览</h2><p>按产品查看所有批次。提交、站方审核、回复和外链核验分别登记。</p><div class="journal-controls"><select id="journal-profile" aria-label="我的站点"></select><input id="journal-search" placeholder="搜索目标站或阻塞原因"><select id="journal-filter" aria-label="进度筛选"><option value="">全部进度</option><option value="received">明确收件</option><option value="pending_moderation">待审核</option><option value="unknown">提交结果未知</option><option value="not_submitted">未提交待处理</option><option value="pending">尚未执行</option><option value="sync">待同步</option><option value="replied">有回复</option><option value="verified">外链已核验</option></select><button id="journal-refresh">从云端刷新</button><button id="journal-recover">将本机最新资料恢复到 D1</button><button id="journal-export">导出逐站明细</button></div><p id="journal-status" role="status"></p><details class="journal-profile"><summary>查看本站资料与截图</summary><div id="journal-profile-details"></div></details><p id="journal-count"></p><div class="journal-scroll"><table><thead><tr><th>目标站</th><th>提交进度</th><th>站方审核</th><th>邮件/站方回复</th><th>外链有效性</th><th>同步 / 详情</th></tr></thead><tbody id="journal-rows"></tbody></table></div><div id="journal-details" class="journal-detail" hidden></div>';
  (document.querySelector('.page-head')||document.body.firstElementChild).after(box);
  const $=id=>document.getElementById('journal-'+id),el=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
  const labels={historical_unverified:'历史登记 · 待核对',received:'站方明确收件',historical_receipt:'历史收件登记',unknown:'未知 / 未核验',not_submitted:'未提交 · 待处理',pending:'待执行',rejected:'站方拒绝',pending_moderation:'待审核',published:'已发布',reported_published:'已登记发布 · 外链未实测',unverified:'未核验',verified:'有外链核验证据',link_missing:'核验未找到外链',unreachable:'页面不可访问'};
  let storage={},localTasks=[],cloudTasks=[],cloudDocuments={},localTotal=null,rows=[],cacheIdentity='',selected='',profileRenderKey='',detailVersion=0;
  const send=async msg=>{const r=await chrome.runtime.sendMessage(msg);if(!r?.ok)throw new Error(r?.error||'请求失败');return r;};
  function identity(config={}){return String(config.endpoint||'')+'|'+String(config.workspaceId||'default');}
  function link(url,label){const a=el('a',label||url);try{const u=new URL(url);if(!['https:','http:'].includes(u.protocol))return el('span',label||url);a.href=u.href;a.target='_blank';a.rel='noopener noreferrer';}catch{return el('span',label||url);}return a;}
  async function load(){storage=await chrome.storage.local.get(['siteProfiles','activeSiteId','submissionRecords','submissionTimeline','cloudSyncConfig','cloudSyncPendingKeys','submissionJournalCache','d1JournalPending']);const nextIdentity=identity(storage.cloudSyncConfig);if(cacheIdentity&&nextIdentity!==cacheIdentity){localTasks=[];localTotal=null;selected='';detailVersion++;$('details').hidden=true;}cacheIdentity=nextIdentity;const cache=storage.submissionJournalCache;if(cache?.identity===cacheIdentity){cloudTasks=cache.tasks||[];cloudDocuments=cache.documents||{};}else{cloudTasks=[];cloudDocuments={};}selected=selected||storage.activeSiteId||'';render();$('status').textContent=(cache?.identity===cacheIdentity?'D1 云端记录缓存时间：'+cache.at:'尚未刷新 D1 云端记录')+'。恢复副本不代表旧队列已处理或投稿成功。';}
  function mergedDocument(key){const local=storage[key]||{},remote=cloudDocuments[key]||{};const pending=storage.cloudSyncPendingKeys||[];const localWins=storage.cloudSyncConfig?.storageBackend!=='d1'||(Array.isArray(pending)?pending.includes(key):!!pending[key]);return localWins?{...remote,...local}:{...local,...remote};}
  function profiles(){return mergedDocument('siteProfiles');}
  function mergedTasks(){const map=new Map(cloudTasks.map(t=>[t.id,{...t,source:'cloud'}]));for(const t of localTasks)if(t.syncStatus!=='confirmed'||!map.has(t.id))map.set(t.id,{...t,source:'local'});return [...map.values()];}
  function render(){
    const timeline={...(cloudDocuments.submissionTimeline||{})};for(const [key,events]of Object.entries(storage.submissionTimeline||{}))if(Array.isArray(events))timeline[key]=[...new Map([...(timeline[key]||[]),...events].map(e=>[e.id,e])).values()];
    for(const item of storage.d1JournalPending||[])if(item.scope===cacheIdentity){const e={...item.event,_pending:true},key=e.destinationKey+'::'+e.profileId;timeline[key]=[...(timeline[key]||[]).filter(v=>v.id!==e.id),e];}
    rows=model.build({tasks:mergedTasks(),records:mergedDocument('submissionRecords'),timeline,historicalRecords:cloudDocuments.historicalRecords||{}});
    const profileMap=profiles(),ids=[...new Set([...Object.keys(profileMap),...rows.map(r=>r.profileId)])];$('profile').replaceChildren();for(const id of ids){const o=el('option',profileMap[id]?.name||id);o.value=id;$('profile').append(o);}if(!ids.includes(selected))selected=ids[0]||'';$('profile').value=selected;
    const query=$('search').value.toLowerCase(),filter=$('filter').value;
    const visible=rows.filter(r=>r.profileId===selected&&(!query||JSON.stringify(r).toLowerCase().includes(query))&&(!filter||(filter==='sync'?r.pendingEvents>0||r.tasks.some(t=>t.syncStatus==='pending'||t.syncStatus==='conflict'):filter==='replied'?r.reply==='received':filter==='verified'?r.validity==='verified':filter==='pending_moderation'?r.moderation===filter:r.submission===filter)));
    $('count').textContent=`${profileMap[selected]?.name||selected}：${visible.length} 个目标站 / 全部 ${rows.filter(r=>r.profileId===selected).length} 个。${localTotal!==null?'本机待同步 '+localTotal+' 条事件。':''}外链核验不代表搜索收录或SEO效果。`;
    $('rows').replaceChildren();for(const r of visible){const tr=el('tr');const site=el('td');site.append(link(/^https?:/.test(r.url)?r.url:'https://'+r.url,r.host));tr.append(site);const status=el('td',labels[r.submission]);for(const t of r.tasks)if(t.reason)status.append(el('small',t.reason));tr.append(status,el('td',labels[r.moderation]||r.moderation),el('td',r.reply==='received'?'有已登记回复':'尚无回复证据'));
      const validity=el('td',labels[r.validity]);if(r.publicUrl)validity.append(link(r.publicUrl,' 查看公开页面'));if(r.checkedAt)validity.append(el('small',r.checkedAt));tr.append(validity);
      const detail=el('td',r.pendingEvents?`${r.pendingEvents}条待上传`:r.tasks.some(t=>t.syncStatus==='pending')?'本机待上传':r.sync==='cloud'?'云端任务记录':'同步状态待核对');const b=el('button','内容 / 证据 / 登记进度');b.onclick=()=>showDetail(r);detail.append(b);tr.append(detail);$('rows').append(tr);
    }
    renderProfile(profileMap[selected]);
  }
  function renderProfile(profile){const key=JSON.stringify(profile||null);if(profileRenderKey===key)return;profileRenderKey=key;const target=$('profile-details');target.replaceChildren();if(!profile){target.append(el('p','此设备尚未拉取该站点资料，请使用设置中的云端连接/拉取功能。'));return;}const fields=profile.fields||{};for(const [k,v] of Object.entries(fields)){const d=el('details');d.append(el('summary',k),el('pre',typeof v==='string'?v:JSON.stringify(v)));target.append(d);}const media=el('div');media.className='journal-media';const urls=[profile.logoUrl||fields.LOGO,...new Set([...(profile.media?.screenshots||[]),...Object.entries(fields).filter(([k])=>/^Screenshot [0-9]+$/i.test(k)).map(([,v])=>v)])];for(const [i,raw] of urls.entries()){const url=typeof raw==='object'?raw.ref||raw.url:raw;if(!url)continue;const f=el('figure'),img=el('img');img.alt=i?'已保存截图或产品图 '+i:'Logo';img.loading='lazy';f.append(img);if(/^https?:/.test(url)){img.src=url;f.append(link(url,'查看原图'));}else if(/^cloud-media:\/\//.test(url)){send({action:'fetchCloudSubmissionMedia',ref:url,name:img.alt}).then(r=>{img.src=r.dataUrl;}).catch(e=>{img.alt=e.message;});}img.onerror=()=>{img.alt='素材加载失败；原引用已保留';};media.append(f);}target.append(media);}
  async function showDetail(row){const version=++detailVersion;const target=$('details');target.hidden=false;target.replaceChildren(el('h3',(storage.siteProfiles?.[row.profileId]?.name||row.profileId)+' → '+row.host));
    for(const record of row.history||[]){target.append(el('p','历史备份登记（'+record.archiveSource+'）：当前资料中缺失，需核对；不计为本次提交成功。'),el('pre','原登记时间：'+(record.submittedAt||'未知')+'\n原登记状态：'+(record.publicationStatus||record.status||'未知')+'\n原始依据：'+(record.evidence||'未保存')));if(record.evidenceUrl)target.append(link(record.evidenceUrl,'历史证据页面'));}
    for(const summary of row.tasks){let task=localTasks.find(t=>t.id===summary.id)||summary;if(!task.actualSubmission&&summary.source==='cloud'){try{task=(await send({action:'submissionJournalCloud',taskId:summary.id})).task||task;}catch(e){target.append(el('p','详情暂不可读：'+e.message));}}
      if(version!==detailVersion)return;target.append(el('p','尝试时间：'+(task.attemptBoundary||'未记录')+' · '+(task.reason||'')));const fields=task.actualSubmission?.fields||[];target.append(el('pre',fields.filter(f=>f.type!=='password'&&!/password|token|secret|密码/i.test(f.name||f.label||'')).map(f=>(f.label||f.name)+'：'+f.value).join('\n')||'尚无实际填写快照'));for(const a of task.actualSubmission?.attachments||[])target.append(el('p','实际附件：'+a.name));if(task.receipt?.evidence)target.append(el('pre','站方回执：'+task.receipt.evidence));if(task.receipt?.url)target.append(link(task.receipt.url,'回执页面'));if(task.artifactRef){const figure=el('figure'),img=el('img');img.alt='该站点实际提交过程截图';img.className='journal-evidence-image';figure.append(img,el('figcaption',task.artifactRef));target.append(figure);send({action:'submissionJournalArtifact',ref:task.artifactRef}).then(result=>{if(version===detailVersion)img.src=result.dataUrl;}).catch(error=>{img.alt='截图暂不可读：'+error.message;});}
    }
    for(const event of row.events){target.append(el('p',`${event.occurredAt||''} · ${event.type} · ${event.note||''}`));if(event.publicUrl)target.append(link(event.publicUrl));if(event.evidenceUrl)target.append(link(event.evidenceUrl,'证据'));
    }
    const form=el('form'),type=el('select'),note=el('textarea'),url=el('input'),evidence=el('input');for(const [value,label] of Object.entries({pending_moderation:'站方待审核',published:'站方已发布',email_reply:'收到站方回复',link_verified:'已核验包含外链',link_missing:'已核验外链缺失',link_unreachable:'核验页面无法访问',needs_follow_up:'需继续跟进',note:'补充备注'})){const o=el('option',label);o.value=value;type.append(o);}note.required=true;note.placeholder='填写站方回复、核验结果或剩余步骤';url.placeholder='公开页面URL（链接核验必填）';evidence.placeholder='邮件、截图或站方回执证据URL';type.setAttribute('aria-label','登记进度类型');note.setAttribute('aria-label','回复或核验说明');url.setAttribute('aria-label','公开页面URL');evidence.setAttribute('aria-label','证据URL');const save=el('button','保存进度记录');save.type='submit';form.append(type,note,url,evidence,save);form.onsubmit=async e=>{e.preventDefault();save.disabled=true;try{if(['published','link_verified','link_missing','link_unreachable'].includes(type.value)&&!/^https?:\/\//.test(url.value))throw new Error('请填写实际公开页面URL');const saved=await send({action:'submissionJournalProgress',profileId:row.profileId,destinationUrl:row.url,destinationKey:row.url,type:type.value,note:note.value,publicUrl:url.value,evidenceUrl:evidence.value,source:'manual',occurredAt:new Date().toISOString()});const snapshot=await send({action:'submissionJournalDocuments'}).catch(()=>null);if(snapshot){await chrome.storage.local.set({submissionJournalCache:{identity:cacheIdentity,at:new Date().toISOString(),tasks:cloudTasks,documents:snapshot.documents}});}await load();$('status').textContent=saved.pending?'已保存在本机待上传：'+(saved.error||'稍后点击从云端刷新重试'):'已保存到 D1，并完成独立回读核对。';target.hidden=true;}catch(error){$('status').textContent=error.message;}finally{save.disabled=false;}};target.append(el('h4','登记审核 / 回复 / 外链核验'),form);target.scrollIntoView({block:'nearest'});
  }
  $('refresh').onclick=async()=>{const b=$('refresh'),startedIdentity=cacheIdentity;b.disabled=true;$('status').textContent='正在读取 D1 云端记录…';try{const result=[],seen=new Set();let after='';do{const page=await send({action:'submissionJournalCloud',after});result.push(...page.tasks);if(page.next&&seen.has(page.next))throw new Error('分页游标重复，已保留旧缓存');if(page.next)seen.add(page.next);after=page.next;}while(after);const snapshot=await send({action:'submissionJournalDocuments'});const latest=await chrome.storage.local.get('cloudSyncConfig');if(startedIdentity!==identity(latest.cloudSyncConfig))throw new Error('工作区已切换，未保存旧工作区结果');await chrome.storage.local.set({submissionJournalCache:{identity:startedIdentity,at:new Date().toISOString(),tasks:result,documents:snapshot.documents}});await load();$('status').textContent=`已从 D1 读取 ${result.length} 个任务及站点资料。原待上传事件仍保留，未自动重投。`;}catch(e){$('status').textContent='云端暂不可读，保留本地与上次缓存：'+e.message;}finally{b.disabled=false;}};
  $('recover').onclick=async()=>{const b=$('recover');b.disabled=true;$('status').textContent='正在备份本机最新资料并写入 D1…';try{const result=await send({action:'submissionJournalRecoverLocal'});$('status').textContent='已备份并回读核对 '+result.saved.length+' 份资料；正在刷新台账。';await $('refresh').onclick();}catch(e){$('status').textContent='恢复未完成，本机资料未删除：'+e.message;}finally{b.disabled=false;}};
  $('export').onclick=()=>{const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),profile:profiles()[selected],rows:rows.filter(r=>r.profileId===selected)},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download='externallink-'+selected+'-journal.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  $('profile').onchange=()=>{selected=$('profile').value;detailVersion++;$('details').hidden=true;render();};$('search').oninput=render;$('filter').onchange=render;
  window.addEventListener('externallink:tasks',event=>{localTasks=event.detail.tasks||[];localTotal=event.detail.pendingEvents;render();});
  chrome.storage.onChanged.addListener((changes,area)=>{if(area==='local'&&['siteProfiles','submissionRecords','submissionTimeline','cloudSyncConfig','d1JournalPending'].some(k=>changes[k]))load();});
  load().catch(e=>{$('status').textContent=e.message;});
})();
