let access=new URLSearchParams(location.hash.slice(1)).get('access');
if(access)history.replaceState(null,'',location.pathname);
const $=id=>document.getElementById(id),content=$('content'),status=$('connection-status'),detail=$('detail');
let data,view='products',query='',profileFilter='',page=0,taskScope='fixed';
const labels={reply_received:'收到关联邮件',not_started:'未开始',pending:'待执行',opening:'正在打开',filling:'正在填写',submitting:'正在提交',finished:'已完成',needs_manual:'待处理',submitted_unconfirmed:'结果待核验',excluded:'已排除',received:'已收件',not_submitted:'未投稿',sent_unconfirmed:'已发送待确认',unknown:'未知',published:'已上线',approved:'已审核',confirmed:'已同步',conflict:'同步冲突'};
const text=value=>labels[value]||value||'未知';
function el(tag,attrs={},children=[]){const node=document.createElement(tag);for(const [key,value]of Object.entries(attrs)){if(key==='text')node.textContent=value;else if(key.startsWith('on'))node.addEventListener(key.slice(2),value);else node.setAttribute(key,String(value));}for(const child of Array.isArray(children)?children:[children])if(child!=null)node.append(typeof child==='string'?document.createTextNode(child):child);return node;}
function button(label,run,primary=false){return el('button',{text:label,class:primary?'primary':'',onclick:async event=>{const b=event.currentTarget;b.disabled=true;try{await run();}catch(error){status.textContent=error.message;}finally{b.disabled=false;}}});}
async function request(path,body,raw=false){const response=await fetch(path,{method:body?'POST':'GET',headers:{...(access?{Authorization:'Bearer '+access}:{}),'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});if(raw){if(!response.ok)throw Error('媒体暂不可读');return URL.createObjectURL(await response.blob());}const result=await response.json();if(!response.ok||result.ok===false)throw Error(result.error||'请求失败');return result;}
async function load(refresh=false){data=await request('/appData',{refresh});status.textContent=(data.cached?'本机资料缓存':'已回读云端')+' · '+new Date(data.at).toLocaleString()+' · '+data.model.products.length+' 个网站 · '+data.model.total+' 个外链目标'+(data.error?' · 云端暂不可读：'+data.error:'')+' · 待同步 '+data.runtime.pendingEvents+' · 本机编辑待同步 '+(data.pendingEdits?.length||0)+' · 媒体待同步 '+(data.pendingMedia?.length||0);render();}
function badge(value){return el('span',{class:'badge '+(value==='received'||value==='confirmed'?'good':/pending|unconfirmed|manual/.test(value)?'pending':''),text:text(value)});}
function stat(label,count){return el('div',{class:'surface'},[el('span',{class:'muted',text:label}),el('strong',{text:String(count)})]);}
function table(headers,rows){return el('div',{class:'table-wrap'},el('table',{},[el('thead',{},el('tr',{},headers.map(h=>el('th',{text:h})))),el('tbody',{},rows)]));}
function toolbar(includeProfile=true){const search=el('input',{type:'search',placeholder:'搜索网站、产品或状态',value:query,'aria-label':'搜索',oninput:event=>{query=event.target.value;page=0;renderRows();}}),tools=el('div',{class:'toolbar'},search);
 if(includeProfile){const select=el('select',{'aria-label':'筛选产品',onchange:event=>{profileFilter=event.target.value;page=0;render();}},[el('option',{value:'',text:'全部产品'}),...data.model.products.map(p=>el('option',{value:p.id,text:p.name||p.id}))]);select.value=profileFilter;tools.append(select);}return tools;}
let renderRows=()=>{};
function paginated(rows,headers,makeRow,target){const pages=Math.ceil(rows.length/40);page=Math.min(page,Math.max(0,pages-1));target.replaceChildren(table(headers,rows.slice(page*40,page*40+40).map(makeRow)),el('div',{class:'pager'},[el('span',{class:'muted',text:rows.length+' 项 · '+(page+1)+' / '+Math.max(1,pages)}),button('上一页',()=>{page=Math.max(0,page-1);renderRows();}),button('下一页',()=>{page=Math.min(Math.max(0,pages-1),page+1);renderRows();})]));}
function render(){if(!data)return;content.replaceChildren();$('heading').textContent={products:'我的网站',library:'外链库',overview:'提交总览',tasks:'运行任务'}[view];document.querySelectorAll('[data-view]').forEach(b=>{if(b.dataset.view===view)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});({products:renderProducts,library:renderLibrary,overview:renderOverview,tasks:renderTasks})[view]();
 if(data.pendingEdits?.some(item=>item.status==='conflict'))content.prepend(button('处理同步冲突',showConflicts));
 if(view==='tasks'&&data.acceptances[0]&&data.batch?.status!=='complete'){
  const start=button(data.batch?'继续固定批次':'启动固定批次',async()=>{await request('/startAcceptance',{acceptanceId:data.acceptances[0].id});await load();},true);start.disabled=!data.runtime.paused||data.runtime.busy;content.querySelector('.toolbar').prepend(start);
 }
 if(view==='tasks'&&data.batch){const attempts=Object.values(data.batch.attempts||{});content.querySelector('.notice').append(' · 已处理 '+data.batch.cursor+'/'+data.batch.count+' · 已收件 '+attempts.filter(a=>a.status==='received').length+(data.batch.reason?' · '+data.batch.reason:''));}
}
function renderProducts(){content.append(el('p',{class:'muted',text:'管理实际产品资料和媒体。历史投稿保存当时的资料版本。'}),toolbar(false));content.querySelector('.toolbar').append(button('新增产品',showCreateProduct));const grid=el('div',{class:'cards'});content.append(grid);renderRows=()=>{grid.replaceChildren(...data.model.products.filter(p=>JSON.stringify([p.id,p.name,p.url]).toLowerCase().includes(query.toLowerCase())).map(p=>{
 const cells=data.model.combinations.filter(c=>c.profileId===p.id),card=el('article',{class:'card'},[el('span',{class:'badge',text:p.id+(p.archived?' · 已归档':'')}),el('h2',{text:p.name||p.fields?.Name||p.id}),el('a',{href:p.url||p.fields?.Url||'#',target:'_blank',rel:'noreferrer',text:p.url||p.fields?.Url||''}),el('div',{class:'metrics'},[el('div',{class:'metric'},[el('strong',{text:String(cells.filter(c=>c.submission==='received').length)}),'已收件']),el('div',{class:'metric'},[el('strong',{text:String(cells.filter(c=>c.publication==='published').length)}),'已上线'])]),el('p',{class:'muted',text:p.fields?.['Short description(20-30 words)']||''}),el('div',{class:'controls'},[button('资料与媒体',()=>showProduct(p)),button(p.archived?'恢复产品':'归档产品',async()=>{await request('/libraryMutation',{operation:{type:'profile_archive',profileId:p.id,archived:!p.archived}});await load();}),button('查看投稿',()=>{profileFilter=p.id;view='overview';page=0;render();})])]);return card;}));};renderRows();}

function showCreateProduct(){detail.showModal();const panel=$('detail-content'),name=el('input',{'aria-label':'产品名称'}),url=el('input',{type:'url','aria-label':'产品官网'}),message=el('p',{'role':'status'});panel.replaceChildren(el('h2',{text:'新增产品'}),el('label',{},['名称',name]),el('label',{},['官网',url]),button('保存新产品',async()=>{const id='product-'+crypto.randomUUID(),result=await request('/libraryMutation',{operation:{type:'profile_create',profileId:id,profile:{id,name:name.value.trim(),url:url.value.trim(),fields:{Name:name.value.trim(),Url:url.value.trim()}}}});await load();message.textContent=result.pending?'已保存本机，等待同步：'+(result.error||''):'新产品已回读云端';},true),message);}
function showConflicts(){detail.showModal();const panel=$('detail-content');panel.replaceChildren(el('h2',{text:'处理同步冲突'}));if(!data.pendingEdits.some(item=>item.status==='conflict'))panel.append(el('p',{text:'所有同步冲突已处理，原编辑与处理记录仍保留。'}));for(const item of data.pendingEdits.filter(item=>item.status==='conflict')){panel.append(el('h3',{text:item.type+' · '+item.id.slice(0,8)}),el('p',{text:'比较两个版本后选择。处理记录保留原编辑和云端版本。',class:'muted'}),el('details',{},[el('summary',{text:'本机编辑'}),el('pre',{text:JSON.stringify(item.operation,null,2)})]),el('details',{},[el('summary',{text:'云端资料 · 版本 '+item.remoteRevision}),el('pre',{text:JSON.stringify(item.operation.profileId?item.remoteData?.[item.operation.profileId]:item.remoteData,null,2)})]),el('div',{class:'controls'},[button('保留云端',()=>resolve('cloud')),button('采用本机编辑',()=>resolve('local'))]));async function resolve(choice){await request('/resolveConflict',{id:item.id,choice,revision:item.remoteRevision});await load();showConflicts();}}}

async function showProduct(product){detail.showModal();const panel=$('detail-content');panel.replaceChildren(el('h2',{text:product.name||product.id}));const form=el('form'),inputs=new Map(),message=el('p',{'role':'status'});
 for(const [key,value]of Object.entries({...Object.fromEntries(['Name','Url','Title','Business mail','Short description(20-30 words)','Long description (250-500 words)','Tags Keywords/Hashtags','Pricing','Launch Date','Extra Link:X/Twitter/YouTube/Instagram/..'].map(key=>[key,''])),...product.fields})){if(typeof value!=='string'||/password|token|secret|密码/i.test(key))continue;const input=el('textarea',{rows:/description|描述|feature/i.test(key)?4:2,'aria-label':key});input.value=value;inputs.set(key,input);form.append(el('label',{},[key,input]));}
 const save=el('button',{type:'submit',class:'primary',text:'保存资料'});form.append(save,message);form.addEventListener('submit',async event=>{event.preventDefault();save.disabled=true;try{const fields=Object.fromEntries([...inputs].map(([key,input])=>[key,input.value]));const result=await request('/profile',{profileId:product.id,revision:data.revisions.siteProfiles,profile:{id:product.id,fields,...(fields.Name?{name:fields.Name}:{}),...(fields.Url?{url:fields.Url}:{})}});await load();message.textContent=result.pending?'已保存到本机，等待云端同步；历史投稿保留旧版本。'+(result.error||''):'已保存并回读云端；历史投稿保留旧版本。';}catch(error){message.textContent='尚未确认，编辑内容保留：'+error.message;}finally{save.disabled=false;}});panel.append(form,el('h3',{text:'媒体管理'}));addMediaControls(panel,product);panel.append(el('h3',{text:'媒体预览'}));const media=el('div',{class:'media-grid'});panel.append(media);
 for(const [key,value]of Object.entries({...product.fields,...Object.fromEntries((product.mediaVersions||[]).filter(v=>!Object.values(product.fields||{}).includes(v.ref)).map(v=>['版本 '+v.kind+' '+v.assetId.slice(-8),v.ref]))}).filter(([key,value])=>typeof value==='string'&&/logo|screenshot|featured image|版本/i.test(key)&&value)){const item=el('div',{},[el('p',{text:key,class:'muted'}),el('p',{text:value,class:'muted'})]);media.append(item);try{let url=value;if(value.startsWith('cloud-media://'))url=await request('/cloud/workspace/media/'+encodeURIComponent(value.slice(14)),undefined,true);else if(!/^https:\/\//.test(value)){item.append(el('p',{class:'badge pending',text:'本机路径，需要原设备素材'}));continue;}const img=el('img',{src:url,alt:key,loading:'lazy',onerror:()=>{img.replaceWith(el('p',{class:'badge pending',text:'图片暂不可读'}));}});item.prepend(img);if(url.startsWith('blob:'))detail.addEventListener('close',()=>URL.revokeObjectURL(url),{once:true});}catch{item.append(el('p',{class:'badge pending',text:'图片暂不可读'}));}}
}

function addMediaControls(panel,product){const kinds={logo:'Logo',featured:'封面',screenshot1:'截图 1',screenshot2:'截图 2',screenshot3:'截图 3',screenshot4:'截图 4'},select=el('select',{'aria-label':'上传媒体类型'},Object.entries(kinds).map(([value,label])=>el('option',{value,text:label}))),message=el('p',{'role':'status'}),file=el('input',{type:'file',accept:'image/png,image/jpeg,image/webp','aria-label':'上传新媒体版本',onchange:async event=>{try{const selected=event.target.files[0];if(!selected)return;if(selected.size>6*1024*1024)throw Error('图片超过 6 MB');file.disabled=true;const dataUrl=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(selected);});const result=await request('/mediaUpload',{profileId:product.id,kind:select.value,fileName:selected.name,dataUrl});await load();message.textContent=result.pending?'图片已存本机，等待同步：'+(result.error||''):'新媒体版本已上传并回读';}catch(error){message.textContent=error.message;}finally{file.disabled=false;}}});panel.append(el('p',{class:'muted',text:'PNG/JPEG/WEBP，最多 6 MB。每次上传保存独立版本，历史任务保留原素材。'}),select,file,button('停用此类媒体',async()=>{await request('/libraryMutation',{operation:{type:'profile_media',profileId:product.id,kind:select.value,action:'disable'}});await load();message.textContent='停用已保存，历史素材保留。';}),message);
 for(const asset of product.mediaVersions||[])panel.append(el('div',{class:'controls'},[el('span',{class:'muted',text:(kinds[asset.kind]||asset.kind)+' · '+asset.fileName+' · '+asset.sha256.slice(0,12)}),button('使用这个版本',async()=>{await request('/libraryMutation',{operation:{type:'profile_media',profileId:product.id,kind:asset.kind,assetId:asset.assetId,action:'restore'}});await load();message.textContent='媒体版本选择已保存。';})]));}

function renderLibrary(){content.append(el('p',{class:'muted',text:'完整外链库 · 保留来源、入口、标记和历史记录。站点不同入口共用产品投稿身份。'}),toolbar());content.querySelector('.toolbar').append(button('导入网址',showImport));const target=el('div');content.append(target);renderRows=()=>{const rows=data.model.library.filter(r=>JSON.stringify([r.url,r.site,r.row,r.annotation]).toLowerCase().includes(query.toLowerCase()));paginated(rows,['目标站','入口','来源','标记','已收件产品','维护'],r=>{const cells=data.model.combinations.filter(c=>c.site===r.site&&c.submission==='received');return el('tr',{},[el('td',{class:'site',text:r.site}),el('td',{},el('a',{href:r.url,target:'_blank',rel:'noreferrer',text:r.url})),el('td',{text:r.source||''}),el('td',{text:(r.annotation.statuses||[r.annotation.status]).filter(Boolean).join('、')||'未标记'}),el('td',{text:cells.filter(c=>!profileFilter||c.profileId===profileFilter).map(c=>data.model.products.find(p=>p.id===c.profileId)?.name||c.profileId).join('、')||'暂无'}),el('td',{},button('编辑',()=>showLibrary(r)))]);},target);};renderRows();}
function showImport(){detail.showModal();const panel=$('detail-content'),input=el('textarea',{rows:10,'aria-label':'导入网址',placeholder:'每行一个 HTTP/HTTPS 网址，最多 500 行'}),message=el('p',{'role':'status'});panel.replaceChildren(el('h2',{text:'导入外链入口'}),el('p',{class:'muted',text:'相同目标会去重；原资料、标记和投稿记录保留。'}),input,button('保存导入',async()=>{const urls=input.value.split(/\r?\n/).map(s=>s.trim()).filter(Boolean);const result=await request('/libraryMutation',{operation:{type:'import',urls}});message.textContent=result.pending?'已保存在本机，待同步：'+(result.error||'后台重试'):'已导入并回读云端';await load();},true),message);}
function showLibrary(row){detail.showModal();const panel=$('detail-content'),message=el('p',{'role':'status'}),states={can_submit:'可提交',paid:'付费',broken:'失效',skip:'跳过',needs_otp:'需要 OTP',needs_captcha:'需要验证码',needs_login:'需要登录',needs_manual:'待人工',deleted:'归档'};
 const select=el('select',{'aria-label':'站点标记'},Object.entries(states).map(([value,label])=>el('option',{value,text:label})));select.value=row.annotation.status||'can_submit';const note=el('textarea',{'aria-label':'站点备注',rows:3});note.value=row.annotation.note||'';
 panel.replaceChildren(el('h2',{text:row.site}),el('a',{href:row.url,target:'_blank',rel:'noreferrer',text:row.url}),el('label',{},['站点标记',select]),el('label',{},['备注',note]),button('保存标记',async()=>{const result=await request('/libraryMutation',{operation:{type:'mark',url:row.url,status:select.value,note:note.value}});message.textContent=result.pending?'已保存在本机，待同步：'+(result.error||'后台重试'):'标记已回读云端';await load();}),message);
 if(row.row){const fields=new Map();for(const key of ['name','category','tags','da','dr','price','note']){const input=el('input',{'aria-label':'外链 '+key});input.value=row.row[key]||'';fields.set(key,input);panel.append(el('label',{},[key,input]));}panel.append(button('保存外链资料',async()=>{const result=await request('/libraryMutation',{operation:{type:'edit',url:row.url,fields:Object.fromEntries([...fields].map(([key,input])=>[key,input.value]))}});message.textContent=result.pending?'已保存在本机，待同步：'+(result.error||'后台重试'):'外链资料已回读云端';await load();}),el('details',{},[el('summary',{text:'原始来源资料'}),el('pre',{text:JSON.stringify(row.row,null,2)})]));}
}
function renderOverview(){const pairs=data.model.combinations;content.append(el('div',{class:'top-stats'},[stat('已收件组合',pairs.filter(c=>c.submission==='received').length),stat('结果待核验',pairs.filter(c=>c.submission==='sent_unconfirmed').length),stat('站方待审核',pairs.filter(c=>c.review==='pending').length),stat('公开上线',pairs.filter(c=>c.publication==='published').length)]),toolbar());const target=el('div');content.append(target);renderRows=()=>{const products=data.model.products.filter(p=>!profileFilter||p.id===profileFilter),sites=[...new Set([...data.model.library.map(r=>r.site),...pairs.map(c=>c.site)])].filter(site=>site.toLowerCase().includes(query.toLowerCase()));paginated(sites,['目标站',...products.map(p=>p.name||p.id)],site=>el('tr',{},[el('td',{class:'site',text:site}),...products.map(product=>{const cell=pairs.find(c=>c.site===site&&c.profileId===product.id);return el('td',{class:'matrix'},cell?el('button',{class:'cell-button',onclick:()=>showCombination(cell)},[badge(cell.submission),el('div',{class:'muted',text:'审核 '+(cell.review==='pending'?'待审核':text(cell.review))+' · 邮件 '+text(cell.reply)}),el('div',{class:'muted',text:'上线 '+text(cell.publication)+' · '+text(cell.sync)})]):el('span',{class:'muted',text:'未开始'}));})]),target);};renderRows();}
async function showCombination(cell){detail.showModal();$('detail-content').replaceChildren(el('h2',{text:cell.site+' · '+cell.profileId}),el('div',{class:'controls'},[badge(cell.submission),badge(cell.execution)]),el('p',{text:cell.reason||''}),...(cell.replyEvidence||[]).map(mail=>button('查看邮件 · '+new Date(mail.at).toLocaleString(),()=>showMail(mail.messageId))),...cell.records.map(record=>el('pre',{text:JSON.stringify(record,null,2)})),...cell.taskIds.map(id=>button('任务详情 '+id.slice(0,8),()=>showTask(id))));}
function renderTasks(){const frozen=data.acceptances[0],execution=frozen?.execution?.items||{},fixedIds=new Set(Object.values(execution).map(i=>i.taskId));content.append(el('div',{class:'notice',text:'执行器'+(data.runtime.paused?'已暂停':'运行中')+' · '+(data.runtime.busy?'正在处理原任务':'空闲')+' · 待同步 '+data.runtime.pendingEvents+(frozen?' · 固定验收 '+frozen.count+' 个组合':'')}),el('div',{class:'toolbar'},[button('暂停执行',async()=>{await request('/pause',{});await load();}),button('同步与核验',async()=>{await request('/sync',{});await load(true);}),...(frozen?[button('恢复原范围注册',async()=>{await request('/registerAcceptance',{acceptanceId:frozen.id});await load();})]:[])]),toolbar());const scope=el('select',{'aria-label':'任务范围',onchange:event=>{taskScope=event.target.value;page=0;renderRows();}},[el('option',{value:'fixed',text:'本次固定验收'}),el('option',{value:'all',text:'所有历史任务'})]);scope.value=taskScope;content.querySelector('.toolbar').append(scope);const target=el('div');content.append(target);renderRows=()=>{const tasks=data.tasks.filter(t=>(taskScope!=='fixed'||fixedIds.has(t.id))&&(!profileFilter||t.profileId===profileFilter)&&JSON.stringify([t.url,t.profileId,t.status,t.reason]).toLowerCase().includes(query.toLowerCase()));paginated(tasks,['产品','目标站','执行','收件','同步','详情'],t=>el('tr',{},[el('td',{text:data.model.products.find(p=>p.id===t.profileId)?.name||t.profileId}),el('td',{text:t.url,class:'site'}),el('td',{},[badge(t.status),el('p',{class:'muted',text:t.reason||''})]),el('td',{},badge(t.receipt?'received':t.attemptBoundary?'sent_unconfirmed':'not_submitted')),el('td',{},badge(t.syncStatus)),el('td',{},button('查看',()=>showTask(t.id)))]),target);};renderRows();}
async function showTask(id){const {task}=await request('/taskDetails',{taskId:id});if(!detail.open)detail.showModal();const panel=$('detail-content');panel.replaceChildren(el('h2',{text:(data.model.products.find(p=>p.id===task.profileId)?.name||task.profileId)+' · '+task.url}),el('div',{class:'controls'},[badge(task.status),badge(task.receipt?'received':task.attemptBoundary?'sent_unconfirmed':'not_submitted')]),el('p',{text:task.reason||''}));const frozen=data.acceptances.find(f=>f.execution&&Object.values(f.execution.items).some(i=>i.taskId===id));
 if(frozen&&!task.attemptBoundary&&!task.receipt){panel.append(el('div',{class:'controls'},[button('准备原任务',async()=>{const result=await request('/prepareTask',{taskId:id,acceptanceId:frozen.id});status.textContent=result.prepared?'原任务资料已准备，尚未提交':'准备待处理：'+result.reason;await load();await showTask(id);}),button('运行原任务',async()=>{await request('/runTask',{taskId:id,acceptanceId:frozen.id});detail.close();await load();},true)]));}
 if(task.attemptBoundary&&!task.receipt)panel.append(el('p',{class:'notice',text:'存在提交尝试边界，必须先核验原页面；不会创建重复投稿。'}),button('核验原任务',async()=>{await request('/verify',{taskId:id});await load(true);await showTask(id);}));
 for(const [label,value]of [['实际提交内容',task.actualSubmission],['实际准备内容',task.actualPreparation],['站方回执',task.receipt],['AI 接管',task.aiTakeover],['已用媒体',task.usedMedia],['登录记录',task.authAttempts]])if(value)panel.append(el('h3',{text:label}),el('pre',{text:JSON.stringify(value,null,2)}));
 if(task.screenshot)try{const result=await request('/evidence/'+id);panel.append(el('h3',{text:'原任务页面证据'}),el('img',{src:result.dataUrl,class:'evidence',alt:'原任务页面截图'}));}catch{panel.append(el('p',{class:'muted',text:'截图暂不可读，原记录保留。'}));}
}
async function showMail(messageId){const {message}=await request('/gmailMessage',{messageId});if(!detail.open)detail.showModal();$('detail-content').replaceChildren(el('h2',{text:message.subject||'关联邮件'}),el('p',{text:message.from+' · '+new Date(message.at).toLocaleString()}),el('p',{class:'notice',text:'只读邮件证据；审核与上线状态需要独立核验。'}),el('pre',{text:message.text}),el('p',{class:'muted',text:'SHA256 '+message.sha256}));}
async function showGmail(){const {gmail}=await request('/gmailStatus',{});if(!detail.open)detail.showModal();const panel=$('detail-content');panel.replaceChildren(el('h2',{text:'Gmail 只读连接'}),el('p',{text:'仅读取邮件，凭据保存于本机系统凭据库。连接后每分钟增量同步；不会发送邮件或修改邮箱。'}),el('pre',{text:JSON.stringify(gmail,null,2)}));
 if(gmail.refreshGrantExpiresAt)panel.append(el('p',{class:'notice',text:'Google 当前授权有效至 '+new Date(gmail.refreshGrantExpiresAt).toLocaleString()+'，届时需重新授权。'}));
 const file=el('input',{type:'file',accept:'.json','aria-label':'Google 桌面客户端 JSON',onchange:async event=>{try{const selected=event.target.files[0];if(!selected)return;if(selected.size>32768)throw Error('客户端 JSON 过大');await request('/gmailConfigure',{client:JSON.parse(await selected.text())});await showGmail();}catch(error){status.textContent=error.message;}}});panel.append(el('label',{text:'导入 Google Cloud 桌面应用客户端 JSON'}),file,
 button('开始本机只读授权',async()=>{const result=await request('/gmailAuthorize',{});panel.append(el('a',{href:result.authorizationUrl,target:'_blank',rel:'noreferrer',text:'打开 Google 只读授权页面'}));}),button('同步邮箱',async()=>{await request('/gmailSync',{});await showGmail();}),button('验证令牌续期',async()=>{await request('/gmailRefresh',{});await showGmail();}));}
$('gmail-settings').onclick=()=>showGmail().catch(error=>status.textContent=error.message);
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{view=b.dataset.view;page=0;query='';render();}));$('close-detail').onclick=()=>detail.close();$('refresh').onclick=async()=>{const b=$('refresh');b.disabled=true;try{await load(true);}catch(error){status.textContent=error.message;}finally{b.disabled=false;}};
try{await request('/connection');access=null;await load();setInterval(async()=>{if(!detail.open&&!document.activeElement?.matches('input,textarea,select'))try{await load();}catch(error){status.textContent='本机后台暂不可达，当前资料仍保留：'+error.message;}},15000);}catch(error){status.textContent='暂未连接：'+error.message;content.append(el('p',{class:'notice',text:'请使用本机统一启动入口打开；登录态和原任务不会被清空。'}));}
