import {showSetup} from './setup.js';
import {renderCommentStudio} from './comment-studio.js';
const consumedQuickOpen=new Set();
function renderAssistantSettings(){const state=data.assistant||{},saved=state.settings||{};let enabled=saved.enabled===true,autoFill=saved.autoFillOnVisit===true;const options=data.model.products.filter(p=>!p.archived).map(p=>[p.id,p.name||p.id]),selected=selectControl('浏览器助手使用的产品',options,saved.profileId||options[0]?.[0]||'',()=>{}),message=el('p',{role:'status'});content.append(el('h3',{text:'浏览器填表助手'}),el('p',{class:'muted',text:'在执行器浏览器网页的字段旁显示填写按钮。访问时自动填写仅处理已登记、尚未投稿且仍在原标签页的任务；填写后由你检查。'}),fieldRow('填写所用产品',selected),checkControl('启用浏览器填表助手',enabled,v=>enabled=v),checkControl('访问原任务页面时自动填写',autoFill,v=>autoFill=v),button('保存浏览器助手设置',async()=>{const result=await request('/saveAssistantSettings',{enabled,autoFillOnVisit:autoFill,profileId:selected.value});data.assistant=result;message.textContent=result.settings.enabled?'助手已启用，后台正在连接网页。':'助手已关闭，网页填写按钮已移除。';},true),el('p',{class:'muted',text:'已连接网页区域 '+(state.connectedFrames||0)+(state.error?' · '+state.error:'')}),message);}
async function showBrowserAdd(){const result=await request('/browserLibraryPages',{});if(!result.pages.length)throw Error('执行器浏览器中没有普通网页');if(!detail.open)detail.showModal();const selected=selectControl('选择执行器浏览器页面',result.pages.map(p=>[p.targetId,(p.title||p.url)+' · '+p.url]),result.pages[0].targetId,()=>{}),message=el('p',{role:'status'});$('detail-content').replaceChildren(el('h2',{text:'当前网页加入外链库并置顶'}),el('p',{text:'选择执行器浏览器中的网页。相同入口保留原记录、收藏与分组；已移除的入口会重新启用，其他提交条件保留。'}),fieldRow('浏览器页面',selected),button('确认加入库并置顶',async()=>{const page=result.pages.find(p=>p.targetId===selected.value),saved=await request('/addBrowserPage',{targetId:page.targetId,expectedUrl:page.url});await load();message.textContent=saved.remaining?'原变更已存本机，等待同步':'页面已加入外链库并置顶，未投稿。';},true),message);}
function showResetWorkspace(){if(!detail.open)detail.showModal();const confirmation=el('input',{'aria-label':'清空本机工作区确认文字'});$('detail-content').replaceChildren(el('h2',{text:'清空本机工作区'}),el('p',{text:'先创建本机完整备份，再清空本机资料缓存、连接和任务队列。云端账本、浏览器登录和素材文件保留。完成后需要重新连接云端。'}),fieldRow('输入“清空本机工作区”确认',confirmation),button('确认备份并清空本机',async()=>{const result=await request('/resetWorkspace',{confirmation:confirmation.value});$('detail-content').replaceChildren(el('h2',{text:'本机工作区已清空'}),el('p',{text:'备份完整性：'+result.integrity}),el('p',{text:'恢复备份保存在：'+result.backupDirectory}),button('重新连接云端',()=>location.reload(),true));},true));}
async function showCloudStatus(){const result=await request('/cloudSyncStatus',{});if(!detail.open)detail.showModal();$('detail-content').replaceChildren(el('h2',{text:'云端连接与版本'}),el('p',{text:'云端地址：'+result.endpoint}),el('p',{text:'工作区：'+result.workspaceId}),el('p',{text:'已连接设备：'+result.deviceId}),el('p',{text:'待同步资料 '+result.pendingEdits+' · 媒体 '+result.pendingMedia+' · 动态 '+result.pendingTimeline+' · 事件 '+result.pendingEvents}),el('p',{text:result.outOfDateKeys.length?'云端有 '+result.outOfDateKeys.length+' 类资料更新，可点击“刷新云端”回读。':'本机资料版本与云端一致。'}));}
function productFormState(form){return JSON.stringify([...form.querySelectorAll('input,textarea,select')].map(n=>n.type==='checkbox'?n.checked:n.value));}
async function showMediaLibrary(){const result=await request('/mediaLibrary',{});if(!detail.open)detail.showModal();$('detail-content').replaceChildren(el('h2',{text:'云端媒体目录'}),el('p',{text:result.assets.length+' 个云端素材 · '+result.references.length+' 个在用产品引用 · '+result.missing.length+' 个引用未在目录中找到'}),el('p',{class:'muted',text:'目录检查不会替换素材；原设备本机路径需在原设备恢复。'}),table(['产品','类型','文件名','大小'],result.assets.map(a=>el('tr',{},[el('td',{text:data.model.products.find(p=>p.id===a.profile_id)?.name||a.profile_id||'未标注产品'}),el('td',{text:mediaKindLabel(a.media_kind)}),el('td',{text:a.file_name}),el('td',{text:Math.ceil(a.byte_length/1024)+' KB'})]))),...result.missing.map(r=>el('p',{class:'notice',text:r.profileName+' · '+mediaKindLabel(r.kind)+' · 目录中未发现 '+r.ref})));}
function mediaKindLabel(kind){return{logo:'产品标志图片',featured:'封面图片',screenshot1:'产品截图 1',screenshot2:'产品截图 2',screenshot3:'产品截图 3',screenshot4:'产品截图 4'}[kind]||'其他素材';}
function showDeleteProduct(product){if(!detail.open)detail.showModal();const name=product.name||product.id,confirmation=el('input',{'aria-label':'确认删除的产品名称'}),message=el('p',{role:'status'});$('detail-content').replaceChildren(el('h2',{text:'删除产品资料'}),el('p',{text:'删除「'+name+'」的云端产品资料。历史投稿和收件记录保留；需要恢复资料时可导入备份。'}),fieldRow('输入产品名称确认',confirmation),button('确认删除产品资料',async()=>{if(confirmation.value!==name)throw Error('请输入完整产品名称');const result=await request('/libraryMutation',{operation:{type:'profile_delete',profileId:product.id}});await load();if(result.pending){message.textContent='删除变更已存本机，尚待同步，请勿重复操作。';}else{detail.close();status.textContent='产品资料已删除并回读云端。';}},true),message);}
function showQuickOpen(){let removeOpened=true;const urls=[...selectedUrls];if(!urls.length)throw Error('请先选择外链网站');const size=el('input',{type:'number',min:1,max:20,value:5,'aria-label':'每批打开数量'}),interval=el('input',{type:'number',min:100,max:5000,value:800,'aria-label':'打开间隔（毫秒）'});if(!detail.open)detail.showModal();$('detail-content').replaceChildren(el('h2',{text:'批量打开网站'}),el('p',{text:'已选择 '+urls.length+' 个入口。按间隔打开下一批，完成后从选择中移除已打开项；可查看打开失败的入口。'}),fieldRow('每批数量（1–20）',size),fieldRow('间隔（100–5000 毫秒）',interval),checkControl('打开后从临时选择中移除',true,v=>removeOpened=v),button('打开下一批',async()=>{await request('/quickOpenLibrary',{urls,batchSize:Number(size.value),intervalMs:Number(interval.value),removeOpened});detail.close();await load();},true));}
function renderQuickOpenJobs(){for(const job of (data.quickOpenJobs||[]).slice(-5).reverse()){if(job.status==='completed'&&!consumedQuickOpen.has(job.id)){if(job.removeOpened!==false)job.items.filter(i=>i.status==='opened').forEach(i=>selectedUrls.delete(i.url));consumedQuickOpen.add(job.id);renderRows();}content.append(el('article',{class:'card'},[el('h3',{text:'批量打开网站 · '+job.cursor+' / '+job.count}),el('p',{text:job.status==='completed'?'本批已结束':job.status==='running'?'正在按间隔打开':'打开已暂停，请查看记录'}),...(job.status==='paused'&&job.items.slice(job.cursor).every(i=>i.status==='queued')?[button('继续打开剩余入口',async()=>{await request('/quickOpenLibrary',{jobId:job.id});await load();})]:[]),...(job.error?[el('p',{class:'notice',text:'打开未完成：'+job.error})]:[]),...job.items.map(i=>el('p',{text:i.url+' · '+({queued:'等待打开',opening:'正在打开',opened:'已打开',failed:'打开失败'}[i.status]||'状态待核验')+(i.error?'：'+i.error:'')}))]));}}
import {parseActivityTime} from './activity-time.js';
let access=new URLSearchParams(location.hash.slice(1)).get('access');
if(access)history.replaceState(null,'',location.pathname);
const $=id=>document.getElementById(id),content=$('content'),status=$('connection-status'),detail=$('detail');
let settingsDirty=false,commentStudioState;
content.addEventListener('input',()=>{if(view==='settings')settingsDirty=true;});content.addEventListener('change',()=>{if(view==='settings')settingsDirty=true;});
let data,view='products',query='',profileFilter='',page=0,taskScope='fixed',showArchived=false,libraryCategory='',libraryGroup='',libraryFavorite='',libraryEnabled='',libraryAccess='',libraryProgress='',libraryMinQuality=0,libraryMinDr=0,librarySort='quality',overviewState='',selectedUrls=new Set();
const labels={reply_received:'收到关联邮件',not_started:'未开始',pending:'待执行',opening:'正在打开',filling:'正在填写',submitting:'正在提交',finished:'已完成',needs_manual:'待处理',submitted_unconfirmed:'结果待核验',excluded:'已排除',received:'已收件',not_submitted:'未投稿',sent_unconfirmed:'已发送待确认',unknown:'未知',published:'已上线',approved:'已审核',confirmed:'已同步',conflict:'同步冲突',submitted:'已记录提交',pending_moderation:'待审核',rejected:'被拒绝',needs_follow_up:'需要跟进',link_missing:'链接失效',link_submit:'有历史提交动作',note:'跟进笔记',legacy_import:'历史导入',awaiting_index:'等待收录',action_recorded:'有提交动作',unsubmitted:'未提交',status:'状态更新'};
const text=value=>labels[value]||value||'未知';
Object.assign(labels,{can_submit:'可以提交',paid:'需要付费',broken:'网址失效',skip:'暂不提交',needs_otp:'需要邮箱或手机验证码',needs_captcha:'需要完成验证码',needs_login:'需要登录',needs_manual:'需要人工处理',deleted:'已归档'});
const monitorLabels={live:'目标外链可见',missing:'页面未发现目标外链',unreachable:'暂时无法访问',uncheckable:'需人工核验'};
const sourceLabels={'cloud.sheetTableData':'表格导入','cloud.urlList':'网址列表导入','application_manual':'手工添加','submify-public':'公共外链库（Submify）'};
const fieldLabels={'Name':'产品名称','Url':'产品官网','Title':'宣传标题','Business mail':'商务联系邮箱','Feedback mail':'用户反馈邮箱','Note':'补充说明','Tags Keywords/Hashtags':'关键词与标签','Pricing':'价格说明','PRICING TYPE':'收费方式','Launch Date':'上线日期','Feature description':'功能介绍','Extra Link:X/Twitter/YouTube/Instagram/..':'社交账号与其他链接','LOGO':'产品标志图片','Featured image':'封面图片','Local media folder':'本机素材文件夹','Affiliate link':'推广合作链接','Cost & Subscription':'费用与订阅说明','Credits System':'积分使用规则','Data Storage Policy':'数据保存政策','Ease of Use':'操作难易程度','Export Formats':'支持的导出格式','Media Support':'支持的媒体格式','OS Compatibility':'支持的操作系统','Offline Mode':'是否支持离线使用','Payment Methods':'付款方式','Platform Accessibility':'使用平台与访问方式','Promos':'优惠活动','Starting Price':'起始价格','Subscription Model':'订阅方案','User Anonvmitv':'是否支持匿名使用','Maker Handle':'开发者账号','Solo Maker':'是否由个人开发','Product Hunt First Comment':'Product Hunt 首条介绍评论','Product Hunt Topics':'Product Hunt 产品分类','AI Providers / Models':'使用的人工智能服务与模型','API Availability':'是否提供接口','Authentication':'登录与身份验证方式','Content Restrictions':'内容使用限制','Output / Aspect Ratios':'输出格式与画面比例','Preset Library':'内置预设素材库','Source Repository':'源代码地址','Target Users':'适合的用户','Tech Stack':'使用的技术','Use Cases':'使用场景','Founded year':'成立年份'};
function fieldLabel(key){if(fieldLabels[key])return fieldLabels[key];const description=key.match(/^(Short description|Short Discription|Long description)\s*\((\d+-\d+) words\)$/i);if(description)return(description[1].startsWith('Long')?'详细介绍':'简短介绍')+'（'+description[2]+' 个英文单词）';if(key==='Long description')return '详细介绍';if(key.startsWith('Local '))return '本机'+fieldLabel(key.slice(6));if(key.startsWith('Cloud '))return '云端'+fieldLabel(key.slice(6));const screenshot=key.match(/^Screenshot[ -](\d+)$/i);if(screenshot)return '产品截图 '+screenshot[1];if(/^(Discord|Twitter|GitHub|LinkedIn|Slack|YouTube|Youtube|Telegram|Instagram|Facebook|Product Hunt)$/.test(key))return key+'账号链接';return '补充资料（'+key+'）';}

function el(tag,attrs={},children=[]){const node=document.createElement(tag);for(const [key,value]of Object.entries(attrs)){if(key==='text')node.textContent=value;else if(key.startsWith('on'))node.addEventListener(key.slice(2),value);else node.setAttribute(key,String(value));}for(const child of Array.isArray(children)?children:[children])if(child!=null)node.append(typeof child==='string'?document.createTextNode(child):child);return node;}
function button(label,run,primary=false){return el('button',{text:label,class:primary?'primary':'',onclick:async event=>{const b=event.currentTarget;b.disabled=true;try{await run();}catch(error){status.textContent=error.message;}finally{b.disabled=false;}}});}
async function request(path,body,raw=false){const response=await fetch(path,{method:body?'POST':'GET',headers:{...(access?{Authorization:'Bearer '+access}:{}),'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});if(raw){if(!response.ok)throw Error('媒体暂不可读');return URL.createObjectURL(await response.blob());}const result=await response.json();if(!response.ok||result.ok===false)throw Error(result.error||'请求失败');return result;}
async function load(refresh=false){data=await request('/appData',{refresh});status.textContent=(data.cached?'本机资料缓存':'已回读云端')+' · '+new Date(data.at).toLocaleString()+' · '+data.model.products.filter(p=>!p.archived).length+' 个在用网站 · '+data.model.total+' 个外链目标'+(data.error?' · 云端暂不可读：'+data.error:'')+' · 待同步 '+data.runtime.pendingEvents+' · 本机编辑待同步 '+(data.pendingEdits?.length||0)+' · 媒体待同步 '+(data.pendingMedia?.length||0);if(!(view==='comments'&&content.querySelector('#comment-studio'))&&!(view==='settings'&&settingsDirty))render();}
function badge(value){return el('span',{class:'badge '+(value==='received'||value==='confirmed'?'good':/pending|unconfirmed|manual/.test(value)?'pending':''),text:text(value)});}
function stat(label,count){return el('div',{class:'surface'},[el('span',{class:'muted',text:label}),el('strong',{text:String(count)})]);}
function table(headers,rows){return el('div',{class:'table-wrap'},el('table',{},[el('thead',{},el('tr',{},headers.map(h=>el('th',{text:h})))),el('tbody',{},rows)]));}
function toolbar(includeProfile=true){const search=el('input',{type:'search',placeholder:'搜索网站、产品或状态',value:query,'aria-label':'搜索',oninput:event=>{query=event.target.value;page=0;renderRows();}}),tools=el('div',{class:'toolbar'},search);
 if(includeProfile){const select=el('select',{'aria-label':'筛选产品',onchange:event=>{profileFilter=event.target.value;page=0;render();}},[el('option',{value:'',text:'全部产品'}),...data.model.products.map(p=>el('option',{value:p.id,text:(p.name||p.id)+(p.archived?'（已归档）':'')}))]);select.value=profileFilter;tools.append(select);}return tools;}
let renderRows=()=>{};
function paginated(rows,headers,makeRow,target){const pages=Math.ceil(rows.length/40);page=Math.min(page,Math.max(0,pages-1));target.replaceChildren(table(headers,rows.slice(page*40,page*40+40).map(makeRow)),el('div',{class:'pager'},[el('span',{class:'muted',text:rows.length+' 项 · '+(page+1)+' / '+Math.max(1,pages)}),button('上一页',()=>{page=Math.max(0,page-1);renderRows();}),button('下一页',()=>{page=Math.min(Math.max(0,pages-1),page+1);renderRows();})]));}
function render(){if(!data)return;content.replaceChildren();$('heading').textContent={products:'我的网站',library:'外链库',overview:'提交总览',tasks:'运行任务',comments:'AI 评论',settings:'设置与备份'}[view];document.querySelectorAll('[data-view]').forEach(b=>{if(b.dataset.view===view)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});({products:renderProducts,library:renderLibrary,overview:renderOverview,tasks:renderTasks,comments:renderComments,settings:renderSettings})[view]();if(['library','settings'].includes(view))renderDataJobs();if(view==='library')renderQuickOpenJobs();if(view==='settings'){renderAssistantSettings();renderMonitorSettings();}renderMonitorAlerts();
 if(data.pendingEdits?.some(item=>item.status==='conflict'))content.prepend(button('处理同步冲突',showConflicts));
 if(view==='tasks'&&data.acceptances[0]&&data.batch?.status!=='complete'){
  const start=button(data.batch?'继续固定批次':'启动固定批次',async()=>{await request('/startAcceptance',{acceptanceId:data.acceptances[0].id});await load();},true);start.disabled=!data.runtime.paused||data.runtime.busy;content.querySelector('.toolbar').prepend(start);
 }
 if(view==='tasks'&&data.batch){const attempts=Object.values(data.batch.attempts||{});content.querySelector('.notice').append(' · 已处理 '+data.batch.cursor+'/'+data.batch.count+' · 已收件 '+attempts.filter(a=>a.status==='received').length+(data.batch.reason?' · '+data.batch.reason:''));}
}
function renderProducts(){content.append(el('p',{class:'muted',text:'管理实际产品资料和媒体。历史投稿保存当时的资料版本。'}),toolbar(false));content.querySelector('.toolbar').append(button('新增网站',showCreateProduct),el('label',{class:'archive-toggle'},[el('input',{type:'checkbox','aria-label':'显示已归档产品',...(showArchived?{checked:''}:{}),onchange:event=>{showArchived=event.target.checked;renderRows();}}),'显示已归档产品']));const grid=el('div',{class:'cards'});content.append(grid);renderRows=()=>{grid.replaceChildren(...data.model.products.filter(p=>(showArchived||!p.archived)&&JSON.stringify([p.id,p.name,p.url]).toLowerCase().includes(query.toLowerCase())).map(p=>{
 const cells=data.model.combinations.filter(c=>c.profileId===p.id),card=el('article',{class:'card'},[el('span',{class:'badge',text:p.archived?'已归档':'在用网站'}),el('h2',{text:p.name||p.fields?.Name||p.id}),el('a',{href:p.url||p.fields?.Url||'#',target:'_blank',rel:'noreferrer',text:p.url||p.fields?.Url||''}),el('div',{class:'metrics'},[el('div',{class:'metric'},[el('strong',{text:String(cells.filter(c=>c.submission==='received').length)}),'已收件']),el('div',{class:'metric'},[el('strong',{text:String(cells.filter(c=>c.publication==='published').length)}),'已上线'])]),el('p',{class:'muted',text:p.fields?.['Short description(20-30 words)']||''}),el('div',{class:'controls'},[button('资料与媒体',()=>showProduct(p)),button('删除产品资料',()=>showDeleteProduct(p)),button(p.archived?'恢复产品':'归档产品',async()=>{await request('/libraryMutation',{operation:{type:'profile_archive',profileId:p.id,archived:!p.archived}});await load();}),button('查看投稿',()=>{profileFilter=p.id;view='overview';page=0;render();})])]);return card;}));};renderRows();}

function showCreateProduct(){if(!detail.open)detail.showModal();const panel=$('detail-content'),name=el('input',{'aria-label':'产品名称'}),url=el('input',{type:'url','aria-label':'产品官网'}),message=el('p',{'role':'status'});panel.replaceChildren(el('h2',{text:'新增网站（产品官网）'}),fieldRow('产品名称',name),fieldRow('产品官网',url),button('保存新产品',async()=>{const id='product-'+crypto.randomUUID(),result=await request('/libraryMutation',{operation:{type:'profile_create',profileId:id,profile:{id,name:name.value.trim(),url:url.value.trim(),fields:{Name:name.value.trim(),Url:url.value.trim()}}}});await load();message.textContent=result.pending?'已保存本机，等待同步：'+(result.error||''):'新产品已回读云端';},true),message);}
function showConflicts(){if(!detail.open)detail.showModal();const panel=$('detail-content');panel.replaceChildren(el('h2',{text:'处理同步冲突'}));if(!data.pendingEdits.some(item=>item.status==='conflict'))panel.append(el('p',{text:'所有同步冲突已处理，原编辑与处理记录仍保留。'}));for(const item of data.pendingEdits.filter(item=>item.status==='conflict')){panel.append(el('h3',{text:item.type+' · '+item.id.slice(0,8)}),el('p',{text:'比较两个版本后选择。处理记录保留原编辑和云端版本。',class:'muted'}),el('details',{},[el('summary',{text:'本机编辑'}),el('pre',{text:JSON.stringify(item.operation,null,2)})]),el('details',{},[el('summary',{text:'云端资料 · 版本 '+item.remoteRevision}),el('pre',{text:JSON.stringify(item.operation.profileId?item.remoteData?.[item.operation.profileId]:item.remoteData,null,2)})]),el('div',{class:'controls'},[button('保留云端',()=>resolve('cloud')),button('采用本机编辑',()=>resolve('local'))]));async function resolve(choice){await request('/resolveConflict',{id:item.id,choice,revision:item.remoteRevision});await load();showConflicts();}}}

async function showProduct(product){if(!detail.open)detail.showModal();const panel=$('detail-content');panel.replaceChildren(el('h2',{text:product.name||product.id}));const adjacent=data.model.products.filter(p=>showArchived||!p.archived),position=adjacent.findIndex(p=>p.id===product.id);panel.append(el('div',{class:'controls'},[button('上一个产品',()=>switchProduct(adjacent[(position-1+adjacent.length)%adjacent.length])),button('下一个产品',()=>switchProduct(adjacent[(position+1)%adjacent.length]))]));const form=el('form'),inputs=new Map(),message=el('p',{'role':'status'});function switchProduct(next){if(!next)return;if(form.dataset.savedState!==productFormState(form)&&!confirm('当前产品有未保存编辑，切换会丢弃这些编辑。确定切换？'))return;showProduct(next);}
 for(const [key,value]of Object.entries({...Object.fromEntries(['Name','Url','Title','Business mail','Short description(20-30 words)','Long description (250-500 words)','Tags Keywords/Hashtags','Pricing','Launch Date','Extra Link:X/Twitter/YouTube/Instagram/..'].map(key=>[key,''])),...product.fields})){if(typeof value!=='string'||/password|token|secret|密码/i.test(key))continue;const input=el('textarea',{rows:/description|描述|feature/i.test(key)?4:2,'aria-label':fieldLabel(key)});input.value=value;inputs.set(key,input);form.append(el('label',{class:'field-row'},[el('span',{text:fieldLabel(key)}),input]));}
 const productTools=addProductTools(form,inputs,product,message);const save=el('button',{type:'submit',class:'primary',text:'保存资料'});form.append(save,message);form.addEventListener('submit',async event=>{event.preventDefault();save.disabled=true;try{const fields=Object.fromEntries([...inputs].map(([key,input])=>[key,input.value]));const result=await request('/profile',{profileId:product.id,revision:data.revisions.siteProfiles,profile:{id:product.id,fields,...productTools.values(),...(fields.Name?{name:fields.Name}:{}),...(fields.Url?{url:fields.Url}:{})}});await load();form.dataset.savedState=productFormState(form);message.textContent=result.pending?'已保存到本机，等待云端同步；历史投稿保留旧版本。'+(result.error||''):'已保存并回读云端；历史投稿保留旧版本。';}catch(error){message.textContent='尚未确认，编辑内容保留：'+error.message;}finally{save.disabled=false;}});form.dataset.savedState=productFormState(form);panel.append(form,el('h3',{text:'媒体管理'}));addMediaControls(panel,product);panel.append(el('h3',{text:'媒体预览'}));const media=el('div',{class:'media-grid'});panel.append(media);
 for(const [key,value]of Object.entries({...product.fields,...Object.fromEntries((product.mediaVersions||[]).filter(v=>!Object.values(product.fields||{}).includes(v.ref)).map(v=>['版本 '+v.kind+' '+v.assetId.slice(-8),v.ref]))}).filter(([key,value])=>typeof value==='string'&&/logo|screenshot|featured image|版本/i.test(key)&&value)){const item=el('div',{},[el('p',{text:key.startsWith('版本 ')?key:fieldLabel(key),class:'muted'}),el('p',{text:value,class:'muted'})]);media.append(item);try{let url=value;if(value.startsWith('cloud-media://'))url=await request('/cloud/workspace/media/'+encodeURIComponent(value.slice(14)),undefined,true);else if(!/^https:\/\//.test(value)){item.append(el('p',{class:'badge pending',text:'本机路径，需要原设备素材'}));continue;}const img=el('img',{src:url,alt:key,loading:'lazy',onerror:()=>{img.replaceWith(el('p',{class:'badge pending',text:'图片暂不可读'}));}});item.prepend(img);if(url.startsWith('blob:'))detail.addEventListener('close',()=>URL.revokeObjectURL(url),{once:true});}catch{item.append(el('p',{class:'badge pending',text:'图片暂不可读'}));}}
}


function addProductTools(form,inputs,product,message){
 const meta=new Map(),anchor=new Map(),blog={};form.append(el('h3',{text:'资料提取与生成'}));
 const language=selectControl('产品资料语言',[['auto','自动识别'],['zh-CN','中文'],['en','英文']],product.language||'auto',()=>{}),extractUrl=el('input',{type:'url','aria-label':'提取资料的网站网址',value:product.url||product.fields?.Url||''});
 form.append(fieldRow('网站网址',extractUrl),fieldRow('资料语言',language),el('p',{class:'muted',text:'提取或补全的结果先放入下方编辑表单。检查后点击“保存资料”，才更新产品资料。'}));
 const draftProfile=()=>({id:product.id,fields:Object.fromEntries([...inputs].map(([k,input])=>[k,input.value])),...values()});
 function applyDraft(profile){for(const [key,value]of Object.entries(profile.fields||{})){if(typeof value!=='string'||!value||/password|token|secret/i.test(key))continue;if(!inputs.has(key)){const input=el('textarea',{rows:3,'aria-label':fieldLabel(key)});inputs.set(key,input);form.insertBefore(fieldRow(fieldLabel(key),input),form.querySelector('button[type=submit]'));}inputs.get(key).value=value;}for(const [key,input]of meta)if(profile[key]!==undefined)input.value=Array.isArray(profile[key])?profile[key].join('\n'):profile[key];for(const [key,input]of anchor)if(profile.anchorRules?.[key]!==undefined){if(key==='allowExactMatch')input.checked=profile.anchorRules[key];else input.value=profile.anchorRules[key].join('\n');}for(const [key,input]of Object.entries(blog))if(profile.blogRules?.[key]!==undefined)input.value=profile.blogRules[key];}
 form.append(el('div',{class:'controls'},[button('从网站提取资料',async()=>{const result=await request('/extractProfile',{profileId:product.id,url:extractUrl.value.trim(),language:language.value});applyDraft(result.profile||{});message.textContent='网站资料已提取并填入表单，请检查后保存。';}),button('AI 补全产品资料',async()=>{const result=await request('/generateProfile',{profile:draftProfile(),language:language.value});applyDraft(result.profile||{});message.textContent='资料草稿已补全，请检查后保存。';})]));
 form.append(el('h3',{text:'推广与评论资料'}));for(const [key,label]of [['targetAudience','目标用户'],['valueProposition','产品价值说明'],['useCases','使用场景（每行一项）'],['sellablePoints','产品卖点（每行一项）'],['avoidContent','避免提及的内容（每行一项）']]){const input=el('textarea',{rows:2,'aria-label':label});input.value=Array.isArray(product[key])?product[key].join('\n'):product[key]||'';meta.set(key,input);form.append(fieldRow(label,input));}
 form.append(el('h3',{text:'推广链接文字规则'}));for(const [key,label]of [['brandKeywords','品牌关键词'],['urlKeywords','网址关键词'],['naturalExpressions','自然表达'],['keywordExpressions','关键词表达'],['avoidWords','避免使用的词']]){const input=el('textarea',{rows:2,'aria-label':label});input.value=(product.anchorRules?.[key]||[]).join('\n');anchor.set(key,input);form.append(fieldRow(label+'（每行一项）',input));}const exact=el('input',{type:'checkbox','aria-label':'允许精确匹配关键词'});exact.checked=product.anchorRules?.allowExactMatch===true;anchor.set('allowExactMatch',exact);form.append(fieldRow('允许精确匹配关键词',exact));
 blog.tone=selectControl('默认评论语气',[['helpful','务实'],['professional','专业'],['casual','轻松'],['enthusiastic','热情']],product.blogRules?.tone||'helpful',()=>{});blog.preferredAnchor=selectControl('默认推广链接文字',[['natural','自然表达'],['brand','品牌名称'],['keyword','关键词'],['url','完整网址']],product.blogRules?.preferredAnchor||'natural',()=>{});blog.maxLinksPerDraft=el('input',{type:'number',min:0,max:5,value:product.blogRules?.maxLinksPerDraft??1,'aria-label':'每条评论最多链接数'});for(const [key,label]of [['tone','默认评论语气'],['preferredAnchor','推广链接文字'],['maxLinksPerDraft','每条评论最多链接数']])form.append(fieldRow(label,blog[key]));
 function values(){const split=input=>input.value.split(/\r?\n/).map(v=>v.trim()).filter(Boolean);return{language:language.value,...Object.fromEntries([...meta].map(([k,input])=>[k,['useCases','sellablePoints','avoidContent'].includes(k)?split(input):input.value])),anchorRules:Object.fromEntries([...anchor].map(([k,input])=>[k,k==='allowExactMatch'?input.checked:split(input)])),blogRules:{tone:blog.tone.value,preferredAnchor:blog.preferredAnchor.value,maxLinksPerDraft:Number(blog.maxLinksPerDraft.value)}};}
 return{values};
}
function addMediaControls(panel,product){const kinds={logo:'产品标志图片',featured:'封面',screenshot1:'截图 1',screenshot2:'截图 2',screenshot3:'截图 3',screenshot4:'截图 4'},select=el('select',{'aria-label':'上传媒体类型'},Object.entries(kinds).map(([value,label])=>el('option',{value,text:label}))),message=el('p',{'role':'status'}),file=el('input',{type:'file',accept:'image/png,image/jpeg,image/webp','aria-label':'上传新媒体版本',onchange:async event=>{try{const selected=event.target.files[0];if(!selected)return;if(selected.size>6*1024*1024)throw Error('图片超过 6 MB');file.disabled=true;const dataUrl=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(selected);});const result=await request('/mediaUpload',{profileId:product.id,kind:select.value,fileName:selected.name,dataUrl});await load();message.textContent=result.pending?'图片已存本机，等待同步：'+(result.error||''):'新媒体版本已上传并回读';}catch(error){message.textContent=error.message;}finally{file.disabled=false;}}});panel.append(el('p',{class:'muted',text:'PNG/JPEG/WEBP，最多 6 MB。每次上传保存独立版本，历史任务保留原素材。'}),select,file,button('停用此类媒体',async()=>{await request('/libraryMutation',{operation:{type:'profile_media',profileId:product.id,kind:select.value,action:'disable'}});await load();message.textContent='停用已保存，历史素材保留。';}),message);
 for(const asset of product.mediaVersions||[])panel.append(el('div',{class:'controls'},[el('span',{class:'muted',text:(kinds[asset.kind]||asset.kind)+' · '+asset.fileName+' · '+asset.sha256.slice(0,12)}),button('使用这个版本',async()=>{await request('/libraryMutation',{operation:{type:'profile_media',profileId:product.id,kind:asset.kind,assetId:asset.assetId,action:'restore'}});await load();message.textContent='媒体版本选择已保存。';})]));}


const groupLabels={high_quality:'高质量优先',free_submit:'免费可提交'},accessLabels={free:'免费',freemium:'免费增值',paid:'付费',unknown:'费用待核验'};
const markLabels={can_submit:'可以提交',paid:'需要付费',broken:'网址失效',skip:'暂不提交',needs_otp:'需要邮箱或手机验证码',needs_captcha:'需要完成验证码',needs_login:'需要登录',needs_manual:'需要人工处理',deleted:'已归档'};
function formatTime(value){if(!value)return '暂无记录时间';const time=parseActivityTime(value);if(!Number.isFinite(time))return value==='unknown'?'暂无记录时间':value;const date=new Date(time);return /^\d{5}(?:\.\d+)?$/.test(String(value))?date.toLocaleDateString('zh-CN'):date.toLocaleString('zh-CN',{hour12:false});}
function selectControl(label,choices,value,change){const node=el('select',{'aria-label':label,onchange:event=>change(event.target.value)},choices.map(([value,text])=>el('option',{value,text})));node.value=String(value);return node;}
function checkControl(label,checked,change){const input=el('input',{type:'checkbox','aria-label':label,onchange:event=>change(event.target.checked)});input.checked=checked;return el('label',{class:'check-control'},[input,label]);}
function fieldRow(label,input){return el('label',{class:'field-row'},[el('span',{text:label}),input]);}
function filteredLibrary(){const q=query.toLowerCase();const rows=data.model.library.filter(r=>JSON.stringify([r.site,r.name,r.url,r.category,r.tags,r.row,r.annotation]).toLowerCase().includes(q)&&(!libraryCategory||r.category===libraryCategory)&&(!libraryGroup||r.groups?.includes(libraryGroup))&&(!libraryFavorite||(libraryFavorite==='favorite')===!!r.preferences?.favorite)&&(!libraryEnabled||(libraryEnabled==='enabled')===(r.preferences?.enabled!==false))&&(!libraryAccess||r.accessModel===libraryAccess)&&(!libraryProgress||r.progress?.current===libraryProgress)&&Number(r.quality?.score||0)>=libraryMinQuality&&(!libraryMinDr||r.metrics?.dr!=null&&r.metrics.dr>=libraryMinDr)&&(!profileFilter||!r.preferences?.profileIds?.length||r.preferences.profileIds.includes(profileFilter)));
 return rows.sort((a,b)=>Number(b.pinned)-Number(a.pinned)||(librarySort==='dr'?(b.metrics?.dr??-1)-(a.metrics?.dr??-1):librarySort==='recent'?(parseActivityTime(b.lastActivityAt||b.time)||0)-(parseActivityTime(a.lastActivityAt||a.time)||0):librarySort==='name'?a.site.localeCompare(b.site):Number(b.quality?.score||0)-Number(a.quality?.score||0)));
}
async function savePreferences(row,preferences){const result=await request('/libraryMutation',{operation:{type:'preferences',url:row.url,preferences}});await load();status.textContent=result.pending?'偏好已存本机，等待同步':'收藏与分组已保存并回读云端';}
function renderLibrary(){content.append(el('p',{class:'muted',text:'新增外链网站后自动进入此库。分类、分组、收藏和评分沿用原插件规则；投稿前仍须核对站方费用。'}),toolbar());const tools=content.querySelector('.toolbar');tools.append(button('新增外链网站',showAddTarget,true),button('浏览器当前页加入库并置顶',showBrowserAdd),button('批量导入网址',showImport),button('同步公共外链库',async()=>{await request('/startPublicLibrarySync',{});await load();status.textContent='已开始同步公共外链库，读取完整后合并；付费或不适用的新入口先停用。';}),button('批量打开网站',showQuickOpen),button('批量提交',showBatch),button('查询域名年龄',async()=>{const urls=selectedUrls.size?[...selectedUrls]:filteredLibrary().map(r=>r.url);await request('/startDomainAge',{urls});await load();status.textContent='已开始域名年龄查询，进度见页面下方；不进行投稿。';}),button('选择当前筛选',()=>{filteredLibrary().forEach(r=>selectedUrls.add(r.url));renderRows();}),button('清空选择',()=>{selectedUrls.clear();renderRows();}));
 const filters=el('div',{class:'filter-grid'}),rerender=()=>{page=0;renderRows();};
 filters.append(selectControl('外链分类',[['','全部分类'],...[...new Set(data.model.library.map(r=>r.category).filter(Boolean))].sort().map(v=>[v,v])],libraryCategory,v=>{libraryCategory=v;rerender();}),selectControl('外链分组',[['','全部分组'],...Object.entries(groupLabels)],libraryGroup,v=>{libraryGroup=v;rerender();}),selectControl('收藏状态',[['','全部收藏状态'],['favorite','我的收藏'],['plain','未收藏']],libraryFavorite,v=>{libraryFavorite=v;rerender();}),selectControl('启用状态',[['','全部启用状态'],['enabled','已启用'],['disabled','已停用']],libraryEnabled,v=>{libraryEnabled=v;rerender();}),selectControl('费用类型',[['','全部费用'],...Object.entries(accessLabels)],libraryAccess,v=>{libraryAccess=v;rerender();}),selectControl('提交进度',[['','全部进度'],...['unsubmitted','action_recorded','awaiting_index','pending_moderation','published','needs_follow_up','rejected','link_missing'].map(v=>[v,text(v)])],libraryProgress,v=>{libraryProgress=v;rerender();}),selectControl('最低质量分',[[0,'不限质量分'],[35,'质量分 ≥ 35'],[55,'质量分 ≥ 55'],[75,'质量分 ≥ 75']],libraryMinQuality,v=>{libraryMinQuality=Number(v);rerender();}),selectControl('最低 DR',[[0,'不限 DR'],[20,'DR ≥ 20'],[40,'DR ≥ 40'],[60,'DR ≥ 60'],[80,'DR ≥ 80']],libraryMinDr,v=>{libraryMinDr=Number(v);rerender();}),selectControl('外链排序',[['quality','质量分优先'],['dr','DR 从高到低'],['recent','最近有动态优先'],['name','网站名称排序']],librarySort,v=>{librarySort=v;rerender();}));
 const summary=el('p',{class:'muted','role':'status'}),target=el('div');content.append(filters,summary,target);renderRows=()=>{const rows=filteredLibrary();summary.textContent='筛选到 '+rows.length+' 个入口 · 已选择 '+selectedUrls.size+' 个 · 质量分 0–100：优先 ≥75，可做 ≥55，观察 ≥35；未知 DR 显示为未提供。';paginated(rows,['选择','目标网站 / 分类','质量与权重','收藏 / 分组','提交条件','进度 / 最近动态','操作'],r=>{const selected=el('input',{type:'checkbox','aria-label':'选择 '+r.url,onchange:event=>{event.target.checked?selectedUrls.add(r.url):selectedUrls.delete(r.url);summary.textContent='筛选到 '+rows.length+' 个入口 · 已选择 '+selectedUrls.size+' 个';}});selected.checked=selectedUrls.has(r.url);return el('tr',{},[el('td',{},selected),el('td',{class:'site'},[el('strong',{text:r.name||r.site}),el('div',{class:'muted',text:r.category||'其他目录'}),el('a',{href:r.url,target:'_blank',rel:'noreferrer',text:r.url}),el('div',{class:'muted',text:(sourceLabels[r.row?.source]||sourceLabels[r.source]||'其他导入来源')+' · '+(accessLabels[r.accessModel]||'费用待核验')+' · '+(r.language||'语言未知')})]),el('td',{},[el('span',{class:'badge',title:(r.quality?.reasons||[]).join('；'),text:'质量分 '+(r.quality?.score??'待计算')+' · '+(r.quality?.tier||'待核实')}),el('p',{class:'muted',text:'DR '+(r.metrics?.dr??'未提供')+' · DA '+(r.metrics?.da??'未提供')}),...(r.metrics?.traffic!=null?[el('p',{class:'muted',text:'自然流量 '+r.metrics.traffic})]:[])]),el('td',{},[button(r.preferences?.favorite?'★ 已收藏':'☆ 收藏',()=>savePreferences(r,{favorite:!r.preferences?.favorite})),...(r.groups||[]).map(g=>el('div',{class:'muted',text:groupLabels[g]})),el('div',{class:'muted',text:r.preferences?.enabled===false?'已停用':r.pinned?'已置顶':'已启用'})]),el('td',{text:(r.annotation.statuses||[r.annotation.status]).filter(Boolean).map(v=>markLabels[v]||'待核实').join('、')||'尚未检查'}),el('td',{},[badge(r.progress?.current||'unsubmitted'),el('div',{class:'muted',text:formatTime(r.lastActivityAt||r.time)})]),el('td',{},[button('编辑',()=>showLibrary(r)),button('时间线',()=>showTimeline(r)),button('打开网站',()=>window.open(r.url,'_blank','noopener,noreferrer'))])]);},target);};renderRows();}
function showImport(){if(!detail.open)detail.showModal();const panel=$('detail-content'),input=el('textarea',{rows:10,'aria-label':'导入网址',placeholder:'每行一个 HTTP/HTTPS 网址，最多 500 行'}),message=el('p',{'role':'status'});panel.replaceChildren(el('h2',{text:'批量导入外链网址'}),el('p',{class:'muted',text:'相同入口会去重；原分类、收藏、分组和投稿记录保留。'}),input,button('保存导入',async()=>{const urls=input.value.split(/\r?\n/).map(s=>s.trim()).filter(Boolean);const result=await request('/libraryMutation',{operation:{type:'import',urls}});message.textContent=result.pending?'已存本机，等待同步：'+(result.error||'后台重试'):'已导入并回读云端';await load();},true),message);}
function targetFields(row={}){return ['name','category','tags','dr','da','price','language','accessModel','note'].map(key=>{const label={name:'网站名称',category:'网站分类',tags:'分类标签',dr:'域名评分（DR）',da:'域名权重（DA）',price:'投稿费用',language:'网站语言',accessModel:'费用类型',note:'备注'}[key];const input=key==='accessModel'?selectControl('外链 '+label,Object.entries(accessLabels),row[key]||'unknown',()=>{}):el('input',{'aria-label':'外链 '+label,value:row[key]??row.metrics?.[key]??''});return{key,input,node:fieldRow(label,input)};});}
function showAddTarget(){if(!detail.open)detail.showModal();const panel=$('detail-content'),url=el('input',{type:'url','aria-label':'外链网站网址',placeholder:'https://example.com/submit'}),fields=targetFields(),message=el('p',{'role':'status'});panel.replaceChildren(el('h2',{text:'新增外链网站'}),el('p',{class:'muted',text:'填写要投稿的目标网站入口。你自己的产品官网在“我的网站 → 新增网站”管理。'}),fieldRow('投稿入口网址',url),...fields.map(f=>f.node),button('保存外链网站',async()=>{const result=await request('/libraryMutation',{operation:{type:'create',url:url.value.trim(),fields:Object.fromEntries(fields.map(f=>[f.key,f.input.value]))}});await load();message.textContent=result.pending?'新网站已存本机，等待同步：'+(result.error||''):'新网站已添加并回读云端';},true),message);}
function showLibrary(row){if(!detail.open)detail.showModal();const panel=$('detail-content'),message=el('p',{'role':'status'}),marked=new Set(row.annotation.statuses||[row.annotation.status]);panel.replaceChildren(el('h2',{text:row.name||row.site}),el('a',{href:row.url,target:'_blank',rel:'noreferrer',text:row.url}),el('h3',{text:'提交条件'}),el('p',{class:'muted',text:'可同时记录多个条件。这些条件不代表投稿成功。'}));const marks=el('div',{class:'check-grid'});for(const [value,label]of Object.entries(markLabels))marks.append(checkControl(label,marked.has(value),checked=>checked?marked.add(value):marked.delete(value)));const note=el('textarea',{'aria-label':'站点备注',rows:3});note.value=row.annotation.note||'';panel.append(marks,fieldRow('备注',note),button('保存提交条件',async()=>{const result=await request('/libraryMutation',{operation:{type:'mark',url:row.url,statuses:[...marked].filter(Boolean),note:note.value}});await load();message.textContent=result.pending?'提交条件已存本机，等待同步':'提交条件已保存并回读云端';}),el('h3',{text:'收藏、启用与分组'}));
 const prefs={favorite:!!row.preferences?.favorite,enabled:row.preferences?.enabled!==false,pinned:!!row.pinned,groups:[...(row.groups||[])],profileIds:[...(row.preferences?.profileIds||[])]};const preferences=el('div',{class:'check-grid'},[checkControl('收藏此网站',prefs.favorite,v=>prefs.favorite=v),checkControl('启用此网站',prefs.enabled,v=>prefs.enabled=v),checkControl('置顶此网站',prefs.pinned,v=>prefs.pinned=v)]);for(const [value,label]of Object.entries(groupLabels))preferences.append(checkControl(label,prefs.groups.includes(value),checked=>{prefs.groups=checked?[...new Set([...prefs.groups,value])]:prefs.groups.filter(g=>g!==value);}));panel.append(preferences,el('p',{class:'muted',text:'适用产品：不勾选表示所有产品都可使用这个外链。'}));const assignments=el('div',{class:'check-grid'});for(const product of data.model.products.filter(p=>!p.archived))assignments.append(checkControl('适用于 '+(product.name||product.id),prefs.profileIds.includes(product.id),checked=>{prefs.profileIds=checked?[...prefs.profileIds,product.id]:prefs.profileIds.filter(id=>id!==product.id);}));panel.append(assignments,button('保存收藏与分组',()=>savePreferences(row,prefs)),el('h3',{text:'外链网站资料'}));
 const fields=targetFields(row.row||{});panel.append(...fields.map(f=>f.node),button('保存外链资料',async()=>{const result=await request('/libraryMutation',{operation:{type:row.row?'edit':'create',url:row.url,fields:Object.fromEntries(fields.map(f=>[f.key,f.input.value]))}});await load();message.textContent=result.pending?'资料已存本机，等待同步':'外链资料已保存并回读云端';}),button('查看记录时间线',()=>showTimeline(row)),message,el('details',{},[el('summary',{text:'查看导入时的原始资料'}),el('pre',{text:JSON.stringify(row.row||{},null,2)})]));}
function activityRows(){return(data.model.activity||data.model.combinations.filter(c=>c.hasActivity||c.records?.length||c.events?.length||c.submission==='received'||c.submission==='sent_unconfirmed'||!['not_started','pending','excluded'].includes(c.execution))).filter(c=>(!profileFilter||c.profileId===profileFilter)&&(!overviewState||c.submission===overviewState||c.publication===overviewState||c.progress===overviewState)&&JSON.stringify([c.site,c.url,c.profileId,data.model.products.find(p=>p.id===c.profileId)?.name,c.reason]).toLowerCase().includes(query.toLowerCase()));}
function renderOverview(){const pairs=activityRows();content.append(el('p',{class:'muted',text:'只显示有投稿、实际处理或跟进动态的记录。新增产品自动出现在筛选中；从未处理的目标请到外链库选择。'}),el('div',{class:'top-stats'},[stat('已收件',pairs.filter(c=>c.submission==='received').length),stat('结果待核验',pairs.filter(c=>c.submission==='sent_unconfirmed').length),stat('站方待审核',pairs.filter(c=>c.review==='pending').length),stat('公开上线',pairs.filter(c=>c.publication==='published').length)]),toolbar());content.querySelector('.toolbar').append(selectControl('总览进度',[['','全部动态'],['received','已收件'],['sent_unconfirmed','结果待核验'],['published','已上线'],['pending_moderation','待审核'],['needs_follow_up','需要跟进']],overviewState,v=>{overviewState=v;page=0;renderRows();}));const target=el('div');content.append(target);renderRows=()=>{const rows=activityRows();if(!rows.length){target.replaceChildren(el('p',{class:'empty',text:'暂无处理或提交动态。可以先到外链库选择网站，再预览批量提交。'}));return;}paginated(rows,['目标网站','我的产品','提交与进度','审核 / 上线 / 邮件','最近动态时间','详情'],c=>el('tr',{},[el('td',{class:'site'},el('a',{href:c.url||'https://'+c.site,target:'_blank',rel:'noreferrer',text:c.site})),el('td',{text:data.model.products.find(p=>p.id===c.profileId)?.name||c.profileId}),el('td',{},[badge(c.submission),el('p',{class:'muted',text:text(c.progress||c.execution)})]),el('td',{},[el('div',{text:'审核 '+(c.review==='pending'?'待审核':text(c.review))}),el('div',{text:'上线 '+text(c.publication)+' · '+text(c.sync)}),el('div',{text:'邮件 '+text(c.reply)})]),el('td',{text:formatTime(c.lastActivityAt)}),el('td',{},button('查看动态',()=>showCombination(c)))]),target);};renderRows();}
async function showCombination(cell){if(!detail.open)detail.showModal();const panel=$('detail-content');panel.replaceChildren(el('h2',{text:cell.site+' · '+(data.model.products.find(p=>p.id===cell.profileId)?.name||cell.profileId)}),el('div',{class:'controls'},[badge(cell.submission),badge(cell.execution)]),el('p',{text:cell.reason||''}),...(cell.replyEvidence||[]).map(mail=>button('查看邮件 · '+formatTime(mail.at),()=>showMail(mail.messageId))),...cell.taskIds.map(id=>button('任务详情 '+id.slice(0,8),()=>showTask(id))));appendTimeline(panel,{site:cell.site,url:cell.url||'https://'+cell.site,events:cell.events||[]},cell.profileId);if(cell.records.length)panel.append(el('details',{},[el('summary',{text:'站方收件与历史记录'}),el('pre',{text:JSON.stringify(cell.records,null,2)})]));}
function appendTimeline(panel,row,profileId=''){panel.append(el('h3',{text:'记录时间线'}));const events=(row.events||[]).filter(e=>!profileId||e.profileId===profileId);if(!events.length)panel.append(el('p',{class:'muted',text:'暂无时间线动态。'}));for(const event of events){const item=el('article',{class:'timeline-event'},[el('strong',{text:text(event.type||event.status)+' · '+(data.model.products.find(p=>p.id===event.profileId)?.name||event.profileId)}),el('div',{class:'muted',text:formatTime(event.occurredAt)}),el('p',{text:event.note||''})]);for(const [label,url]of [['查看证据',event.evidenceUrl],['查看公开外链',event.publicUrl]])if(/^https?:\/\//.test(url||''))item.append(el('a',{href:url,target:'_blank',rel:'noreferrer',text:label}));if(event.source!=='migration')item.append(button('编辑动态',()=>showTimelineEditor(row,event)),button('删除动态',async()=>{if(!confirm('删除这条动态？站方收件账本和历史版本仍保留。'))return;await request('/libraryMutation',{operation:{type:'timeline',action:'remove',eventId:event.id}});await load(true);showTimeline(data.model.library.find(r=>r.url===row.url)||{...row,events:(data.model.combinations.find(c=>c.site===row.site&&c.profileId===event.profileId)?.events||[])});}));panel.append(item);}panel.append(button('添加跟进动态',()=>showTimelineEditor(row,null,profileId)));}
function showTimeline(row){if(!detail.open)detail.showModal();const panel=$('detail-content');panel.replaceChildren(el('h2',{text:(row.name||row.site)+' · 提交进度'}));appendTimeline(panel,row);}
function localDate(value){const time=parseActivityTime(value);const date=new Date(Number.isFinite(time)?time:Date.now());return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);}
function showTimelineEditor(row,event,profileId=''){if(!detail.open)detail.showModal();const panel=$('detail-content'),product=selectControl('动态所属产品',data.model.products.map(p=>[p.id,p.name||p.id]),event?.profileId||profileId||data.model.products.find(p=>!p.archived)?.id,()=>{}),type=selectControl('动态类型',['note','submitted','pending_moderation','published','rejected','needs_follow_up','needs_manual','link_missing'].map(v=>[v,text(v)]),event?.type||'note',()=>{}),time=el('input',{type:'datetime-local','aria-label':'动态时间',value:localDate(event?.occurredAt)}),note=el('textarea',{rows:4,'aria-label':'动态说明'}),evidence=el('input',{type:'url','aria-label':'证据网址',value:event?.evidenceUrl||''}),publicUrl=el('input',{type:'url','aria-label':'公开外链网址',value:event?.publicUrl||''}),message=el('p',{'role':'status'});note.value=event?.note||'';if(event)product.disabled=true;panel.replaceChildren(el('h2',{text:event?'编辑时间线动态':'添加时间线动态'}),fieldRow('我的产品',product),fieldRow('进度',type),fieldRow('记录时间',time),fieldRow('说明',note),fieldRow('证据网址',evidence),fieldRow('公开外链网址',publicUrl),button('保存动态',async()=>{if(type.value==='published'&&!publicUrl.value.trim())throw Error('请填写已上线的公开外链网址');const patch={type:type.value,status:type.value,publicationStatus:type.value==='note'?'':type.value,occurredAt:new Date(time.value).toISOString(),note:note.value,evidenceUrl:evidence.value.trim(),publicUrl:publicUrl.value.trim()};let result;if(event)result=await request('/libraryMutation',{operation:{type:'timeline',action:'update',eventId:event.id,patch}});else result=await request('/journalProgress',{event:{...patch,destinationUrl:row.url,profileId:product.value}});await load(true);message.textContent=result.pending?'动态已存本机，等待同步':'动态已保存并回读云端';},true),message);}
function showBatch(){if(!selectedUrls.size)throw Error('请先勾选要提交的外链，或点击“选择当前筛选”');if(!detail.open)detail.showModal();const panel=$('detail-content'),profileIds=new Set(profileFilter?[profileFilter]:[]),message=el('p',{'role':'status'}),choices=el('div',{class:'check-grid'});for(const p of data.model.products.filter(p=>!p.archived))choices.append(checkControl('提交 '+(p.name||p.id),profileIds.has(p.id),checked=>checked?profileIds.add(p.id):profileIds.delete(p.id)));panel.replaceChildren(el('h2',{text:'批量提交 · 选择产品'}),el('p',{text:'已选择 '+selectedUrls.size+' 个外链入口。先预览每个组合和排除原因，再确认启动。'}),choices,button('预览批量提交',async()=>{if(!profileIds.size)throw Error('请至少选择一个产品');const result=await request('/previewBatch',{profileIds:[...profileIds],urls:[...selectedUrls]});showBatchPreview(result.batch);},true),message);}
function showBatchPreview(batch){if(!detail.open)detail.showModal();const panel=$('detail-content'),ready=batch.items.filter(i=>!['excluded','complete'].includes(i.status)),message=el('p',{'role':'status'});panel.replaceChildren(el('h2',{text:'批量提交范围确认'}),el('p',{text:batch.count+' 个组合 · 可安排 '+ready.length+' 个 · 排除 '+batch.items.filter(i=>i.status==='excluded').length+' 个 · '+text(batch.status)}),el('p',{class:'muted',text:'确认后按当前固定列表逐站处理；费用上限为 0。同站已收件和结果未知的任务不会重复提交。'}),table(['产品','目标网站','安排结果'],batch.items.map(i=>el('tr',{},[el('td',{text:data.model.products.find(p=>p.id===i.profileId)?.name||i.profileId}),el('td',{text:i.url}),el('td',{text:i.reason||(i.existingTask?'继续原任务':'新任务')})]))),button('确认并开始批量提交',async()=>{await request('/startBatch',{batchId:batch.id,ordinaryPermissionsAuthorized:true});detail.close();view='tasks';taskScope='all';await load();},true),message);}
function renderComments(){commentStudioState=renderCommentStudio({content,data,profileFilter,el,fieldRow,selectControl,checkControl,button,request,formatTime});}
function renderSettings(){const settings=data.settings||{},filters=settings.targetFilters||{},fields=new Map();content.append(el('h2',{text:'投稿筛选与默认资料'}),el('p',{class:'muted',text:'已有配置从云端回读。历史任务继续保留当时的产品资料。'}));for(const [key,label,value]of [['cfgName','默认联系人姓名',settings.cfgName],['cfgEmail','默认联系邮箱',settings.cfgEmail],['cfgCommentTemplate','默认评论模板',settings.cfgCommentTemplate],['domainBlacklist','域名黑名单（每行一个）',Array.isArray(settings.domainBlacklist)?settings.domainBlacklist.join('\n'):settings.domainBlacklist]]){const input=el('textarea',{rows:key==='domainBlacklist'?5:2,'aria-label':label});input.value=value||'';fields.set(key,input);content.append(fieldRow(label,input));}for(const [key,label]of [['blacklistEnabled','启用域名黑名单'],['requireKnownDomainAge','域名年龄未知也排除'],['aiComments','博客评论使用 AI 生成'],['aiCommentAllowLink','允许 AI 评论包含推广链接'],['showManualFillIcons','显示人工填表提示']])content.append(checkControl(label,key==='requireKnownDomainAge'?filters[key]===true:filters[key]!==false,v=>filters[key]=v));const qualityFields=new Map();for(const [key,label]of [['minOpportunityScore','最低质量分'],['minDr','最低 DR'],['minDa','最低 DA'],['minDomainAgeMonths','最低域名月龄']]){const input=el('input',{type:'number',min:0,max:key==='minDomainAgeMonths'?10000:100,value:filters[key]||0,'aria-label':label});qualityFields.set(key,input);content.append(fieldRow(label+'（0 不限制）',input));}const message=el('p',{'role':'status'});content.append(button('保存设置',async()=>{for(const [key,input]of fields){if(JSON.stringify(settings[key]||'')!==JSON.stringify(input.value))await request('/libraryMutation',{operation:{type:'settings',key,value:input.value}});}await request('/libraryMutation',{operation:{type:'settings',key:'targetFilters',value:{...filters,...Object.fromEntries([...qualityFields].map(([k,input])=>[k,Number(input.value)]))}}});settingsDirty=false;await load();message.textContent=data.pendingEdits?.length?'设置已存本机，等待同步':'设置已保存并回读云端';status.textContent+=' · '+message.textContent;},true),message,el('h3',{text:'备份与导出'}),el('p',{class:'muted',text:'导出产品、外链库和活动记录，不包含连接凭据。'}),button('轻量核对云端版本',showCloudStatus),button('上传本机待同步修改',async()=>{const result=await request('/cloudSyncPush',{});await load(true);status.textContent='本机待同步：资料 '+result.pendingEdits+' · 媒体 '+result.pendingMedia+' · 动态 '+result.pendingTimeline+' · 事件 '+result.pendingEvents;}),button('检查云端媒体',showMediaLibrary),button('导出原格式备份',async()=>{const result=await request('/exportBackup',{});downloadBackup(result.data);}),button('导入原插件备份',()=>showBackupImport()),button('首次迁移到云端',()=>showBackupImport()),button('清空本机工作区',showResetWorkspace));}
function downloadBackup(value){const blob=new Blob([JSON.stringify(value,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=el('a',{href:url,download:'externallink-backup-'+new Date().toISOString().slice(0,10)+'.json'});a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function showBackupImport(){const file=el('input',{type:'file',accept:'application/json,.json','aria-label':'原插件备份文件'}),summary=el('div',{'role':'status'});if(!detail.open)detail.showModal();$('detail-content').replaceChildren(el('h2',{text:'导入原插件备份'}),el('p',{text:'先检查合并范围，再确认导入。已有收件证据保留；同一产品的非空资料按原备份规则合并。媒体路径不会变成实际文件，请保留原素材。'}),file,summary);file.onchange=async()=>{try{const chosen=file.files?.[0];if(!chosen)return;if(chosen.size>8*1024*1024)throw Error('备份文件超过 8 MB');const result=await request('/previewBackup',{backup:JSON.parse(await chosen.text())}),preview=result.preview;summary.replaceChildren(el('p',{text:'备份包含 '+preview.profilesImported+' 个产品、'+preview.recordsImported+' 条账本记录、'+preview.targetsImported+' 个外链入口；将合并 '+preview.changes.length+' 类资料。'}),button('确认合并导入',async()=>{const result=await request('/importBackup',{id:preview.id});await load();summary.replaceChildren(el('p',{text:result.remaining?'导入已存本机，尚有 '+result.remaining+' 类资料待同步或解决冲突':'备份已合并并回读云端'}));if(result.remaining)summary.append(button('继续同步此备份',async()=>{const next=await request('/importBackup',{id:preview.id});await load();summary.textContent=next.remaining?'仍有待同步资料':'备份已完成云端回读';}));},true));}catch(error){summary.textContent=error.message;}};}

function renderTasks(){for(const batch of (data.workbenchBatches||[]).filter(b=>b.status!=='preview'))content.append(el('div',{class:'notice'},[el('strong',{text:'自选批次 · '+text(batch.status)+' · '+batch.cursor+'/'+batch.count}),el('p',{text:'已收件 '+batch.items.filter(i=>i.result==='received').length+' · 待核验 '+batch.items.filter(i=>i.result==='sent_unconfirmed').length+' · 排除 '+batch.items.filter(i=>i.status==='excluded').length}),button('查看批次范围',()=>showBatchPreview(batch))]));const frozen=data.acceptances[0],execution=frozen?.execution?.items||{},fixedIds=new Set(Object.values(execution).map(i=>i.taskId));content.append(el('div',{class:'notice',text:'执行器'+(data.runtime.paused?'已暂停':'运行中')+' · '+(data.runtime.busy?'正在处理原任务':'空闲')+' · 待同步 '+data.runtime.pendingEvents+(frozen?' · 固定验收 '+frozen.count+' 个组合':'')}),el('div',{class:'toolbar'},[button('暂停执行',async()=>{await request('/pause',{});await load();}),button('同步与核验',async()=>{await request('/sync',{});await load(true);}),...(frozen?[button('恢复原范围注册',async()=>{await request('/registerAcceptance',{...(frozen?{acceptanceId:frozen.id}:{})});await load();})]:[])]),toolbar());const scope=el('select',{'aria-label':'任务范围',onchange:event=>{taskScope=event.target.value;page=0;renderRows();}},[el('option',{value:'fixed',text:'本次固定验收'}),el('option',{value:'all',text:'所有历史任务'})]);scope.value=taskScope;content.querySelector('.toolbar').append(scope);const target=el('div');content.append(target);renderRows=()=>{const tasks=data.tasks.filter(t=>(taskScope!=='fixed'||fixedIds.has(t.id))&&(!profileFilter||t.profileId===profileFilter)&&JSON.stringify([t.url,t.profileId,t.status,t.reason]).toLowerCase().includes(query.toLowerCase()));paginated(tasks,['产品','目标站','执行','收件','同步','详情'],t=>el('tr',{},[el('td',{text:data.model.products.find(p=>p.id===t.profileId)?.name||t.profileId}),el('td',{text:t.url,class:'site'}),el('td',{},[badge(t.status),el('p',{class:'muted',text:t.reason||''})]),el('td',{},badge(t.receipt?'received':t.attemptBoundary?'sent_unconfirmed':'not_submitted')),el('td',{},badge(t.syncStatus)),el('td',{},button('查看',()=>showTask(t.id)))]),target);};renderRows();}
async function showTask(id){const {task}=await request('/taskDetails',{taskId:id});if(!detail.open)detail.showModal();const panel=$('detail-content');panel.replaceChildren(el('h2',{text:(data.model.products.find(p=>p.id===task.profileId)?.name||task.profileId)+' · '+task.url}),el('div',{class:'controls'},[badge(task.status),badge(task.receipt?'received':task.attemptBoundary?'sent_unconfirmed':'not_submitted')]),el('p',{text:task.reason||''}));const frozen=data.acceptances.find(f=>f.execution&&Object.values(f.execution.items).some(i=>i.taskId===id));
 if(!task.attemptBoundary&&!task.receipt&&['pending','needs_manual'].includes(task.status)){panel.append(el('div',{class:'controls'},[button('检测原页',async()=>{const result=await request('/detectOriginalTask',{taskId:id});const report=el('div');report.append(el('h3',{text:'原页面检测结果'}),...result.frames.map(f=>el('p',{text:(f.platform||'普通表单')+' · 可填写字段 '+f.formFieldCount+' 个 · '+(f.operable?'存在可操作表单':'未找到可操作表单')+' · '+(f.commentFound?'有评论区':'未发现评论区')+' · '+(f.hasCaptcha?'需要验证码':'未发现验证码')})));panel.append(report);}),button('准备原任务',async()=>{const result=await request('/prepareTask',{taskId:id,...(frozen?{acceptanceId:frozen.id}:{})});status.textContent=result.prepared?'原任务资料已准备，尚未提交':'准备待处理：'+result.reason;await load();await showTask(id);}),...(frozen?[button('运行原任务',async()=>{await request('/runTask',{taskId:id,acceptanceId:frozen.id});detail.close();await load();},true)]:[])]));}
 if(task.attemptBoundary&&!task.receipt)panel.append(el('p',{class:'notice',text:'存在提交尝试边界，必须先核验原页面；不会创建重复投稿。'}),button('核验原任务',async()=>{await request('/verify',{taskId:id});await load(true);await showTask(id);}));
 for(const [label,value]of [['实际提交内容',task.actualSubmission],['实际准备内容',task.actualPreparation],['站方回执',task.receipt],['AI 接管',task.aiTakeover],['已用媒体',task.usedMedia],['登录记录',task.authAttempts]])if(value)panel.append(el('h3',{text:label}),el('pre',{text:JSON.stringify(value,null,2)}));
 if(task.screenshot)try{const result=await request('/evidence/'+id);panel.append(el('h3',{text:'原任务页面证据'}),el('img',{src:result.dataUrl,class:'evidence',alt:'原任务页面截图'}));}catch{panel.append(el('p',{class:'muted',text:'截图暂不可读，原记录保留。'}));}
}
async function showMail(messageId){const {message}=await request('/gmailMessage',{messageId});if(!detail.open)detail.showModal();$('detail-content').replaceChildren(el('h2',{text:message.subject||'关联邮件'}),el('p',{text:message.from+' · '+new Date(message.at).toLocaleString()}),el('p',{class:'notice',text:'只读邮件证据；审核与上线状态需要独立核验。'}),el('pre',{text:message.text}),el('p',{class:'muted',text:'SHA256 '+message.sha256}));}
async function showGmail(){const {gmail}=await request('/gmailStatus',{});if(!detail.open)detail.showModal();const panel=$('detail-content');panel.replaceChildren(el('h2',{text:'Gmail 只读连接'}),el('p',{text:'仅读取邮件，凭据保存于本机系统凭据库。连接后每分钟增量同步；不会发送邮件或修改邮箱。'}),el('pre',{text:JSON.stringify(gmail,null,2)}));
 if(gmail.refreshGrantExpiresAt)panel.append(el('p',{class:'notice',text:'Google 当前授权有效至 '+new Date(gmail.refreshGrantExpiresAt).toLocaleString()+'，届时需重新授权。'}));
 const file=el('input',{type:'file',accept:'.json','aria-label':'Google 桌面客户端 JSON',onchange:async event=>{try{const selected=event.target.files[0];if(!selected)return;if(selected.size>32768)throw Error('客户端 JSON 过大');await request('/gmailConfigure',{client:JSON.parse(await selected.text())});await showGmail();}catch(error){status.textContent=error.message;}}});panel.append(el('label',{text:'导入 Google Cloud 桌面应用客户端 JSON'}),file,
 button('开始本机只读授权',async()=>{const result=await request('/gmailAuthorize',{});panel.append(el('a',{href:result.authorizationUrl,target:'_blank',rel:'noreferrer',text:'打开 Google 只读授权页面'}));}),button('同步邮箱',async()=>{await request('/gmailSync',{});await showGmail();}),button('验证令牌续期',async()=>{await request('/gmailRefresh',{});await showGmail();}));}
$('gmail-settings').onclick=()=>showGmail().catch(error=>status.textContent=error.message);
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',async()=>{try{if(view==='comments')await commentStudioState?.saveCurrent();if(view==='settings'&&settingsDirty&&!confirm('设置有未保存编辑，确定离开？'))return;view=b.dataset.view;settingsDirty=false;page=0;query='';render();}catch(error){status.textContent=error.message;}}));$('close-detail').onclick=()=>detail.close();$('refresh').onclick=async()=>{const b=$('refresh');b.disabled=true;try{await load(true);}catch(error){status.textContent=error.message;}finally{b.disabled=false;}};
try{const connection=await request('/connection');access=null;if(connection.setupRequired){showSetup({connection,content,status,el,button,request});}else{await load();setInterval(async()=>{if(!detail.open&&!document.activeElement?.matches('input,textarea,select'))try{await load();}catch(error){status.textContent='本机后台暂不可达，当前资料仍保留：'+error.message;}},15000);}}catch(error){status.textContent='暂未连接：'+error.message;content.append(el('p',{class:'notice',text:'请使用本机统一启动入口打开；登录态和原任务不会被清空。'}));}

function renderDataJobs(){for(const job of data.publicLibraryJobs||[])content.append(el('div',{class:'notice'},[el('p',{text:'公共库同步 · '+(job.status==='completed'?'已完成':job.status==='running'?'读取与合并中':'已暂停')+(job.stats?' · 新增 '+job.stats.added+' · 更新 '+job.stats.updated+' · 安全停用 '+job.stats.safetyDisabled:'')+(job.error?' · '+job.error:'')}),...(!['running','completed'].includes(job.status)?[button('继续原公共库同步',async()=>{await request('/startPublicLibrarySync',{jobId:job.id});await load();})]:[])]));for(const job of data.linkMonitorJobs||[])content.append(el('div',{class:'notice'},[el('p',{text:'外链监测 '+job.cursor+' / '+job.count+' · '+(job.status==='completed'?'已完成':job.status==='running'?'检测中':'已暂停')+(job.error?' · '+job.error:'')}),...(!['running','completed'].includes(job.status)?[button('继续原外链监测',async()=>{await request('/startLinkMonitor',{jobId:job.id});await load();})]:[])]));for(const job of data.domainAgeJobs||[])content.append(el('div',{class:'notice'},[el('p',{text:'域名年龄查询 '+job.cursor+' / '+job.count+' · '+(job.status==='completed'?'已完成':job.status==='running'?'查询中':'已暂停')+(job.error?' · '+job.error:'')}),...(!['completed','running'].includes(job.status)?[button('继续原查询',async()=>{await request('/startDomainAge',{jobId:job.id});await load();})]:[])]));for(const plan of data.backupImports||[])if(plan.status==='queued')content.append(el('div',{class:'notice'},[el('p',{text:'备份导入待同步 '+plan.remaining+' / '+plan.count+' 类资料'}),button('继续原备份导入',async()=>{await request('/importBackup',{id:plan.id});await load();})]));}


function renderMonitorSettings(){const schedule=data.settings?.linkMonitorSchedule||{enabled:true,minutes:1440};let enabled=schedule.enabled!==false,desktopNotifications=schedule.desktopNotifications!==false;const minutes=el('input',{type:'number',min:15,max:10080,value:schedule.minutes||1440,'aria-label':'外链监测间隔（分钟）'});content.append(el('h3',{text:'外链存活监测'}),el('p',{class:'muted',text:'检查已有收件记录中的公开链接，记录是否仍包含我的网站，以及链接的 follow 属性。无法访问时标记待复查，不抹掉历史收件。定时检测由本机后台执行。'}),checkControl('启用定时外链监测',enabled,v=>enabled=v),checkControl('链接变化时发送桌面提醒（后台有效）',desktopNotifications,v=>desktopNotifications=v),fieldRow('检测间隔（分钟）',minutes),el('div',{class:'controls'},[button('保存监测计划',async()=>{await request('/libraryMutation',{operation:{type:'settings',key:'linkMonitorSchedule',value:{enabled,minutes:Number(minutes.value),desktopNotifications}}});await load();}),button('立即检测外链',async()=>{await request('/startLinkMonitor',{});await load();})]));const rows=Object.entries(data.linkMonitorResults||{}).sort(([,a],[,b])=>(parseActivityTime(b.checkedAt)||0)-(parseActivityTime(a.checkedAt)||0));if(!rows.length){content.append(el('p',{class:'muted',text:'尚无监测结果。'}));return;}const table=el('table'),head=el('thead',{},el('tr',{},['公开页面','推广产品','结果','链接属性','检测时间'].map(label=>el('th',{text:label})))),body=el('tbody');for(const [key,result]of rows){const productId=key.split('::').slice(1).join('::'),product=data.model.products.find(p=>p.id===productId);body.append(el('tr',{},[el('td',{},el('a',{href:result.url,target:'_blank',rel:'noreferrer',text:result.url||'缺少公开网址'})),el('td',{text:product?.name||productId||'待核对'}),el('td',{},[el('span',{text:monitorLabels[result.status]||'待核对'}),...(result.error?[el('p',{class:'muted',text:result.error})]:[])]),el('td',{text:({dofollow:'正常跟随',nofollow:'不跟随',ugc:'用户内容',sponsored:'赞助链接'})[result.rel]||'未确认'}),el('td',{text:formatTime(result.checkedAt)})]));}table.append(head,body);content.append(el('div',{class:'table-wrap'},table));}
function renderMonitorAlerts(){for(const alert of data.monitorAlerts||[])content.prepend(el('div',{class:'notice'},[el('strong',{text:'外链状态发生变化'}),el('p',{text:(data.model.products.find(p=>p.id===alert.profileId)?.name||'我的网站')+' · '+(monitorLabels[alert.status]||'请人工复查')}),el('a',{href:alert.url,target:'_blank',rel:'noreferrer',text:'打开原公开页面'}),button('已查看',async()=>{await request('/dismissMonitorAlert',{id:alert.id});await load();})]));}
