export function renderCommentStudio({content,data,profileFilter,el,fieldRow,selectControl,checkControl,button,request,formatTime}){
 const product=selectControl('评论推广产品',data.model.products.filter(p=>!p.archived).map(p=>[p.id,p.name||p.id]),profileFilter||data.model.products.find(p=>!p.archived)?.id,()=>changeTarget()),url=el('input',{type:'url','aria-label':'评论页面网址',placeholder:'https://example.com/article'}),context=el('textarea',{rows:5,'aria-label':'文章内容',placeholder:'可粘贴文章内容；留空时读取网址正文'}),tone=selectControl('评论语气',[['helpful','务实'],['professional','专业'],['casual','轻松'],['enthusiastic','热情']],'helpful',()=>{}),language=selectControl('评论语言',[['auto','跟随页面语言'],['zh','中文'],['zh-CN','中文（简体）'],['en','英文']],'auto',()=>{}),maxChars=el('input',{type:'number',min:80,max:2000,value:700,'aria-label':'评论字数上限'}),drafts=el('div',{class:'cards'}),history=el('div'),message=el('p',{role:'status'});
 let allowLink=data.settings?.targetFilters?.aiCommentAllowLink!==false,areas=[],draftTarget=null;
 const config=()=>({profileId:product.value,pageUrl:url.value.trim(),tone:tone.value,language:language.value,maxChars:Number(maxChars.value),allowLink});
 const reset=()=>{areas=[];draftTarget=null;drafts.replaceChildren();history.replaceChildren();};url.onchange=changeTarget;async function changeTarget(){try{await saveCurrent();reset();}catch(error){message.textContent=error.message;}}
 async function saveCurrent(){if(!areas.length)return; await request('/saveCommentVersion',{...config(),...draftTarget,drafts:areas.map(a=>({text:a.value}))});}
 function show(payload){reset();draftTarget={profileId:product.value,pageUrl:url.value.trim()};tone.value=payload.tone||tone.value;language.value=payload.language||language.value;maxChars.value=payload.maxChars||maxChars.value;if(payload.allowLink!==undefined){allowLink=payload.allowLink;allowInput.checked=allowLink;}
  payload.drafts.forEach((draft,index)=>{const area=el('textarea',{rows:7,'aria-label':'评论候选 '+(index+1)});area.value=draft.text;areas.push(area);const count=el('p',{class:'muted',text:area.value.length+' / '+maxChars.value+' 字'});area.oninput=()=>count.textContent=area.value.length+' / '+maxChars.value+' 字';drafts.append(el('article',{class:'card'},[el('h3',{text:'候选 '+(index+1)}),area,count,button('复制评论',async()=>{await navigator.clipboard.writeText(area.value);message.textContent='已复制评论草稿';}),button('填入原任务评论区',async()=>{const host=v=>new URL(v).hostname.replace(/^www\./,'');const matches=data.tasks.filter(t=>t.profileId===product.value&&host(t.url)===host(url.value)&&!t.attemptBoundary&&!t.receipt&&['pending','needs_manual'].includes(t.status));if(matches.length!==1)throw Error('请先在运行任务中准备对应的原任务页面；不新建重复投稿');const result=await request('/fillCommentDraft',{taskId:matches[0].id,text:area.value});message.textContent=result.filled?'评论已填入并核验，尚未提交':'评论尚未确认';})]));});
 }
 async function showHistory(){const result=await request('/commentHistory',config());history.replaceChildren(el('p',{class:'muted',text:'按产品和文章保存最近 9 版，包括编辑后的候选。'}),...result.versions.map(version=>button('载入 '+formatTime(version.at),async()=>{await saveCurrent();show(version.payload);await showHistory();message.textContent='历史草稿已载入，未填表或发布。';})));return result.versions;}
 const allowControl=checkControl('允许草稿包含推广链接',allowLink,v=>allowLink=v),allowInput=allowControl.querySelector('input');
 content.append(el('h2',{id:'comment-studio',text:'AI 评论草稿'}),el('p',{class:'muted',text:'根据文章内容生成 3 条候选；可编辑、复制和恢复历史版本。'}),fieldRow('我的产品',product),fieldRow('文章网址',url),fieldRow('文章正文',context),fieldRow('语气',tone),fieldRow('语言',language),fieldRow('字数上限',maxChars),allowControl,button('生成 3 条评论',async()=>{await saveCurrent();const result=await request('/commentDrafts',{...config(),pageText:context.value});show({...config(),drafts:result.drafts});await showHistory();message.textContent='评论已生成并保存在本机。';},true),button('保存编辑后的草稿',async()=>{if(!areas.length)throw Error('请先生成或载入草稿');await saveCurrent();await showHistory();message.textContent='编辑后的草稿已保存。';}),button('载入最近草稿',async()=>{const versions=await request('/commentHistory',config());if(!versions.versions.length)throw Error('此产品和文章尚无草稿');show(versions.versions[0].payload);await showHistory();}),button('恢复上一版',async()=>{await saveCurrent();const result=await request('/commentHistory',config()),version=result.versions[areas.length?1:0];if(!version)throw Error('尚无上一版草稿');show(version.payload);await showHistory();message.textContent='上一版已恢复，当前版本仍在历史记录中。';}),message,drafts,history);return{saveCurrent};
}
