export function renderCommentStudio({content,data,profileFilter,el,fieldRow,selectControl,checkControl,button,request,formatTime}){
 const product=selectControl('评论推广产品',data.model.products.filter(p=>!p.archived).map(p=>[p.id,p.name||p.id]),profileFilter||data.model.profileSelection?.activeSiteId||data.model.products.find(p=>!p.archived)?.id,()=>changeTarget()),url=el('input',{type:'url','aria-label':'评论页面网址',placeholder:'https://example.com/article'}),context=el('textarea',{rows:5,'aria-label':'文章内容',placeholder:'可粘贴文章内容；留空时读取网址正文'}),tone=selectControl('评论语气',[['helpful','务实'],['professional','专业'],['casual','轻松'],['enthusiastic','热情']],'helpful',()=>{}),language=selectControl('评论语言',[['auto','跟随页面语言'],['zh','中文'],['zh-CN','中文（简体）'],['en','英文']],'auto',()=>{}),maxChars=el('input',{type:'number',min:80,max:2000,value:700,'aria-label':'评论字数上限'}),drafts=el('div',{class:'cards'}),history=el('div'),message=el('p',{role:'status'});
 const plainComment=el('textarea',{rows:7,'aria-label':'手输评论（无候选也可保存）'}),plainRow=fieldRow('手输评论',plainComment);
 let allowLink=data.settings?.targetFilters?.aiCommentAllowLink!==false,areas=[],draftInfo=[],draftTarget=null,epoch=0,disposed=false,busy=false,selected=-1,selectionTracked=false,selectionButtons=[];
 const config=()=>({profileId:product.value,pageUrl:url.value.trim(),tone:tone.value,language:language.value,maxChars:Number(maxChars.value),allowLink});
 const current=(owner,version)=>!disposed&&epoch===version&&product.value===owner.profileId&&url.value.trim()===owner.pageUrl;
 const reset=()=>{areas=[];draftInfo=[];draftTarget=null;selected=-1;selectionTracked=false;selectionButtons=[];plainComment.value='';plainRow.hidden=false;drafts.replaceChildren();history.replaceChildren();};
 plainComment.oninput=()=>{draftTarget??={profileId:product.value,pageUrl:url.value.trim()};};
 url.onchange=changeTarget;
 async function changeTarget(){const version=++epoch;try{await saveCurrent();if(!disposed&&version===epoch)reset();}catch(error){message.textContent=error.message;}}
 async function saveCurrent({beforeSwitch=false,label}={}){if(!areas.length&&!plainComment.value.trim())return;await request('/saveCommentVersion',{...config(),...draftTarget,...(beforeSwitch?{captureBeforeSwitch:true}:{}),...(label?{label}:{}),...(!areas.length?{text:plainComment.value}:selectionTracked?{selected,text:areas[selected]?.value||''}:{}),drafts:areas.map((area,index)=>({...draftInfo[index],text:area.value}))});}
 const operation=run=>async()=>{if(busy)throw Error('评论操作进行中，请等待完成');busy=true;try{return await run();}finally{busy=false;}};
 function show(payload){reset();draftTarget={profileId:payload.profileId||product.value,pageUrl:payload.pageUrl||url.value.trim()};tone.value=payload.tone||tone.value;language.value=payload.language||language.value;maxChars.value=payload.maxChars||maxChars.value;if(payload.allowLink!==undefined){allowLink=payload.allowLink;allowInput.checked=allowLink;}
  draftInfo=payload.drafts.map(draft=>({...draft}));selected=Number.isInteger(payload.selected)&&payload.selected>=0&&payload.selected<draftInfo.length?payload.selected:draftInfo.length?0:-1;selectionTracked=Number.isInteger(payload.selected);plainComment.value=payload.text||'';plainRow.hidden=draftInfo.length>0;draftInfo.forEach((draft,index)=>{const area=el('textarea',{rows:7,'aria-label':'评论候选 '+(index+1)});area.value=draft.text;areas.push(area);const count=el('p',{class:'muted',text:area.value.length+' 字'});area.oninput=()=>{draftInfo[index].chars=area.value.length;count.textContent=area.value.length+' 字';};const selectButton=button('选择候选 '+(index+1),operation(async()=>{if(selected===index)return;const owner={...draftTarget},started=epoch;selectionTracked=true;const captured=!!areas[selected]?.value.trim();if(captured)await saveCurrent({beforeSwitch:true,label:'切换候选前'});if(!current(owner,started))return;selected=index;selectionButtons.forEach((node,i)=>node.setAttribute('aria-pressed',String(i===selected)));if(captured)await showHistory(owner,started);message.textContent='已选择候选 '+(index+1)+(captured?'，切换前的草稿已保存。':'，可编辑后填写。');}));selectButton.setAttribute('aria-pressed',String(index===selected));selectionButtons.push(selectButton);drafts.append(el('article',{class:'card'},[selectButton,el('h3',{text:'候选 '+(index+1)+(draft.angle?' · '+draft.angle:'')}),area,count,button('复制评论',async()=>{await navigator.clipboard.writeText(area.value);message.textContent='已复制评论草稿';}),button('填入原任务评论区',operation(async()=>{const owner={...draftTarget};if(!current(owner,epoch))throw Error('产品或文章已切换，请先载入对应草稿');const host=value=>new URL(value).hostname.replace(/^www\./,'');const matches=data.tasks.filter(task=>task.profileId===owner.profileId&&host(task.url)===host(owner.pageUrl)&&!task.attemptBoundary&&!task.receipt&&['pending','needs_manual'].includes(task.status));if(matches.length!==1)throw Error('请先在运行任务中准备对应的原任务页面；不新建重复投稿');const result=await request('/fillCommentDraft',{taskId:matches[0].id,text:area.value,...owner});message.textContent=result.filled?'评论已填入并核验，尚未提交':'评论尚未确认';}))]));});
 }
 async function showHistory(owner=config(),version=epoch){const result=await request('/commentHistory',owner);if(!current(owner,version))return result.versions;history.replaceChildren(el('p',{class:'muted',text:'按产品和文章保存最近 9 版，包括编辑后的候选。'}),...result.versions.map(saved=>button('载入 '+(saved.label?saved.label+' · ':'')+formatTime(saved.at),operation(async()=>{const selected=config(),started=epoch;await saveCurrent({label:'恢复前'});if(!current(selected,started))return;show({...selected,...saved.payload});await showHistory(selected,started);message.textContent='历史草稿已载入，未填表或发布。';}))));return result.versions;}
 const allowControl=checkControl('允许草稿包含推广链接',allowLink,value=>allowLink=value),allowInput=allowControl.querySelector('input');
 content.append(el('h2',{id:'comment-studio',text:'AI 评论草稿'}),el('p',{class:'muted',text:'根据文章内容生成 3 条候选；可编辑、复制和恢复历史版本。'}),fieldRow('我的产品',product),fieldRow('文章网址',url),fieldRow('文章正文',context),fieldRow('语气',tone),fieldRow('语言',language),fieldRow('生成字数上限',maxChars),allowControl,plainRow,
  button('生成 3 条评论',operation(async()=>{const owner={...config(),count:3,pageText:context.value,refresh:true},started=epoch;await saveCurrent({label:'重新生成前'});if(!current(owner,started))return;const result=await request('/commentDrafts',owner);if(!current(owner,started)){message.textContent='产品或文章已切换，已放弃旧评论结果。';return;}if(!Array.isArray(result.drafts)||!result.drafts.some(draft=>draft.text?.trim()))throw Error('AI 评论生成失败，请确认文章正文足够长');const hadPrevious=areas.length>0||!!plainComment.value.trim();if(hadPrevious){await saveCurrent({label:'重新生成前'});if(!current(owner,started))return;}show({...owner,...result});if(hadPrevious)await saveCurrent();await showHistory(owner,started);message.textContent='评论已生成并保存在本机。';}),true),
  button('保存编辑后的草稿',operation(async()=>{if(!areas.length&&!plainComment.value.trim())throw Error('请先输入评论或载入草稿');const owner=config(),started=epoch;await saveCurrent();if(!current(owner,started))return;await showHistory(owner,started);message.textContent='编辑后的草稿已保存。';})),
  button('载入最近草稿',operation(async()=>{const owner=config(),started=epoch;const result=await request('/commentHistory',owner);if(!current(owner,started))return;if(!result.versions.length)throw Error('此产品和文章尚无草稿');await saveCurrent({label:'恢复前'});if(!current(owner,started))return;show({...owner,...result.versions[0].payload});await showHistory(owner,started);})),
  button('恢复上一版',operation(async()=>{const owner=config(),started=epoch;await saveCurrent({label:'恢复前'});if(!current(owner,started))return;const result=await request('/commentHistory',owner);if(!current(owner,started))return;const saved=result.versions[areas.length||plainComment.value.trim()?1:0];if(!saved)throw Error('尚无上一版草稿');show({...owner,...saved.payload});await showHistory(owner,started);message.textContent='上一版已恢复，当前版本仍在历史记录中。';})),message,drafts,history);
 return{saveCurrent,dispose(){disposed=true;epoch++;}};
}
