export function renderCommentStudio({content,data,profileFilter,el,fieldRow,selectControl,checkControl,button,request,formatTime}){
 const product=selectControl('评论推广产品',data.model.products.filter(p=>!p.archived).map(p=>[p.id,p.name||p.id]),profileFilter||data.model.profileSelection?.activeSiteId||data.model.products.find(p=>!p.archived)?.id,()=>changeTarget()),url=el('input',{type:'url','aria-label':'评论页面网址',placeholder:'https://example.com/article'}),context=el('textarea',{rows:5,'aria-label':'文章内容',placeholder:'可粘贴文章内容；留空时读取网址正文'}),tone=selectControl('评论语气',[['helpful','务实'],['professional','专业'],['casual','轻松'],['enthusiastic','热情']],'helpful',()=>{}),language=selectControl('评论语言',[['auto','跟随页面语言'],['zh','中文'],['zh-CN','中文（简体）'],['en','英文']],'auto',()=>{}),maxChars=el('input',{type:'number',min:80,max:2000,value:700,'aria-label':'评论字数上限'}),drafts=el('div',{class:'cards'}),history=el('div',{'aria-label':'评论历史版本'}),message=el('p',{role:'status'});
 const plainComment=el('textarea',{rows:7,'aria-label':'手输评论（无候选也可保存）'}),plainRow=fieldRow('手输评论',plainComment);
 let selectedBrowserPage=null;const browserPage=el('select',{'aria-label':'评论使用的执行器网页'}),browserPageRow=fieldRow('已打开的文章页',browserPage);browserPageRow.hidden=true;browserPage.onchange=()=>{const option=browserPage.selectedOptions[0];if(!option?.dataset.url)return;selectedBrowserPage={targetId:option.value,pageUrl:option.dataset.url};url.value=option.dataset.url;changeTarget();};
 let allowLink=data.settings?.targetFilters?.aiCommentAllowLink!==false,areas=[],draftInfo=[],draftTarget=null,epoch=0,disposed=false,busy=false,selected=-1,selectionTracked=false,selectionButtons=[];
 const config=()=>({profileId:product.value,pageUrl:url.value.trim(),tone:tone.value,language:language.value,maxChars:Number(maxChars.value),allowLink,...(selectedBrowserPage?.pageUrl===url.value.trim()?{targetId:selectedBrowserPage.targetId}:{})});
 const current=(owner,version)=>!disposed&&epoch===version&&product.value===owner.profileId&&url.value.trim()===owner.pageUrl;
 const reset=()=>{areas=[];draftInfo=[];draftTarget=null;selected=-1;selectionTracked=false;selectionButtons=[];plainComment.value='';plainRow.hidden=false;drafts.replaceChildren();history.replaceChildren(el('div',{class:'empty-state compact-empty',text:'生成或编辑后，这里会保留上一版'}));if(restorePrevious)restorePrevious.disabled=true;};
 plainComment.oninput=()=>{draftTarget??={profileId:product.value,pageUrl:url.value.trim()};};
 url.onchange=()=>{selectedBrowserPage=null;changeTarget();};
 async function changeTarget(){const version=++epoch;try{await saveCurrent();if(!disposed&&version===epoch)reset();}catch(error){message.textContent=error.message;}}
 const currentPayload=()=>({tone:tone.value,language:language.value,maxChars:Number(maxChars.value),allowLink,selected,text:areas.length?areas[selected]?.value||'':plainComment.value,drafts:areas.map((area,index)=>({...draftInfo[index],text:area.value}))});
 async function saveCurrent({label,capture=true,allowEmpty=false}={}){if(!areas.length&&!plainComment.value.trim()){if(!allowEmpty)return;const owner={...config(),...draftTarget},started=epoch,previous=await request('/originalCommentState',owner);if(!current(owner,started))return;return request('/captureOriginalCommentState',{...owner,capture:false,current:previous.active||previous.versions[0]?.payload||currentPayload()});}return request('/captureOriginalCommentState',{...config(),...draftTarget,...(label?{label}:{}),capture,current:currentPayload()});}
 async function restoreSaved(saved,messageText='历史草稿已载入，未填表或发布。'){const owner=config(),started=epoch,before=JSON.stringify(currentPayload()),result=await request('/restoreOriginalCommentState',{...owner,versionId:saved.id,current:currentPayload()});if(!current(owner,started))return;if(JSON.stringify(currentPayload())!==before)throw Error('评论已变化，当前输入保留。');show({...owner,...result.active});await showHistory(owner,started);message.textContent=messageText;}

 const operation=run=>async()=>{if(busy)throw Error('评论操作进行中，请等待完成');busy=true;try{return await run();}finally{busy=false;}};
 function show(payload){reset();draftTarget={profileId:payload.profileId||product.value,pageUrl:payload.pageUrl||url.value.trim(),...(payload.targetId?{targetId:payload.targetId}:{})};tone.value=payload.tone||tone.value;language.value=payload.language||language.value;maxChars.value=payload.maxChars||maxChars.value;if(payload.allowLink!==undefined){allowLink=payload.allowLink;allowInput.checked=allowLink;}
  draftInfo=payload.drafts.map(draft=>({...draft}));selected=Number.isInteger(payload.selected)&&payload.selected>=0&&payload.selected<draftInfo.length?payload.selected:draftInfo.length?0:-1;selectionTracked=Number.isInteger(payload.selected);plainComment.value=payload.text||'';plainRow.hidden=draftInfo.length>0;draftInfo.forEach((draft,index)=>{const area=el('textarea',{rows:7,'aria-label':'评论候选 '+(index+1)});area.value=draft.text;areas.push(area);const count=el('p',{class:'muted',text:area.value.length+' 字'});area.oninput=()=>{draftInfo[index].chars=area.value.length;count.textContent=area.value.length+' 字';};const selectButton=button('选择候选 '+(index+1),operation(async()=>{if(selected===index)return;const owner={...draftTarget},started=epoch;selectionTracked=true;const captured=!!areas[selected]?.value.trim();if(captured)await saveCurrent({beforeSwitch:true,label:'切换候选前'});if(!current(owner,started))return;selected=index;selectionButtons.forEach((node,i)=>node.setAttribute('aria-pressed',String(i===selected)));await saveCurrent({capture:false});if(!current(owner,started))return;if(captured)await showHistory(owner,started);message.textContent='已选择候选 '+(index+1)+(captured?'，切换前的草稿已保存。':'，可编辑后填写。');}));selectButton.setAttribute('aria-pressed',String(index===selected));selectionButtons.push(selectButton);drafts.append(el('article',{class:'card'},[selectButton,el('h3',{text:'候选 '+(index+1)+(draft.angle?' · '+draft.angle:'')}),area,count,button('复制评论',async()=>{await navigator.clipboard.writeText(area.value);message.textContent='已复制评论草稿';}),button('填入原任务评论区',operation(async()=>{const owner={...draftTarget};if(!current(owner,epoch))throw Error('产品或文章已切换，请先载入对应草稿');const host=value=>new URL(value).hostname.replace(/^www\./,'');const matches=data.tasks.filter(task=>task.profileId===owner.profileId&&(!owner.targetId||task.targetId===owner.targetId)&&host(task.url)===host(owner.pageUrl)&&!task.attemptBoundary&&!task.receipt&&['pending','needs_manual'].includes(task.status));if(matches.length!==1)throw Error('请先在运行任务中准备对应的原任务页面；不新建重复投稿');const result=await request('/fillCommentDraft',{taskId:matches[0].id,text:area.value,...owner});message.textContent=result.filled?'评论已填入并核验，尚未提交':'评论尚未确认';}))]));});
 }
 let restorePrevious=null;
 async function showHistory(owner=config(),version=epoch){const result=await request('/originalCommentState',owner);if(!current(owner,version))return result.versions;restorePrevious.disabled=!result.versions.length;if(!result.versions.length){history.replaceChildren(el('div',{class:'empty-state compact-empty',text:'生成或编辑后，这里会保留上一版'}));return result.versions;}history.replaceChildren(el('p',{class:'muted',text:'按产品和文章保存最近 8 版，包括编辑后的候选。'}),...result.versions.map(saved=>{const label=saved.label||'上一版',preview=String(saved.payload.text||saved.payload.drafts?.[saved.payload.selected]?.text||''),restore=button('载入 '+(saved.label?saved.label+' · ':'')+formatTime(saved.at),operation(async()=>{await restoreSaved(saved);}));restore.title='恢复 '+label;restore.dataset.commentHistoryId=saved.id;return el('div',{class:'comment-history-item'},[el('span',{class:'comment-history-summary',text:label+' · '+formatTime(saved.at)+' · '+(preview||'候选集')}),restore]);}));return result.versions;}
 const allowControl=checkControl('允许草稿包含推广链接',allowLink,value=>allowLink=value),allowInput=allowControl.querySelector('input');
 content.append(el('h2',{id:'comment-studio',text:'AI 评论草稿'}),el('p',{class:'muted',text:'根据文章内容生成 3 条候选；可编辑、复制和恢复历史版本。'}),fieldRow('我的产品',product),fieldRow('文章网址',url),button('选择已打开的文章页',operation(async()=>{const started=epoch,result=await request('/browserLibraryPages',{});if(disposed||epoch!==started)return;if(!result.pages.length)throw Error('执行器中没有已打开的普通网页');browserPage.replaceChildren(el('option',{value:'',text:'请选择评论使用的网页'}),...result.pages.map(page=>{const option=el('option',{value:page.targetId,text:page.title+' · '+page.url});option.dataset.url=page.url;return option;}));browserPageRow.hidden=false;})),browserPageRow,fieldRow('文章正文',context),fieldRow('语气',tone),fieldRow('语言',language),fieldRow('生成字数上限',maxChars),allowControl,plainRow,
  button('生成 3 条评论',operation(async()=>{const owner={...config(),count:3,pageText:context.value,refresh:true},started=epoch;await saveCurrent({label:'重新生成前',allowEmpty:true,capture:areas.length>0||!!plainComment.value.trim()});if(!current(owner,started))return;const generated=await request('/commentDrafts',owner),result={...generated,drafts:(Array.isArray(generated.drafts)?generated.drafts:[]).filter(draft=>typeof draft?.text==='string'&&draft.text.trim()).slice(0,3)};if(!current(owner,started)){message.textContent='产品或文章已切换，已放弃旧评论结果。';return;}if(!Array.isArray(result.drafts)||!result.drafts.some(draft=>draft.text?.trim()))throw Error('AI 评论生成失败，请确认文章正文足够长');const hadPrevious=areas.length>0||!!plainComment.value.trim();if(hadPrevious){await saveCurrent({label:'重新生成前'});if(!current(owner,started))return;}show({...owner,...result});await saveCurrent({capture:false});await showHistory(owner,started);message.textContent='评论已生成并保存在本机。';}),true),
  button('保存编辑后的草稿',operation(async()=>{if(!areas.length&&!plainComment.value.trim())throw Error('请先输入评论或载入草稿');const owner=config(),started=epoch;await saveCurrent();if(!current(owner,started))return;await showHistory(owner,started);message.textContent='编辑后的草稿已保存。';})),
  button('载入最近草稿',operation(async()=>{const owner=config(),started=epoch;const result=await request('/originalCommentState',owner);if(!current(owner,started))return;const saved=(result.active&&(result.active.drafts.length||result.active.text?.trim())?result.active:null)||result.versions[0]?.payload;if(!saved)throw Error('此产品和文章尚无草稿');await saveCurrent({label:'恢复前'});if(!current(owner,started))return;const before=JSON.stringify(currentPayload());await request('/captureOriginalCommentState',{...owner,capture:false,current:saved});if(!current(owner,started))return;if(JSON.stringify(currentPayload())!==before)throw Error('评论已变化，当前输入保留。');show({...owner,...saved});await showHistory(owner,started);})),
  restorePrevious=button('恢复上一版',operation(async()=>{const owner=config(),started=epoch,result=await request('/originalCommentState',owner);if(!current(owner,started))return;const saved=result.versions[0];if(!saved)throw Error('尚无上一版草稿');await restoreSaved(saved,'上一版已恢复，当前版本仍在历史记录中。');})),message,drafts,history);
 restorePrevious.disabled=true;reset();
 return{saveCurrent,dispose(){disposed=true;epoch++;}};
}
