import test from 'node:test';import assert from 'node:assert/strict';import {Store} from '../executor/src/store.mjs';import {workbenchScope} from '../executor/src/workbench-sync.mjs';import {enqueueProfileMutation,overlayApplication} from '../executor/src/application-mutations.mjs';import {applicationMutation} from '../core/application-mutation.mjs';
const documents=()=>({siteProfiles:{p:{id:'p',name:'Original',url:'https://original.example',fields:{Name:'Original',Title:'Original title'},mediaVersions:[{assetId:'original-asset'}]}},submissionRecords:{original:{profileId:'p',status:'success'}}});
function fixture(){const store=new Store(':memory:'),pair={endpoint:'https://fixture.invalid',workspaceId:'editor'},scope=workbenchScope(pair),snapshot={documents:documents(),revisions:{siteProfiles:4}};store.set('pair',pair);store.set('paused',true);store.set('applicationSnapshot',{scope,snapshot});return{store,pair,scope,snapshot};}
test('profile save returns its confirmed original revision and profile for the editor and original executor-connected settings',async()=>{
 const f=fixture();let writes=0;const runtime={store:f.store,cloud:{async request(route,input){if(route==='snapshot')return structuredClone(f.snapshot);assert.equal(route,'profile');writes++;const change=applicationMutation(f.snapshot.documents,{type:'profile',profileId:input.profileId,profile:input.profile,at:'now'});f.snapshot.documents[change.key]=change.data;f.snapshot.revisions.siteProfiles++;return{ok:true};}}};try{const result=await enqueueProfileMutation(runtime,{profileId:'p',revision:4,profile:{id:'p',name:'Saved',fields:{Title:'Saved title'}}});assert.equal(writes,1);assert.equal(result.revision,5);assert.equal(result.profile.name,'Saved');assert.equal(result.profile.fields.Title,'Saved title');assert.deepEqual(result.profile.mediaVersions,documents().siteProfiles.p.mediaVersions);assert.deepEqual(f.snapshot.documents.submissionRecords,documents().submissionRecords);assert.equal(f.store.get('paused'),true);}finally{f.store.close();}
});
test('offline profile save returns the durable overlaid draft and current revision while retaining pending sync',async()=>{
 const f=fixture(),runtime={store:f.store,cloud:{async request(){throw Error('offline');}}};try{const result=await enqueueProfileMutation(runtime,{profileId:'p',revision:4,profile:{id:'p',name:'Offline draft'}});assert.equal(result.pending,1);assert.equal(result.revision,4);assert.equal(result.profile.name,'Offline draft');assert.equal(overlayApplication(runtime,f.snapshot).documents.siteProfiles.p.name,'Offline draft');assert.equal(f.snapshot.documents.siteProfiles.p.name,'Original');}finally{f.store.close();}
});
test('stale editor revision is rejected as a conflict before enqueuing or accessing cloud and does not overwrite the refreshed profile',async()=>{
 const f=fixture();f.snapshot.documents.siteProfiles.p.fields.Title='Concurrent title';f.snapshot.revisions.siteProfiles=5;f.store.set('applicationSnapshot',{scope:f.scope,snapshot:f.snapshot});let reads=0;const runtime={store:f.store,cloud:{async request(){reads++;throw Error('must not access cloud');}}};try{assert.throws(()=>enqueueProfileMutation(runtime,{profileId:'p',revision:4,profile:{id:'p',fields:{Title:'Old draft'}}}),error=>error.status===409&&/版本/.test(error.message));assert.equal(reads,0);assert.equal(f.store.values('appMutation:').length,0);assert.equal(f.store.get('applicationSnapshot').snapshot.documents.siteProfiles.p.fields.Title,'Concurrent title');}finally{f.store.close();}
});
test('workspace switch during save cannot return another workspace profile or revision as this editor acknowledgement',async()=>{
 const f=fixture();let writes=0;const runtime={store:f.store,cloud:{async request(route){if(route!=='snapshot'){writes++;throw Error('must not write');}const second={...f.pair,workspaceId:'other'},snapshot={documents:{siteProfiles:{p:{id:'p',name:'Other workspace'}}},revisions:{siteProfiles:100}};f.store.set('pair',second);f.store.set('applicationSnapshot',{scope:workbenchScope(second),snapshot});return snapshot;}}};try{const result=await enqueueProfileMutation(runtime,{profileId:'p',revision:4,profile:{id:'p',name:'Original workspace draft'}});assert.match(result.error,/工作区/);assert.equal(writes,0);assert.equal(result.profile,undefined);assert.equal(result.revision,undefined);assert.equal(f.store.values('appMutation:')[0].scope,f.scope);}finally{f.store.close();}
});
