import test from 'node:test';import assert from 'node:assert/strict';
import {Store} from '../executor/src/store.mjs';import {preparedTask} from '../executor/src/single-page.mjs';import {queue} from '../executor/src/shared.mjs';
test('single page restores a cloud-only original task using its full run without a missing Neon task endpoint',async()=>{
 const store=new Store(':memory:'),url='https://directory.example/form',profile={id:'p',fields:{Name:'Original',Url:'https://product.example'}},run={id:'run',profileId:'p',profileRevision:1,profile,mediaManifest:[{asset_id:'original',sha256:'a'.repeat(64)}],tasks:['task']},task={id:'task',runId:'run',profileId:'p',url,destinationKey:queue.normalizeDestinationKey(url),status:'needs_manual',version:3,reason:'原人工页',manualSubmissionConsent:{old:true}},requests=[],runtime={store,cloud:{async request(route){requests.push(route);if(route==='runs?view=inventory')return{runs:[{id:'run'}],tasks:[{id:'task',runId:'run',profileId:'p',url,destinationKey:task.destinationKey,status:'needs_manual'}]};if(route==='runs?runId=run')return{runs:[run],tasks:[task]};throw Error('Unsupported original interface '+route);}}};
 try{store.set('pair',{endpoint:'https://original.example',workspaceId:'original'});store.set('paused',true);const result=await preparedTask(runtime,{profileId:'p',expectedUrl:url},{documents:{siteProfiles:{p:{...profile,name:'New live product'}}},revisions:{siteProfiles:2}});assert.equal(result.id,task.id);assert.deepEqual(result.profileSnapshot,profile);assert.equal(result.profileRevision,1);assert.deepEqual(result.manualSubmissionConsent,task.manualSubmissionConsent);assert.deepEqual(store.get('run:run'),run);assert.deepEqual(requests,['runs?view=inventory','runs?runId=run']);assert.equal(store.get('paused'),true);assert.equal(store.values('singlePagePlan:').length,0);}finally{store.close();}
});
test('single page cannot save an original cloud task after workspace changes during full run readback',async()=>{
 const store=new Store(':memory:'),url='https://directory.example/form',before={endpoint:'https://original.example',workspaceId:'original'},runtime={store,cloud:{async request(route){if(route==='runs?view=inventory')return{runs:[],tasks:[{id:'task',runId:'run',profileId:'p',url,destinationKey:queue.normalizeDestinationKey(url),status:'pending'}]};store.set('pair',{...before,workspaceId:'changed'});return{runs:[],tasks:[]};}}};
 try{store.set('pair',before);await assert.rejects(preparedTask(runtime,{profileId:'p',expectedUrl:url},{}),/工作区已切换/);assert.equal(store.get('task:task'),null);assert.equal(store.get('run:run'),null);assert.equal(store.values('singlePagePlan:').length,0);}finally{store.close();}
});
