import test from 'node:test';
import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import {originalExternalFormSource} from './helpers/original-external-form-source.mjs';
import {trustedExternalFormDestination,isStandaloneExternalFormUrl} from '../executor/src/external-form-source.mjs';
test('external form allowlist, query, path and directory canonicalization match frozen original functions',()=>{
 const original=originalExternalFormSource(),forms=['https://loxr142exnq.typeform.com/to/RB6ZnEf2','https://loxr142exnq.typeform.com/to/RB6ZnEf2?typeform-source=aitools.inc','https://typeform.com/to/RB6ZnEf2?typeform_source=startupstash.com','https://loxr142exnq.typeform.com/to/other','https://docs.google.com/forms/d/e/1FAIpQLSeuaZvj-s7KkI5Zp41q9LX0i9suH61c7JR2qe6sBdDtP9r9Sg/viewform','https://docs.google.com/forms/d/e/copied/viewform','https://forms.gle/Ze6pdWzmweCfKWnLA','https://typeform.com.evil.example/to/RB6ZnEf2','invalid'],sources=['https://aitools.inc/?source=x#anchor','https://www.startupstash.com/submit?utm=x','https://aiinfinity-meetpatel.notion.site/directory?source=x#anchor','https://aitools.inc.evil.example/submit','','invalid'];
 for(const form of forms){assert.equal(isStandaloneExternalFormUrl(form),original.standalone(form));for(const source of sources)assert.deepEqual(trustedExternalFormDestination(form,source),original.destination(form,source));}
});
for(const [name,...args] of [['original-external-form-source'],['original-external-form-source','--existing-source'],['original-external-form-source','--cross-origin'],['original-external-form-source','--untrusted-redirect'],['original-external-form-source','--d1'],['original-external-form-source','--d1-lost-reply'],['original-external-form-source','--d1','--google'],['original-external-form-source','--stale-route'],['original-external-form-popup']])test(name+' '+args.join(' ')+' actual isolated browser matches original attribution',{timeout:45000},()=>{
 const result=spawnSync(process.execPath,['executor/test/'+name+'.mjs',...args],{encoding:'utf8',timeout:40000,maxBuffer:1024*1024});assert.equal(result.status,0,result.stderr+'\n'+result.stdout);const proof=JSON.parse(result.stdout.trim().split('\n').at(-1));assert.equal(proof.ok,true);assert.equal(proof.realSubmissions,0);assert.equal(proof.realModelCalls,0);if(args.includes('--stale-route')){assert.equal(proof.staleFormClickRejected,true);return;}if(name==='original-external-form-source'){for(const key of ['sourceDirectoryTask','unrelatedTaskPreserved','manualWatchBoundToOriginalDirectory','watchArmedWithoutBrowserAssistant','trustedClickObserved','clickTimeFieldEditsPreserved','sqliteIndependentReadback','copiedFormRejectedBeforeRegistration'])assert.equal(proof[key],true);assert.equal(proof.isolatedRegistrations,args.includes('--existing-source')?0:1);assert.equal(proof.authenticatedD1ReceiptReadback,args.some(arg=>arg.startsWith('--d1')));assert.equal(proof.lostReceiptReplyRecovered,args.includes('--d1-lost-reply'));assert.equal(proof.receiptRecordedUnderSource,!args.includes('--untrusted-redirect'));assert.equal(proof.untrustedRedirectRemainsUnknown,args.includes('--untrusted-redirect'));}else for(const key of ['actualNoopenerShortLinkCaptured','originalCapturedSourceMatched','expiredSourceRejected','changedSourceRejected','closedSourceRejected','browserRestartRejected','unattributedFormRejected'])assert.equal(proof[key],true);
});
