import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {execFileSync} from 'node:child_process';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve,sep} from 'node:path';
import {Store} from '../executor/src/store.mjs';
import {Runtime} from '../executor/src/runtime.mjs';
import {originalUnattended as U} from '../core/original-batch-config.mjs';
import {freezeBatchConfig,initializeBatchPolicy,reserveBatchModelCall,batchActionAllowed} from '../executor/src/workbench-batch-policy.mjs';
import {manualSubmit} from '../executor/src/manual-controls.mjs';
const original=execFileSync('git',['show','bd916b2944a577b160a6afcb8a7d73d263044c0c:extension/background.js'],{encoding:'utf8',maxBuffer:4*1024*1024});
const manualBody=original.slice(original.indexOf('async function handleManualSubmit('),original.indexOf('\n// ─── Manual skip',original.indexOf('async function handleManualSubmit(')));
const reserveStart=original.indexOf('async function reserveUnattendedModelCall('),reserveBody=original.slice(reserveStart,original.indexOf('\nasync function ',reserveStart+1));
function fixture(path=':memory:'){
 const store=new Store(path),runtime=new Runtime(store,'unused'),profile={id:'p',name:'Original',fields:{Name:'Original',Url:'https://product.example'}},task={id:'original',runId:'run',profileId:'p',url:'https://target.example/submit',status:'needs_manual',controller:'executor',targetId:'target',browserInstance:'browser',profileRevision:1,profileSnapshot:profile,workbenchBatchId:'b',taskDeadlineAt:Date.now()-1000,unattendedClaimed:true,unattendedBatchId:'b'};
 store.set('pair',{endpoint:'https://cloud.example',workspaceId:'one'});store.set('paused',true);store.set('task:original',task);store.set('run:run',{id:'run',profile});
 const batch=initializeBatchPolicy({id:'b',scope:'https://cloud.example|one',...freezeBatchConfig({unattendedPreferences:{enabled:true,hours:8,tasks:30,manualTabs:1}},{fillOnly:true}),status:'paused',count:30,cursor:13,items:[{taskId:task.id,status:'complete',result:'needs_manual'},{taskId:'unknown',status:'complete',result:'sent_unconfirmed'}],interruptedTasks:{original:1,unknown:2},taskInterruptionReasons:{original:'task_deadline',unknown:'unknown_receipt'}});
 batch.unattendedState={...batch.unattendedState,taskBudgetUsed:13,modelCallsUsed:4,manualTodoIds:['original','unknown'],manualTabCount:2,waitReason:'manual_capacity',originalMetadata:{note:'Keep original extra checkpoint data'}};store.set('workbenchBatch:b',batch);store.set('task:unknown',{id:'unknown',runId:'other',workbenchBatchId:'b',status:'submitted_unconfirmed',targetId:'other-target',attemptBoundary:'original-attempt'});
 let calls=0,ticks=0;Object.defineProperty(runtime,'cloud',{value:{async request(route){if(route==='snapshot')return{documents:{siteProfiles:{p:profile},submissionRecords:{}},revisions:{siteProfiles:1}};assert.equal(route,'ai/comment');calls++;return{ok:true,status:'ok',drafts:[{text:'Original candidate'}]};}}});runtime.findPage=async()=>({});runtime.lease=async()=>{};runtime.synchronize=async()=>{for(const event of store.pending())store.ack(event.id);};runtime.tick=()=>ticks++;
 return{runtime,store,task,batch,get calls(){return calls;},get ticks(){return ticks;},input:{taskId:'original',expectedRunId:'run',expectedTargetId:'target',ordinaryPermissionsAuthorized:true}};
}
async function originalResume(state,now,custom){
 const task={id:'original',index:0,domain:'target.example',status:'needs_manual',taskDeadlineAt:now-1000},entry={taskId:task.id,taskIndex:0,slotActive:false};const runtimeState={runId:'run',tasks:[task],activeTabs:new Map([[1,entry]]),unattended:structuredClone(state),parkedTaskIds:new Set(['original'])};
 const context=vm.createContext({Date:{now:()=>now},state:runtimeState,self:{ExtLinkUnattended:U},unattendedEnabled:()=>true,log(){},clearManualWaitTimer(){},isCustomLaunchTask:()=>custom,getTaskConfig:()=>({}),async syncUnattendedManualCapacity(){runtimeState.unattended=U.noteManualCapacity(runtimeState.unattended,1,now);},async persistParkedTaskIds(){},resetEntryTimeout(){},EXECUTION_TIMEOUT_MS:1,chrome:{tabs:{async sendMessage(){}}},async runRuleBasedFill(){},async runProductHuntLaunchLoop(){}});vm.runInContext(manualBody,context);await vm.runInContext('handleManualSubmit({runId:"run",taskId:"original"},1)',context);return{state:runtimeState.unattended,deadline:task.taskDeadlineAt};
}
test('ordinary and Product Hunt manual continuation match original deadline, todo and capacity without renewing global budgets',async()=>{
 const realNow=Date.now,now=realNow();Date.now=()=>now;
 try{for(const custom of [false,true]){const f=fixture();try{if(custom)f.store.set('task:original',{...f.task,url:'https://www.producthunt.com/posts/new',productHunt:{readyToCreate:true}});const expected=await originalResume(f.batch.unattendedState,now,custom),unknown=structuredClone(f.store.get('task:unknown'));await f.runtime.control('manualSubmit',{...f.input,confirmProductHuntCreate:custom});const saved=f.store.get('workbenchBatch:b');assert.deepEqual(saved.unattendedState,expected.state);assert.equal(f.store.get('task:original').taskDeadlineAt,expected.deadline);assert.equal(saved.cursor,13);assert.equal(saved.count,30);assert.deepEqual(saved.items,f.batch.items);assert.equal(saved.status,'paused');assert.equal(saved.interruptedTasks.original,undefined);assert.equal(saved.interruptedTasks.unknown,2);assert.deepEqual(f.store.get('task:unknown'),unknown);assert.equal(f.store.get('singleTaskId'),'original');assert.equal(f.ticks,1);assert.equal(f.calls,0);}finally{f.store.close();}}}finally{Date.now=realNow;}
});
test('manual model reservations match frozen original remaining, exhausted and expired budgets',async()=>{
 const realNow=Date.now,now=realNow();Date.now=()=>now;
 try{for(const mode of ['remaining','exhausted','expired']){const f=fixture();try{await f.runtime.control('manualSubmit',f.input);let batch=f.store.get('workbenchBatch:b');if(mode==='exhausted')batch.unattendedState.modelCallsUsed=batch.unattendedState.maxAgentCalls;if(mode==='expired')batch.unattendedState.runDeadlineAt=now-1;f.store.set('workbenchBatch:b',batch);let referenceState=structuredClone(batch.unattendedState),denied;
 const context=vm.createContext({Date:{now:()=>now},self:{ExtLinkUnattended:U},state:{unattended:referenceState},unattendedEnabled:()=>true,async updateUnattendedCheckpoint(fn){referenceState=fn(referenceState);},async pauseUnattendedBatch(){},log(){},UnattendedBudgetError:class extends Error{constructor(reason){super(reason);denied=reason;}}});vm.runInContext(reserveBody,context);await vm.runInContext('reserveUnattendedModelCall("/comment")',context).catch(()=>{});
 if(mode==='remaining'){reserveBatchModelCall(f.runtime,f.store.get('task:original'));assert.equal(f.store.get('workbenchBatch:b').unattendedState.modelCallsUsed,referenceState.modelCallsUsed);}else{assert.ok(denied);assert.throws(()=>reserveBatchModelCall(f.runtime,f.store.get('task:original')),/预算|截止/);assert.equal(f.store.get('workbenchBatch:b').unattendedState.modelCallsUsed,referenceState.modelCallsUsed);assert.equal(f.store.get('paused'),true);}assert.equal(f.store.get('workbenchBatch:b').cursor,13);assert.equal(f.calls,0);
 }finally{f.store.close();}}}finally{Date.now=realNow;}
});
test('native original comment bridge caches before charging but rejects real model calls after the original budget is exhausted',async()=>{
 const f=fixture();try{await f.runtime.control('manualSubmit',f.input);const message={action:'generateCommentDrafts',pageUrl:'https://article.example/post',count:3,config:{projectKey:'p'}};await f.runtime.bridge(f.store.get('task:original'),message);assert.equal(f.store.get('workbenchBatch:b').unattendedState.modelCallsUsed,5);assert.equal((await f.runtime.bridge(f.store.get('task:original'),message)).cached,true);assert.equal(f.calls,1);const batch=f.store.get('workbenchBatch:b');batch.unattendedState.modelCallsUsed=batch.unattendedState.maxAgentCalls;f.store.set('workbenchBatch:b',batch);await assert.rejects(f.runtime.bridge(f.store.get('task:original'),{...message,refresh:true}),/预算/);assert.equal(f.calls,1);assert.equal(f.store.get('task:unknown').attemptBoundary,'original-attempt');}finally{f.store.close();}
});
test('manual permission cannot bypass the resumed task deadline or original global deadline before the next action',async()=>{
 for(const mode of ['task','global']){const f=fixture();try{await f.runtime.control('manualSubmit',f.input);const batch=f.store.get('workbenchBatch:b');if(mode==='global'){batch.unattendedState.runDeadlineAt=Date.now()-1;f.store.set('workbenchBatch:b',batch);}else f.store.set('task:original',{...f.store.get('task:original'),taskDeadlineAt:Date.now()-1});assert.equal(batchActionAllowed(f.runtime,f.store.get('task:original')),false);assert.equal(f.calls,0);assert.equal(f.store.get('workbenchBatch:b').unattendedState.taskBudgetUsed,13);assert.equal(f.store.get('task:unknown').attemptBoundary,'original-attempt');}finally{f.store.close();}}
});
test('manual task and original batch checkpoint rollback together if SQLite rejects the batch save',async()=>{
 const f=fixture();try{const task=f.store.get('task:original'),batch=f.store.get('workbenchBatch:b');f.store.db.exec("CREATE TRIGGER reject_manual_checkpoint BEFORE INSERT ON state WHEN NEW.id='workbenchBatch:b' BEGIN SELECT RAISE(ABORT,'fixture checkpoint rejected'); END;");await assert.rejects(f.runtime.control('manualSubmit',f.input),/checkpoint rejected/);assert.deepEqual(f.store.get('task:original'),task);assert.deepEqual(f.store.get('workbenchBatch:b'),batch);assert.equal(f.store.pendingCount(),0);assert.equal(f.store.get('paused'),true);assert.equal(f.ticks,0);}finally{f.store.close();}
});
test('late page cancellation restores the selected original manual todo and capacity without starting or resetting its batch',async()=>{
 const f=fixture();let current=true;f.runtime.synchronize=async()=>{current=false;};
 try{await assert.rejects(manualSubmit(f.runtime,f.input,{assertContext(){if(!current)throw Error('original selection changed');}}),/selection changed/);const batch=f.store.get('workbenchBatch:b'),task=f.store.get('task:original');assert.deepEqual(new Set(batch.unattendedState.manualTodoIds),new Set(['unknown','original']));assert.equal(batch.unattendedState.manualTabCount,2);assert.equal(task.status,'needs_manual');assert.equal(task.manualSubmissionConsent,null);assert.equal(batch.unattendedState.taskBudgetUsed,13);assert.equal(batch.unattendedState.modelCallsUsed,4);assert.equal(f.store.get('paused'),true);assert.equal(f.ticks,0);}finally{f.store.close();}
});
test('real SQLite reopen preserves resumed task deadline, original counters and unknown attempts',async()=>{
 const home=await mkdtemp(join(tmpdir(),'el-manual-budget-')),path=join(home,'outbox.sqlite'),f=fixture(path);let reopened,closed=false;
 try{await f.runtime.control('manualSubmit',f.input);const task=f.store.get('task:original'),batch=f.store.get('workbenchBatch:b'),unknown=f.store.get('task:unknown');f.store.close();closed=true;reopened=new Store(path);assert.deepEqual(reopened.get('task:original'),task);assert.deepEqual(reopened.get('workbenchBatch:b'),batch);assert.deepEqual(reopened.get('task:unknown'),unknown);assert.equal(batch.unattendedState.taskBudgetUsed,13);assert.equal(batch.unattendedState.modelCallsUsed,4);}finally{reopened?.close();if(!closed)f.store.close();assert.ok(resolve(home).startsWith(resolve(tmpdir())+sep));await rm(home,{recursive:true,force:true});}
});
