import test from 'node:test';
import assert from 'node:assert/strict';
import {Store} from '../executor/src/store.mjs';
import {workbenchScope} from '../executor/src/workbench-sync.mjs';
import {applicationMutation} from '../core/application-mutation.mjs';
import {classifyOriginalTaskGate,originalLinkrenaPostSubmitLogin} from '../executor/src/original-site-classification.mjs';
import vm from 'node:vm';
import path from 'node:path';
import {Runtime} from '../executor/src/runtime.mjs';
import {profiles,plain} from '../executor/src/shared.mjs';
import {execFileSync} from 'node:child_process';

function fixture({attempt=false,url='https://directory.example/submit'}={}){
 const store=new Store(':memory:'),task={id:'original',runId:'original-run',profileId:'p',profileSnapshot:{id:'p',fields:{Name:'Original',Url:'https://original.example'}},profileRevision:7,targetId:'original-target',browserInstance:'original-browser',version:1,controller:'executor',url,status:attempt?'submitting':'filling',...(attempt?{attemptBoundary:'original-boundary',siteStatus:'sent_unconfirmed'}:{})};
 store.set('pair',{endpoint:'https://cloud.fixture.invalid',workspaceId:'original'});store.set('task:'+task.id,task);store.set('paused',false);store.set('acceptanceBatch',{status:'paused',cursor:13,count:30});
 let pageUrl=task.url,closed=false,writes=0;const key=globalThis.ExtLinkQueue.normalizeLibraryDestinationKey(url),previous={status:'can_submit',statuses:['can_submit'],auto:false,note:'Original verdict',library:{favorite:true,groups:['original']}};
 const snapshot={documents:{siteAnnotations:{[key]:previous},deletedSubmissionKeys:['retained.example/old'],submissionRecords:{old:{status:'success',evidence:'Keep original receipt'}}},revisions:{siteAnnotations:1,deletedSubmissionKeys:1}};
 store.set('applicationSnapshot',{scope:workbenchScope(store.get('pair')),snapshot:structuredClone(snapshot)});
 const runtime={store,update(t,patch,type){Object.assign(t,patch);store.transition(t,type);},cloud:{async request(route,input){if(route==='snapshot')return structuredClone(snapshot);assert.equal(route,'library');writes++;const change=applicationMutation(snapshot.documents,input.operation);Object.assign(snapshot.documents,change.updates);for(const key of Object.keys(change.updates))snapshot.revisions[key]++;return{ok:true};}}},page={url:()=>pageUrl,isClosed:()=>closed};
 return{store,runtime,task,page,key,snapshot,previous,counts:()=>({writes}),move:url=>pageUrl=url,close:()=>closed=true};
}
test('task gate observations preserve original preferences, queue and receipts before and after a submission boundary',async()=>{
 for(const attempt of [false,true])for(const [result,status]of [[{captcha:true},'needs_captcha'],[{gate:'login'},'needs_login'],[{needs_manual:true,reason:'OTP verification code required'},'needs_otp'],[{blocked:true,reason:'Submission requires a payment'},'paid'],[{needs_manual:true,reason:'Accept terms'},'needs_manual']]){
  const f=fixture({attempt});try{const boundary=f.task.attemptBoundary,profile=structuredClone(f.task.profileSnapshot),fixed=structuredClone(f.store.get('acceptanceBatch'));const observed=await classifyOriginalTaskGate(f.runtime,{task:f.task,page:f.page,result});assert.equal(observed.status,status);const annotation=structuredClone(f.snapshot.documents.siteAnnotations[f.key]);assert.equal(annotation.lastAutomaticObservation.status,status);delete annotation.lastAutomaticObservation;assert.deepEqual(annotation,f.previous);assert.deepEqual(f.snapshot.documents.deletedSubmissionKeys,['retained.example/old']);assert.deepEqual(f.snapshot.documents.submissionRecords,{old:{status:'success',evidence:'Keep original receipt'}});assert.equal(f.task.attemptBoundary,boundary);assert.equal(f.task.status,attempt?'submitting':status==='paid'?'skip':'filling');assert.deepEqual(f.task.profileSnapshot,profile);assert.deepEqual(f.store.get('acceptanceBatch'),fixed);assert.equal(f.counts().writes,1);}finally{f.store.close();}
 }
});
test('uncertain payment semantic review, known receipts, validation-only errors and ready-to-create results do not classify a site',async()=>{
 for(const result of [{needs_manual:true,semanticReview:true,reason:'Uncertain pricing'},{blocked:true,payment_uncertain:true},{needs_manual:true,uncertain:true},{needs_manual:true,humanGate:'payment_uncertain'},{matched:true,captcha:true,evidence:'Original receipt'},{validationFailed:true},{ready_to_create:true},{ok:false,reason:'no_permitted_action'}]){const f=fixture();try{assert.equal(await classifyOriginalTaskGate(f.runtime,{task:f.task,page:f.page,result}),null);assert.equal(f.counts().writes,0);assert.equal(f.task.siteAutomaticObservation,undefined);assert.deepEqual(f.snapshot.documents.siteAnnotations[f.key],f.previous);assert.equal(f.store.values('appMutation:').length,0);}finally{f.store.close();}}
});

test('native gate cold start loads the original cloud documents before observing and refuses changed connections',async()=>{
 for(const changed of [false,true]){const f=fixture();try{f.store.set('applicationSnapshot',null);const request=f.runtime.cloud.request;f.runtime.cloud.request=async(route,input)=>{const result=await request(route,input);if(route==='snapshot'&&changed)f.store.set('pair',{...f.store.get('pair'),deviceId:'changed-device'});return result;};if(changed){await assert.rejects(()=>classifyOriginalTaskGate(f.runtime,{task:f.task,page:f.page,result:{captcha:true}}),/连接已变化/);assert.equal(f.counts().writes,0);assert.equal(f.store.get('applicationSnapshot'),null);}else{const observed=await classifyOriginalTaskGate(f.runtime,{task:f.task,page:f.page,result:{captcha:true}});assert.equal(observed.status,'needs_captcha');assert.equal(f.snapshot.documents.siteAnnotations[f.key].note,'Original verdict');assert.equal(f.counts().writes,1);}}finally{f.store.close();}}
});
test('task gate context changes stop before mutation and late page changes cannot write task observation metadata',async()=>{
 const changes=[f=>f.store.set('executionStopped',{at:'stop'}),f=>f.store.set('connectionExecutionHold',true),f=>f.close(),f=>f.task.receipt={evidence:'received'}];for(const change of changes){const f=fixture();try{change(f);f.store.set('task:'+f.task.id,f.task);await assert.rejects(classifyOriginalTaskGate(f.runtime,{task:f.task,page:f.page,result:{captcha:true}}),/自动观察停止/);assert.equal(f.counts().writes,0);}finally{f.store.close();}}
 const f=fixture();try{let checks=0;await assert.rejects(classifyOriginalTaskGate(f.runtime,{task:f.task,page:f.page,result:{captcha:true},assertPageDocument:async()=>{if(++checks===2)f.move('https://directory.example/new-page');}}),/自动观察停止/);assert.equal(f.task.siteAutomaticObservation,undefined);assert.equal(f.task.attemptBoundary,undefined);assert.equal(f.snapshot.documents.siteAnnotations[f.key].status,'can_submit');assert.equal(f.snapshot.documents.siteAnnotations[f.key].lastAutomaticObservation.status,'needs_captcha');}finally{f.store.close();}
});

test('original native work method invokes observations at explicit form and post-submit gates while retaining unknown boundaries',async()=>{
 const scenarios=[{name:'detected-captcha',captcha:true,status:'needs_captcha'}, {name:'blocked-destination',blocker:{blocked:true,reason:'Cannot submit'},status:'broken'}, {name:'uncertain-payment',blocker:{needs_manual:true,payment_uncertain:true,reason:'Unclear pricing'}}, {name:'semantic-review',fill:{ok:false,needs_manual:true,semanticReview:true,reason:'Unclear product field'},fillOnly:true}, {name:'manual-fill-gate',fill:{ok:false,needs_manual:true,reason:'Login required'},fillOnly:true,status:'needs_login'}, {name:'validation-only',invalid:true,fillOnly:true}, ...[{captcha:true}, {needs_manual:true,reason:'OTP verification code required'}, {blocked:true,reason:'Cannot submit'}, {needs_manual:true,semanticReview:true,reason:'Unclear payment'}].map((result,index)=>({name:'after-submit-'+index,submit:result,status:index===0?'needs_captcha':index===1?'needs_otp':index===2?'broken':undefined,afterSubmit:true}))];
 scenarios.push({name:'linkrena-post-submit-login',redirect:'https://linkrena.com/login?callbackUrl=%2Fsubmit',submit:{},afterSubmit:true,status:'needs_login',expectedSubmit:{needs_manual:true,reason:'站方在最终提交后跳转邮箱登录，未产生投稿回执；登录页要求同意条款'}});
 for(const scenario of scenarios){
  const f=fixture(scenario.redirect?{url:'https://linkrena.com/submit'}:{});try{
   f.task.status='pending';f.task.fillOnlyRun=scenario.fillOnly===true;f.task.submitPreparedRun=scenario.afterSubmit===true;f.store.set('task:'+f.task.id,f.task);f.store.set('run:'+f.task.runId,{id:f.task.runId,profileId:'p',profile:f.task.profileSnapshot,tasks:[f.task.id]});f.snapshot.documents.siteProfiles={p:f.task.profileSnapshot};
   const detection={operable:true,formFieldCount:4,platform:'directory',hasCaptcha:scenario.captcha===true,submitBlocker:scenario.blocker},frame={url:()=>f.task.url,locator:()=>({evaluateAll:async()=>[]})},calls=[];
   Object.assign(f.page,{frames:()=>[frame],mainFrame:()=>frame,on(){},off(){},locator:()=>({first:()=>({waitFor:async()=>{}})})});
   const engine={documentId:27,isCurrentDocument:async()=>true,detach:async()=>{},async call(input){calls.push(input.action);if(input.action==='detectPage')return detection;if(input.action==='smartFill')return scenario.fill||{ok:true};if(input.action==='collectFormValidation')return{validationFailed:scenario.invalid===true,allValid:!scenario.invalid,issues:[]};if(input.action==='inspectSubmitAction')return{allowed:true,finalFound:true};if(input.action==='getFilledFieldsReport')return{fields:[],attachments:[]};if(input.action==='classifySubmitEvidence')return{evidence:'Original baseline'};if(input.action==='submitFilledForm'){if(scenario.redirect)f.move(scenario.redirect);return scenario.submit||{};}if(input.action==='persistFillLearnings')return{};throw Error('Unexpected fixture engine call '+input.action);}};
   const runtime=f.runtime;Object.assign(runtime,{home:'unused-task-classification-home',context:{},host:{startedAt:'original-browser'},synchronize:async()=>{},lease:async()=>{},findPage:async()=>f.page,preparePublicPage:async()=>{},prepareKnownPage:async()=>{},reconcileTextInputs:async()=>{},completeKnownForm:async()=>{},knownFormIssues:async()=>[],accept:async()=>{throw Error('No fixture receipt');},prepareWithAi:async()=>{throw Error('Unexpected fixture AI takeover');}});runtime.cloud.flush=async()=>{};
   const sandbox=vm.createContext({path,profiles,plain,classifyOriginalTaskGate,priorProductSuccess:()=>false,findUnambiguousOfflineRun:store=>store.get('run:'+f.task.runId),applySubmissionPreferences:(_runtime,_task,_defaults,config)=>config,applyDestinationFormKnowledge:(_defaults,config)=>config,batchActionAllowed:()=>true,assertParkedResumePage:async()=>{},getTargetInfo:async()=>({targetId:f.task.targetId}),isProductHuntLaunch:()=>false,attachEngine:async()=>engine,assessSubmissionQuality:()=>[],navToolsAdapter:{matches:()=>false},armCaptchaResume:()=>true,finalizeBatchDeadline(){},finalizeUserPause(){},withinDeadline:promise=>promise,capturePageEvidence:async()=>{},classifyBlocker:reason=>/captcha|验证码/i.test(reason)?'human_verification':'manual'});
   sandbox.URL=URL;sandbox.originalLinkrenaPostSubmitLogin=originalLinkrenaPostSubmitLogin;sandbox.armPageCaptchaResume=async()=>true;const work=vm.runInContext('({'+Runtime.prototype.work.toString()+'}).work',sandbox);await work.call(runtime,{taskId:f.task.id});Object.assign(f.task,f.store.get('task:'+f.task.id));
   const annotation=f.snapshot.documents.siteAnnotations[f.key];assert.equal(annotation.lastAutomaticObservation?.status,scenario.status,scenario.name+': '+f.task.reason);assert.equal(f.counts().writes,scenario.status?1:0,scenario.name);assert.equal(annotation.status,'can_submit');assert.deepEqual(annotation.library,f.previous.library);assert.deepEqual(f.snapshot.documents.deletedSubmissionKeys,['retained.example/old']);
   if(scenario.afterSubmit){assert.equal(f.task.status,'submitted_unconfirmed');assert.equal(f.task.siteStatus,'sent_unconfirmed');assert.ok(f.task.attemptBoundary);assert.equal(f.task.receipt,undefined);assert.deepEqual(plain(f.task.submitResult),{...(scenario.expectedSubmit||scenario.submit),networkResponses:[]});assert.equal(calls.filter(action=>action==='submitFilledForm').length,1);}else{assert.equal(f.task.status,scenario.name==='blocked-destination'?'err':'needs_manual');assert.equal(f.task.attemptBoundary,undefined);assert.equal(calls.includes('submitFilledForm'),false);}assert.equal(f.task.id,'original');assert.equal(f.task.runId,'original-run');assert.equal(f.store.get('acceptanceBatch').cursor,13);
  }finally{f.store.close();}
 }
});

test('Linkrena post-submit login detection retains the exact original destination and callback conditions',()=>{
 const source=execFileSync('git',['show','bd916b2944a577b160a6afcb8a7d73d263044c0c:extension/background.js'],{encoding:'utf8',maxBuffer:4*1024*1024}),start=source.indexOf('function isLinkrenaPostSubmitLogin('),end=source.indexOf('\nasync function assertFillContext',start),sandbox=vm.createContext({URL});assert.ok(start>=0&&end>start);vm.runInContext(source.slice(start,end),sandbox);
 for(const [before,after,expected]of [['https://linkrena.com/submit','https://linkrena.com/login?callbackUrl=%2Fsubmit',true],['https://linkrena.com/submit','https://linkrena.com/login?callbackUrl=/submit',true],['https://linkrena.com/other','https://linkrena.com/login?callbackUrl=/submit',false],['https://linkrena.com/submit','https://linkrena.com/login?callbackUrl=/other',false],['https://linkrena.com/submit','https://other.example/login?callbackUrl=/submit',false],['https://www.linkrena.com/submit','https://www.linkrena.com/login?callbackUrl=/submit',false],['invalid','invalid',false]]){assert.equal(sandbox.isLinkrenaPostSubmitLogin(before,after),expected);assert.equal(originalLinkrenaPostSubmitLogin(before,after),expected);}
});

test('both native AI entry points retain terminal reasons and never overwrite late unknown or foreign task state during cleanup',async()=>{
 for(const entry of ['no-form','incomplete-form'])for(const outcome of ['login','blocked','late-unknown','foreign-owner']){
  const f=fixture();try{
   f.task.status='pending';f.store.set('task:'+f.task.id,f.task);f.store.set('run:'+f.task.runId,{id:f.task.runId,profileId:'p',profile:f.task.profileSnapshot,tasks:[f.task.id]});
   const calls=[],detection={operable:entry!=='no-form',formFieldCount:4,platform:'directory',hasCaptcha:false},frame={url:()=>f.task.url,locator:()=>({evaluateAll:async()=>[]})};let detached=0,screenshots=0,synchronized=0,takeovers=0;
   Object.assign(f.page,{frames:()=>[frame],mainFrame:()=>frame,on(){},off(){},locator:()=>({first:()=>({waitFor:async()=>{}})})});
   const engine={isCurrentDocument:async()=>true,detach:async()=>{detached++;},async call(input){calls.push(input.action);if(input.action==='detectPage')return detection;if(input.action==='smartFill')return{ok:false};if(input.action==='collectFormValidation')return{validationFailed:true};if(input.action==='inspectSubmitAction')return{allowed:true,finalFound:true};if(input.action==='getFilledFieldsReport')return{fields:[]};throw Error('No further engine operation allowed after original AI terminal decision: '+input.action);}};
   Object.assign(f.runtime,{home:'unused-original-agent-terminal-home',context:{},host:{startedAt:'original-browser'},synchronize:async()=>{synchronized++;},lease:async()=>{},findPage:async()=>f.page,preparePublicPage:async()=>{},prepareKnownPage:async()=>{},reconcileTextInputs:async()=>{},completeKnownForm:async()=>{},knownFormIssues:async()=>[],prepareWithAi:async(_page,workingTask)=>{
    takeovers++;if(['late-unknown','foreign-owner'].includes(outcome)){const change=outcome==='late-unknown'?{status:'submitted_unconfirmed',attemptBoundary:'late-boundary',reason:'Keep late unknown'}:{controller:'supervisor',version:2,reason:'Keep foreign owner'};f.store.set('task:'+f.task.id,{...f.store.get('task:'+f.task.id),...change});throw Object.assign(Error('Old preparation is stale'),{staleTask:true});}
    const result=outcome==='login'?{ok:false,needs_manual:true,reason:'Original login required'}:{ok:false,blocked:true,reason:'Original destination cannot submit'};await classifyOriginalTaskGate(f.runtime,{task:workingTask,page:f.page,result});return{...result,candidate:{engine,frame,detection}};
   }});f.runtime.cloud.flush=async()=>{};
   const sandbox=vm.createContext({URL,path,profiles,plain,classifyOriginalTaskGate,priorProductSuccess:()=>false,findUnambiguousOfflineRun:store=>store.get('run:'+f.task.runId),applySubmissionPreferences:(_r,_t,_d,c)=>c,applyDestinationFormKnowledge:(_d,c)=>c,batchActionAllowed:()=>true,assertParkedResumePage:async()=>{},getTargetInfo:async()=>({targetId:f.task.targetId}),isProductHuntLaunch:()=>false,attachEngine:async()=>engine,assessSubmissionQuality:()=>[],navToolsAdapter:{matches:()=>false},armCaptchaResume:()=>true,finalizeBatchDeadline(){},finalizeUserPause(){},withinDeadline:p=>p,capturePageEvidence:async()=>{screenshots++;},classifyBlocker:()=> 'manual'});
   await vm.runInContext('({'+Runtime.prototype.work.toString()+'}).work',sandbox).call(f.runtime,{taskId:f.task.id});const saved=f.store.get('task:'+f.task.id);assert.equal(takeovers,1);assert.equal(calls.includes('submitFilledForm'),false);assert.ok(detached>=1);
   if(outcome==='late-unknown'){assert.equal(saved.status,'submitted_unconfirmed');assert.equal(saved.attemptBoundary,'late-boundary');assert.equal(saved.reason,'Keep late unknown');}
   if(outcome==='foreign-owner'){assert.equal(saved.controller,'supervisor');assert.equal(saved.version,2);assert.equal(saved.reason,'Keep foreign owner');}
   if(['late-unknown','foreign-owner'].includes(outcome)){assert.equal(screenshots,0);assert.equal(synchronized,1);assert.equal(f.counts().writes,0);}else{assert.equal(saved.status,outcome==='blocked'?'err':'needs_manual');assert.equal(saved.reason,outcome==='login'?'Original login required':'Original destination cannot submit');assert.equal(f.snapshot.documents.siteAnnotations[f.key].lastAutomaticObservation.status,outcome==='login'?'needs_login':'broken');assert.equal(f.counts().writes,1);assert.equal(saved.attemptBoundary,undefined);}
   assert.equal(f.store.get('acceptanceBatch').cursor,13);
  }finally{f.store.close();}
 }
});
