import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {join,resolve,sep} from 'node:path';
import {tmpdir} from 'node:os';
import {Store} from '../executor/src/store.mjs';
import {Runtime} from '../executor/src/runtime.mjs';
import {workbenchScope} from '../executor/src/workbench-sync.mjs';
import {armCaptchaResume,checkCaptchaResumes} from '../executor/src/captcha-resume.mjs';

function fixture(file=':memory:'){
 const store=new Store(file),runtime=new Runtime(store,'unused-captcha-test-home'),profile={id:'p',name:'Original product',url:'https://product.example',fields:{Name:'Original product',Url:'https://product.example'}},task={id:'original-task',runId:'original-run',profileId:'p',profileSnapshot:profile,profileRevision:7,targetId:'original-target',browserInstance:'original-browser',workbenchBatchId:'original-batch',controller:'executor',status:'filling',fillOnlyRun:true,version:1,url:'https://directory.example/submit'};
 store.set('pair',{endpoint:'https://cloud.example',workspaceId:'original-workspace'});store.set('paused',false);store.set('activeWorkbenchBatch','original-batch');store.set('workbenchBatch:original-batch',{id:'original-batch',scope:workbenchScope(store.get('pair')),status:'running',config:{fillOnly:true},cursor:13,count:30,items:[{taskId:task.id,identity:'original-combination',status:'complete'}]});store.set('task:'+task.id,task);store.set('run:'+task.runId,{id:task.runId,profileId:'p',profile:structuredClone(profile),tasks:[task.id],mediaManifest:[]});store.set('task:unknown',{id:'unknown',status:'submitted_unconfirmed',attemptBoundary:'keep-original-boundary'});runtime.host={startedAt:'original-browser'};let browserCalls=0,ticks=0;runtime.context={async newCDPSession(){browserCalls++;throw Error('Unexpected browser operation');}};runtime.tick=()=>ticks++;return{store,runtime,task,site:{pageUrl:task.url,frameUrl:task.url,documentId:27},counts:()=>({browserCalls,ticks}),close:()=>store.close()};
}
function park(f){armCaptchaResume(f.runtime,f.task,f.site);f.runtime.update(f.task,{status:'needs_manual',attentionType:'human_verification'},'fixture_captcha_wait');}

test('captcha recovery freezes the original product document and execution identity without replacing scope or budgets',()=>{
 const f=fixture();try{const batch=structuredClone(f.store.get('workbenchBatch:original-batch')),run=structuredClone(f.store.get('run:original-run')),profile=structuredClone(f.task.profileSnapshot);assert.equal(armCaptchaResume(f.runtime,f.task,f.site),true);assert.equal(f.task.captchaResume.documentId,27);assert.equal(f.task.captchaResume.execution.kind,'workbench');assert.equal(f.task.captchaResume.execution.id,'original-batch');assert.match(f.task.captchaResume.profileSha256,/^[a-f0-9]{64}$/);assert.equal(f.task.fillOnlyRun,true);assert.deepEqual(f.task.profileSnapshot,profile);assert.deepEqual(f.store.get('workbenchBatch:original-batch'),batch);assert.deepEqual(f.store.get('run:original-run'),run);assert.equal(f.task.attemptBoundary,undefined);assert.equal(f.task.receipt,undefined);assert.equal(f.store.get('task:unknown').attemptBoundary,'keep-original-boundary');}finally{f.close();}
});
test('paused stopped attempted unknown or invalid-document tasks cannot arm an automatic captcha recovery',()=>{
 for(const change of [f=>f.store.set('paused',true),f=>f.store.set('executionStopped',{at:'stopped'}),f=>f.task.attemptBoundary='unknown',f=>f.task.receipt={evidence:'original receipt'},f=>f.site.documentId='27',f=>f.site.documentId=0,f=>f.site.documentId=-1,f=>f.store.set('activeWorkbenchBatch','different-batch')]){const f=fixture();try{change(f);assert.equal(armCaptchaResume(f.runtime,f.task,f.site),false);assert.equal(f.task.captchaResume,undefined);assert.equal(f.store.pendingCount(),0);}finally{f.close();}}
});
test('changed product page ownership workspace controller pause or receipt prevents recovery before browser access',async()=>{
 for(const change of [f=>f.task.profileSnapshot.fields.Name='Changed',f=>f.task.targetId='new-target',f=>f.task.browserInstance='new-browser',f=>f.task.controller='supervisor',f=>f.task.attemptBoundary='new-unknown',f=>f.task.receipt={evidence:'received'},f=>f.store.set('executionPaused',{at:'new-user-pause'}),f=>f.store.set('executionStopped',{at:'stopped'}),f=>f.store.set('pair',{endpoint:'https://other-cloud.example',workspaceId:'other-workspace'})]){const f=fixture();try{park(f);change(f);f.store.set('task:'+f.task.id,f.task);const pending=f.store.pendingCount(),batch=structuredClone(f.store.get('workbenchBatch:original-batch'));const result=await checkCaptchaResumes(f.runtime);assert.deepEqual(result.resumed,[]);assert.equal(f.counts().browserCalls,0);assert.equal(f.counts().ticks,0);assert.equal(f.store.pendingCount(),pending);assert.deepEqual(f.store.get('workbenchBatch:original-batch'),batch);}finally{f.close();}}
});
test('stale captcha callback documents and frames cannot resume the original task',async()=>{
 const f=fixture();try{park(f);for(const input of [{taskId:f.task.id,expectedDocumentId:28},{taskId:f.task.id,frameUrl:'https://other.example/form'}]){const result=await checkCaptchaResumes(f.runtime,input);assert.deepEqual(result.resumed,[]);}assert.equal(f.counts().browserCalls,0);assert.equal(f.task.status,'needs_manual');assert.equal(f.task.captchaResume.status,'armed');}finally{f.close();}
});
test('captcha recovery cannot reuse a batch id after its original parameters or frozen scope change',async()=>{
 for(const change of [batch=>{batch.config.fillOnly=false;},batch=>{batch.items[0].url='https://changed-destination.example/submit';}]){const f=fixture();try{park(f);const batch=f.store.get('workbenchBatch:original-batch');change(batch);f.store.set('workbenchBatch:original-batch',batch);const pending=f.store.pendingCount();assert.deepEqual((await checkCaptchaResumes(f.runtime)).resumed,[]);assert.equal(f.counts().browserCalls,0);assert.equal(f.counts().ticks,0);assert.equal(f.store.pendingCount(),pending);assert.equal(f.store.get('task:'+f.task.id).status,'needs_manual');}finally{f.close();}}
});
test('original captcha recovery identity survives SQLite reopen without replacing unknown tasks or frozen profiles',async()=>{
 const folder=await mkdtemp(join(tmpdir(),'el-captcha-reopen-')),file=join(folder,'outbox.sqlite');let f;try{f=fixture(file);park(f);const expected=structuredClone(f.task.captchaResume),profile=structuredClone(f.task.profileSnapshot);f.close();f=null;const store=new Store(file);try{assert.deepEqual(store.get('task:original-task').captchaResume,expected);assert.deepEqual(store.get('task:original-task').profileSnapshot,profile);assert.equal(store.get('task:unknown').attemptBoundary,'keep-original-boundary');assert.equal(store.get('workbenchBatch:original-batch').cursor,13);}finally{store.close();}}finally{f?.close();assert.ok(resolve(folder).startsWith(resolve(tmpdir())+sep)&&folder.includes('el-captcha-reopen-'));await rm(folder,{recursive:true,force:true});}
});
