import test from 'node:test';import assert from 'node:assert/strict';import {Store} from '../executor/src/store.mjs';import {registerAcceptance} from '../executor/src/acceptance-register.mjs';
import {queue} from '../executor/src/shared.mjs';
function fixture(){const store=new Store(':memory:');store.set('paused',true);const profile={id:'p',fields:{Name:'P',Url:'https://product.example'}};
 store.set('acceptance:fixed',{sha256:'frozen',count:2,combinations:['one.example','two.example'].map(siteId=>({identity:siteId+'::p',siteId,url:'https://'+siteId+'/submit',profileId:'p',profileRevision:2,profile}))});
 const requests=[];const runtime={store,job:null,cloud:{async request(route,body){requests.push({route,body});if(route==='snapshot')return{documents:{siteProfiles:{p:profile}},revisions:{siteProfiles:2}};if(route.startsWith('runs?'))return{runs:[],tasks:[]};if(route==='runs')return{run:{...body.run,profile,mediaManifest:[],tasks:body.run.tasks.map(t=>t.id)},tasks:body.run.tasks.map(t=>({...t,profileId:'p',runId:body.run.id,status:'pending'}))};}}};return{runtime,store,requests};}
test('fixed registration preserves denominator and task IDs across repeated calls without starting browser work',async()=>{
 const f=fixture();const first=await registerAcceptance(f.runtime,'fixed');assert.equal(first.count,2);assert.equal(first.started,false);
 const second=await registerAcceptance(f.runtime,'fixed');assert.deepEqual(first.items,second.items);assert.equal(f.requests.filter(r=>r.route==='runs').length,2);assert.equal(f.store.get('paused'),true);f.store.close();
});

function lostRegistration(){
 const f=fixture(),combo=f.store.get('acceptance:fixed').combinations[0],profile=combo.profile,run={id:'original-run',profileId:'p',profileRevision:2,profile,createdAt:'2026-10-01T00:00:00Z',tasks:['original-task'],mediaManifest:[{asset_id:'original-logo',sha256:'a'.repeat(64)}]},task={id:'original-task',runId:run.id,profileId:'p',url:combo.url,destinationKey:queue.normalizeDestinationKey(combo.url),status:'needs_manual',attemptBoundary:'2026-10-01T00:01:00Z',receipt:{publicUrl:'https://receipt.example/original'},version:4};
 f.store.set('acceptanceExecution:fixed',{id:'fixed',scopeSha256:'frozen',items:{[combo.identity]:{status:'registration_unknown',runId:run.id,taskId:task.id,request:{id:run.id}},'two.example::p':{status:'excluded'}}});
 f.runtime.cloud.request=async(route,body)=>{f.requests.push({route,body});if(route==='snapshot')return{documents:{siteProfiles:{p:profile}},revisions:{siteProfiles:2}};if(route==='runs?view=inventory')return{runs:[{id:run.id,profileId:'p'}],tasks:[{id:task.id,runId:run.id,profileId:'p',url:task.url}]};if(route==='tasks/'+task.id)return{task:structuredClone(task)};if(route==='runs?runId='+run.id)return{runs:[structuredClone(run)],tasks:[structuredClone(task)]};throw Error('Unexpected route '+route);};
 return{...f,combo,run,task};
}
test('lost registration reply recovers exact full run profile media and receipt without replacing or replaying IDs',async()=>{
 const f=lostRegistration();try{const first=await registerAcceptance(f.runtime,'fixed'),item=first.items[f.combo.identity];assert.equal(item.status,'registered');assert.equal(item.originalTask,undefined);assert.equal(item.taskId,f.task.id);assert.equal(item.runId,f.run.id);assert.equal(item.request,undefined);assert.deepEqual(f.store.get('run:'+f.run.id),f.run);assert.deepEqual(f.store.get('task:'+f.task.id),{...f.task,acceptanceId:'fixed'});assert.equal(f.requests.filter(r=>r.route==='runs').length,0);const requests=f.requests.length;await registerAcceptance(f.runtime,'fixed');assert.equal(f.requests.length-requests,2);assert.equal(f.store.get('paused'),true);}finally{f.store.close();}
});
test('old registered index summary is repaired from full original run and keeps newer local unknown attempt',async()=>{
 const f=lostRegistration();try{const execution=f.store.get('acceptanceExecution:fixed');execution.items[f.combo.identity].status='registered';f.store.set('acceptanceExecution:fixed',execution);f.store.set('run:'+f.run.id,{id:f.run.id,profileId:'p'});const retained={...f.task,version:5,reason:'原本机未知结果保留',mediaUploadState:{uploaded:[{name:'original.png'}]}};f.store.set('task:'+f.task.id,retained);await registerAcceptance(f.runtime,'fixed');assert.deepEqual(f.store.get('run:'+f.run.id),f.run);assert.deepEqual(f.store.get('task:'+f.task.id),{...retained,acceptanceId:'fixed'});assert.equal(f.requests.filter(r=>r.route==='runs').length,0);}finally{f.store.close();}
});
test('a stronger original cloud submission boundary is never hidden by a local pending task during registration repair',async()=>{
 const f=lostRegistration();try{const local={...f.task,status:'pending'};delete local.attemptBoundary;delete local.receipt;f.store.set('task:'+f.task.id,local);const before=f.store.get('acceptanceExecution:fixed');await assert.rejects(registerAcceptance(f.runtime,'fixed'),/已有提交边界或收件/);assert.deepEqual(f.store.get('task:'+f.task.id),local);assert.equal(f.store.get('run:'+f.run.id),null);assert.deepEqual(f.store.get('acceptanceExecution:fixed'),before);assert.equal(f.requests.filter(r=>r.route==='runs').length,0);}finally{f.store.close();}
});
test('wrong original run task profile or incomplete media cannot turn uncertain registration into a replacement',async()=>{
 for(const patch of [{tasks:['different-task']},{profile:{id:'p',fields:{Name:'Changed'}}},{profileRevision:3},{mediaManifest:undefined}]){const f=lostRegistration();try{Object.assign(f.run,patch);const before=f.store.get('acceptanceExecution:fixed');await assert.rejects(registerAcceptance(f.runtime,'fixed'),/原批次|原注册资料/);assert.deepEqual(f.store.get('acceptanceExecution:fixed'),before);assert.equal(f.store.get('run:'+f.run.id),null);assert.equal(f.store.get('task:'+f.task.id),null);assert.equal(f.requests.filter(r=>r.route==='runs').length,0);}finally{f.store.close();}}
});
test('Neon object key reordering retains original profile identity while device changes reject stale readbacks',async()=>{
 const f=fixture(),request=f.runtime.cloud.request;try{f.runtime.cloud.request=async(route,body)=>{if(route==='snapshot')return{documents:{siteProfiles:{p:{fields:{Url:'https://product.example',Name:'P'},id:'p'}}},revisions:{siteProfiles:2}};return request(route,body);};const result=await registerAcceptance(f.runtime,'fixed');assert.equal(Object.values(result.items).filter(item=>item.status==='registered').length,2);}finally{f.store.close();}
 const changed=lostRegistration(),original=changed.runtime.cloud.request;try{changed.store.set('pair',{endpoint:'https://original.example',workspaceId:'original',deviceId:'original-device'});changed.runtime.cloud.request=async(route,body)=>{const result=await original(route,body);if(route==='runs?runId='+changed.run.id)changed.store.set('pair',{endpoint:'https://other.example',workspaceId:'other',deviceId:'other-device'});return result;};const before=changed.store.get('acceptanceExecution:fixed');await assert.rejects(registerAcceptance(changed.runtime,'fixed'),/工作区或设备/);assert.deepEqual(changed.store.get('acceptanceExecution:fixed'),before);assert.equal(changed.store.get('run:'+changed.run.id),null);assert.equal(changed.store.get('task:'+changed.task.id),null);}finally{changed.store.close();}
});
test('uncertain registration persists intent and refuses to replay or replace its task',async()=>{
 const f=fixture(),original=f.runtime.cloud.request;f.runtime.cloud.request=async(route,body)=>{if(route==='runs'){assert.equal(f.store.get('acceptanceExecution:fixed').items['one.example::p'].status,'registering');throw Object.assign(Error('connection lost'),{cloudNetwork:true});}return original(route,body);};
 const first=await registerAcceptance(f.runtime,'fixed');const taskId=first.items['one.example::p'].taskId;assert.equal(first.items['one.example::p'].status,'registration_unknown');
 const second=await registerAcceptance(f.runtime,'fixed');assert.equal(second.items['one.example::p'].taskId,taskId);assert.equal(second.items['one.example::p'].status,'registration_unknown');f.store.close();
});
