import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join,resolve,sep} from 'node:path';import {Store} from '../executor/src/store.mjs';import {workbenchScope} from '../executor/src/workbench-sync.mjs';import {enqueueLibraryMutation,flushApplicationMutations,overlayApplication,pendingApplication,resolveApplicationConflict} from '../executor/src/application-mutations.mjs';import {applicationMutation} from '../core/application-mutation.mjs';
const documents=()=>({siteProfiles:{p:{id:'p',name:'First',sortIndex:0,url:'https://p.example'},q:{id:'q',name:'Current',sortIndex:1,url:'https://q.example'}},activeSiteId:'q',selectedSiteIds:['q'],submissionRecords:{original:{profileId:'q',status:'success',evidence:'Original receipt'}}});
const create=id=>({type:'profile_create',profileId:id,profile:{id,name:'New '+id,url:'https://'+id+'.example'}});
function fixture(store,docs=documents()){const pair={endpoint:'https://fixture.invalid',workspaceId:'lifecycle'},scope=workbenchScope(pair),snapshot={documents:docs,revisions:{siteProfiles:1,activeSiteId:4,selectedSiteIds:5}};store.set('pair',pair);store.set('paused',true);store.set('applicationSnapshot',{scope,snapshot});let online=false;const writes=[],runtime={store,cloud:{async request(route,input){if(!online)throw Error('offline');if(route==='snapshot')return structuredClone(snapshot);writes.push(structuredClone(input));const change=applicationMutation(snapshot.documents,input.operation);snapshot.documents[change.key]=change.data;snapshot.revisions[change.key]=(snapshot.revisions[change.key]||0)+1;throw Error('committed response lost');}}};return{runtime,snapshot,writes,online(){online=true;}};}
test('original new site becomes current in a durable offline plan before any request and survives restart and lost responses',async()=>{
 const home=await mkdtemp(join(tmpdir(),'el-current-lifecycle-')),path=join(home,'outbox.sqlite');let store=new Store(path);const f=fixture(store);
 try{const result=await enqueueLibraryMutation(f.runtime,{operation:create('new')});assert.equal(result.pending,2);assert.equal(overlayApplication(f.runtime,f.snapshot).documents.activeSiteId,'new');assert.deepEqual(overlayApplication(f.runtime,f.snapshot).documents.selectedSiteIds,['q']);const ids=pendingApplication(f.runtime).map(item=>item.id);assert.equal(ids.length,2);store.close();store=new Store(path);f.runtime.store=store;f.online();for(let i=0;i<4;i++)await flushApplicationMutations(f.runtime);assert.equal(f.writes.length,2);assert.deepEqual(f.writes.map(write=>write.operation.id),ids);assert.equal(f.snapshot.documents.activeSiteId,'new');assert.equal(f.snapshot.documents.siteProfiles.new.sortIndex,2);assert.equal(store.get('applicationPlan:'+result.planId).status,'completed');assert.deepEqual(f.snapshot.documents.submissionRecords,documents().submissionRecords);assert.equal(store.get('paused'),true);}finally{store.close();assert.ok(resolve(home).startsWith(resolve(tmpdir())+sep)&&home.includes('el-current-lifecycle-'));await rm(home,{recursive:true,force:true});}
});
test('deleting current chooses first remaining in saved order; deleting another preserves current; last deletion persists empty',async()=>{
 for(const [target,profiles,active,expected]of [['q',documents().siteProfiles,'q','p'],['p',documents().siteProfiles,'q','q'],['q',{q:documents().siteProfiles.q},'q','']]){const store=new Store(':memory:'),docs={...documents(),siteProfiles:profiles,activeSiteId:active},f=fixture(store,docs);try{const result=await enqueueLibraryMutation(f.runtime,{operation:{type:'profile_delete',profileId:target}});assert.equal(result.pending,2);assert.equal(overlayApplication(f.runtime,f.snapshot).documents.activeSiteId,expected);f.online();for(let i=0;i<4;i++)await flushApplicationMutations(f.runtime);assert.equal(f.snapshot.documents.activeSiteId,expected);assert.equal(f.snapshot.documents.siteProfiles[target],undefined);assert.deepEqual(f.snapshot.documents.submissionRecords,documents().submissionRecords);assert.deepEqual(f.snapshot.documents.selectedSiteIds,['q']);}finally{store.close();}}
});
test('consecutive offline new sites append their full plans after prior selection edits and keep newest current',async()=>{
 const store=new Store(':memory:'),f=fixture(store);try{await enqueueLibraryMutation(f.runtime,{operation:{type:'profile_selection',key:'activeSiteId',value:'p'}});await enqueueLibraryMutation(f.runtime,{operation:create('new')});await enqueueLibraryMutation(f.runtime,{operation:create('newer')});assert.equal(pendingApplication(f.runtime).length,5);assert.equal(overlayApplication(f.runtime,f.snapshot).documents.activeSiteId,'newer');f.online();for(let i=0;i<7;i++)await flushApplicationMutations(f.runtime);assert.equal(f.writes.length,5);assert.equal(f.snapshot.documents.activeSiteId,'newer');assert.equal(f.snapshot.documents.siteProfiles.newer.sortIndex,3);}finally{store.close();}
});
test('remote profile conflict prevents a new-site plan from changing remote current site',async()=>{
 const store=new Store(':memory:'),f=fixture(store);try{await enqueueLibraryMutation(f.runtime,{operation:create('new')});f.snapshot.documents.siteProfiles.remote={id:'remote',name:'Remote',url:'https://remote.example'};f.snapshot.revisions.siteProfiles++;f.online();await flushApplicationMutations(f.runtime);assert.equal(f.writes.length,0);assert.equal(f.snapshot.documents.activeSiteId,'q');assert.ok(pendingApplication(f.runtime).some(item=>item.status==='conflict'));assert.equal(f.snapshot.documents.siteProfiles.new,undefined);}finally{store.close();}
});
test('keeping remote product content discards its dependent current-site change without choosing an absent product',async()=>{
 const store=new Store(':memory:'),f=fixture(store);try{await enqueueLibraryMutation(f.runtime,{operation:create('new')});f.snapshot.documents.siteProfiles.remote={id:'remote',name:'Remote'};f.snapshot.revisions.siteProfiles++;f.online();await flushApplicationMutations(f.runtime);const conflict=pendingApplication(f.runtime).find(item=>item.status==='conflict');await resolveApplicationConflict(f.runtime,{id:conflict.id,choice:'cloud',revision:f.snapshot.revisions.siteProfiles});assert.equal(f.writes.length,0);assert.equal(pendingApplication(f.runtime).length,0);assert.equal(f.snapshot.documents.activeSiteId,'q');assert.equal(f.snapshot.documents.siteProfiles.new,undefined);assert.ok(store.values('appMutation:').every(item=>item.status==='discarded'));assert.ok(store.values('applicationPlan:').every(plan=>plan.status==='completed'&&plan.excludedIds.length===2));}finally{store.close();}
});
test('failure while persisting the product plan rolls back both local entries before any cloud request',async()=>{
 const store=new Store(':memory:'),f=fixture(store),set=store.set.bind(store);store.set=(key,value)=>{if(key.startsWith('appMutation:')&&value.operation.type==='profile_selection')throw Error('simulated local storage failure');return set(key,value);};try{await assert.rejects(enqueueLibraryMutation(f.runtime,{operation:create('new')}),/local storage failure/);assert.equal(store.values('applicationPlan:').length,0);assert.equal(pendingApplication(f.runtime).length,0);assert.deepEqual(overlayApplication(f.runtime,f.snapshot).documents,documents());assert.equal(f.writes.length,0);}finally{store.close();}
});
test('original named site without homepage can be created and later clear its homepage while preserving receipt',()=>{
 const docs=documents(),op={type:'profile_create',profileId:'draft',at:'now',profile:{id:'draft',name:'新站点',url:'',fields:{Name:'新站点',Url:''}}},created=applicationMutation(docs,op);assert.equal(created.data.draft.url,'');const cleared=applicationMutation(docs,{type:'profile',profileId:'q',at:'now',profile:{id:'q',url:'',fields:{Url:''}}});assert.equal(cleared.data.q.url,'');assert.equal(docs.submissionRecords.original.evidence,'Original receipt');
});
test('original URL-only new site is accepted while missing both values and invalid supplied URLs are rejected',()=>{
 const docs=documents(),op={type:'profile_create',profileId:'url-only',at:'now',profile:{id:'url-only',name:'',url:'https://url-only.example'}};assert.equal(applicationMutation(docs,op).data['url-only'].url,op.profile.url);for(const patch of [{name:'',url:''},{name:7,url:''},{name:'Original',url:'javascript:alert(1)'},{name:'Original',url:7}])assert.throws(()=>applicationMutation(docs,{...op,profile:{id:'url-only',...patch}}),error=>error.status===400);
});
