import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PGlite } from '../executor/node_modules/@electric-sql/pglite/dist/index.js';
import { executorApi } from '../cloud/worker/src/executor-api.mjs';
import { artifactObjectKey } from '../cloud/worker/src/worker-core.mjs';

test('formal device API executes PostgreSQL constraints, scope, idempotent events and non-destructive receipt/review writes', async () => {
  const db = new PGlite();
  await db.exec(await readFile(new URL('../cloud/worker/schema.sql', import.meta.url), 'utf8'));
  const sql = (strings, ...params) => {
    const query = strings.reduce((s, part, i) => s + part + (i < params.length ? `$${i+1}` : ''), '');
    return { query, params, then: (resolve,reject) => db.query(query,params).then(x=>x.rows).then(resolve,reject) };
  };
  sql.transaction = queries => db.transaction(async tx => { const results=[]; for(const q of queries)results.push((await tx.query(q.query,q.params)).rows); return results; });
  const profile={id:'JevPlay',name:'JevPlay',fields:{Name:'JevPlay',Url:'https://jevplay.com'}};
  const original={'protected::Other':{status:'success',manual:true,reviewStatus:'reviewed'}};
  await sql`insert into externallink_workspaces(workspace_id) values('default')`;
  for (const [key,value] of Object.entries({siteProfiles:{JevPlay:profile},sheetTableData:{entries:[{link:'https://new.example/submit'}]},submissionRecords:original,submissionTimeline:{},siteAnnotations:{}})) await sql`insert into externallink_workspace_documents(workspace_id,document_key,data) values('default',${key},${JSON.stringify(value)}::jsonb)`;
  const artifacts=new Map();
  const env={APP_ACCESS_TOKEN:'admin-test-secret',MEDIA_BUCKET:{
    put:async(key,bytes)=>artifacts.set(key,new Uint8Array(bytes)),
    get:async key=>artifacts.has(key)?{arrayBuffer:async()=>artifacts.get(key).slice().buffer}:null,
  }};
  let fullSnapshotCalls=0;
  const helpers={artifactObjectKey,recordEvent:async()=>{},listSnapshot:async()=>{fullSnapshotCalls++;const rows=await sql`select document_key,data,revision from externallink_workspace_documents where workspace_id='default'`;return {documents:Object.fromEntries(rows.map(x=>[x.document_key,x.data])),revisions:Object.fromEntries(rows.map(x=>[x.document_key,Number(x.revision)]))};}};
  const call=async(route,token,body,workspace='default')=>{
    const response=await executorApi(new Request(`https://cloud.example/v1/executor/${route}`,{method:body?'POST':'GET',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined}),env,sql,workspace,helpers);
    return {status:response.status,...await response.json()};
  };
  assert.equal((await call('devices','not-authorized',{name:'x'})).status,401);
  const device=await call('devices',env.APP_ACCESS_TOKEN,{name:'Windows'});assert.equal(device.status,200,JSON.stringify(device));
  const token=device.deviceToken;
  assert.equal((await call('devices',token,{name:'forbidden'})).status,401);
  assert.equal((await call('snapshot',token,undefined,'other')).status,401);
  const run={id:'run1',profileId:'JevPlay',profileRevision:1,tasks:[{id:'task1',url:'https://new.example/submit',destinationKey:'new.example/submit'}]};
  const started=await call('runs',token,{run}); assert.equal(started.status,200,JSON.stringify(started));
  assert.equal((await call('runs',token,{run:{...run,id:'run2'}})).status,409);
  assert.equal((await call('lease',token,{taskId:'task1',version:99})).status,409);
  const task=started.tasks[0];
  const png=new Uint8Array(512*1024);for(let i=0;i<png.length;i++)png[i]=i%251;
  const uploaded=await call('artifact',token,{taskId:task.id,dataUrl:'data:image/png;base64,'+Buffer.from(png).toString('base64')});
  assert.equal(uploaded.status,200,JSON.stringify(uploaded));
  const downloaded=await call('artifact-read',token,{taskId:task.id,ref:uploaded.ref});
  assert.equal(downloaded.status,200);assert.deepEqual(new Uint8Array(Buffer.from(downloaded.dataUrl.split(',')[1],'base64')),png);
  assert.equal((await call('artifact-read',token,{taskId:task.id,ref:'cloud-artifact://executor-other-task-deadbeef'})).status,403);
  assert.equal((await call('artifact',token,{taskId:task.id,dataUrl:'data:image/png;base64,@@AA=='})).status,400);
  const lease=await call('lease',token,{taskId:task.id,version:1,controllerId:'worker1'});assert.equal(lease.status,200);
  assert.equal((await call('lease',token,{taskId:task.id,version:1,controllerId:'worker2'})).status,409);
  task.controllerId='worker1';
  const boundaryAt=new Date().toISOString();
  const event={id:'evt1',taskId:task.id,version:1,type:'attempt_boundary',at:boundaryAt,state:{...task,status:'submitting',attemptBoundary:boundaryAt,actualSubmission:{website:'https://jevplay.com'}}};
  assert.equal((await call('event',token,event)).status,200);
  assert.equal((await call('event',token,event)).duplicate,true);
  assert.deepEqual((await call('events/evt1',token)).event,event);
  const proof=await call('events/evt1?proof=1',token);assert.equal(proof.eventId,'evt1');assert.equal(typeof proof.checksum,'string');assert.equal(proof.event,undefined);
  assert.equal((await call('event',token,{...event,type:'changed'})).status,409,'same event id cannot acknowledge changed evidence');
  const inventory=await call('runs?view=inventory',token);
  assert.deepEqual(inventory.tasks[0],{id:task.id,runId:task.runId,url:task.url,destinationKey:task.destinationKey,profileId:task.profileId,
    status:'submitting',siteStatus:'not_submitted',attemptBoundary:event.at,version:1,controllerId:'worker1'});
  assert.equal(JSON.stringify(inventory).includes('actualSubmission'),false,'inventory omits task evidence payloads');
  const batchRead=await call('runs?runId=run1',token);
  assert.equal(batchRead.runs.length,1);assert.equal(batchRead.tasks.length,1);assert.equal(batchRead.tasks[0].actualSubmission.website,'https://jevplay.com');
  assert.deepEqual((await call('runs?runId=run1',await call('devices',env.APP_ACCESS_TOKEN,{name:'isolated-reader'}).then(x=>x.deviceToken))).tasks,[],'single-run reads stay device-scoped');
  assert.equal((await call('runs?runId=bad%2Fid',token)).status,400);
  const record={profileId:'JevPlay',destinationKey:task.destinationKey,destinationUrl:task.url,taskId:task.id,status:'success',publicationStatus:'submitted',evidence:'Received',submittedAt:event.at,actualSubmission:{website:'https://jevplay.com'},reviewStatus:'pending_review'};
  assert.equal((await call('receipt',token,{taskId:task.id,version:1,record})).status,200);
  assert.equal((await call('receipt',token,{taskId:task.id,version:1,record})).inserted,false);
  const beforeSnapshot=fullSnapshotCalls;
  const snapshot=await call('snapshot',token);assert.deepEqual(snapshot.documents.submissionRecords['protected::Other'],original['protected::Other']);
  assert.equal(fullSnapshotCalls,beforeSnapshot,'read-only device snapshot must not parse the complete workspace in the Worker');
  assert.equal(snapshot.documents.submissionTimeline['new.example/submit::JevPlay'].length,1);
  assert.equal((await call('receipt-status',token,{taskId:task.id,status:'pending_moderation',expectedEvidence:'Wrong'})).status,409);
  const receiptStatus=await call('receipt-status',token,{taskId:task.id,status:'pending_moderation',expectedEvidence:'Received'});
  assert.equal(receiptStatus.record.publicationStatus,'pending_moderation');
  assert.equal((await call('receipt-status',token,{taskId:task.id,status:'pending_moderation',expectedEvidence:'Received'})).duplicate,true);
  assert.equal((await call('snapshot',token)).documents.submissionTimeline['new.example/submit::JevPlay'].length,2);
  const review=await call('review',token,{taskId:task.id,reviewStatus:'reviewed'});assert.equal(review.task.reviewStatus,'reviewed');
  assert.equal((await call('snapshot',token)).documents.submissionRecords['new.example/submit::JevPlay'].publicationStatus,'pending_moderation');
  const handoff=await call('handoff',token,{taskId:task.id,version:1,previousControllerId:'worker1',controllerId:'supervisor'});assert.equal(handoff.version,2);
  assert.equal((await call('event',token,{...event,id:'stale-write'})).status,409);
  const returned=await call('handoff',token,{taskId:task.id,version:2,previousControllerId:'supervisor',controllerId:'worker1'});assert.equal(returned.version,3);
  const takeoverEvent={...event,id:'takeover-late',version:2,type:'takeover',state:{...task,version:2,controller:'supervisor',controllerId:'supervisor'}};
  assert.equal((await call('event',token,takeoverEvent)).historical,true,'late takeover audit must not restore stale state');
  assert.deepEqual((await call('events/takeover-late',token)).event,takeoverEvent);
  const returnEvent={...event,id:'returned',version:3,type:'returned_to_executor',state:{...task,version:3,controller:'executor',controllerId:'worker1',status:'pending'}};
  assert.equal((await call('event',token,returnEvent)).status,200);
  assert.equal((await call('runs',token)).tasks.find(x=>x.id===task.id).controllerId,'worker1');
  const corrected=await call('profile',token,{profileId:'JevPlay',revision:1,profile:{id:'JevPlay',fields:{Note:'Verified live play'}}});
  assert.equal(corrected.status,200);assert.equal(corrected.revision,2);
  assert.equal((await call('profile',token,{profileId:'JevPlay',revision:1,profile:{id:'JevPlay',fields:{Note:'stale write'}}})).status,409);
  assert.equal((await call('snapshot',token)).documents.siteProfiles.JevPlay.fields.Url,'https://jevplay.com');
  const isolated=await call('devices',env.APP_ACCESS_TOKEN,{name:'isolated-device'});
  assert.deepEqual((await call('runs',isolated.deviceToken)).tasks,[]);
  assert.deepEqual((await call('runs',isolated.deviceToken)).runs,[]);
  assert.deepEqual((await call('runs',token)).runs[0].profile,profile,'existing runs keep their original profile snapshot');
  await call('revoke',env.APP_ACCESS_TOKEN,{deviceId:device.deviceId});assert.equal((await call('snapshot',token)).status,401);
  await db.close();
});
