import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {randomUUID,createHash} from 'node:crypto';
import {PGlite} from '../executor/node_modules/@electric-sql/pglite/dist/index.js';
import {D1Store} from '../cloud/worker/src/d1-store.mjs';
import {d1Executor} from '../cloud/worker/src/d1-executor.mjs';
import {executorApi} from '../cloud/worker/src/executor-api.mjs';
import {Store} from '../executor/src/store.mjs';
import {Runtime} from '../executor/src/runtime.mjs';
import {Cloud} from '../executor/src/cloud.mjs';
import {previewWorkbenchBatch,startWorkbenchBatch,nextWorkbenchTask,finishWorkbenchTask} from '../executor/src/workbench-features.mjs';
import {batchJson,batchScopeRows} from '../core/workbench-batch-recovery.mjs';
import {freshRoundProof} from '../core/original-fresh-round.mjs';
import {recoverCloudBatchRecords} from '../executor/src/workbench-batch-recovery.mjs';
import vm from 'node:vm';
import {execFileSync} from 'node:child_process';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve,sep} from 'node:path';
import {chromium} from '../executor/node_modules/playwright/index.mjs';
const hash=value=>createHash('sha256').update(value).digest('hex');

async function fixture(kind){
 const savedFetch=globalThis.fetch,locals=[],objects=new Map(),bucket={head:async key=>objects.has(key)?{}:null,put:async(key,value,meta)=>objects.set(key,{bytes:new Uint8Array(value),meta}),get:async key=>{const value=objects.get(key);return value?{arrayBuffer:async()=>value.bytes.slice().buffer,httpMetadata:value.meta?.httpMetadata}:null;}};
 const env={APP_ACCESS_TOKEN:'isolated-admin',MEDIA_BUCKET:bucket},documents={siteProfiles:{p:{id:'p',name:'Original',fields:{Name:'Original',Url:'https://product.example'}}},sheetTableData:{entries:[{link:'https://target.example/form'}]},submissionRecords:{},unattendedPreferences:{enabled:true,hours:8,tasks:3,manualTabs:20}};
 let db,sql,backend,race;
 if(kind==='d1'){
  db=new DatabaseSync(':memory:');for(const name of ['0001_d1_storage.sql','0002_d1_executor.sql'])db.exec(readFileSync(new URL('../cloud/worker/migrations/'+name,import.meta.url),'utf8'));
  const adapter={prepare(text){let args=[];return{bind(...values){args=values;return this;},first:async()=>db.prepare(text).get(...args)||null,all:async()=>({results:db.prepare(text).all(...args)}),run:async()=>{const statement=db.prepare(text);return statement.columns().length?{results:statement.all(...args),meta:{changes:0}}:{results:[],meta:{changes:statement.run(...args).changes}};}};},async batch(statements){if(race){const work=race;race=null;await work();}db.exec('BEGIN');try{const result=[];for(const statement of statements)result.push(await statement.run());db.exec('COMMIT');return result;}catch(error){db.exec('ROLLBACK');throw error;}}};
  env.LEDGER_DB=adapter;backend=new D1Store(adapter,bucket,'default');for(const [key,data]of Object.entries(documents))await backend.putDocument(key,data,0);
  globalThis.fetch=(url,options)=>d1Executor(new Request(url,options),env,'default');
 }else{
  db=new PGlite();await db.exec(readFileSync(new URL('../cloud/worker/schema.sql',import.meta.url),'utf8'));
  sql=(strings,...params)=>{const query=strings.reduce((text,part,index)=>text+part+(index<params.length?'$'+(index+1):''),'');return{query,params,then:(done,reject)=>db.query(query,params).then(result=>result.rows).then(done,reject)};};
  sql.transaction=async queries=>{if(race){const work=race;race=null;await work();}return db.transaction(async tx=>{const result=[];for(const query of queries)result.push((await tx.query(query.query,query.params)).rows);return result;});};
  await sql`insert into externallink_workspaces(workspace_id) values('default')`;for(const [key,data]of Object.entries(documents))await sql`insert into externallink_workspace_documents(workspace_id,document_key,data) values('default',${key},${JSON.stringify(data)}::jsonb)`;
  const helpers={recordEvent:async()=>{},listSnapshot:async()=>{const rows=await sql`select document_key,data,revision from externallink_workspace_documents where workspace_id='default'`;return{documents:Object.fromEntries(rows.map(row=>[row.document_key,row.data])),revisions:Object.fromEntries(rows.map(row=>[row.document_key,Number(row.revision)]))};}};
  globalThis.fetch=(url,options)=>executorApi(new Request(url,options),env,sql,'default',helpers);
 }
 const enrollment=await (await globalThis.fetch('https://fixture.example/v1/executor/devices',{method:'POST',headers:{Authorization:'Bearer isolated-admin'},body:'{}'})).json(),pair={endpoint:'https://fixture.example',workspaceId:'default',deviceToken:enrollment.deviceToken,...(kind==='d1'?{storageBackend:'d1'}:{})},cloud=new Cloud(pair);
 const runtime=()=>{const store=new Store(':memory:');locals.push(store);store.set('pair',pair);store.set('paused',true);const runtime=new Runtime(store,'isolated');Object.defineProperty(runtime,'cloud',{value:cloud});runtime.tick=()=>{};return runtime;};
 const original=runtime(),preview=await previewWorkbenchBatch(original,{profileIds:['p'],urls:['https://target.example/form'],config:{fillOnly:true}});await startWorkbenchBatch(original,{batchId:preview.batch.id,ordinaryPermissionsAuthorized:true});
 const source=await nextWorkbenchTask(original);original.update(source,{status:'skip',siteStatus:'not_submitted',reason:'Original service unavailable',originalAgentSkip:{at:'old',cause:'cloud fetch failed'},targetId:'old-page',browserInstance:'old-browser'},'fixture_old_round');finishWorkbenchTask(original,source.id);await nextWorkbenchTask(original);await cloud.flush(original.store);original.store.set('paused',true);
 const count=async()=>kind==='d1'?db.prepare('SELECT count(*) n FROM executor_runs').get().n:Number((await sql`select count(*) as n from externallink_executor_runs`)[0].n);
 return{kind,original,source,cloud,runtime,db,sql,backend,count,oldBatch:preview.batch,async setProfile(){const profile={id:'p',name:'Current',fields:{Name:'Current',Url:'https://product.example'}};if(kind==='d1'){const row=await backend.document('siteProfiles');await backend.putDocument('siteProfiles',{p:profile},row.revision);}else await sql`update externallink_workspace_documents set data=${JSON.stringify({p:profile})}::jsonb,revision=revision+1 where workspace_id='default' and document_key='siteProfiles'`;},set race(work){race=work;},async close(){globalThis.fetch=savedFetch;for(const store of locals)store.close();await db.close();}};
}
for(const kind of ['d1','postgres']){
 test(kind+' fresh original round retains historical body and events, selects current product, resets its own budget and restores both rounds',async()=>{
  const f=await fixture(kind);try{
   const oldRead=(await f.cloud.request('runs?runId='+f.source.runId)).tasks[0],oldBody=kind==='d1'?f.db.prepare('SELECT object_key,checksum,summary FROM journal_tasks WHERE id=?').get(f.source.id):(await f.sql`select data from externallink_executor_tasks where task_id=${f.source.id}`)[0].data,oldEventCount=kind==='d1'?f.db.prepare('SELECT count(*) n FROM executor_events WHERE task_id=?').get(f.source.id).n:Number((await f.sql`select count(*) n from externallink_executor_events where task_id=${f.source.id}`)[0].n);
   await f.setProfile();const {batch}=await previewWorkbenchBatch(f.original,{profileIds:['p'],urls:['https://target.example/form'],config:{fillOnly:true}}),item=batch.items[0];assert.equal(item.status,'ready',item.reason);assert.equal(item.existingTask,false);assert.notEqual(item.taskId,f.source.id);assert.notEqual(item.runId,f.source.runId);assert.equal(item.originalFreshRound.sourceTaskId,f.source.id);assert.equal(item.profile.fields.Name,'Current');
   await startWorkbenchBatch(f.original,{batchId:batch.id,ordinaryPermissionsAuthorized:true});assert.equal(await f.count(),2);const next=await nextWorkbenchTask(f.original);assert.equal(next.id,item.taskId);assert.equal(next.profileSnapshot.fields.Name,'Current');for(const key of ['targetId','browserInstance','originalAgentSkip','originalGroupPage','originalGroupAdvance','attemptBoundary','receipt'])assert.equal(next[key],undefined);
   assert.equal(f.original.store.get('workbenchBatch:'+batch.id).unattendedState.taskBudgetUsed,1);assert.equal(f.original.store.get('workbenchBatch:'+f.oldBatch.id).unattendedState.taskBudgetUsed,1);
   const retired=(await f.cloud.request('runs?runId='+f.source.runId)).tasks[0];assert.equal(retired.originalFreshRoundSuccessorTaskId,next.id);assert.equal(retired.reason,oldRead.reason);assert.equal(retired.version,oldRead.version+1);
   assert.deepEqual(kind==='d1'?f.db.prepare('SELECT object_key,checksum,summary FROM journal_tasks WHERE id=?').get(f.source.id):(await f.sql`select data from externallink_executor_tasks where task_id=${f.source.id}`)[0].data,oldBody);
   assert.equal(kind==='d1'?f.db.prepare('SELECT count(*) n FROM executor_events WHERE task_id=?').get(f.source.id).n:Number((await f.sql`select count(*) n from externallink_executor_events where task_id=${f.source.id}`)[0].n),oldEventCount);
   await assert.rejects(f.cloud.request('lease',{taskId:retired.id,version:retired.version,controllerId:f.original.controllerId}),error=>error.status===409);f.original.store.set('offlineMode',{enabled:true});await assert.rejects(f.original.lease(f.original.store.get('task:'+retired.id)),/旧任务/);f.original.store.set('offlineMode',null);
   const restored=f.runtime();await restored.restoreCloud();assert.equal(restored.store.get('paused'),true);assert.equal(restored.store.get('task:'+retired.id).originalFreshRoundSuccessorTaskId,next.id);assert.equal(restored.store.get('workbenchBatch:'+batch.id).scopeSha256,batch.scopeSha256);assert.deepEqual(restored.store.get('workbenchBatch:'+batch.id).items[0].originalFreshRound,item.originalFreshRound);assert.equal(restored.store.get('workbenchBatch:'+f.oldBatch.id).count,1);
  }finally{await f.close();}
 });
 test(kind+' lost fresh-round registration response recovers only exact new IDs and preserves original retired evidence',async()=>{
  const f=await fixture(kind);try{const {batch}=await previewWorkbenchBatch(f.original,{profileIds:['p'],urls:['https://target.example/form'],config:{fillOnly:true}}),request=f.cloud.request.bind(f.cloud);let lost=true;
   f.cloud.request=async(route,input,...rest)=>{const result=await request(route,input,...rest);if(lost&&route==='runs'&&input?.run){lost=false;throw Error('lost fresh round reply');}return result;};await assert.rejects(startWorkbenchBatch(f.original,{batchId:batch.id,ordinaryPermissionsAuthorized:true}),/lost fresh round reply/);assert.equal(await f.count(),2);assert.equal(f.original.store.get('workbenchBatch:'+batch.id).status,'registration_unknown');
   await startWorkbenchBatch(f.original,{batchId:batch.id,ordinaryPermissionsAuthorized:true});assert.equal(await f.count(),2);assert.equal(f.original.store.get('task:'+f.source.id).originalFreshRoundSuccessorTaskId,batch.items[0].taskId);assert.equal(f.original.store.get('task:'+batch.items[0].taskId).runId,batch.items[0].runId);
  }finally{await f.close();}
 });
 test(kind+' stale body, unknown attempt, wrong source and a registration race never retire the protected task or leave a new run',async()=>{
  const f=await fixture(kind);try{
   const {batch}=await previewWorkbenchBatch(f.original,{profileIds:['p'],urls:['https://target.example/form'],config:{fillOnly:true}}),item=batch.items[0],snapshot=await f.cloud.request('snapshot'),makeRun=proof=>({id:randomUUID(),profileId:'p',profileRevision:snapshot.revisions.siteProfiles,createdAt:'now',freshRoundControllerId:f.original.controllerId,tasks:[{id:randomUUID(),url:item.url,destinationKey:item.destinationKey,originalFreshRound:proof}]});
   f.original.update(f.source,{reason:'Changed old reason'},'fixture_same_version_change');await f.cloud.flush(f.original.store);await assert.rejects(f.cloud.request('runs',{run:makeRun(item.originalFreshRound)}),error=>error.status===409);assert.equal(await f.count(),1);
   f.original.update(f.source,{attemptBoundary:'unknown-original-attempt'},'fixture_unknown');await f.cloud.flush(f.original.store);const unknown=(await f.cloud.request('runs?runId='+f.source.runId)).tasks[0],proof=await freshRoundProof(unknown,hash);await assert.rejects(f.cloud.request('runs',{run:makeRun(proof)}),error=>error.status===409);const excluded=await previewWorkbenchBatch(f.original,{profileIds:['p'],urls:[item.url]});assert.equal(excluded.batch.items[0].status,'excluded');assert.equal(await f.count(),1);
   // Fixture explicitly restores its synthetic unsubmitted state to test the
   // independent CAS race; production unknown attempts are never cleared.
   f.original.update(f.source,{attemptBoundary:null},'fixture_reset_only');await f.cloud.flush(f.original.store);const source=(await f.cloud.request('runs?runId='+f.source.runId)).tasks[0],current=await freshRoundProof(source,hash);
   await assert.rejects(f.cloud.request('runs',{run:makeRun({...current,sourceTaskId:'another-task'})}),error=>[403,409].includes(error.status));
   f.race=async()=>{if(kind==='d1')f.db.prepare('UPDATE executor_controls SET version=version+1 WHERE id=?').run(source.id);else await f.sql`update externallink_executor_tasks set version=version+1 where task_id=${source.id}`;};await assert.rejects(f.cloud.request('runs',{run:makeRun(current)}),error=>error.status===409);assert.equal(await f.count(),1);assert.equal((await f.cloud.request('runs?runId='+source.runId)).tasks[0].originalFreshRoundSuccessorTaskId,undefined);
  }finally{await f.close();}
 });
 test(kind+' repeated original error and failed rounds allow an alternate same-host entrance and protect receipts, active controls and other devices',async()=>{
  const f=await fixture(kind);try{let source=f.source;
   for(const status of ['err','failed','excluded']){
    f.original.update(source,{status,reason:'Historical '+status},'fixture_terminal');finishWorkbenchTask(f.original,source.id);await nextWorkbenchTask(f.original);await f.cloud.flush(f.original.store);f.original.store.set('paused',true);
    const {batch}=await previewWorkbenchBatch(f.original,{profileIds:['p'],urls:['https://www.target.example/form'],config:{fillOnly:true}});assert.equal(batch.items[0].status,'ready',batch.items[0].reason);assert.equal(batch.items[0].originalFreshRound.sourceTaskId,source.id);await startWorkbenchBatch(f.original,{batchId:batch.id,ordinaryPermissionsAuthorized:true});source=await nextWorkbenchTask(f.original);assert.equal(source.url,'https://www.target.example/form');assert.equal(source.version,1);assert.equal(f.original.store.get('workbenchBatch:'+batch.id).unattendedState.taskBudgetUsed,1);
   }
   assert.equal(await f.count(),4);const snapshot=await f.cloud.request('snapshot'),run={id:randomUUID(),profileId:'p',profileRevision:snapshot.revisions.siteProfiles,createdAt:'now',tasks:[{id:randomUUID(),url:'https://target.example/form',destinationKey:f.source.destinationKey}]};await assert.rejects(f.cloud.request('runs',{run}),error=>error.status===409);
   const enrollment=await (await globalThis.fetch('https://fixture.example/v1/executor/devices',{method:'POST',headers:{Authorization:'Bearer isolated-admin'},body:'{}'})).json(),other=new Cloud({...f.original.store.get('pair'),deviceToken:enrollment.deviceToken});await assert.rejects(other.request('runs',{run:{...run,id:randomUUID(),tasks:[{...run.tasks[0],id:randomUUID()}]}}),error=>error.status===409);assert.equal(await f.count(),4);
   f.original.update(source,{status:'skip',reason:'Before foreign lease'},'fixture_terminal');finishWorkbenchTask(f.original,source.id);await nextWorkbenchTask(f.original);await f.cloud.flush(f.original.store);f.original.store.set('paused',true);const remote=(await f.cloud.request('runs?runId='+source.runId)).tasks[0],proof=await freshRoundProof(remote,hash);
   await assert.rejects(f.cloud.request('runs',{run:{...run,id:randomUUID(),freshRoundControllerId:f.original.controllerId,tasks:[{...run.tasks[0],id:f.source.id,originalFreshRound:proof}]}}),error=>error.status===409);assert.equal(await f.count(),4);const rolledBack=(await f.cloud.request('runs?runId='+source.runId)).tasks[0];assert.equal(rolledBack.version,remote.version);assert.equal(rolledBack.originalFreshRoundSuccessorTaskId,undefined);
   if(kind==='d1')f.db.prepare('UPDATE executor_controls SET controller_id=?,lease_until=? WHERE id=?').run('foreign',Date.now()+90000,source.id);else await f.sql`update externallink_executor_tasks set controller_id='foreign',lease_until=now()+interval '90 seconds' where task_id=${source.id}`;
   const foreign=(await f.cloud.request('runs?runId='+source.runId)).tasks[0],foreignProof=await freshRoundProof(foreign,hash);await assert.rejects(f.cloud.request('runs',{run:{...run,id:randomUUID(),freshRoundControllerId:f.original.controllerId,tasks:[{...run.tasks[0],id:randomUUID(),originalFreshRound:foreignProof}]}}),error=>error.status===409);assert.equal(await f.count(),4);
   f.original.store.set('task:'+source.id,{...source,receipt:{evidence:'late original receipt'}});const protectedPreview=await previewWorkbenchBatch(f.original,{profileIds:['p'],urls:[source.url]});assert.equal(protectedPreview.batch.items[0].status,'excluded');assert.equal(await f.count(),4);assert.ok(proof.sourceSha256);
  }finally{await f.close();}
 });
 test(kind+' new-round provenance cannot be changed by a task event or a restored task body',async()=>{
  const f=await fixture(kind);try{const {batch}=await previewWorkbenchBatch(f.original,{profileIds:['p'],urls:['https://target.example/form'],config:{fillOnly:true}});await startWorkbenchBatch(f.original,{batchId:batch.id,ordinaryPermissionsAuthorized:true});const task=await nextWorkbenchTask(f.original);await f.cloud.flush(f.original.store);const state={...task,originalFreshRound:{...task.originalFreshRound,sourceTaskId:'changed'}};
   await assert.rejects(f.cloud.request('event',{id:randomUUID(),taskId:task.id,version:task.version,type:'forged_round_source',at:'now',state}),error=>error.status===403);const remote=await f.cloud.request('runs');assert.equal(remote.tasks.find(row=>row.id===task.id).originalFreshRound.sourceTaskId,f.source.id);
   remote.tasks.find(row=>row.id===task.id).originalFreshRound=state.originalFreshRound;const restored=f.runtime();assert.throws(()=>recoverCloudBatchRecords(restored,remote.runs,remote.tasks),/新一轮来源/);assert.equal(restored.store.values('workbenchBatch:').length,0);
  }finally{await f.close();}
 });
}
test('new retry provenance is immutable while existing recovery scope hashes remain byte-for-byte compatible',()=>{
 const item={identity:'p::target.example',url:'https://target.example',profile:{id:'p'},profileRevision:1,taskId:'old',runId:'run'},batch={items:[item]};assert.equal(batchJson(batchScopeRows(batch)),batchJson([{identity:item.identity,url:item.url,profile:item.profile,profileRevision:1,taskId:'old',runId:'run'}]));const old=hash(batchJson(batchScopeRows(batch)));item.originalFreshRound={sourceTaskId:'source',sourceRunId:'before',sourceVersion:1,sourceSha256:'a'.repeat(64)};assert.notEqual(hash(batchJson(batchScopeRows(batch))),old);const first=hash(batchJson(batchScopeRows(batch)));item.originalFreshRound.sourceVersion=2;assert.notEqual(hash(batchJson(batchScopeRows(batch))),first);
});
test('the original pre-executor queue rebuild admits skipped products but still excludes receipt and dead-end site annotations',()=>{
 const source=execFileSync('git',['show','bd916b2944a577b160a6afcb8a7d73d263044c0c:extension/lib/queue.js'],{encoding:'utf8'}),sandbox=vm.createContext({self:{},URL,Date});vm.runInContext(source,sandbox);const queue=sandbox.self.ExtLinkQueue,input={tableData:{entries:[{link:'https://target.example/form'}]},siteProfiles:{p:{id:'p',name:'Original',fields:{Url:'https://product.example'}}},selectedProfileIds:['p'],submissionRecords:{},annotations:{},historicalTasks:[{status:'skip',profileId:'p'}]};assert.equal(queue.buildDestinationGroups(input)[0].jobs.length,1);const destinationKey=queue.normalizeDestinationKey(input.tableData.entries[0].link);input.submissionRecords[queue.submissionRecordKey(destinationKey,'p')]={status:'success',profileId:'p',destinationKey,confirmedBy:'manual',evidence:'Isolated original receipt'};assert.equal(queue.buildDestinationGroups(input).length,0);input.submissionRecords={};input.annotations[destinationKey]={status:'paid'};assert.equal(queue.buildDestinationGroups(input).length,0);
});
test('actual isolated native fresh round fills the current product without the old page, agent state or submission',async()=>{
 const f=await fixture('d1'),home=await mkdtemp(join(tmpdir(),'el-fresh-round-browser-'));let browser;
 try{await f.setProfile();const runtime=f.original,{batch}=await previewWorkbenchBatch(runtime,{profileIds:['p'],urls:['https://target.example/form'],config:{fillOnly:true}});await startWorkbenchBatch(runtime,{batchId:batch.id,ordinaryPermissionsAuthorized:true});runtime.home=home;browser=await chromium.launch({channel:'chrome',headless:true,args:['--disable-extensions']});const context=await browser.newContext();let posts=0,external=0;
  await context.route('**/*',async route=>{if(!/^https:\/\/(target|user-page)\.example\//.test(route.request().url())){external++;await route.abort();return;}if(route.request().method()==='POST'){posts++;await route.abort();return;}await route.fulfill({contentType:'text/html',body:'<!doctype html><title>Submit your tool</title><form><label>Product name<input name="name" required></label><label>Website<input name="url" type="url" required></label><button type="submit">Submit tool</button></form>'});});
  const user=await context.newPage();await user.goto('https://user-page.example/keep');runtime.context=context;runtime.host={startedAt:'isolated-fresh-browser'};const task=await nextWorkbenchTask(runtime);await runtime.work({taskId:task.id});const saved=runtime.store.get('task:'+task.id),page=await runtime.findPage(saved);assert.equal(saved.status,'needs_manual');assert.equal(saved.fillOnlyPrepared,true);assert.equal(saved.originalAgentSkip,undefined);assert.equal(saved.originalGroupPage,undefined);assert.equal(saved.attemptBoundary,undefined);assert.equal(saved.receipt,undefined);assert.notEqual(saved.targetId,'old-page');assert.equal(await page.locator('input[name=name]').inputValue(),'Current');assert.equal(await page.locator('input[name=url]').inputValue(),'https://product.example');assert.equal(user.isClosed(),false);assert.equal(posts,0);assert.equal(external,0);assert.equal(runtime.store.get('task:'+f.source.id).reason,'Original service unavailable');assert.equal(runtime.store.get('workbenchBatch:'+batch.id).unattendedState.taskBudgetUsed,1);
 }finally{await browser?.close();await f.close();const absolute=resolve(home);assert.ok(absolute.startsWith(resolve(tmpdir())+sep)&&absolute.split(sep).at(-1).startsWith('el-fresh-round-browser-'));await rm(absolute,{recursive:true,force:true});}
});
test('native fresh-round preflight preserves unsynced old edits and rejects local scope or attempt changes during cloud registration',async()=>{
 const f=await fixture('d1');try{f.original.update(f.source,{reason:'Pending old edit'},'fixture_pending_edit');const excluded=await previewWorkbenchBatch(f.original,{profileIds:['p'],urls:[f.source.url]});assert.equal(excluded.batch.items[0].status,'excluded');assert.equal(await f.count(),1);await f.cloud.flush(f.original.store);
  const {batch}=await previewWorkbenchBatch(f.original,{profileIds:['p'],urls:[f.source.url],config:{fillOnly:true}}),request=f.cloud.request.bind(f.cloud);let late=true;
  f.cloud.request=async(route,input,...rest)=>{const result=await request(route,input,...rest);if(late&&route==='runs'&&input?.run){late=false;f.original.store.set('task:'+f.source.id,{...f.original.store.get('task:'+f.source.id),attemptBoundary:'late-local-unknown'});}return result;};await assert.rejects(startWorkbenchBatch(f.original,{batchId:batch.id,ordinaryPermissionsAuthorized:true}),/注册期间原任务/);assert.equal(await f.count(),2);assert.equal(f.original.store.get('workbenchBatch:'+batch.id).status,'registration_unknown');assert.equal(f.original.store.get('paused'),true);assert.equal(f.original.store.get('task:'+f.source.id).attemptBoundary,'late-local-unknown');await assert.rejects(startWorkbenchBatch(f.original,{batchId:batch.id,ordinaryPermissionsAuthorized:true}),/同步或核验/);assert.equal(await f.count(),2);assert.equal(f.original.store.get('task:'+batch.items[0].taskId),null);
 }finally{await f.close();}
});
