import test from 'node:test';import assert from 'node:assert/strict';
import {applicationModel} from '../core/application-model.mjs';import {applicationMutation,applicationMutationSatisfied} from '../core/application-mutation.mjs';
import {Store} from '../executor/src/store.mjs';import {previewWorkbenchBatch,startWorkbenchBatch,nextWorkbenchTask,finishWorkbenchTask,pauseWorkbenchBatch} from '../executor/src/workbench-features.mjs';
import {originalAssistantTask,saveAssistantSettings,assistantState,fillAssistantTask} from '../executor/src/browser-assistant.mjs';
const profile=id=>({id,name:id,url:'https://'+id+'.example',fields:{Name:id,Url:'https://'+id+'.example'}});
test('assistant is opt-in and binds only an unattempted original task in the original browser target',async()=>{
 const store=new Store(':memory:'),runtime={store,host:{startedAt:'original-host'},cloud:{request:async()=>({documents:{siteProfiles:{p:profile('p')}},revisions:{siteProfiles:1}})}};
 try{store.set('pair',{endpoint:'https://cloud.example',workspaceId:'workspace',deviceId:'device'});assert.equal(assistantState(runtime).settings.enabled,false);await saveAssistantSettings(runtime,{enabled:true,autoFillOnVisit:true,profileId:'p'});
  const task={id:'one',profileId:'p',targetId:'original-target',browserInstance:'original-host',url:'https://target.example/submit',status:'pending'};store.set('task:one',task);
  assert.equal(originalAssistantTask(runtime,'p','original-target',task.url).id,'one');assert.equal(originalAssistantTask(runtime,'p','other-target',task.url),undefined);assert.equal(originalAssistantTask(runtime,'p','original-target','https://other.example/submit'),undefined);
  store.set('task:one',{...task,attemptBoundary:'unknown'});assert.equal(originalAssistantTask(runtime,'p','original-target',task.url),undefined);store.set('paused',true);await assert.rejects(fillAssistantTask(runtime,{taskId:task.id,targetId:task.targetId,url:task.url}),/原任务/);
  store.set('pair',{endpoint:'https://cloud.example',workspaceId:'another',deviceId:'device'});assert.equal(assistantState(runtime).settings.enabled,false);await assert.rejects(saveAssistantSettings(runtime,{enabled:true,autoFillOnVisit:true,profileId:'missing'}),/产品/);
 }finally{store.close();}
});
test('pin keeps platform tags and unrelated URL rows while removing only the selected deletion marker',()=>{
 const docs={urlList:'https://other.test/a|wp_comment\nhttps://same.test/page|profile\nhttps://same.test/page|directory',deletedSubmissionKeys:['same.test/page','other.test/a']},pin={type:'pin',url:'https://same.test/page',id:'pin',at:'now'},next=applicationMutation(docs,pin);
 assert.equal(next.data,'https://same.test/page|profile\nhttps://other.test/a|wp_comment');assert.equal(applicationMutationSatisfied({...docs,urlList:next.data},pin),true);
 const clear=applicationMutation(docs,{type:'clear_deleted',url:'https://same.test/page',id:'clear',at:'now'});assert.deepEqual(clear.data,['other.test/a']);assert.deepEqual(docs.deletedSubmissionKeys,['same.test/page','other.test/a']);assert.throws(()=>applicationMutation(docs,{...pin,url:'chrome://extensions'}),/普通/);
});
test('delete removes only the chosen profile, keeps receipt and media evidence and acknowledges lost replies',()=>{
 const docs=documents();docs.submissionRecords.receipt={profileId:'p',status:'success',evidence:'original'};docs.siteProfiles.p.mediaVersions=[{assetId:'one',ref:'cloud-media://one'}];const original=structuredClone(docs),operation={type:'profile_delete',profileId:'p',id:'delete',at:'now'},change=applicationMutation(docs,operation);
 assert.equal(change.key,'siteProfiles');assert.equal(change.data.p,undefined);assert.deepEqual(change.data.q,{...original.siteProfiles.q,sortIndex:0});assert.deepEqual(docs,original);assert.equal(applicationMutationSatisfied({...docs,siteProfiles:change.data},operation),true);assert.equal(docs.submissionRecords.receipt.evidence,'original');
});
const documents=()=>({siteProfiles:{p:profile('p'),q:profile('q')},sheetTableData:{entries:[{link:'https://one.example/submit',category:'Startup launch',metrics:{dr:85,traffic:20000}},{link:'https://two.example/add',category:'AI tool directory',metrics:{dr:20}}]},siteAnnotations:{},submissionRecords:{},submissionTimeline:{}});
function runtimeFixture(){const store=new Store(':memory:');store.set('paused',true);const snapshot={documents:documents(),revisions:{siteProfiles:1}},runs=[],tasks=[];let runWrites=0,ticks=0,lost=false;const runtime={store,job:null,cloud:{async request(route,input){if(route==='snapshot')return structuredClone(snapshot);if(route==='runs?view=inventory')return{runs:structuredClone(runs),tasks:structuredClone(tasks)};if(route.startsWith('tasks/'))return{task:tasks.find(t=>t.id===route.slice(6))};if(route==='runs'){runWrites++;const run={...input.run,tasks:input.run.tasks.map(t=>t.id)};runs.push(run);const created=input.run.tasks.map(t=>({...t,runId:run.id,profileId:run.profileId,status:'pending',version:1}));tasks.push(...created);if(lost)throw Error('reply lost');return{run,tasks:created};}throw Error('Unexpected route '+route);}},async lease(){},update(task,patch){Object.assign(task,patch);store.set('task:'+task.id,task);},tick(){ticks++;}};return{runtime,snapshot,tasks,runs,get writes(){return runWrites;},get ticks(){return ticks;},set lost(value){lost=value;}};}
test('overview excludes untouched registrations, includes notes and real handling, and accepts new products without adding matrix columns',()=>{
 const docs=documents();docs.submissionTimeline={'one.example/submit::q':[{id:'note',profileId:'q',destinationUrl:'https://one.example/submit',destinationKey:'one.example/submit',occurredAt:'2026-09-30T01:00:00Z',type:'note',note:'Follow up'}]};
 const model=applicationModel({documents:docs},[{id:'fresh',profileId:'p',url:'https://two.example/add',status:'pending',createdAt:'2026-09-30T02:00:00Z'},{id:'handled',profileId:'p',url:'https://one.example/submit',status:'needs_manual',reason:'Needs login',updatedAt:'2026-09-30T03:00:00Z'}]);
 assert.deepEqual(model.activity.map(c=>c.identity),['one.example::p','one.example::q']);assert.equal(model.activity[1].submission,'not_submitted');assert.equal(model.library.find(r=>r.site==='one.example').metrics.dr,85);assert.ok(model.library[0].quality.score>model.library[1].quality.score);assert.equal(model.library[0].groups.includes('high_quality'),true);
 docs.siteProfiles.new=profile('new');assert.equal(applicationModel({documents:docs}).products.length,3);assert.equal(applicationModel({documents:docs}).activity.length,1);
});
test('original favorites, explicit group removals, enabled state and DR updates are preserved by independent mutations',()=>{
 const docs=documents();docs.siteAnnotations['one.example/submit']={status:'needs_login',note:'Original',library:{favorite:true,groups:[],profileIds:['p']}};
 const model=applicationModel({documents:docs});assert.equal(model.library[0].preferences.favorite,true);assert.deepEqual(model.library[0].groups,[]);
 const mark={id:'mark',at:'now',type:'mark',url:'https://one.example/submit',statuses:['needs_login','needs_captcha'],note:'Original'};docs.siteAnnotations=applicationMutation(docs,mark).data;assert.equal(docs.siteAnnotations['one.example/submit'].library.favorite,true);assert.equal(applicationMutationSatisfied(docs,mark),true);
 const prefs={id:'prefs',at:'now',type:'preferences',url:'https://one.example/submit',preferences:{enabled:false}};docs.siteAnnotations=applicationMutation(docs,prefs).data;assert.equal(docs.siteAnnotations['one.example/submit'].note,'Original');assert.equal(docs.siteAnnotations['one.example/submit'].library.favorite,true);assert.equal(applicationMutationSatisfied(docs,prefs),true);
 const edit={id:'edit',at:'now',type:'edit',url:'https://one.example/submit',fields:{dr:'77'}};docs.sheetTableData=applicationMutation(docs,edit).data;assert.equal(applicationModel({documents:docs}).library[0].metrics.dr,77);
 assert.throws(()=>applicationMutation(docs,{...edit,fields:{dr:'200'}}),/DR/);assert.throws(()=>applicationMutation(docs,{...prefs,preferences:{profileIds:['missing']}}),/产品/);
});
test('manual timeline edit and removal never erase a receipt ledger; rules and old filter fields roundtrip',()=>{
 const docs=documents();docs.submissionRecords.proof={status:'success',profileId:'p',evidence:'Original receipt'};docs.submissionTimeline={'one.example::p':[{id:'note',profileId:'p',destinationKey:'one.example',type:'note',note:'Old',occurredAt:'2026-09-30T00:00:00Z'}]};
 const op={id:'edit',at:'now',type:'timeline',action:'update',eventId:'note',patch:{note:'New'}};docs.submissionTimeline=applicationMutation(docs,op).data;assert.equal(applicationMutationSatisfied(docs,op),true);docs.submissionTimeline=applicationMutation(docs,{...op,action:'remove'}).data;assert.equal(docs.submissionRecords.proof.evidence,'Original receipt');
 const settings={id:'settings',at:'now',type:'settings',key:'targetFilters',value:{aiComments:true,aiCommentAllowLink:false,blacklistEnabled:false,requireKnownDomainAge:true,minOpportunityScore:55,minDomainAgeMonths:6,showManualFillIcons:false}};assert.deepEqual(applicationMutation(docs,settings).data,settings.value);
 const update={type:'profile',profileId:'p',profile:{id:'p',language:'en',anchorRules:{brandKeywords:['p'],allowExactMatch:false},blogRules:{tone:'professional',maxLinksPerDraft:1,preferredAnchor:'natural'},targetAudience:'Developers',useCases:['Explore']},at:'now'};docs.siteProfiles=applicationMutation(docs,update).data;assert.equal(applicationMutationSatisfied(docs,update),true);
});
test('batch preview is side effect free, isolates pending tasks, supports multiple products and preserves the original fixed denominator',async()=>{
 const f=runtimeFixture(),r=f.runtime;const fixed={id:'original',count:30,cursor:13,status:'paused'};r.store.set('acceptanceBatch',fixed);r.store.set('task:unrelated',{id:'unrelated',profileId:'p',url:'https://other.example',status:'pending'});
 const {batch}=await previewWorkbenchBatch(r,{profileIds:['p','q'],urls:['https://one.example/submit','https://two.example/add']});assert.equal(batch.count,4);assert.equal(f.writes,0);assert.equal(f.ticks,0);assert.equal(r.store.get('paused'),true);
 r.cloud.flush=async store=>{for(const event of store.pending())store.ack(event.id);};await startWorkbenchBatch(r,{batchId:batch.id,ordinaryPermissionsAuthorized:true});assert.equal(f.writes,4);assert.deepEqual(r.store.get('acceptanceBatch'),fixed);assert.equal(r.store.get('task:unrelated').status,'pending');
 const first=await nextWorkbenchTask(r);assert.equal(first.id,batch.items[0].taskId);first.status='finished';first.receipt={evidence:'Received'};r.store.set('task:'+first.id,first);assert.equal(finishWorkbenchTask(r,first.id),true);assert.equal(r.store.get('workbenchBatch:'+batch.id).cursor,1);
 pauseWorkbenchBatch(r);r.store.set('paused',true);assert.equal(r.store.get('workbenchBatch:'+batch.id).status,'paused');assert.deepEqual(r.store.get('acceptanceBatch'),fixed);r.store.close();
});
test('a lost batch registration response reads back exact IDs and never creates a replacement task',async()=>{
 const f=runtimeFixture();f.lost=true;const {batch}=await previewWorkbenchBatch(f.runtime,{profileIds:['p'],urls:['https://one.example/submit']});await assert.rejects(startWorkbenchBatch(f.runtime,{batchId:batch.id,ordinaryPermissionsAuthorized:true}),/reply lost/);assert.equal(f.writes,1);assert.equal(f.runtime.store.get('paused'),true);
 f.runtime.cloud.flush=async store=>{for(const event of store.pending())store.ack(event.id);};f.lost=false;await startWorkbenchBatch(f.runtime,{batchId:batch.id,ordinaryPermissionsAuthorized:true});assert.equal(f.writes,1);assert.equal(f.runtime.store.get('task:'+batch.items[0].taskId).id,batch.items[0].taskId);f.runtime.store.close();
});
test('quality, DR, blacklist and age gates affect actual batch eligibility instead of only the UI',async()=>{
 const f=runtimeFixture();f.snapshot.documents.targetFilters={minDr:60,minDomainAgeMonths:6,requireKnownDomainAge:true};f.snapshot.documents.domainMetricsCache={'one.example':{ageMonths:36}};
 const {batch}=await previewWorkbenchBatch(f.runtime,{profileIds:['p'],urls:['https://one.example/submit','https://two.example/add']});assert.equal(batch.items[0].status,'ready');assert.equal(batch.items[1].status,'excluded');assert.match(batch.items[1].reason,/DR/);f.runtime.store.close();
});

test('legacy Excel and Chinese record times sort as real dates and preserve canonical categories',()=>{const T=globalThis.ExtLinkSubmissionTimeline;assert.equal(T.parseTime('46261'),Date.UTC(2026,7,27));assert.equal(T.parseTime('2026-8-27 上午12:00:00'),Date.parse('2026-08-27T00:00:00+08:00'));assert.equal(T.parseTime('2026-8-27 下午1:10:00'),Date.parse('2026-08-27T13:10:00+08:00'));const docs=documents();docs.sheetTableData.entries[0].category='启动发布';assert.equal(applicationModel({documents:docs}).library[0].category,'启动发布');});
