import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,mkdtemp,rm} from 'node:fs/promises';
import {join,resolve,sep} from 'node:path';
import {tmpdir} from 'node:os';
import {createHash} from 'node:crypto';
import {PGlite} from '../executor/node_modules/@electric-sql/pglite/dist/index.js';
import {d1Executor} from '../cloud/worker/src/d1-executor.mjs';
import {executorApi} from '../cloud/worker/src/executor-api.mjs';
import {aiCloudFixture} from '../executor/test/fixtures/ai-cloud.mjs';
import {Store} from '../executor/src/store.mjs';
import {Runtime} from '../executor/src/runtime.mjs';
import {originalTaskMediaConfig} from '../executor/src/original-task-media-config.mjs';
import {materializeTaskMedia} from '../executor/src/task-media.mjs';
import {profiles,plain} from '../executor/src/shared.mjs';

for(const backend of ['d1','neon'])for(const scenario of ['available','catalogue-error'])test('authenticated '+backend+' '+scenario+' registration freezes original cloud media fallback, ignores caller substitutions and restores original fields from an empty native store',async()=>{
 const home=await mkdtemp(join(tmpdir(),'el-original-default-media-')),previousFetch=globalThis.fetch,stores=[],objects=new Map(),assets=[],bytes=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAALklEQVR4AeyTsQ0AAAjCCC/5kz95rcYbGFggYWVoKKtnlRJiMgCEQRi8Rv4fHAAAAP//8jNqvAAAAAZJREFUAwA59iMxZX+kfAAAAABJRU5ErkJggg==','base64'),sha256=createHash('sha256').update(bytes).digest('hex'),profile={id:'JevPlay',name:'JevPlay',fields:{Name:'JevPlay',Url:'https://jevplay.com',LOGO:'https://product.fixture.invalid/logo.png','Screenshot 1':'https://product.fixture.invalid/example-output.png'}},documents={siteProfiles:{JevPlay:profile,other:{id:'other',name:'Other product'}},submissionRecords:{protected:{status:'success',evidence:'Keep original receipt'}},siteAnnotations:{protected:{library:{favorite:true,groups:['original']}}},sheetTableData:{entries:[{link:'https://directory.fixture.invalid/form'}]},cfgPingIndex:false};let db,sqlite,request,lostRunReply=false;
 const bucket={head:async key=>objects.has(key)?objects.get(key):null,get:async key=>{const object=objects.get(key);return object?{...object,arrayBuffer:async()=>object.bytes.slice().buffer}:null;},put:async(key,value,metadata)=>objects.set(key,{key,bytes:new Uint8Array(value),...metadata}),list:async({prefix,cursor})=>{const rows=[...objects.values()].filter(object=>object.key.startsWith(prefix)).sort((a,b)=>a.key.localeCompare(b.key));return{objects:cursor?rows.slice(2):rows.slice(0,2),truncated:!cursor&&rows.length>2,cursor:!cursor&&rows.length>2?'second-page':undefined};}};
 if(scenario==='catalogue-error')bucket.list=async()=>{throw Error('Fixture original catalogue unavailable');};
 const add=async(id,owner,kind,index,name)=>{const key='workspaces/default/media/'+id;await bucket.put(key,bytes,{httpMetadata:{contentType:'image/png'},customMetadata:{profileId:owner,kind:kind==='screenshot'?'screenshot'+index:kind,sha256,fileName:name}});assets.push({asset_id:id,profile_id:owner,media_kind:kind,media_index:index,file_name:name,object_key:key});if(db)await db.query("insert into externallink_media_assets(workspace_id,asset_id,profile_id,media_kind,media_index,object_key,file_name,content_type,byte_length,sha256) values('default',$1,$2,$3,$4,$5,$6,'image/png',$7,$8)",[id,owner,kind,index,key,name,bytes.length,sha256]);};
 try{
  if(backend==='d1'){const fixture=aiCloudFixture();sqlite=fixture.sqlite;fixture.env.MEDIA_BUCKET=bucket;fixture.ledger.bucket=bucket;for(const [key,value]of Object.entries(documents))await fixture.ledger.putDocument(key,value,0);request=value=>d1Executor(value,fixture.env,'default',async()=>{throw Error('No model calls');});}
  else{db=new PGlite();await db.exec(await readFile(new URL('../cloud/worker/schema.sql',import.meta.url),'utf8'));const sql=(strings,...params)=>{const query=strings.reduce((value,part,index)=>value+part+(index<params.length?'$'+(index+1):''),'');return{query,params,then:(resolve,reject)=>(scenario==='catalogue-error'&&query.includes('select asset_id,profile_id,media_kind,media_index,content_type')?Promise.reject(Error('Fixture original catalogue unavailable')):db.query(query,params).then(value=>value.rows)).then(resolve,reject)};};sql.transaction=queries=>db.transaction(async tx=>{const rows=[];for(const query of queries)rows.push((await tx.query(query.query,query.params)).rows);return rows;});await sql`insert into externallink_workspaces(workspace_id) values('default')`;for(const [key,value]of Object.entries(documents))await sql`insert into externallink_workspace_documents(workspace_id,document_key,data) values('default',${key},${JSON.stringify(value)}::jsonb)`;const helpers={recordEvent:async()=>{},listSnapshot:async()=>{const rows=await sql`select document_key,data,revision from externallink_workspace_documents where workspace_id='default'`;return{documents:Object.fromEntries(rows.map(row=>[row.document_key,row.data])),revisions:Object.fromEntries(rows.map(row=>[row.document_key,Number(row.revision)]))};}};request=value=>executorApi(value,{APP_ACCESS_TOKEN:'fixture-admin',MEDIA_BUCKET:bucket},sql,'default',helpers);}
  await add('01-own-logo','JevPlay','logo',null,'01-own-logo.png');await add('02-own-screen2','JevPlay','screenshot',2,'02-own-screen2.png');await add('03-own-screen1','JevPlay','screenshot',1,'03-own-screen1.png');await add('00-other-logo','other','logo',null,'00-other-logo.png');
  globalThis.fetch=async(url,options)=>{const value=new Request(url,options);assert.equal(new URL(value.url).hostname,'cloud.fixture.invalid');const result=await request(value);if(value.method==='POST'&&new URL(value.url).pathname.endsWith('/runs')&&result.ok&&!lostRunReply){lostRunReply=true;return Response.json({ok:false,error:'Fixture lost durable registration reply'},{status:503});}return result;};
  const enrollment=await request(new Request('https://cloud.fixture.invalid/'+(backend==='d1'?'v2':'v1')+'/executor/devices?workspace=default',{method:'POST',headers:{Authorization:'Bearer fixture-admin'},body:'{}'}));assert.equal(enrollment.status,200);const device=await enrollment.json(),pair={endpoint:'https://cloud.fixture.invalid',workspaceId:'default',deviceId:device.deviceId,deviceToken:device.deviceToken,storageBackend:backend},make=()=>{const store=new Store(':memory:');stores.push(store);store.set('pair',pair);store.set('paused',true);const runtime=new Runtime(store,home);runtime.tick=()=>{throw Error('Cloud restore must stay paused');};return runtime;},runtime=make(),before=await runtime.cloud.request('snapshot'),run={id:'original-default-media-run',profileId:'JevPlay',profileRevision:before.revisions.siteProfiles,authorization:'fill_only',originalMediaDefaults:{logo:'cloud-media://00-other-logo'},tasks:[{id:'original-default-media-task',url:'https://directory.fixture.invalid/form',destinationKey:'directory.fixture.invalid/form'}]};
  await assert.rejects(runtime.cloud.request('runs',{run}),/lost durable/);const original=(await runtime.cloud.request('runs')).runs[0];assert.deepEqual(original.profile,profile);assert.deepEqual(original.originalMediaDefaults,scenario==='catalogue-error'?{}:{logo:'cloud-media://01-own-logo',screenshots:['cloud-media://03-own-screen1','cloud-media://02-own-screen2']});assert.equal(original.mediaManifest.length,scenario==='catalogue-error'?0:3);if(scenario==='catalogue-error')assert.match(original.originalMediaLookupWarning,/保留原资料图片/);assert.ok(original.mediaManifest.every(asset=>asset.sha256===sha256));
  await add('00-new-own-logo','JevPlay','logo',null,'00-new-own-logo.png');const restored=make();await restored.restoreCloud();assert.equal(restored.store.values('task:').length,1);const task=restored.store.get('task:original-default-media-task');const restoredRun=restored.store.get('run:'+task.runId);assert.deepEqual(restoredRun,original);const config=originalTaskMediaConfig(restored,task,plain(profiles.buildAgentConfigFromProfile(restoredRun.profile)));if(scenario==='catalogue-error'){assert.equal(config.logoUrl,profile.fields.LOGO);assert.deepEqual(config.screenshots,[profile.fields['Screenshot 1']]);const after=await restored.cloud.request('snapshot');for(const key of Object.keys(documents)){assert.deepEqual(after.documents[key],before.documents[key]);assert.equal(after.revisions[key],before.revisions[key]);}assert.equal(task.attemptBoundary,undefined);assert.equal(task.receipt,undefined);assert.equal(restored.store.get('paused'),true);return;}assert.equal(config.logoUrl,'cloud-media://01-own-logo');assert.equal(config.projectFields.LOGO,profile.fields.LOGO);
  await restored.lease(task);restored.update(task,{profileSnapshot:profile,controller:'executor'},'fixture_original_profile');for(const kind of ['logo','screenshot1','screenshot2']){const file=await materializeTaskMedia(restored,task,config,kind);assert.deepEqual(await readFile(file),bytes);assert.equal(task.usedMedia.find(item=>item.kind===kind).sha256,sha256);}await restored.synchronize();
  await assert.rejects(restored.bridge(task,{action:'fetchCloudSubmissionMedia',ref:'cloud-media://00-other-logo'}));await assert.rejects(restored.bridge(task,{action:'fetchCloudSubmissionMedia',ref:'cloud-media://00-new-own-logo'}));const after=await restored.cloud.request('snapshot');for(const key of Object.keys(documents)){assert.deepEqual(after.documents[key],before.documents[key]);assert.equal(after.revisions[key],before.revisions[key]);}assert.equal(task.attemptBoundary,undefined);assert.equal(task.receipt,undefined);assert.equal(restored.store.get('paused'),true);
 }finally{globalThis.fetch=previousFetch;for(const store of stores)store.close();sqlite?.close();await db?.close();assert.ok(resolve(home).startsWith(resolve(tmpdir())+sep)&&home.includes('el-original-default-media-'));await rm(home,{recursive:true,force:true});}
});
