import test from 'node:test';import assert from 'node:assert/strict';
import{mkdtemp,rm}from'node:fs/promises';import{tmpdir}from'node:os';import{join,resolve,sep}from'node:path';
import{Store}from'../executor/src/store.mjs';import{startDomainAge}from'../executor/src/domain-age.mjs';
import{applicationMutation,applicationMutationSatisfied}from'../core/application-mutation.mjs';
import{resolveApplicationConflict}from'../executor/src/application-mutations.mjs';
const week=7*24*60*60*1000;
async function fixture(cache={}){
 const home=await mkdtemp(join(tmpdir(),'el-domain-cache-')),file=join(home,'outbox.sqlite');let store=new Store(file),lost=false;
 store.set('pair',{endpoint:'https://cloud.example',workspaceId:'original'});store.set('paused',true);store.set('acceptanceBatch',{status:'paused',cursor:13,count:30});
 const snapshot={documents:{siteProfiles:{p:{id:'p',name:'Original',fields:{Name:'Original'}}},submissionRecords:{proof:{status:'success',taskId:'original-task',evidence:'Original receipt'}},domainMetricsCache:cache},revisions:{domainMetricsCache:1,siteProfiles:1}},queries=[],writes=[];
 const runtime={store,status:()=>({tasks:[],paused:true,busy:false,pendingEvents:0}),cloud:{async request(route,input){if(route==='snapshot')return structuredClone(snapshot);if(route==='ai/domain-metrics'){queries.push([...input.domains]);await runtime.onQuery?.();return{ok:true,results:input.domains.map(domain=>({domain,status:'unknown',ageMonths:null,ageDays:null,message:'Unavailable'}))};}if(route==='library'){const change=applicationMutation(snapshot.documents,input.operation);assert.equal(input.revision,snapshot.revisions[change.key]);snapshot.documents[change.key]=change.data;snapshot.revisions[change.key]++;writes.push(input.operation);if(lost){lost=false;throw Error('reply lost after commit');}return{ok:true};}throw Error('Unexpected '+route);}}};
 return{runtime,snapshot,queries,writes,loseWrite(){lost=true;},async reopen(){store.close();store=new Store(file);runtime.store=store;},async close(){runtime.store.close();assert.ok(resolve(home).startsWith(resolve(tmpdir())+sep)&&home.includes('el-domain-cache-'));await rm(home,{recursive:true,force:true});}};
}
async function finish(f,input){const result=await startDomainAge(f.runtime,input);await f.runtime.domainAgeJob;return f.runtime.store.get('domainAgeJob:'+result.job.id);}
test('seven-day original caches include unknowns and migrated checkedAt records; only stale domains are queried',async()=>{
 const now=Date.now(),cache={'fresh.example':{domain:'fresh.example',status:'ok',ageMonths:12,fetchedAt:now-1000},'unknown.example':{domain:'unknown.example',status:'unknown',ageMonths:null,fetchedAt:now-2000},'expired.example':{domain:'expired.example',status:'ok',ageMonths:12,fetchedAt:now-week},'new-cache.example':{domain:'new-cache.example',status:'ok',ageMonths:20,checkedAt:new Date(now-2000).toISOString()}};
 const f=await fixture(cache);try{const job=await finish(f,{urls:Object.keys(cache).map(d=>'https://www.'+d+'/page')});assert.deepEqual(f.queries,[['expired.example']]);assert.equal(job.cursor,4);assert.equal(job.cachedCount,3);assert.equal(job.lookedUp,1);assert.equal(job.knownCount,2);assert.equal(job.results['unknown.example'].ageMonths,null);assert.equal(f.snapshot.documents.domainMetricsCache['expired.example'].status,'unknown');assert.equal(typeof f.snapshot.documents.domainMetricsCache['expired.example'].fetchedAt,'number');assert.equal(f.runtime.store.get('acceptanceBatch').cursor,13);assert.equal(f.runtime.store.values('task:').length,0);}finally{await f.close();}
});
test('original raw domain normalization deduplicates and forced refresh bypasses the cache without changing its frozen scope',async()=>{
 const f=await fixture({'one.example':{domain:'one.example',status:'ok',ageMonths:12,fetchedAt:Date.now()}});try{const job=await finish(f,{domains:['WWW.ONE.EXAMPLE','https://one.example/a','two.example'],refresh:true});assert.deepEqual(f.queries,[['one.example','two.example']]);assert.equal(job.refresh,true);assert.equal(job.cachedCount,0);assert.equal(job.lookedUp,2);assert.equal(job.knownCount,0);await finish(f,{jobId:job.id,urls:['https://replacement.example'],refresh:false});assert.deepEqual(f.queries,[['one.example','two.example']]);assert.deepEqual(f.runtime.store.get('domainAgeJob:'+job.id).domains,['one.example','two.example']);}finally{await f.close();}
});
test('interleaved cache hits still batch all missing domains by twenty as in the original plugin',async()=>{
 const domains=Array.from({length:60},(_,i)=>'site'+i+'.example'),cache=Object.fromEntries(domains.filter((_,i)=>i%2===0).map(domain=>[domain,{domain,status:'ok',ageMonths:3,fetchedAt:Date.now()}])),f=await fixture(cache);try{const job=await finish(f,{urls:domains.map(d=>'https://'+d)});assert.deepEqual(f.queries.map(batch=>batch.length),[20,10]);assert.deepEqual(f.queries.flat(),domains.filter((_,i)=>i%2===1));assert.equal(job.cachedCount,30);assert.equal(job.lookedUp,30);assert.equal(job.cursor,60);assert.equal(job.knownCount,30);}finally{await f.close();}
});
test('a lost cache-write response and SQLite restart finish the original batch and IDs without querying the same domains again',async()=>{
 const f=await fixture();try{f.loseWrite();let job=await finish(f,{urls:Array.from({length:25},(_,i)=>'https://site'+i+'.example')});assert.equal(job.status,'paused');assert.equal(job.cursor,0);assert.ok(job.pendingResult);const id=job.id,plan=job.pendingResult.planId,operationIds=f.runtime.store.get('applicationPlan:'+plan).items.map(i=>i.id);assert.equal(f.queries.length,1);await f.reopen();job=await finish(f,{jobId:id,refresh:true,urls:['https://replacement.example']});assert.equal(job.status,'completed');assert.equal(job.id,id);assert.equal(job.cursor,25);assert.equal(job.lookedUp,25);assert.equal(job.cachedCount,0);assert.deepEqual(f.queries.map(q=>q.length),[20,5]);assert.equal(f.writes.length,2);assert.equal(new Set(f.writes.map(w=>w.id)).size,2);assert.deepEqual(f.runtime.store.get('applicationPlan:'+plan).items.map(i=>i.id),operationIds);assert.equal(f.runtime.store.get('paused'),true);assert.equal(f.snapshot.documents.submissionRecords.proof.evidence,'Original receipt');}finally{await f.close();}
});
test('original 5000-record pruning retains newest results and unknown state without reporting an unpruned mutation as confirmed',()=>{
 const cache=Object.fromEntries(Array.from({length:5001},(_,i)=>['site'+i+'.example',{domain:'site'+i+'.example',status:'ok',ageMonths:1,fetchedAt:i}])),op={id:'lookup',at:'2026-10-05T00:00:00Z',type:'domain_metrics',results:[{domain:'new.example',status:'unknown',ageMonths:null,ageDays:null,fetchedAt:Date.now()}]};
 const result=applicationMutation({domainMetricsCache:cache},op);assert.equal(Object.keys(result.data).length,5000);assert.equal(result.data['site0.example'],undefined);assert.equal(result.data['site1.example'],undefined);assert.equal(result.data['new.example'].ageMonths,null);assert.equal(applicationMutationSatisfied({domainMetricsCache:result.data},op),true);assert.equal(applicationMutationSatisfied({domainMetricsCache:{...cache,'new.example':op.results[0]}},op),false);
});
test('all-cached queries avoid provider calls and prune an oversized original cache once',async()=>{
 const now=Date.now(),cache=Object.fromEntries(Array.from({length:5001},(_,i)=>['site'+i+'.example',{domain:'site'+i+'.example',status:'unknown',ageMonths:null,fetchedAt:now-i}])),f=await fixture(cache);try{const job=await finish(f,{urls:['https://site0.example']});assert.equal(job.status,'completed');assert.equal(job.cachedCount,1);assert.equal(job.lookedUp,0);assert.equal(f.queries.length,0);assert.equal(f.writes.length,1);assert.equal(Object.keys(f.snapshot.documents.domainMetricsCache).length,5000);assert.ok(f.snapshot.documents.domainMetricsCache['site0.example']);assert.equal(f.snapshot.documents.domainMetricsCache['site5000.example'],undefined);}finally{await f.close();}
});
test('the cache limit does not truncate the original query range or its results',async()=>{
 const cache=Object.fromEntries(Array.from({length:5001},(_,i)=>['site'+i+'.example',{domain:'site'+i+'.example',status:'unknown',ageMonths:null,fetchedAt:Date.now()}])),f=await fixture(cache);try{const job=await finish(f,{urls:Object.keys(cache).map(domain=>'https://'+domain)});assert.equal(job.status,'completed');assert.equal(job.domains.length,5001);assert.equal(job.cursor,5001);assert.equal(job.cachedCount,5001);assert.equal(Object.keys(job.results).length,5001);assert.equal(Object.keys(f.snapshot.documents.domainMetricsCache).length,5000);assert.equal(f.queries.length,0);}finally{await f.close();}
});
test('keeping a conflicting cloud cache records excluded domains and retains the original receipt and query IDs',async()=>{
 const f=await fixture();try{f.loseWrite();let job=await finish(f,{urls:['https://one.example']});assert.equal(job.lookedUp,1);const originalId=job.id,planId=job.pendingResult.planId;f.snapshot.documents.domainMetricsCache={'one.example':{domain:'one.example',status:'ok',ageMonths:24,fetchedAt:Date.now()+1000}};f.snapshot.revisions.domainMetricsCache++;job=await finish(f,{jobId:originalId});assert.equal(job.status,'paused');const item=f.runtime.store.get('applicationPlan:'+planId).items[0];assert.equal(f.runtime.store.get('appMutation:'+item.id).status,'conflict');await resolveApplicationConflict(f.runtime,{id:item.id,choice:'cloud',revision:f.snapshot.revisions.domainMetricsCache});job=await finish(f,{jobId:originalId});assert.equal(job.status,'completed_with_exclusions');assert.deepEqual(job.excludedDomains,['one.example']);assert.equal(job.lookedUp,1);assert.equal(f.queries.length,1);assert.equal(f.writes.length,1);assert.equal(f.snapshot.documents.domainMetricsCache['one.example'].ageMonths,24);assert.equal(f.snapshot.documents.submissionRecords.proof.evidence,'Original receipt');}finally{await f.close();}
});
test('a workspace change after querying preserves the original result and forbids writing it under the new workspace',async()=>{
 const f=await fixture();try{f.runtime.onQuery=async()=>f.runtime.store.set('pair',{endpoint:'https://cloud.example',workspaceId:'other'});const job=await finish(f,{urls:['https://original.example']});assert.equal(job.status,'paused');assert.match(job.error,/工作区已切换/);assert.ok(job.pendingResult);assert.equal(job.pendingResult.results[0].domain,'original.example');assert.equal(f.writes.length,0);f.runtime.onQuery=null;f.runtime.store.set('pair',{endpoint:'https://cloud.example',workspaceId:'original'});const resumed=await finish(f,{jobId:job.id});assert.equal(resumed.status,'completed');assert.equal(f.queries.length,1);assert.equal(f.writes.length,1);}finally{await f.close();}
});
test('a lost reply confirms the frozen pruning result even when newer original timestamps prune the fetched domain',async()=>{
 const now=Date.now(),cache=Object.fromEntries(Array.from({length:5001},(_,i)=>['future'+i+'.example',{domain:'future'+i+'.example',status:'ok',ageMonths:8,fetchedAt:now+86400000+i}])),f=await fixture(cache);
 try{f.loseWrite();let job=await finish(f,{urls:['https://future0.example'],refresh:true});assert.equal(job.status,'paused');assert.equal(job.lookedUp,1);assert.equal(f.snapshot.documents.domainMetricsCache['future0.example'],undefined);const id=job.id,planId=job.pendingResult.planId;await f.reopen();job=await finish(f,{jobId:id});assert.equal(job.status,'completed');assert.equal(job.id,id);assert.equal(job.cursor,1);assert.equal(f.queries.length,1);assert.equal(f.writes.length,1);assert.equal(f.runtime.store.get('applicationPlan:'+planId).status,'completed');const expected={...cache};delete expected['future0.example'];assert.deepEqual(f.snapshot.documents.domainMetricsCache,expected);assert.equal(f.snapshot.documents.submissionRecords.proof.evidence,'Original receipt');}
 finally{await f.close();}
});
