import test from 'node:test';import assert from 'node:assert/strict';import '../core/profiles.js';import {applicationMutation} from '../core/application-mutation.mjs';
const P=globalThis.ExtLinkProfiles,profiles=()=>({p:{id:'p',name:'Original',url:'https://original.example',fields:{Name:'Original',Url:'https://original.example'},mediaVersions:[]},q:{id:'q',name:'Other'}}),asList=map=>Object.values(map);
test('an editor adopts only its own uploaded kind and preserves unrelated profile content and append-only versions',()=>{
 const before=profiles();for(const kind of ['logo','featured','screenshot1','screenshot2','screenshot3','screenshot4']){const media=kind==='logo'?{logo:'cloud-media://new'}:kind==='featured'?{featured:'cloud-media://new'}:{screenshots:Array.from({length:4},(_,i)=>i===Number(kind.slice(10))-1?'cloud-media://new':'')},fields=kind==='logo'?{'Cloud LOGO':'cloud-media://new'}:kind==='featured'?{'Cloud Featured image':'cloud-media://new'}:{['Screenshot '+kind.slice(10)]:'cloud-media://new'},after=applicationMutation({siteProfiles:before},{type:'profile',profileId:'p',at:'now',profile:{id:'p',fields,media,mediaDisabled:{[kind]:false},mediaVersions:[{assetId:'new',kind,ref:'cloud-media://new'}]}}).data;assert.ok(P.profileEditorMediaCompatible(asList(before),asList(after),'p',kind));}
});
test('an editor never adopts simultaneous product text, other product content, or another kind of media as its own refresh',()=>{
 const before=profiles(),base=applicationMutation({siteProfiles:before},{type:'profile',profileId:'p',at:'now',profile:{id:'p',fields:{'Cloud LOGO':'cloud-media://new'},media:{logo:'cloud-media://new'},mediaVersions:[{assetId:'new',kind:'logo'}]}}).data;for(const mutate of [after=>after.p.fields.Name='Concurrent name',after=>after.q.name='Concurrent other',after=>after.p.media.featured='cloud-media://concurrent',after=>after.p.mediaVersions.push({assetId:'other-kind',kind:'featured'})]){const after=structuredClone(base);mutate(after);assert.equal(P.profileEditorMediaCompatible(asList(before),asList(after),'p','logo'),false);}
});
test('disable and restore can advance an editor while changed old version history or missing identity cannot',()=>{
 const before=profiles();before.p.mediaVersions=[{assetId:'old',kind:'logo',ref:'cloud-media://old'}];for(const action of ['disable','restore']){const after=structuredClone(applicationMutation({siteProfiles:before},{type:'profile_media',profileId:'p',kind:'logo',action,assetId:'old',at:'now'}).data);assert.ok(P.profileEditorMediaCompatible(asList(before),asList(after),'p','logo'));after.p.mediaVersions[0].ref='cloud-media://changed-old';assert.equal(P.profileEditorMediaCompatible(asList(before),asList(after),'p','logo'),false);}assert.equal(P.profileEditorMediaCompatible(asList(before),[],'p','logo'),false);
});
test('fourth screenshot refresh keeps the three preceding slots and does not admit another slot change',()=>{
 const before=profiles();before.p.media={screenshots:['cloud-media://one','','cloud-media://three','']};const after=applicationMutation({siteProfiles:before},{type:'profile',profileId:'p',at:'now',profile:{id:'p',fields:{'Screenshot 4':'cloud-media://four'},media:{screenshots:['cloud-media://one','','cloud-media://three','cloud-media://four']},mediaVersions:[{assetId:'four',kind:'screenshot4'}]}}).data;assert.ok(P.profileEditorMediaCompatible(asList(before),asList(after),'p','screenshot4'));after.p.media.screenshots[0]='cloud-media://different';assert.equal(P.profileEditorMediaCompatible(asList(before),asList(after),'p','screenshot4'),false);
});
