import test from 'node:test';import assert from 'node:assert/strict';import {Runtime} from '../executor/src/runtime.mjs';import {readFileSync} from 'node:fs';import vm from 'node:vm';
function fixture(){const task={id:'task',runId:'run',profileId:'p',profileRevision:1,targetId:'owned-target',browserInstance:'owned-browser',version:1,controller:'executor',status:'filling'},rows=new Map([['task:task',structuredClone(task)],['paused',true],['workbenchBatch:original',{cursor:13,usedTasks:13,usedAiActions:4}]]),events=[],runtime={store:{get:key=>structuredClone(rows.get(key))},update(t,patch,type){Object.assign(t,patch);rows.set('task:'+t.id,structuredClone(t));events.push(type);}},message={action:'mediaUploadStatus',status:'success',pageUrl:'https://directory.example/form',executorFrameUrl:'https://directory.example/form',executorDocumentId:4,name:'original.png',source:'original_frozen_backup',sourceSha256:'a'.repeat(64),bytes:70,mime:'image/png'};return{task,rows,events,runtime,message};}
test('original image feedback retains Chinese source and deduplicates success and failure without changing attempts or budgets',async()=>{
 const f=fixture(),before=structuredClone(f.rows.get('workbenchBatch:original'));assert.equal((await Runtime.prototype.bridge.call(f.runtime,f.task,f.message)).ok,true);assert.equal((await Runtime.prototype.bridge.call(f.runtime,f.task,f.message)).duplicate,true);assert.deepEqual(f.events,['media_upload_success']);assert.equal(f.task.mediaUploadState.uploaded[0].source,'原任务冻结备份');assert.equal(f.task.mediaUploadState.uploaded[0].sourceSha256,'a'.repeat(64));const failed={...f.message,status:'failed',name:'Screenshot 1',reason:'未找到原图片'};await Runtime.prototype.bridge.call(f.runtime,f.task,failed);await Runtime.prototype.bridge.call(f.runtime,f.task,failed);assert.equal(f.task.mediaUploadState.skipped.length,1);assert.equal(f.task.mediaUploadState.status,'warn');await Runtime.prototype.bridge.call(f.runtime,f.task,f.message);assert.equal(f.task.mediaUploadState.status,'ok');assert.equal(f.task.mediaUploadState.uploaded.length,1);assert.deepEqual(f.rows.get('workbenchBatch:original'),before);assert.equal(f.rows.get('paused'),true);assert.equal(f.task.attemptBoundary,undefined);assert.equal(f.task.status,'filling');
});
test('stale browser product controller frame or task version cannot record image status',async()=>{
 for(const patch of [{targetId:'other'},{browserInstance:'other'},{profileId:'q'},{profileRevision:2},{runId:'other'},{version:2},{controller:'supervisor'},{controller:'ai'}]){const f=fixture();f.rows.set('task:task',{...f.rows.get('task:task'),...patch});assert.equal((await Runtime.prototype.bridge.call(f.runtime,f.task,f.message)).ok,false);assert.equal(f.events.length,0);}
 for(const patch of [{pageUrl:'https://old.example/form'},{executorDocumentId:'4'},{status:'unknown'}]){const f=fixture();assert.equal((await Runtime.prototype.bridge.call(f.runtime,f.task,{...f.message,...patch})).ok,false);assert.equal(f.events.length,0);}
});
test('mixed upload sources retain an explicit Chinese source and failed preview reason in the original task',async()=>{
 const f=fixture(),before=structuredClone(f.rows.get('workbenchBatch:original'));const result=await Runtime.prototype.bridge.call(f.runtime,f.task,{...f.message,status:'failed',fieldLabel:'Gallery',name:'gallery',source:'mixed',reason:'未检测到本站图片上传预览'});assert.equal(result.ok,true);assert.equal(f.task.mediaUploadState.skipped[0].source,'混合图片来源');assert.equal(f.task.mediaUploadState.skipped[0].label,'Gallery');assert.equal(f.task.mediaUploadState.skipped[0].reason,'未检测到本站图片上传预览');assert.equal(f.task.attemptBoundary,undefined);assert.deepEqual(f.rows.get('workbenchBatch:original'),before);
});
test('actual task details render successful and failed uploads with clear Chinese sources and reasons',()=>{
 const source=readFileSync(new URL('../executor/web/application.js',import.meta.url),'utf8'),start=source.indexOf('function appendMediaUploadStatus('),end=source.indexOf('const consumedQuickOpen',start),nodes=[],sandbox={el:(tag,options)=>({tag,...options})};vm.createContext(sandbox);vm.runInContext(source.slice(start,end),sandbox);sandbox.appendMediaUploadStatus({append(...items){nodes.push(...items);}},{mediaUploadState:{uploaded:[{label:'产品标志',name:'logo.png',source:'original_frozen_backup',sourceSha256:'a'.repeat(64)}],skipped:[{label:'截图 2',source:'remote',reason:'原图片无法读取'}]}});const text=nodes.map(node=>node.text).join('\n');assert.match(text,/图片上传状态/);assert.match(text,/1 个字段已上传 · 1 个字段未上传/);assert.match(text,/产品标志：已上传 · 来源：原任务冻结备份/);assert.match(text,/截图 2：未上传 · 来源：远程图片 · 原因：原图片无法读取/);assert.ok(!text.includes('original_frozen_backup'));assert.match(text,/原件校验已通过/);
});
