import test from 'node:test';import assert from 'node:assert/strict';
import {pendingSubmissionQueue} from '../core/submission-queue.mjs';
import {libraryMutation} from '../core/library-mutation.mjs';
import {submissionQueue,removeFromSubmissionQueue} from '../executor/src/submission-queue.mjs';
import {originalNavigationState} from './helpers/original-library-catalog.mjs';
import {Store} from '../executor/src/store.mjs';import {workbenchScope} from '../executor/src/workbench-sync.mjs';
const snapshot=()=>({documents:{siteProfiles:{p:{id:'p',name:'Product P',fields:{Url:'https://p.example'}},q:{id:'q',name:'Product Q',fields:{Url:'https://q.example'}},old:{id:'old',name:'Archived',archived:true}},selectedSiteIds:['p','q'],sheetTableData:{entries:[{link:'https://first.example/form',metrics:{dr:90,da:80}},{link:'https://second.example/form',metrics:{dr:10,da:10}},{link:'https://blocked.example/form',metrics:{dr:90,da:80}}]},siteAnnotations:{'blocked.example/form':{status:'paid'}},submissionRecords:{'first.example::p':{profileId:'p',destinationUrl:'https://first.example/old',status:'success',confirmedBy:'agent',evidence:'Original concrete directory receipt'}},deletedSubmissionKeys:[]},revisions:{siteProfiles:1,siteAnnotations:1,deletedSubmissionKeys:1}});
test('pending queue groups products by site, sorts original quality, and applies receipt, archive and removal exclusions',()=>{
 const saved=snapshot(),result=pendingSubmissionQueue(saved);assert.deepEqual(result.selectedProfileIds,['p','q']);assert.equal(result.groups.length,2);assert.equal(result.groups[0].domain,'first.example');assert.deepEqual(result.groups[0].jobs.map(j=>j.profileId),['q']);assert.equal(result.groups[1].jobs.length,2);assert.equal(result.meta.total,3);assert.throws(()=>pendingSubmissionQueue(saved,{selectedSiteIds:['old']}),/在用/);
 saved.documents.deletedSubmissionKeys=['second.example/form'];assert.equal(pendingSubmissionQueue(saved).groups.length,1);saved.documents.targetFilters={minDr:95};assert.equal(pendingSubmissionQueue(saved).groups.length,0);
});
test('cursor follows the original complete queue after insertion and wraps without losing source identity',async()=>{
 const store=new Store(':memory:');try{let saved=snapshot();store.set('pair',{endpoint:'https://cloud.example',workspaceId:'one'});const runtime={store,cloud:{request:async()=>structuredClone(saved)}};
  let cursor={};for(const [input,advance]of [[{},false],[{delta:1,open:false},true]]){const expected=await originalNavigationState(saved,{input,cursor,advance}),actual=await submissionQueue(runtime,input,advance);assert.equal(actual.task.key,expected.cursor.key);assert.equal(actual.index,expected.result.index);cursor=expected.cursor;}
  const originalKey=cursor.key;saved.documents.sheetTableData.entries.unshift({link:'https://new.example/form',metrics:{dr:100,da:100}});
  let expected=await originalNavigationState(saved,{cursor}),result=await submissionQueue(runtime);assert.equal(result.task.key,originalKey);assert.equal(result.index,expected.result.index);assert.equal(result.total,expected.result.total);
  const last=expected.result.tasks.at(-1);store.set('submissionQueue',{...store.get('submissionQueue'),key:last.key,index:result.total-1});result=await submissionQueue(runtime,{delta:1,currentKey:last.key,open:false},true);assert.equal(result.index,0);result=await submissionQueue(runtime,{delta:-1,open:false},true);assert.equal(result.index,result.total-1);assert.equal(result.task.key,last.key);
  await assert.rejects(submissionQueue(runtime,{delta:3},true),/上一站/);assert.equal(runtime.context,undefined);store.set('pair',{endpoint:'https://cloud.example',workspaceId:'two'});result=await submissionQueue(runtime);assert.equal(result.index,0);
 }finally{store.close();}
});
test('removal preserves knowledge, preferences and receipts while updating both aliases and deletion key with one durable plan',async()=>{
 const store=new Store(':memory:');try{let saved=snapshot();const original={note:'Keep note',formKnowledge:{name:'#name'},library:{favorite:true,groups:['high_quality']},submittedProjects:['p']};saved.documents.siteAnnotations['second.example/form']=original;
  store.set('pair',{endpoint:'https://cloud.example',workspaceId:'one'});let writes=0,lostReply=true;const runtime={store,status:()=>({tasks:[],paused:true,busy:false,pendingEvents:0}),cloud:{async request(route,input){if(route==='snapshot')return structuredClone(saved);assert.ok(store.values('applicationPlan:').length);writes++;const change=libraryMutation(saved.documents,input.operation);saved.documents[change.key]=change.data;saved.revisions[change.key]++;if(lostReply){lostReply=false;throw Error('Reply lost');}return{ok:true};}}};
  const removed=await removeFromSubmissionQueue(runtime,{url:'https://second.example/form'});assert.ok(removed.remaining);const originalPlan=store.get('applicationPlan:'+removed.planId),ids=originalPlan.items.map(i=>i.id);assert.deepEqual(saved.documents.siteAnnotations['second.example/form'].formKnowledge,original.formKnowledge);assert.deepEqual(saved.documents.siteAnnotations['second.example'].library,original.library);assert.deepEqual(saved.documents.siteAnnotations['second.example'].submittedProjects,['p']);assert.equal(saved.documents.submissionRecords['first.example::p'].status,'success');
  const resumed=await removeFromSubmissionQueue(runtime,{planId:removed.planId});assert.equal(resumed.remaining,0);assert.equal(writes,2);assert.deepEqual(store.get('applicationPlan:'+removed.planId).items.map(i=>i.id),ids);assert.deepEqual(saved.documents.deletedSubmissionKeys,['second.example/form']);assert.equal(pendingSubmissionQueue(saved).groups.some(g=>g.domain==='second.example'),false);assert.equal(store.get('applicationSnapshot').scope,workbenchScope(store.get('pair')));
 }finally{store.close();}
});
