import test from 'node:test';import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';import {readFileSync} from 'node:fs';
import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join,resolve,sep} from 'node:path';import {createServer} from 'node:http';
import {Store} from '../executor/src/store.mjs';import {Cloud} from '../executor/src/cloud.mjs';import {D1Store} from '../cloud/worker/src/d1-store.mjs';import {d1Executor} from '../cloud/worker/src/d1-executor.mjs';import {enqueueLibraryMutation,enqueueProfileMutation} from '../executor/src/application-mutations.mjs';
import {localRecoverySources,previewLocalRecovery,recoverLocalDocuments} from '../executor/src/local-recovery.mjs';import {workbenchScope} from '../executor/src/workbench-sync.mjs';
import {backupKeys} from '../core/application-backup.mjs';
import {enqueueMediaUpload} from '../executor/src/media-uploads.mjs';
import {imageFormatFixtures} from '../executor/test/image-format-fixtures.mjs';
import {clearSiteAnnotation} from '../executor/src/library-reset.mjs';
import {removeFromSubmissionQueue} from '../executor/src/submission-queue.mjs';
test('original local documents recover through real HTTP, device authentication, D1 CAS and independent readback with a dropped write response',async()=>{
 const home=await mkdtemp(join(tmpdir(),'el-recovery-http-')),sql=new DatabaseSync(':memory:');let local,server;
 try{
 for(const file of ['0001_d1_storage.sql','0002_d1_executor.sql'])sql.exec(readFileSync(new URL('../cloud/worker/migrations/'+file,import.meta.url),'utf8'));
 const db={prepare(text){let args=[];return{bind(...values){args=values;return this;},first:async()=>sql.prepare(text).get(...args)||null,all:async()=>({results:sql.prepare(text).all(...args)}),run:async()=>{const q=sql.prepare(text);return q.columns().length?{results:q.all(...args),meta:{changes:0}}:{results:[],meta:{changes:q.run(...args).changes}};}};},async batch(statements){sql.exec('BEGIN');try{const values=[];for(const statement of statements)values.push(await statement.run());sql.exec('COMMIT');return values;}catch(error){sql.exec('ROLLBACK');throw error;}}};
 const objects=new Map(),bucket={head:async key=>objects.has(key)?{}:null,put:async(key,value,meta)=>{if(meta?.onlyIf?.etagDoesNotMatch==='*'&&objects.has(key))return null;objects.set(key,{bytes:new Uint8Array(value),meta});return{};},get:async key=>{const value=objects.get(key);return value?{arrayBuffer:async()=>value.bytes.slice().buffer,body:value.bytes,httpMetadata:value.meta?.httpMetadata,customMetadata:value.meta?.customMetadata,writeHttpMetadata(headers){for(const [key,data]of Object.entries(value.meta?.httpMetadata||{}))headers.set(key==='contentType'?'Content-Type':key,data);}}:null;}};
 const env={LEDGER_DB:db,MEDIA_BUCKET:bucket,APP_ACCESS_TOKEN:'fixture-admin'},remote=new D1Store(db,bucket,'default'),receipt={taskId:'original-task',profileId:'p',status:'success',evidence:'Original receipt'};
 for(const [key,value]of Object.entries({siteProfiles:{p:{id:'p',name:'Cloud P',fields:{Name:'Cloud P'}}},siteAnnotations:{},submissionRecords:{'protected.example::p':receipt}}))await remote.putDocument(key,value,0);
 let dropped=false;const writes=[];
 server=createServer(async(req,res)=>{let body='';for await(const bytes of req)body+=bytes;const url=new URL(req.url,'http://cloud.test'),input=body?JSON.parse(body):null,write=url.pathname.endsWith('/library');if(write)writes.push(input.operation.id);const response=await d1Executor(new Request(url,{method:req.method,headers:req.headers,body:req.method==='GET'?undefined:body}),env,'default',async()=>({}));const output=Buffer.from(await response.arrayBuffer());if(write&&!dropped&&response.ok){dropped=true;req.socket.destroy();return;}res.writeHead(response.status,Object.fromEntries(response.headers));res.end(output);});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 const endpoint='http://127.0.0.1:'+server.address().port,enrollment=await fetch(endpoint+'/v2/executor/devices',{method:'POST',headers:{Authorization:'Bearer fixture-admin','Content-Type':'application/json'},body:JSON.stringify({name:'isolated recovery'})});assert.equal(enrollment.status,200);const device=await enrollment.json(),pair={endpoint,workspaceId:'default',storageBackend:'d1',deviceToken:device.deviceToken};
 const backupRoot=join(home,'backups'),folder=join(backupRoot,'original-local');await mkdir(folder,{recursive:true});local=new Store(join(home,'outbox.sqlite'));local.set('pair',pair);local.set('paused',true);local.set('acceptanceBatch',{status:'paused',cursor:13,count:30});
 const documents={siteProfiles:{p:{id:'p',name:'Original P',logoDataUrl:imageFormatFixtures[0].dataUrl,logoUrl:'https://original-product.example/logo.png',fields:{Name:'Original P'},learnedFieldMappings:{name:'Name'},fieldNotes:{Name:'旧字段备注',Title:'保留标题备注'}}},siteAnnotations:{'target.example':{library:{favorite:true,groups:['high_quality']},formKnowledge:{name:'#name'}}},submissionRecords:{'protected.example::p':{status:'failed'},'old.example::p':{profileId:'p',status:'success',evidence:'Older receipt'}},cfgName:'Original contact',cfgEmail:'owner@example.com',cfgCommentTemplate:'Original comment',cfgPingIndex:false,autoFillOnVisit:false,urlList:'https://target.example/submit',activeSiteId:'p',selectedSiteIds:['p'],deletedSubmissionKeys:['removed.example'],sheetTableData:{entries:[{link:'https://target.example/submit',metrics:{dr:88}}]},domainBlacklist:['blocked.example'],targetFilters:{minDr:60},domainMetricsCache:{'target.example':{ageMonths:20}},linkMonitorResults:{},linkMonitorSchedule:{enabled:false,intervalHours:24},autoSubmitStandardWpComments:false,autoSubmitDirectoryListings:false,submissionSchemaVersion:2,timelineSchemaVersion:2,submissionTimeline:{'old.example::p':[{id:'original-event',destinationKey:'old.example',profileId:'p',occurredAt:'2026-09-30T00:00:00Z',type:'note',note:'Original history'}]}};assert.deepEqual(Object.keys(documents).sort(),[...backupKeys].sort());await writeFile(join(folder,'snapshot.json'),JSON.stringify({scope:workbenchScope(pair),documents}));
 const runtime={home,backupRoot,store:local,cloud:new Cloud(pair),status:()=>({tasks:[],paused:true,busy:false,pendingEvents:0})},listing=await localRecoverySources(runtime),preview=await previewLocalRecovery(runtime,{sourceId:listing.sources.find(s=>s.id).id}),input={id:preview.preview.id,confirmation:'恢复所选本机资料'};
 let result=await recoverLocalDocuments(runtime,input);assert.ok(result.remaining);assert.match(result.error,/云端连接失败/);const originalPlan=local.get('localRecoveryPlan:'+input.id).applicationPlanId,ids=local.get('applicationPlan:'+originalPlan).items.map(i=>i.id);
 local.close();local=new Store(join(home,'outbox.sqlite'));runtime.store=local;result=await recoverLocalDocuments(runtime,input);assert.equal(result.remaining,0);assert.deepEqual(local.get('applicationPlan:'+originalPlan).items.map(i=>i.id),ids);assert.equal(writes.length,new Set(writes).size);
 const proof=await runtime.cloud.request('snapshot');assert.deepEqual(proof.documents.submissionRecords['protected.example::p'],receipt);assert.equal(proof.documents.siteAnnotations['target.example'].library.favorite,true);assert.equal(proof.documents.siteProfiles.p.learnedFieldMappings.name,'Name');assert.equal(proof.documents.cfgName,'Original contact');assert.equal(local.get('acceptanceBatch').cursor,13);assert.equal(sql.prepare('SELECT count(*) n FROM executor_runs').get().n,0);assert.equal(sql.prepare('SELECT count(*) n FROM recovery_objects').get().n,writes.length*2);
 for(const key of backupKeys.filter(key=>!['submissionRecords','submissionTimeline'].includes(key)))assert.deepEqual(proof.documents[key],documents[key],key);assert.equal(proof.documents.submissionTimeline['old.example::p'][0].note,'Original history');assert.equal(local.get('applicationPlan:'+originalPlan).items.length,backupKeys.length);
 const setting={type:'settings',id:'original-wp-opt-in',at:'2026-10-05T11:00:00Z',key:'autoSubmitStandardWpComments',value:true};await runtime.cloud.request('library',{operation:setting,revision:proof.revisions[setting.key]});const enabled=await runtime.cloud.request('snapshot');assert.equal(enabled.documents.autoSubmitStandardWpComments,true);assert.equal(enabled.documents.autoSubmitDirectoryListings,false);await assert.rejects(runtime.cloud.request('library',{operation:{...setting,id:'invalid-wp-flag',value:'false'},revision:enabled.revisions[setting.key]}),/提交设置/);const afterRejected=await runtime.cloud.request('snapshot');assert.equal(afterRejected.revisions[setting.key],enabled.revisions[setting.key]);assert.equal(afterRejected.documents.autoSubmitStandardWpComments,true);assert.deepEqual(afterRejected.documents.submissionRecords['protected.example::p'],receipt);assert.equal(sql.prepare('SELECT count(*) n FROM executor_runs').get().n,0);assert.equal(local.get('paused'),true);
 // Device-authenticated cache mutation uses the same D1/R2 CAS and validators as production.
 const now=Date.now(),cache=Object.fromEntries(Array.from({length:5001},(_,i)=>['cached'+i+'.example',{domain:'cached'+i+'.example',status:'ok',ageMonths:12,fetchedAt:now-100000-i}]));
 const seeded=await remote.putDocument('domainMetricsCache',cache,afterRejected.revisions.domainMetricsCache);
 const metrics={id:'original-domain-query',at:new Date(now).toISOString(),type:'domain_metrics',results:[{domain:'queried.example',status:'unknown',ageMonths:null,ageDays:null,fetchedAt:now}]};
 await runtime.cloud.request('library',{operation:metrics,revision:seeded.revision});
 const domainProof=await runtime.cloud.request('snapshot');assert.equal(Object.keys(domainProof.documents.domainMetricsCache).length,5000);assert.equal(domainProof.documents.domainMetricsCache['queried.example'].fetchedAt,now);assert.equal(domainProof.documents.domainMetricsCache['queried.example'].ageMonths,null);assert.equal(domainProof.documents.domainMetricsCache['cached5000.example'],undefined);assert.equal(domainProof.documents.domainMetricsCache['cached4999.example'],undefined);
 await assert.rejects(runtime.cloud.request('library',{operation:{...metrics,id:'invalid-domain-time',results:[{...metrics.results[0],fetchedAt:'recent'}]},revision:domainProof.revisions.domainMetricsCache}),/域名查询结果/);
 const domainAfterRejected=await runtime.cloud.request('snapshot');assert.equal(domainAfterRejected.revisions.domainMetricsCache,domainProof.revisions.domainMetricsCache);assert.deepEqual(domainAfterRejected.documents.submissionRecords['protected.example::p'],receipt);assert.equal(sql.prepare('SELECT count(*) n FROM executor_runs').get().n,0);assert.equal(local.get('paused'),true);assert.equal(local.get('acceptanceBatch').cursor,13);
 assert.equal(domainAfterRejected.documents.cfgPingIndex,false);const notifyPreference={id:'original-indexnow-setting',at:new Date().toISOString(),type:'settings',key:'cfgPingIndex',value:true};await runtime.cloud.request('library',{operation:notifyPreference,revision:domainAfterRejected.revisions.cfgPingIndex});const notifyProof=await runtime.cloud.request('snapshot');assert.equal(notifyProof.documents.cfgPingIndex,true);await assert.rejects(runtime.cloud.request('library',{operation:{...notifyPreference,id:'invalid-indexnow-setting',value:'false'},revision:notifyProof.revisions.cfgPingIndex}),/搜索引擎通知设置/);const notifyAfterRejected=await runtime.cloud.request('snapshot');assert.deepEqual(notifyAfterRejected.revisions,notifyProof.revisions);assert.deepEqual(notifyAfterRejected.documents.submissionRecords['protected.example::p'],receipt);assert.equal(sql.prepare('SELECT count(*) n FROM executor_runs').get().n,0);
 assert.equal(notifyAfterRejected.documents.autoFillOnVisit,false);const visitPreference={id:'original-visit-setting',at:new Date().toISOString(),type:'settings',key:'autoFillOnVisit',value:true};await runtime.cloud.request('library',{operation:visitPreference,revision:notifyAfterRejected.revisions.autoFillOnVisit});const visitProof=await runtime.cloud.request('snapshot');assert.equal(visitProof.documents.autoFillOnVisit,true);await assert.rejects(runtime.cloud.request('library',{operation:{...visitPreference,id:'invalid-visit-setting',value:'true'},revision:visitProof.revisions.autoFillOnVisit}),/访问自动填写设置/);const visitAfterRejected=await runtime.cloud.request('snapshot');assert.deepEqual(visitAfterRejected.revisions,visitProof.revisions);assert.deepEqual(visitAfterRejected.documents.submissionRecords['protected.example::p'],receipt);assert.equal(sql.prepare('SELECT count(*) n FROM executor_runs').get().n,0);assert.equal(local.get('paused'),true);assert.equal(local.get('acceptanceBatch').cursor,13);
 const originalRules={id:'p',language:'zh',fields:{Name:'Edited original'},fieldNotes:{Name:'  新字段备注  ',Title:''},blogRules:{tone:'professional',preferredAnchor:'brand',maxLinksPerDraft:10}};await runtime.cloud.request('profile',{profileId:'p',profile:originalRules,revision:visitAfterRejected.revisions.siteProfiles});const profileProof=await runtime.cloud.request('snapshot');assert.equal(profileProof.documents.siteProfiles.p.language,'zh');assert.equal(profileProof.documents.siteProfiles.p.blogRules.maxLinksPerDraft,10);assert.equal(profileProof.documents.siteProfiles.p.fieldNotes.Name,'新字段备注');assert.equal(profileProof.documents.siteProfiles.p.fieldNotes.Title,'保留标题备注');assert.equal(profileProof.documents.siteProfiles.p.learnedFieldMappings.name,'Name');await assert.rejects(runtime.cloud.request('profile',{profileId:'p',profile:{...originalRules,blogRules:{...originalRules.blogRules,maxLinksPerDraft:1.5}},revision:profileProof.revisions.siteProfiles}),error=>error.status===400&&/评论规则/.test(error.message));await assert.rejects(runtime.cloud.request('profile',{profileId:'p',profile:{id:'p',fieldNotes:{Name:123}},revision:profileProof.revisions.siteProfiles}),error=>error.status===400&&/字段备注/.test(error.message));const profileAfterRejected=await runtime.cloud.request('snapshot');assert.deepEqual(profileAfterRejected.revisions,profileProof.revisions);assert.deepEqual(profileAfterRejected.documents.submissionRecords['protected.example::p'],receipt);assert.equal(sql.prepare('SELECT count(*) n FROM executor_runs').get().n,0);assert.equal(local.get('paused'),true);
 // Original product navigation and independent promotional URL use authenticated production HTTP/D1 CAS.
 const navigationProfile={id:'p',url:'https://original-product.example',promoUrl:'https://original-product.example/offer',fields:{Url:'https://original-product.example'}};
 await runtime.cloud.request('profile',{profileId:'p',profile:navigationProfile,revision:profileAfterRejected.revisions.siteProfiles});const navigationProof=await runtime.cloud.request('snapshot');assert.equal(navigationProof.documents.siteProfiles.p.url,navigationProfile.url);assert.equal(navigationProof.documents.siteProfiles.p.fields.Url,navigationProfile.url);assert.equal(navigationProof.documents.siteProfiles.p.promoUrl,navigationProfile.promoUrl);assert.equal(globalThis.ExtLinkProfiles.buildAgentConfigFromProfile(navigationProof.documents.siteProfiles.p).targetDomain,navigationProfile.promoUrl);
 const createProduct={id:'original-navigation-new',at:new Date().toISOString(),type:'profile_create',profileId:'q',profile:{id:'q',name:'New original site',url:'https://new-original.example',promoUrl:'https://new-original.example/promotion'}};await runtime.cloud.request('library',{operation:createProduct,revision:navigationProof.revisions.siteProfiles});const createdProductProof=await runtime.cloud.request('snapshot');assert.equal(createdProductProof.documents.siteProfiles.q.sortIndex,0);assert.equal(createdProductProof.documents.siteProfiles.q.promoUrl,createProduct.profile.promoUrl);
 const orderProducts={id:'original-navigation-order',at:new Date().toISOString(),type:'profile_order',profileIds:['q','p']};await runtime.cloud.request('library',{operation:orderProducts,revision:createdProductProof.revisions.siteProfiles});const orderProof=await runtime.cloud.request('snapshot');assert.deepEqual(globalThis.ExtLinkProfiles.orderedProfileIds(orderProof.documents.siteProfiles),['q','p']);assert.equal(orderProof.documents.siteProfiles.p.sortIndex,1);assert.equal(orderProof.documents.siteProfiles.p.fieldNotes.Title,'保留标题备注');assert.equal(orderProof.documents.siteProfiles.p.learnedFieldMappings.name,'Name');assert.equal(orderProof.documents.siteProfiles.p.promoUrl,navigationProfile.promoUrl);
 await assert.rejects(runtime.cloud.request('library',{operation:{...orderProducts,id:'invalid-navigation-order',profileIds:['q']},revision:orderProof.revisions.siteProfiles}),error=>error.status===400&&/排序/.test(error.message));await assert.rejects(runtime.cloud.request('profile',{profileId:'p',profile:{id:'p',promoUrl:'javascript:alert(1)'},revision:orderProof.revisions.siteProfiles}),error=>error.status===400&&/推广网址/.test(error.message));await assert.rejects(runtime.cloud.request('library',{operation:{...orderProducts,id:'stale-navigation-order',profileIds:['p','q']},revision:createdProductProof.revisions.siteProfiles}),/其他客户端更新/);
 const afterNavigationRejected=await runtime.cloud.request('snapshot');assert.deepEqual(afterNavigationRejected.revisions,orderProof.revisions);assert.deepEqual(afterNavigationRejected.documents.submissionRecords['protected.example::p'],receipt);assert.equal(afterNavigationRejected.documents.activeSiteId,'p');assert.equal(sql.prepare('SELECT count(*) n FROM executor_runs').get().n,0);assert.equal(local.get('paused'),true);assert.equal(local.get('acceptanceBatch').cursor,13);
 // Upload and independently read both original formats through real authenticated production routes.
 local.set('applicationSnapshot',{scope:workbenchScope(pair),snapshot:afterNavigationRejected});const originalFormatAssetIds=[];
 for(const image of imageFormatFixtures){const result=await enqueueMediaUpload(runtime,{profileId:'p',kind:'logo',dataUrl:image.dataUrl,fileName:image.name});assert.equal(result.pending,0,result.error);originalFormatAssetIds.push(result.assetId);const asset=(await runtime.cloud.request('media-assets/'+result.assetId)).asset;assert.equal(asset.mime,image.mime);assert.equal(asset.profileId,'p');assert.equal(asset.kind,'logo');const imageUrl=new URL('/v2/executor/workspace/media/'+result.assetId,endpoint);imageUrl.searchParams.set('workspace','default');const imageRead=await fetch(imageUrl,{headers:{Authorization:'Bearer '+pair.deviceToken}});assert.equal(imageRead.status,200);assert.equal(imageRead.headers.get('Content-Type'),image.mime);assert.deepEqual(Buffer.from(await imageRead.arrayBuffer()),image.bytes);if(image.mime==='image/svg+xml')assert.match(imageRead.headers.get('Content-Security-Policy')||'',/sandbox/);}
 const imageProof=await runtime.cloud.request('snapshot');assert.equal(imageProof.documents.siteProfiles.p.mediaVersions.length,2);assert.deepEqual(imageProof.documents.siteProfiles.p.mediaVersions.map(asset=>asset.assetId),originalFormatAssetIds);assert.equal(imageProof.documents.siteProfiles.p.mediaVersions[0].mime,'image/gif');assert.equal(imageProof.documents.siteProfiles.p.mediaVersions[1].mime,'image/svg+xml');assert.equal(imageProof.documents.siteProfiles.p.fieldNotes.Title,'保留标题备注');assert.equal(imageProof.documents.siteProfiles.p.promoUrl,navigationProfile.promoUrl);assert.deepEqual(imageProof.documents.submissionRecords['protected.example::p'],receipt);assert.equal(sql.prepare('SELECT count(*) n FROM executor_runs').get().n,0);assert.equal(local.get('paused'),true);assert.equal(local.get('acceptanceBatch').cursor,13);
 // Original clear preserves the independent public URL and every immutable media version.
 assert.equal(imageProof.documents.siteProfiles.p.logoDataUrl,imageFormatFixtures[0].dataUrl);await runtime.cloud.request('profile',{profileId:'p',profile:{id:'p',logoDataUrl:''},revision:imageProof.revisions.siteProfiles});let mediaControlProof=await runtime.cloud.request('snapshot');assert.equal(mediaControlProof.documents.siteProfiles.p.logoDataUrl,'');assert.equal(mediaControlProof.documents.siteProfiles.p.logoUrl,'https://original-product.example/logo.png');assert.deepEqual(mediaControlProof.documents.siteProfiles.p.mediaVersions,imageProof.documents.siteProfiles.p.mediaVersions);
 await runtime.cloud.request('profile',{profileId:'p',profile:{id:'p',logoUrl:'https://original-product.example/new-logo.svg'},revision:mediaControlProof.revisions.siteProfiles});mediaControlProof=await runtime.cloud.request('snapshot');assert.equal(mediaControlProof.documents.siteProfiles.p.logoUrl,'https://original-product.example/new-logo.svg');
 for(const kind of ['featured','screenshot1','screenshot2','screenshot3','screenshot4']){local.set('applicationSnapshot',{scope:workbenchScope(pair),snapshot:mediaControlProof});await enqueueMediaUpload(runtime,{profileId:'p',kind,dataUrl:imageFormatFixtures[0].dataUrl,fileName:imageFormatFixtures[0].name});mediaControlProof=await runtime.cloud.request('snapshot');}
 const retainedVersions=structuredClone(mediaControlProof.documents.siteProfiles.p.mediaVersions);for(const kind of ['logo','featured','screenshot1','screenshot2','screenshot3','screenshot4']){const operation={id:'original-disable-'+kind,type:'profile_media',profileId:'p',kind,action:'disable',at:new Date().toISOString()};await runtime.cloud.request('library',{operation,revision:mediaControlProof.revisions.siteProfiles});mediaControlProof=await runtime.cloud.request('snapshot');const hint=kind==='featured'?'cover image':kind.startsWith('screenshot')?'screenshot '+kind.slice(10):'logo';assert.equal(globalThis.ExtLinkProfiles.resolveMediaField(globalThis.ExtLinkProfiles.buildAgentConfigFromProfile(mediaControlProof.documents.siteProfiles.p),hint).value,'');assert.deepEqual(mediaControlProof.documents.siteProfiles.p.mediaVersions,retainedVersions);const asset=retainedVersions.find(asset=>asset.kind===kind);await runtime.cloud.request('library',{operation:{...operation,id:'original-restore-'+kind,action:'restore',assetId:asset.assetId},revision:mediaControlProof.revisions.siteProfiles});mediaControlProof=await runtime.cloud.request('snapshot');assert.equal(globalThis.ExtLinkProfiles.resolveMediaField(globalThis.ExtLinkProfiles.buildAgentConfigFromProfile(mediaControlProof.documents.siteProfiles.p),hint).value,asset.ref);}
 await assert.rejects(runtime.cloud.request('profile',{profileId:'p',profile:{id:'p',logoUrl:'javascript:alert(1)'},revision:mediaControlProof.revisions.siteProfiles}),error=>error.status===400);await assert.rejects(runtime.cloud.request('profile',{profileId:'p',profile:{id:'p',mediaDisabled:{logo:'false'}},revision:mediaControlProof.revisions.siteProfiles}),error=>error.status===400);const afterMediaRejected=await runtime.cloud.request('snapshot');assert.deepEqual(afterMediaRejected.revisions,mediaControlProof.revisions);assert.deepEqual(afterMediaRejected.documents.submissionRecords['protected.example::p'],receipt);assert.deepEqual(afterMediaRejected.documents.siteProfiles.p.mediaVersions,retainedVersions);assert.equal(sql.prepare('SELECT count(*) n FROM executor_runs').get().n,0);assert.equal(local.get('paused'),true);assert.equal(local.get('acceptanceBatch').cursor,13);
 // Original current and batch choices use authenticated independent documents and CAS.
 let selectionProof=afterMediaRejected;
 for(const [key,value]of [['activeSiteId','q'],['selectedSiteIds',['q','p']],['selectedSiteIds',[]]]){
  const operation={type:'profile_selection',key,value,id:'original-selection-'+key+'-'+JSON.stringify(value),at:new Date().toISOString()};
  await runtime.cloud.request('library',{operation,revision:selectionProof.revisions[key]||0});selectionProof=await runtime.cloud.request('snapshot');assert.deepEqual(selectionProof.documents[key],value);
  assert.deepEqual(selectionProof.documents.siteProfiles,afterMediaRejected.documents.siteProfiles);assert.deepEqual(selectionProof.documents.submissionRecords,afterMediaRejected.documents.submissionRecords);
 }
 for(const [key,value]of [['activeSiteId','missing'],['selectedSiteIds',['q','q']],['selectedSiteIds',['missing']],['siteProfiles',['p']]])await assert.rejects(runtime.cloud.request('library',{operation:{type:'profile_selection',key,value,id:'invalid-selection-'+key,at:new Date().toISOString()},revision:selectionProof.revisions[key]||0}),error=>error.status===400);
 await assert.rejects(runtime.cloud.request('library',{operation:{type:'profile_selection',key:'activeSiteId',value:'p',id:'stale-original-selection',at:new Date().toISOString()},revision:afterMediaRejected.revisions.activeSiteId||0}),/其他客户端更新/);
 const selectionRejected=await runtime.cloud.request('snapshot');assert.deepEqual(selectionRejected.documents,selectionProof.documents);assert.deepEqual(selectionRejected.revisions,selectionProof.revisions);assert.equal(local.get('paused'),true);assert.equal(local.get('acceptanceBatch').cursor,13);assert.equal(sql.prepare('SELECT count(*) n FROM executor_runs').get().n,0);
 local.set('applicationSnapshot',{scope:workbenchScope(pair),snapshot:selectionRejected});
 const editorAck=await enqueueProfileMutation(runtime,{profileId:'p',revision:selectionRejected.revisions.siteProfiles,profile:{id:'p',fields:{Title:'Original editor save acknowledgement'}}});assert.equal(editorAck.pending,0,editorAck.error);const editorRead=await runtime.cloud.request('snapshot');assert.equal(editorAck.revision,editorRead.revisions.siteProfiles);assert.equal(editorAck.profile.fields.Title,'Original editor save acknowledgement');assert.deepEqual(editorAck.profile.mediaVersions,retainedVersions);assert.throws(()=>enqueueProfileMutation(runtime,{profileId:'p',revision:selectionRejected.revisions.siteProfiles,profile:{id:'p',fields:{Title:'Rejected stale draft'}}}),error=>error.status===409);assert.deepEqual((await runtime.cloud.request('snapshot')).revisions,editorRead.revisions);
 // Original destination preferences, shared aliases and archive queue plans cross authenticated HTTP/D1.
 const libraryUrl='https://library-state.example/submit',libraryKey='library-state.example/submit',libraryDomain='library-state.example';
 const favoriteAck=await enqueueLibraryMutation(runtime,{operation:{type:'preferences',url:libraryUrl,preferences:{favorite:true}}});assert.equal(favoriteAck.pending,0,favoriteAck.error);let libraryProof=await runtime.cloud.request('snapshot');assert.equal(libraryProof.documents.siteAnnotations[libraryKey].library.favorite,true);assert.equal(Object.hasOwn(libraryProof.documents.siteAnnotations[libraryKey].library,'groups'),false);assert.deepEqual(libraryProof.documents.siteAnnotations[libraryDomain],libraryProof.documents.siteAnnotations[libraryKey]);
 const groupAck=await enqueueLibraryMutation(runtime,{operation:{type:'preferences',url:libraryUrl,preferences:{groups:['high_quality','high_quality'],profileIds:['p','p']}}});assert.equal(groupAck.pending,0,groupAck.error);libraryProof=await runtime.cloud.request('snapshot');assert.deepEqual(libraryProof.documents.siteAnnotations[libraryKey].library.groups,['high_quality']);assert.deepEqual(libraryProof.documents.siteAnnotations[libraryKey].library.profileIds,['p']);assert.equal(libraryProof.documents.siteAnnotations[libraryDomain].library.groups,undefined);
 const markAck=await enqueueLibraryMutation(runtime,{operation:{type:'mark',url:libraryUrl,statuses:['can_submit','paid','deleted'],note:'Original mark HTTP proof'}});assert.equal(markAck.pending,0,markAck.error);libraryProof=await runtime.cloud.request('snapshot');assert.equal(libraryProof.documents.siteAnnotations[libraryKey].status,'deleted');assert.deepEqual(libraryProof.documents.siteAnnotations[libraryDomain],libraryProof.documents.siteAnnotations[libraryKey]);assert.ok(libraryProof.documents.deletedSubmissionKeys.includes(libraryKey));assert.equal(local.get('applicationPlan:'+markAck.planId).status,'completed');
 const restoreAck=await enqueueLibraryMutation(runtime,{operation:{type:'mark',url:libraryUrl,statuses:['can_submit'],note:''}});assert.equal(restoreAck.pending,0,restoreAck.error);libraryProof=await runtime.cloud.request('snapshot');assert.equal(libraryProof.documents.deletedSubmissionKeys.includes(libraryKey),false);assert.equal(libraryProof.documents.siteAnnotations[libraryKey].note,'Original mark HTTP proof');assert.deepEqual(libraryProof.documents.siteAnnotations[libraryKey].library.groups,['high_quality']);assert.deepEqual(libraryProof.documents.submissionRecords,selectionRejected.documents.submissionRecords);assert.deepEqual(libraryProof.documents.siteProfiles.p.mediaVersions,retainedVersions);
 for(const operation of [{type:'mark',url:libraryUrl,statuses:['invalid']},{type:'preferences',url:libraryUrl,preferences:{groups:['invalid']}}])await assert.rejects(runtime.cloud.request('library',{operation:{...operation,id:'invalid-library-state-'+operation.type,at:new Date().toISOString()},revision:libraryProof.revisions.siteAnnotations}),error=>error.status===400);assert.deepEqual((await runtime.cloud.request('snapshot')).revisions,libraryProof.revisions);
 // Original display aliases preserve their canonical preference key through HTTP/D1.
 for(const aliasDomain of ['tipseason.com','library.phygital.plus']){const aliasUrl='https://'+aliasDomain+'/submit',aliasAck=await enqueueLibraryMutation(runtime,{operation:{type:'preferences',url:aliasUrl,preferences:{favorite:true,groups:['high_quality'],profileIds:['p']}}});assert.equal(aliasAck.pending,0,aliasAck.error);const aliasProof=await runtime.cloud.request('snapshot');assert.equal(aliasProof.documents.siteAnnotations[aliasDomain].library.favorite,true);assert.deepEqual(aliasProof.documents.siteAnnotations[aliasDomain].library.groups,['high_quality']);assert.deepEqual(aliasProof.documents.siteAnnotations[aliasDomain].library.profileIds,['p']);assert.equal(aliasProof.documents.siteAnnotations[aliasDomain].url,aliasUrl);assert.equal(aliasProof.documents.siteAnnotations[aliasDomain+'/submit'],undefined);}
 for(const aliasDomain of ['tipseason.com','library.phygital.plus']){const aliasUrl='https://'+aliasDomain+'/submit';const archived=await enqueueLibraryMutation(runtime,{operation:{type:'mark',url:aliasUrl,statuses:['deleted']}});assert.equal(archived.pending,0,archived.error);assert.ok((await runtime.cloud.request('snapshot')).documents.deletedSubmissionKeys.includes(aliasDomain));const restored=await enqueueLibraryMutation(runtime,{operation:{type:'mark',url:aliasUrl,statuses:['can_submit']}});assert.equal(restored.pending,0,restored.error);let proof=await runtime.cloud.request('snapshot');assert.equal(proof.documents.deletedSubmissionKeys.includes(aliasDomain),false);assert.equal(proof.documents.siteAnnotations[aliasDomain].library.favorite,true);const removed=await removeFromSubmissionQueue(runtime,{url:aliasUrl});assert.equal(removed.remaining,0);assert.ok((await runtime.cloud.request('snapshot')).documents.deletedSubmissionKeys.includes(aliasDomain));const cleared=await clearSiteAnnotation(runtime,{url:aliasUrl,confirmation:'清除网站标记'});assert.equal(cleared.remaining,0);proof=await runtime.cloud.request('snapshot');assert.equal(proof.documents.siteAnnotations[aliasDomain],undefined);assert.equal(proof.documents.deletedSubmissionKeys.includes(aliasDomain),false);assert.deepEqual(proof.documents.submissionRecords,selectionRejected.documents.submissionRecords);assert.equal(local.get('paused'),true);}
 // Original partial filter and blacklist updates cross the authenticated device API.
 const filterFlags=await enqueueLibraryMutation(runtime,{operation:{type:'settings',key:'targetFilters',value:{aiComments:false,aiCommentAllowLink:false,showManualFillIcons:false}}});assert.equal(filterFlags.pending,0,filterFlags.error);
 const filterPatch=await enqueueLibraryMutation(runtime,{operation:{type:'settings',key:'targetFilters',value:{minDomainAgeMonths:'9999',minOpportunityScore:'25'}}});assert.equal(filterPatch.pending,0,filterPatch.error);let settingsProof=await runtime.cloud.request('snapshot');assert.equal(settingsProof.documents.targetFilters.minDomainAgeMonths,600);assert.equal(settingsProof.documents.targetFilters.minOpportunityScore,25);assert.equal(settingsProof.documents.targetFilters.minDr,60);for(const key of ['aiComments','aiCommentAllowLink','showManualFillIcons'])assert.equal(settingsProof.documents.targetFilters[key],false);
 const blacklistReplace=await enqueueLibraryMutation(runtime,{operation:{type:'settings',key:'domainBlacklist',value:['*.WWW.Blocked.example','https://other.example/path','other.example']}});assert.equal(blacklistReplace.pending,0,blacklistReplace.error);settingsProof=await runtime.cloud.request('snapshot');assert.deepEqual(settingsProof.documents.domainBlacklist,['.blocked.example','other.example']);
 const blacklistPatch=await enqueueLibraryMutation(runtime,{operation:{type:'settings',key:'domainBlacklist',value:{remove:['https://www.blocked.example/path'],add:['*.new.example']}}});assert.equal(blacklistPatch.pending,0,blacklistPatch.error);settingsProof=await runtime.cloud.request('snapshot');assert.deepEqual(settingsProof.documents.domainBlacklist,['.new.example','other.example']);assert.deepEqual(settingsProof.documents.submissionRecords,libraryProof.documents.submissionRecords);assert.deepEqual(settingsProof.documents.siteProfiles,libraryProof.documents.siteProfiles);
 for(const [key,value]of [['targetFilters',{unknown:true}],['targetFilters',{minDr:{invalid:true}}],['domainBlacklist',{add:['ok.example'],unknown:true}],['domainBlacklist',{remove:'wrong type'}]])await assert.rejects(runtime.cloud.request('library',{operation:{type:'settings',key,value,id:'invalid-original-settings-'+key,at:new Date().toISOString()},revision:settingsProof.revisions[key]}),error=>error.status===400);const settingsRejected=await runtime.cloud.request('snapshot');assert.deepEqual(settingsRejected.documents,settingsProof.documents);assert.deepEqual(settingsRejected.revisions,settingsProof.revisions);
 const newCurrent=await enqueueLibraryMutation(runtime,{operation:{type:'profile_create',profileId:'r',profile:{id:'r',name:'New current site',url:''}}});assert.equal(newCurrent.pending,0,newCurrent.error);let lifecycleProof=await runtime.cloud.request('snapshot');assert.equal(lifecycleProof.documents.activeSiteId,'r');assert.ok(lifecycleProof.documents.siteProfiles.r);assert.equal(lifecycleProof.documents.siteProfiles.r.url,'');assert.deepEqual(lifecycleProof.documents.selectedSiteIds,[]);
 for(const [profileId,expectedCurrent]of [['p','r'],['r','q'],['q','']]){const deleted=await enqueueLibraryMutation(runtime,{operation:{type:'profile_delete',profileId}});assert.equal(deleted.pending,0,deleted.error);lifecycleProof=await runtime.cloud.request('snapshot');assert.equal(lifecycleProof.documents.activeSiteId,expectedCurrent);assert.equal(lifecycleProof.documents.siteProfiles[profileId],undefined);assert.deepEqual(lifecycleProof.documents.submissionRecords,selectionRejected.documents.submissionRecords);assert.equal(local.get('paused'),true);assert.equal(local.get('acceptanceBatch').cursor,13);}
 assert.deepEqual(lifecycleProof.documents.siteProfiles,{});assert.equal(sql.prepare('SELECT count(*) n FROM executor_runs').get().n,0);
 }finally{local?.close();if(server?.listening)await new Promise(resolve=>server.close(resolve));sql.close();assert.ok(resolve(home).startsWith(resolve(tmpdir())+sep)&&home.includes('el-recovery-http-'));await rm(home,{recursive:true,force:true});}
});
