import test from'node:test';import assert from'node:assert/strict';
import{Store}from'../executor/src/store.mjs';import{workbenchScope}from'../executor/src/workbench-sync.mjs';import{assistantState,saveAssistantSettings,autoVisitTarget,requestAutoFill,fillAssistantTask}from'../executor/src/browser-assistant.mjs';import{sidepanelOpened,sidepanelClosed,preparedTask}from'../executor/src/single-page.mjs';import{applicationData}from'../executor/src/application-data.mjs';import{flushApplicationMutations}from'../executor/src/application-mutations.mjs';
import{applicationMutation}from'../core/application-mutation.mjs';import{exportApplicationBackup,mergeApplicationBackup,applicationBackupFragment,validateApplicationBackup}from'../core/application-backup.mjs';import{localRecoveryDocuments}from'../core/local-recovery.mjs';import{STATE_DOCUMENT_KEYS}from'../cloud/worker/src/worker-core.mjs';
const profile={id:'p',name:'Original',fields:{Name:'Original',Url:'https://product.example'}};
function fixture(flag){const store=new Store(':memory:'),pair={endpoint:'https://cloud.example',workspaceId:'original'},snapshot={documents:{siteProfiles:{p:profile},activeSiteId:'p',submissionRecords:{},...(flag===undefined?{}:{autoFillOnVisit:flag})},revisions:{siteProfiles:1,autoFillOnVisit:1}};store.set('pair',pair);store.set('paused',true);store.set('acceptanceBatch',{status:'paused',cursor:13,count:30});const writes=[];let offline=false,lost=false;const runtime={store,status:()=>({tasks:[],paused:true,busy:false,pendingEvents:0}),cloud:{async request(route,input){if(offline)throw Error('offline');if(route==='snapshot')return structuredClone(snapshot);if(route==='library'){const changed=applicationMutation(snapshot.documents,input.operation);assert.equal(input.revision,snapshot.revisions[changed.key]);snapshot.documents[changed.key]=changed.data;snapshot.revisions[changed.key]++;writes.push(input.operation);if(lost){lost=false;throw Error('reply lost after commit');}return{ok:true};}throw Error(route);}}};store.set('applicationSnapshot',{scope:workbenchScope(pair),snapshot});return{store,runtime,snapshot,writes,offline(v){offline=v;},lose(){lost=true;}};}
test('the original visit opt-in is preserved by cloud keys, raw backups, fragments, merging, export and recovery',()=>{
 assert.ok(STATE_DOCUMENT_KEYS.includes('autoFillOnVisit'));for(const enabled of [true,false]){const source={siteProfiles:{p:profile},submissionRecords:{},autoFillOnVisit:enabled},raw={format:'externallink-submission-backup',...source};assert.equal(localRecoveryDocuments(source).autoFillOnVisit,enabled);assert.equal(exportApplicationBackup(source).autoFillOnVisit,enabled);assert.equal(mergeApplicationBackup({},raw).autoFillOnVisit,enabled);assert.equal(applicationBackupFragment(raw,'autoFillOnVisit').autoFillOnVisit,enabled);assert.equal(applicationMutation(source,{id:'settings',at:'now',type:'settings',key:'autoFillOnVisit',value:!enabled}).data,!enabled);}
 const raw={format:'externallink-submission-backup',siteProfiles:{p:profile},submissionRecords:{}};assert.equal(Object.hasOwn(exportApplicationBackup(raw),'autoFillOnVisit'),false);for(const value of ['true',1,null,{},[]]){assert.throws(()=>validateApplicationBackup({...raw,autoFillOnVisit:value}),/设置/);assert.throws(()=>localRecoveryDocuments({...raw,autoFillOnVisit:value}),/设置|格式/);}
});
test('a recovered legacy opt-in is active only in the selected open panel; a new device and explicit modern disable stay off',()=>{
 const f=fixture(true);try{assert.equal(assistantState(f.runtime).settings.enabled,false);assert.equal(assistantState(f.runtime).settings.autoFillOnVisit,true);const {panel}=sidepanelOpened(f.runtime,{profileId:'p',targetId:'original-page'});assert.equal(assistantState(f.runtime).settings.enabled,true);assert.equal(assistantState(f.runtime).settings.profileId,'p');sidepanelClosed(f.runtime,{panelId:panel.id});assert.equal(assistantState(f.runtime).settings.enabled,false);sidepanelOpened(f.runtime,{profileId:'p',targetId:'original-page'});f.store.set('browserAssistantSettings',{scope:workbenchScope(f.store.get('pair')),enabled:false,autoFillOnVisit:false,profileId:'p'});assert.equal(assistantState(f.runtime).settings.enabled,false);f.store.set('pair',{endpoint:'https://cloud.example',workspaceId:'other'});assert.equal(assistantState(f.runtime).settings.enabled,false);assert.equal(assistantState(f.runtime).settings.autoFillOnVisit,false);}finally{f.store.close();}
});
test('assistant preference saves offline first and a lost reply confirms the same original setting mutation',async()=>{
 const f=fixture(false);try{await applicationData(f.runtime,{refresh:true});f.offline(true);const saved=await saveAssistantSettings(f.runtime,{enabled:true,autoFillOnVisit:true,profileId:'p'});assert.equal(saved.settings.autoFillOnVisit,true);assert.equal(f.writes.length,0);const pending=f.store.values('appMutation:');assert.equal(pending.length,1);assert.equal(pending[0].operation.key,'autoFillOnVisit');assert.equal(f.store.get('paused'),true);f.offline(false);f.lose();await flushApplicationMutations(f.runtime);await flushApplicationMutations(f.runtime);assert.equal(f.writes.length,1);assert.equal(f.writes[0].id,pending[0].id);assert.equal(f.snapshot.documents.autoFillOnVisit,true);const data=await applicationData(f.runtime,{refresh:true});assert.equal(data.settings.autoFillOnVisit,true);assert.equal(data.pendingEdits.length,0);assert.equal(f.store.get('acceptanceBatch').cursor,13);}finally{f.store.close();}
});
test('a fresh cloud disable overrides an older local visit flag and an assistant save cannot cross workspaces',async()=>{
 const f=fixture(true);try{f.store.set('browserAssistantSettings',{scope:workbenchScope(f.store.get('pair')),enabled:true,autoFillOnVisit:true,profileId:'p'});f.snapshot.documents.autoFillOnVisit=false;await applicationData(f.runtime,{refresh:true});assert.equal(assistantState(f.runtime).settings.autoFillOnVisit,false);f.runtime.cloud.request=async()=>{f.store.set('pair',{endpoint:'https://cloud.example',workspaceId:'other'});return structuredClone(f.snapshot);};await assert.rejects(saveAssistantSettings(f.runtime,{enabled:true,autoFillOnVisit:true,profileId:'p'}),/工作区/);assert.equal(f.store.values('appMutation:').length,0);}finally{f.store.close();}
});
test('visit matching preserves original destination identity and excludes prior receipts, original quality gates and a marked current form path',()=>{
 const snapshot={documents:{siteProfiles:{p:profile},sheetTableData:{entries:[{link:'https://target.example/submit',indexPage:'https://target.example/submit',metrics:{dr:20}}]},submissionRecords:{}}},url='https://target.example/actual-form';
 assert.equal(autoVisitTarget(snapshot,'p',url).url,'https://target.example/submit');assert.equal(autoVisitTarget(snapshot,'missing',url),null);
 snapshot.documents.submissionRecords={'target.example/older::p':{profileId:'p',destinationUrl:'https://target.example/older',status:'success',confirmedBy:'agent',evidence:'Original received submission'}};assert.equal(autoVisitTarget(snapshot,'p',url),null);snapshot.documents.submissionRecords={};
 snapshot.documents.targetFilters={minDr:60};assert.equal(autoVisitTarget(snapshot,'p',url),null);snapshot.documents.targetFilters={};
 snapshot.documents.siteAnnotations={'target.example/actual-form':{status:'paid'}};assert.equal(autoVisitTarget(snapshot,'p',url),null);
});
test('automatic visiting reuses the one original host task and refuses remote manual gates or an ambiguous host without registration',async()=>{
 const f=fixture(true),run={id:'original-run',profileId:'p',profile,profileRevision:1},task={id:'original-task',runId:run.id,profileId:'p',url:'https://target.example/original',destinationKey:'target.example/original',status:'needs_manual',attentionType:'fill_only'};let inventory=[task],registrations=0;
 f.runtime.cloud.request=async(route)=>{if(route==='runs?view=inventory')return{tasks:inventory,runs:[run]};if(route==='tasks/'+task.id)return{task};if(route==='runs?runId='+run.id)return{runs:[run],tasks:[task]};registrations++;throw Error('Unexpected registration');};
 try{const input={profileId:'p',expectedUrl:'https://target.example/submit',autoVisit:true},saved=await preparedTask(f.runtime,input,f.snapshot);assert.equal(saved.id,task.id);assert.equal(saved.url,task.url);assert.equal(saved.profileRevision,1);assert.equal(f.store.values('singlePagePlan:').length,0);inventory=[{...task,attentionType:'login'}];await assert.rejects(preparedTask(f.runtime,input,f.snapshot),/人工闸门/);inventory=[task,{...task,id:'another',url:'https://target.example/other'}];await assert.rejects(preparedTask(f.runtime,input,f.snapshot),/多个原任务/);assert.equal(registrations,0);assert.equal(f.store.get('acceptanceBatch').cursor,13);}finally{f.store.close();}
});
test('turning off visit filling cancels queued original page work while leaving ordinary assistant settings enabled',async()=>{
 const f=fixture(true);let fired=false;try{const key='assistantFill:queued-original';f.store.set(key,{scope:workbenchScope(f.store.get('pair')),status:'preparing',targetId:'original-target',profileId:'p'});f.runtime.sidepanelAutoTimers=new Map([[key,setTimeout(()=>{fired=true;},30)]]);const result=await saveAssistantSettings(f.runtime,{enabled:true,autoFillOnVisit:false,profileId:'p'});assert.equal(result.settings.enabled,true);assert.equal(result.settings.autoFillOnVisit,false);assert.equal(f.runtime.sidepanelAutoTimers.size,0);await new Promise(resolve=>setTimeout(resolve,40));assert.equal(fired,false);assert.equal(f.store.get(key).status,'cancelled');assert.equal(f.store.get(key).targetId,'original-target');}finally{f.store.close();}
});
test('native automatic fill messages require the current open panel product target and selection generation before any browser or cloud work',async()=>{
 const f=fixture(true);try{const {panel}=sidepanelOpened(f.runtime,{profileId:'p',targetId:'original-target'}),input={fromSidepanel:true,panelId:panel.id,panelGeneration:panel.generation,profileId:'p',targetId:panel.selectedTargetId};assert.equal((await requestAutoFill(f.runtime,input)).reason,'browser_not_connected');for(const patch of [{fromSidepanel:false},{panelId:'old'},{panelGeneration:panel.generation-1},{profileId:'other'},{targetId:'other'}])await assert.rejects(requestAutoFill(f.runtime,{...input,...patch}),/网页面板/);sidepanelClosed(f.runtime,{panelId:panel.id});await assert.rejects(requestAutoFill(f.runtime,input),/网页面板/);assert.equal(f.writes.length,0);assert.equal(f.store.values('assistantFill:').length,0);assert.equal(f.store.get('acceptanceBatch').cursor,13);}finally{f.store.close();}
});
test('changing a panel selection cancels its delayed original request and invalidates its private document binding so selecting it again is possible',async()=>{
 const f=fixture(true);let fired=false;try{const {panel}=sidepanelOpened(f.runtime,{profileId:'p',targetId:'original-target'}),key='assistantFill:original',binding={id:'original-document'};f.store.set(key,{scope:workbenchScope(f.store.get('pair')),status:'preparing',targetId:'original-target',profileId:'p'});f.runtime.sidepanelAutoTimers=new Map([[key,setTimeout(()=>{fired=true;},25)]]);f.runtime.autoVisitBindings=new Map([[key,binding]]);sidepanelOpened(f.runtime,{panelId:panel.id,profileId:'p',targetId:'other'});assert.equal(f.store.get(key).status,'cancelled');assert.equal(binding.cancelled,true);assert.equal(f.runtime.autoVisitBindings.size,0);assert.equal(f.runtime.sidepanelAutoTimers.size,0);await new Promise(resolve=>setTimeout(resolve,40));assert.equal(fired,false);assert.equal(f.writes.length,0);}finally{f.store.close();}
});
test('automatic work cannot use an unbound stale cancelled or replaced browser document even at the same URL',async()=>{
 for(const mode of ['unbound','stale','cancelled','browser-changed']){const f=fixture(true);try{sidepanelOpened(f.runtime,{profileId:'p',targetId:'original-target'});const scope=workbenchScope(f.store.get('pair')),key='assistantFill:original',input={fillKey:key,autoVisitRequestId:'request-original',profileId:'p',targetId:'original-target',url:'https://target.example/submit'};f.runtime.host={startedAt:'original-browser'};f.store.set(key,{scope,...input,status:'preparing'});f.runtime.autoVisitBindings=new Map();if(mode!=='unbound')f.runtime.autoVisitBindings.set(key,{id:input.autoVisitRequestId,scope,profileId:'p',targetId:input.targetId,url:input.url,browserInstance:mode==='browser-changed'?'other-browser':'original-browser',cancelled:mode==='cancelled',engine:{isCurrentDocument:async()=>mode!=='stale'}});await assert.rejects(fillAssistantTask(f.runtime,input),/文档/);assert.equal(f.writes.length,0);assert.equal(f.store.values('task:').length,0);assert.equal(f.store.get('acceptanceBatch').cursor,13);}finally{f.store.close();}}
});
