import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '../executor/node_modules/@electric-sql/pglite/dist/index.js';
import {executorApi} from '../cloud/worker/src/executor-api.mjs';
test('authenticated Neon automatic observations preserve manual preferences and atomically fence annotation and deleted-key versions',async()=>{
 const db=new PGlite();try{
  await db.exec(await readFile(new URL('../cloud/worker/schema.sql',import.meta.url),'utf8'));let beforeTransaction;
  const sql=(strings,...params)=>{const query=strings.reduce((text,part,index)=>text+part+(index<params.length?'$'+(index+1):''),'');return{query,params,then:(resolve,reject)=>db.query(query,params).then(result=>result.rows).then(resolve,reject)};};
  sql.transaction=async queries=>{const hook=beforeTransaction;beforeTransaction=null;await hook?.();return db.transaction(async tx=>{const result=[];for(const query of queries)result.push((await tx.query(query.query,query.params)).rows);return result;});};
  await sql`insert into externallink_workspaces(workspace_id) values('default')`;
  const manual={status:'can_submit',statuses:['can_submit'],auto:false,note:'User verdict',library:{favorite:true,groups:['original']}},automatic={status:'deleted',statuses:['deleted'],auto:true,note:'Old result',library:{favorite:true,groups:['original']}},annotations={'manual.example/submit':manual,'automatic.example/submit':automatic};
  for(const [key,value]of Object.entries({siteAnnotations:annotations,deletedSubmissionKeys:['automatic.example/submit','retained.example/old'],submissionRecords:{receipt:{status:'success',evidence:'Keep original'}}}))await sql`insert into externallink_workspace_documents(workspace_id,document_key,data) values('default',${key},${JSON.stringify(value)}::jsonb)`;
  const env={APP_ACCESS_TOKEN:'fixture-admin'},call=async(route,token,input,workspace='default')=>{const response=await executorApi(new Request('https://cloud.fixture.invalid/v1/executor/'+route,{method:'POST',headers:{Authorization:'Bearer '+token},body:JSON.stringify(input)}),env,sql,workspace,{});return{status:response.status,data:await response.json()};},device=(await call('devices','fixture-admin',{})).data,token=device.deviceToken;
  const read=async()=>Object.fromEntries((await sql`select document_key,data,revision from externallink_workspace_documents where workspace_id='default'`).map(row=>[row.document_key,{data:row.data,revision:Number(row.revision)}]));
  const operation={type:'automatic_mark',id:'automatic-observation',at:'2026-10-07T00:00:00Z',url:'https://automatic.example/submit',status:'needs_captcha',note:'Actual CAPTCHA gate'},request={operation,revision:1,revisions:{siteAnnotations:1,deletedSubmissionKeys:1}},original=await read();
  for(const denied of ['wrong','fixture-admin'])assert.equal((await call('library',denied,request)).status,401);assert.equal((await call('library',token,request,'other')).status,401);
  assert.equal((await call('library',token,{operation,revision:1})).status,400);assert.equal((await call('library',token,{...request,revisions:{siteAnnotations:1,deletedSubmissionKeys:0}})).status,409);assert.deepEqual(await read(),original);
  const saved=await call('library',token,request);assert.equal(saved.status,200,JSON.stringify(saved));assert.deepEqual(saved.data.revisions,{siteAnnotations:2,deletedSubmissionKeys:2});let current=await read();assert.equal(current.siteAnnotations.data['automatic.example/submit'].status,'needs_captcha');assert.deepEqual(current.deletedSubmissionKeys.data,['retained.example/old']);assert.equal(current.siteAnnotations.data['automatic.example/submit'].library.favorite,true);
  const observed=await call('library',token,{operation:{...operation,id:'manual-observation',url:'https://manual.example/submit',status:'paid'},revision:2,revisions:{siteAnnotations:2,deletedSubmissionKeys:2}});assert.equal(observed.status,200);current=await read();const next={...current.siteAnnotations.data['manual.example/submit']};delete next.lastAutomaticObservation;assert.deepEqual(next,manual);assert.equal(current.siteAnnotations.data['manual.example/submit'].lastAutomaticObservation.status,'paid');assert.deepEqual(current.deletedSubmissionKeys,{data:['retained.example/old'],revision:2});assert.deepEqual(current.submissionRecords,original.submissionRecords);
  beforeTransaction=()=>db.query("update externallink_workspace_documents set data=$1::jsonb,revision=revision+1 where workspace_id='default' and document_key='deletedSubmissionKeys'",[JSON.stringify(['concurrent.example/new'])]);
  const race=await call('library',token,{operation:{...operation,id:'race',status:'deleted'},revision:3,revisions:{siteAnnotations:3,deletedSubmissionKeys:2}});assert.equal(race.status,409,JSON.stringify(race));const after=await read();assert.deepEqual(after.siteAnnotations,current.siteAnnotations);assert.deepEqual(after.deletedSubmissionKeys,{data:['concurrent.example/new'],revision:3});assert.deepEqual(after.submissionRecords,original.submissionRecords);
  await call('revoke','fixture-admin',{deviceId:device.deviceId});assert.equal((await call('library',token,{...request,revision:3,revisions:{siteAnnotations:3,deletedSubmissionKeys:3}})).status,401);assert.deepEqual(await read(),after);
 }finally{await db.close();}
});
