import test from 'node:test';
import assert from 'node:assert/strict';
import {originalLibraryAction} from './helpers/original-library-catalog.mjs';
import {applicationMutation,applicationMutationSatisfied} from '../core/application-mutation.mjs';
import {canonicalLibraryDestination} from '../core/library-records.mjs';
import {applicationModel} from '../core/application-model.mjs';
import {selectScope} from '../executor/src/shared.mjs';
import {Store} from '../executor/src/store.mjs';
import {workbenchScope} from '../executor/src/workbench-sync.mjs';
import {enqueueLibraryMutation,enqueueApplicationPlan,flushApplicationMutations,pendingApplication,resolveApplicationConflict} from '../executor/src/application-mutations.mjs';
import {addBrowserPage} from '../executor/src/browser-library.mjs';
import {previewWorkbenchBatch} from '../executor/src/workbench-features.mjs';
import {mkdtempSync,unlinkSync,rmdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
const domains=['startupstash.com','startupcollections.com','aisuperhub.io','launchpedia.co','tipseason.com','library.phygital.plus','aisotools.com','producthunt.com','aitools.neilpatel.com','ordinary.example'];
const Queue=globalThis.ExtLinkQueue;
function fixture(domain){const url='https://'+domain+'/submit',key=canonicalLibraryDestination(url),rawKey=Queue.normalizeDestinationKey(url),documents={siteProfiles:{p:{id:'p',name:'原产品',fields:{Url:'https://product.example'}}},sheetTableData:{entries:[{link:url}]},siteAnnotations:{[key]:{status:'deleted',statuses:['deleted'],note:'Original canonical note',submittedProjects:['p'],formKnowledge:{schema:{canonical:true}},library:{favorite:true,groups:['high_quality']}}},deletedSubmissionKeys:[key,'unrelated.example/form'],submissionRecords:{original:{profileId:'p',status:'success',confirmedBy:'manual',evidence:'Original receipt',destinationUrl:url}},urlList:'https://unrelated.example/form|forum\nhttps://'+domain+'/older|directory\n'+url+'|submission'};if(key!==rawKey)documents.siteAnnotations[rawKey]={status:'can_submit',note:'Original route marker',formKnowledge:{schema:{route:true}}};return{url,key,rawKey,documents};}
const annotations=value=>Object.fromEntries(Object.entries(value).map(([key,record])=>[key,Object.fromEntries(Object.entries(record).filter(([field])=>!['updatedAt','mutationId','source'].includes(field)))]));
function apply(documents,operation){const change=applicationMutation(documents,{...operation,id:'original-action-'+operation.type,at:'2026-10-07T00:00:00Z'});documents[change.key]=change.data;assert.equal(applicationMutationSatisfied(documents,{...operation,id:'original-action-'+operation.type,at:'2026-10-07T00:00:00Z'}),true);}
test('clear original library marks uses the same display key, keeps canonical knowledge and unrelated route records',async()=>{
 for(const domain of domains){const f=fixture(domain),before=structuredClone(f.documents),expected=await originalLibraryAction(before,'clear',{url:f.url}),current=structuredClone(before);apply(current,{type:'clear_annotation',url:f.url});apply(current,{type:'clear_deleted',url:f.url});assert.deepEqual(current.siteAnnotations,expected.documents.siteAnnotations,domain);assert.deepEqual(current.deletedSubmissionKeys,expected.documents.deletedSubmissionKeys,domain);assert.deepEqual(current.submissionRecords,before.submissionRecords);assert.deepEqual(current.sheetTableData,before.sheetTableData);assert.deepEqual(f.documents,before);assert.equal(applicationModel({documents:current}).library[0].annotation.library,undefined);}
});
test('archive and restore original aliases preserve the canonical preferences and exact original deletion key',async()=>{
 for(const domain of domains){const f=fixture(domain);for(const statuses of [['deleted'],['can_submit']]){const expected=await originalLibraryAction(f.documents,'mark',{url:f.url,statuses,auto:false,note:'Changed note'}),current=structuredClone(f.documents);apply(current,{type:'mark',url:f.url,statuses,note:'Changed note'});apply(current,{type:statuses.includes('deleted')?'set_deleted':'clear_deleted',url:f.url});assert.deepEqual(annotations(current.siteAnnotations),annotations(expected.documents.siteAnnotations),domain);assert.deepEqual(current.deletedSubmissionKeys,expected.documents.deletedSubmissionKeys);assert.deepEqual(current.siteAnnotations[f.key].library,f.documents.siteAnnotations[f.key].library);assert.deepEqual(current.submissionRecords,f.documents.submissionRecords);}}
});
test('remove from queue preserves original alias metadata and projects instead of replacing it with stale route marks',async()=>{
 for(const domain of domains){const f=fixture(domain),expected=await originalLibraryAction(f.documents,'mark',{url:f.url,status:'deleted',note:''}),current=structuredClone(f.documents);apply(current,{type:'remove_queue',url:f.url,note:''});apply(current,{type:'set_deleted',url:f.url});assert.deepEqual(annotations(current.siteAnnotations),annotations(expected.documents.siteAnnotations),domain);assert.deepEqual(current.deletedSubmissionKeys,expected.documents.deletedSubmissionKeys);assert.deepEqual(current.submissionRecords,f.documents.submissionRecords);}
});
test('pin original display aliases retains the original URL-list metadata and removes only duplicate display entries',async()=>{
 for(const domain of domains){const f=fixture(domain),expected=await originalLibraryAction(f.documents,'pin',{url:f.url}),current=structuredClone(f.documents);apply(current,{type:'pin',url:f.url});assert.equal(current.urlList,expected.documents.urlList,domain);assert.deepEqual(current.sheetTableData,f.documents.sheetTableData);assert.deepEqual(current.siteAnnotations,f.documents.siteAnnotations);assert.deepEqual(current.submissionRecords,f.documents.submissionRecords);}
});
test('canonical marks and preferences govern every original alias in the displayed queue and batch scope',()=>{
 for(const domain of domains.slice(0,-1)){const f=fixture(domain);f.documents.submissionRecords={};f.documents.siteProfiles.other={id:'other',fields:{Url:'https://other.example'}};f.documents.urlList='';f.documents.sheetTableData.entries.push({link:'https://'+domain});const snapshot={documents:f.documents},before=structuredClone(snapshot);assert.equal(selectScope(snapshot,null,'p').tasks.length,0,domain+' archived');apply(f.documents,{type:'mark',url:f.url,statuses:['can_submit']});apply(f.documents,{type:'clear_deleted',url:f.url});let scope=selectScope(snapshot,null,'p');assert.equal(scope.tasks.length,1,domain+' duplicate aliases');assert.equal(scope.tasks[0].url,f.url);scope=selectScope(snapshot,null,'p',['https://'+domain+'/older']);assert.equal(scope.tasks.length,1,domain+' explicit original alias');apply(f.documents,{type:'preferences',url:f.url,preferences:{enabled:false}});assert.equal(selectScope(snapshot,null,'p').tasks.length,0,domain+' disabled');apply(f.documents,{type:'preferences',url:f.url,preferences:{enabled:true,profileIds:['other']}});assert.equal(selectScope(snapshot,null,'p').tasks.length,0,domain+' assignment');assert.deepEqual(snapshot.documents.sheetTableData,before.documents.sheetTableData);assert.deepEqual(snapshot.documents.submissionRecords,before.documents.submissionRecords);}
});
function runtimeFixture(f,store=new Store(':memory:')){const pair={endpoint:'https://fixture.invalid',workspaceId:'alias-actions'},snapshot={documents:structuredClone(f.documents),revisions:{siteAnnotations:1,deletedSubmissionKeys:1,urlList:1}},writes=[];store.set('pair',pair);store.set('paused',true);store.set('applicationSnapshot',{scope:workbenchScope(pair),snapshot:structuredClone(snapshot)});const runtime={store,status:()=>({paused:true,busy:false,pendingEvents:0,tasks:[]}),cloud:{async request(route,input){if(route==='snapshot')return structuredClone(snapshot);if(route==='runs?view=inventory')return{tasks:[],runs:[]};assert.equal(route,'library');const change=applicationMutation(snapshot.documents,input.operation);writes.push(input.operation);snapshot.documents[change.key]=change.data;snapshot.revisions[change.key]=(snapshot.revisions[change.key]||0)+1;return{ok:true};}}};return{runtime,store,snapshot,writes};}
test('restoring an alias mark clears its original canonical queue exclusion in the same durable plan',async()=>{
 for(const domain of ['tipseason.com','library.phygital.plus']){const f=fixture(domain),r=runtimeFixture(f);try{const result=await enqueueLibraryMutation(r.runtime,{operation:{type:'mark',url:f.url,statuses:['can_submit']}});assert.equal(result.pending,0);assert.equal(r.snapshot.documents.deletedSubmissionKeys.includes(f.key),false);assert.equal(r.writes.length,2);assert.equal(r.store.get('applicationPlan:'+result.planId).status,'completed');assert.equal(r.store.get('paused'),true);assert.deepEqual(r.snapshot.documents.submissionRecords,f.documents.submissionRecords);}finally{r.store.close();}}
});
test('adding an existing original alias from the browser removes its canonical archive flag and retains original URL metadata',async()=>{
 const f=fixture('tipseason.com'),r=runtimeFixture(f),page={url:()=>f.url,title:async()=> '原页面',isClosed:()=>false};r.runtime.context={pages:()=>[page],newCDPSession:async()=>({send:async()=>({targetInfo:{targetId:'original-tab'}}),detach:async()=>{}})};try{const result=await addBrowserPage(r.runtime,{targetId:'original-tab',expectedUrl:f.url});assert.equal(result.remaining,0);const annotation=r.snapshot.documents.siteAnnotations[f.key];assert.equal(Queue.normalizeAnnotationStatuses(annotation).includes('deleted'),false);assert.equal(annotation.library.pinned,true);assert.equal(annotation.library.enabled,true);assert.equal(r.snapshot.documents.deletedSubmissionKeys.includes(f.key),false);assert.equal(r.snapshot.documents.urlList.split('\n')[0],'https://tipseason.com/older|directory');assert.deepEqual(r.snapshot.documents.siteAnnotations[f.rawKey],f.documents.siteAnnotations[f.rawKey]);assert.deepEqual(r.snapshot.documents.submissionRecords,f.documents.submissionRecords);assert.equal(r.store.get('paused'),true);}finally{r.store.close();}
});
test('retaining a concurrent cloud annotation also cancels the dependent original clear or remove queue operation',async()=>{
 for(const type of ['clear_annotation','remove_queue','pin']){const f=fixture('tipseason.com'),r=runtimeFixture(f),request=r.runtime.cloud.request;let online=false;r.runtime.cloud.request=(...args)=>{if(!online)throw Error('offline');return request(...args);};try{const operations=type==='pin'?[{type:'pin',url:f.url},{type:'preferences',url:f.url,preferences:{pinned:true}},{type:'clear_deleted',url:f.url}]:[{type,url:f.url},{type:type==='clear_annotation'?'clear_deleted':'set_deleted',url:f.url}];if(type==='remove_queue'){r.snapshot.documents.deletedSubmissionKeys=[];r.snapshot.documents.siteAnnotations[f.key].status='can_submit';r.snapshot.documents.siteAnnotations[f.key].statuses=['can_submit'];}r.store.set('applicationSnapshot',{scope:workbenchScope(r.store.get('pair')),snapshot:structuredClone(r.snapshot)});const plan=await enqueueApplicationPlan(r.runtime,{operations});const key=type==='pin'?'urlList':'siteAnnotations';if(type==='pin')r.snapshot.documents.urlList='https://concurrent.example/form|directory\n'+r.snapshot.documents.urlList;else r.snapshot.documents.siteAnnotations[f.key].note='Concurrent cloud note';r.snapshot.revisions[key]++;const before=structuredClone(r.snapshot);online=true;await flushApplicationMutations(r.runtime);const conflict=pendingApplication(r.runtime).find(item=>item.status==='conflict');assert.ok(conflict);await resolveApplicationConflict(r.runtime,{id:conflict.id,choice:'cloud',revision:r.snapshot.revisions[key]});assert.equal(r.writes.length,0,type);assert.deepEqual(r.snapshot,before);assert.equal(pendingApplication(r.runtime).length,0);assert.equal(r.store.get('applicationPlan:'+plan.planId).status,'completed');assert.equal(r.store.get('applicationPlan:'+plan.planId).excludedIds.length,operations.length);}finally{r.store.close();}}
});
test('old clear plans retain original identities through SQLite reopen, lost replies and dependency recovery',async()=>{
 const home=mkdtempSync(join(tmpdir(),'externallink-alias-actions-')),path=join(home,'actions.sqlite'),f=fixture('library.phygital.plus'),r=runtimeFixture(f,new Store(path)),request=r.runtime.cloud.request;let online=false;r.runtime.cloud.request=async(...args)=>{if(!online)throw Error('offline');const result=await request(...args);if(args[0]==='library')throw Error('original response lost');return result;};try{const result=await enqueueApplicationPlan(r.runtime,{operations:[{type:'clear_annotation',url:f.url},{type:'clear_deleted',url:f.url}]}),plan=r.store.get('applicationPlan:'+result.planId),ids=plan.items.map(item=>item.id);delete plan.kind;for(const item of plan.items){delete item.dependsOn;const stored=r.store.get('appMutation:'+item.id);delete stored.dependsOn;r.store.set('appMutation:'+item.id,stored);}r.store.set('applicationPlan:'+plan.id,plan);r.store.close();r.store=new Store(path);r.runtime.store=r.store;online=true;for(let i=0;i<5;i++)await flushApplicationMutations(r.runtime);assert.equal(pendingApplication(r.runtime).length,0);assert.deepEqual(r.writes.map(item=>item.id),ids);const recovered=r.store.get('applicationPlan:'+plan.id);assert.equal(recovered.kind,'catalog_lifecycle');assert.equal(recovered.status,'completed');assert.deepEqual(recovered.items.map(item=>item.id),ids);assert.equal(recovered.items[1].dependsOn,ids[0]);assert.deepEqual(r.snapshot.documents.siteAnnotations[f.key].formKnowledge,f.documents.siteAnnotations[f.key].formKnowledge);assert.deepEqual(r.snapshot.documents.siteAnnotations[f.rawKey],f.documents.siteAnnotations[f.rawKey]);assert.deepEqual(r.snapshot.documents.deletedSubmissionKeys,['unrelated.example/form']);assert.deepEqual(r.snapshot.documents.submissionRecords,f.documents.submissionRecords);assert.equal(r.store.get('paused'),true);}finally{r.store.close();for(const suffix of ['','-wal','-shm'])try{unlinkSync(path+suffix);}catch(error){if(error.code!=='ENOENT')throw error;}rmdirSync(home);}
});
test('pinning an already-first alias still performs original duplicate removal before acknowledging the change',async()=>{
 const f=fixture('tipseason.com');f.documents.urlList='https://tipseason.com/older|directory\n'+f.url+'|submission\nhttps://unrelated.example/form|forum';const expected=await originalLibraryAction(f.documents,'pin',{url:f.url}),r=runtimeFixture(f);try{const result=await enqueueLibraryMutation(r.runtime,{operation:{type:'pin',url:f.url}});assert.equal(result.pending,0);assert.equal(r.snapshot.documents.urlList,expected.documents.urlList);assert.equal(r.writes.length,1);assert.deepEqual(r.snapshot.documents.submissionRecords,f.documents.submissionRecords);}finally{r.store.close();}
});
test('old independent clear plan entries do not remove the retained cloud queue exclusion after a conflict',async()=>{
 const f=fixture('tipseason.com'),r=runtimeFixture(f),request=r.runtime.cloud.request;let online=false;r.runtime.cloud.request=(...args)=>{if(!online)throw Error('offline');return request(...args);};try{const result=await enqueueApplicationPlan(r.runtime,{operations:[{type:'clear_annotation',url:f.url},{type:'clear_deleted',url:f.url}]}),plan=r.store.get('applicationPlan:'+result.planId),ids=plan.items.map(item=>item.id);delete plan.kind;delete plan.items[1].dependsOn;r.store.set('applicationPlan:'+plan.id,plan);const second=r.store.get('appMutation:'+ids[1]);delete second.dependsOn;r.store.set('appMutation:'+ids[1],second);r.snapshot.documents.siteAnnotations[f.key].note='Concurrent cloud note';r.snapshot.revisions.siteAnnotations++;const before=structuredClone(r.snapshot);online=true;await flushApplicationMutations(r.runtime);const conflict=pendingApplication(r.runtime).find(item=>item.status==='conflict');assert.ok(conflict);await resolveApplicationConflict(r.runtime,{id:conflict.id,choice:'cloud',revision:r.snapshot.revisions.siteAnnotations});assert.deepEqual(r.snapshot,before);assert.equal(r.writes.length,0);assert.equal(pendingApplication(r.runtime).length,0);assert.deepEqual(r.store.get('applicationPlan:'+plan.id).items.map(item=>item.id),ids);}finally{r.store.close();}
});
test('failure to persist a clear-plan child rolls back the entire original plan before any network write',async()=>{
 const f=fixture('tipseason.com'),r=runtimeFixture(f),set=r.store.set.bind(r.store);r.store.set=(key,value)=>{if(key.startsWith('appMutation:')&&value.operation.type==='clear_deleted')throw Error('SQLite save failed');return set(key,value);};try{await assert.rejects(enqueueApplicationPlan(r.runtime,{operations:[{type:'clear_annotation',url:f.url},{type:'clear_deleted',url:f.url}]}),/SQLite save failed/);assert.equal(r.store.values('applicationPlan:').length,0);assert.equal(pendingApplication(r.runtime).length,0);assert.equal(r.writes.length,0);assert.deepEqual(r.snapshot.documents,f.documents);}finally{r.store.close();}
});
test('batch preview applies canonical exclusions to a different original alias while retaining its frozen input URL',async()=>{
 for(const domain of domains.slice(0,-1)){const f=fixture(domain);f.documents.submissionRecords={};const r=runtimeFixture(f);try{const url='https://'+domain,preview=await previewWorkbenchBatch(r.runtime,{profileIds:['p'],urls:[url]});assert.equal(preview.batch.items[0].status,'excluded',domain);assert.match(preview.batch.items[0].reason,/删除|标记/);assert.equal(preview.batch.items[0].url,url);assert.equal(r.store.get('paused'),true);assert.equal(r.store.values('task:').length,0);assert.deepEqual(r.snapshot.documents,f.documents);}finally{r.store.close();}}
});
