import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {mkdtemp,rm,readFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join,resolve,sep} from 'node:path';
import {decodeImageAsset,MAX_IMAGE_BYTES} from '../core/media-assets.mjs';import {imageFormatFixtures} from '../executor/test/image-format-fixtures.mjs';import {putDeviceMedia,readDeviceMedia} from '../cloud/worker/src/device-media.mjs';import {Store} from '../executor/src/store.mjs';import {enqueueMediaUpload,flushMediaUploads,pendingMediaUploads} from '../executor/src/media-uploads.mjs';import {workbenchScope} from '../executor/src/workbench-sync.mjs';import {applicationMutation} from '../core/application-mutation.mjs';import {materializeTaskMedia} from '../executor/src/task-media.mjs';
const sha=bytes=>createHash('sha256').update(bytes).digest('hex');
function bucketFixture(){const objects=new Map();let writes=0;return{objects,get writes(){return writes;},async get(key){const object=objects.get(key);return object?{httpMetadata:object.httpMetadata,customMetadata:object.customMetadata,arrayBuffer:async()=>object.bytes.buffer.slice(object.bytes.byteOffset,object.bytes.byteOffset+object.bytes.byteLength)}:null;},async put(key,bytes,options){if(objects.has(key))return null;writes++;objects.set(key,{...options,bytes:Buffer.from(bytes)});return{};}};}
test('original offline image queue follows durable insertion order even when IDs and equal timestamps sort in the opposite direction',()=>{
 const store=new Store(':memory:'),pair={endpoint:'https://cloud.fixture.invalid',workspaceId:'one'},scope=workbenchScope(pair);try{store.set('pair',pair);for(const assetId of ['asset-ffffffff-ffff-4fff-8fff-ffffffffffff','asset-11111111-1111-4111-8111-111111111111'])store.set('mediaUpload:'+assetId,{assetId,scope,status:'pending',at:'2026-10-06T00:00:00Z'});const first=store.get('mediaUpload:asset-ffffffff-ffff-4fff-8fff-ffffffffffff');store.set('mediaUpload:'+first.assetId,{...first,status:'uploading'});assert.deepEqual(pendingMediaUploads({store}).map(item=>item.assetId),['asset-ffffffff-ffff-4fff-8fff-ffffffffffff','asset-11111111-1111-4111-8111-111111111111']);}finally{store.close();}
});
test('original GIF and SVG logo uploads retain their original bytes and reject MIME substitutions and oversized files as client errors',()=>{
 for(const image of imageFormatFixtures){assert.deepEqual(Buffer.from(decodeImageAsset(image.dataUrl)),image.bytes);for(const mime of ['image/png','image/jpeg','image/webp',...imageFormatFixtures.filter(f=>f.mime!==image.mime).map(f=>f.mime)])assert.throws(()=>decodeImageAsset('data:'+mime+';base64,'+image.bytes.toString('base64')),error=>error.status===400&&/格式/.test(error.message));}
 const svgWithDoctype='<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"><svg xmlns="http://www.w3.org/2000/svg" width="1" height="1"/>',utf16=Buffer.concat([Buffer.from([255,254]),Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="1" height="1"/>','utf16le')]);for(const bytes of [Buffer.from(svgWithDoctype),utf16])assert.deepEqual(Buffer.from(decodeImageAsset('data:image/svg+xml;base64,'+bytes.toString('base64'))),bytes);
 for(const bytes of [Buffer.from('<html><svg/></html>'),Buffer.from('<svg xmlns="http://www.w3.org/1999/xhtml"></svg>'),Buffer.from([255,253,250])])assert.throws(()=>decodeImageAsset('data:image/svg+xml;base64,'+bytes.toString('base64')),error=>error.status===400&&/格式/.test(error.message));assert.throws(()=>decodeImageAsset('data:image/gif;base64,'+Buffer.alloc(MAX_IMAGE_BYTES+1).toString('base64')),error=>error.status===400&&/6 MB/.test(error.message));
});
test('original GIF and SVG R2 versions remain immutable and task materialization preserves MIME, extension and SHA',async()=>{
 const bucket=bucketFixture(),home=await mkdtemp(join(tmpdir(),'el-original-image-'));try{for(const [index,image]of imageFormatFixtures.entries()){const input={assetId:'asset-11111111-1111-4111-8111-11111111111'+index,profileId:'p',kind:'logo',mime:image.mime,dataUrl:image.dataUrl,sha256:sha(image.bytes),fileName:image.name};await putDeviceMedia(bucket,'one',input,{p:{}});await putDeviceMedia(bucket,'one',input,{p:{}});const asset=await readDeviceMedia(bucket,'one',input.assetId);assert.equal(asset.mime,image.mime);assert.equal(asset.sha256,input.sha256);await assert.rejects(putDeviceMedia(bucket,'one',{...input,profileId:'q'},{q:{}}),/范围/);const task={id:'original-task-'+index,runId:'original-run-'+index,profileId:'p'},runtime={home,store:{get:key=>key==='run:'+task.runId?{profileId:'p',tasks:[task.id],profile:{id:'p',fields:{'Cloud LOGO':'cloud-media://'+input.assetId}},mediaManifest:[{asset_id:input.assetId,sha256:input.sha256}]}:null},bridge:async()=>({name:image.name,dataUrl:image.dataUrl}),update(task,patch){Object.assign(task,patch);}},file=await materializeTaskMedia(runtime,task,{logoUrl:'cloud-media://'+input.assetId},'logo');assert.ok(file.endsWith(image.name.slice(image.name.lastIndexOf('.'))));assert.deepEqual(await readFile(file),image.bytes);assert.equal(task.usedMedia[0].mime,image.mime);assert.equal(task.usedMedia[0].sha256,input.sha256);}assert.equal(bucket.writes,2);}finally{assert.ok(resolve(home).startsWith(resolve(tmpdir())+sep)&&home.includes('el-original-image-'));await rm(home,{recursive:true,force:true});}
});
test('original format bytes survive SQLite restart and lost upload and profile replies without duplicate assets or lost history',async()=>{
 const home=await mkdtemp(join(tmpdir(),'el-original-format-recovery-')),path=join(home,'outbox.sqlite'),pair={endpoint:'https://cloud.fixture.invalid',workspaceId:'original'},bucket=bucketFixture(),snapshot={documents:{siteProfiles:{p:{id:'p',fields:{Name:'Original'},fieldNotes:{Name:'Keep'},mediaVersions:[{assetId:'old-version',ref:'cloud-media://old-version',kind:'logo'}]}},submissionRecords:{original:{profileId:'p',status:'success'}}},revisions:{siteProfiles:1}};let store=new Store(path),online=false,profileWrites=0;const runtime={store,cloud:{async request(route,input){if(!online)throw Error('offline');if(route==='snapshot')return structuredClone(snapshot);if(route.startsWith('media-assets/')){try{return{asset:await readDeviceMedia(bucket,'original',route.slice(13))};}catch(error){throw error;}}if(route==='media-upload'){await putDeviceMedia(bucket,'original',input,snapshot.documents.siteProfiles);throw Error('upload committed reply lost');}if(route==='profile'){profileWrites++;snapshot.documents.siteProfiles=applicationMutation(snapshot.documents,{type:'profile',profileId:input.profileId,profile:input.profile,at:'cloud'}).data;snapshot.revisions.siteProfiles++;throw Error('profile committed reply lost');}throw Error('Unexpected route '+route);}}};
 try{store.set('pair',pair);store.set('paused',true);store.set('applicationSnapshot',{scope:workbenchScope(pair),snapshot});const ids=[];for(const image of imageFormatFixtures){const result=await enqueueMediaUpload(runtime,{profileId:'p',kind:'logo',dataUrl:image.dataUrl,fileName:image.name});ids.push(result.assetId);assert.equal(store.get('mediaUpload:'+result.assetId).dataUrl,image.dataUrl);}store.close();store=new Store(path);runtime.store=store;online=true;for(let attempt=0;attempt<6;attempt++)await flushMediaUploads(runtime);assert.equal(bucket.writes,2);assert.equal(profileWrites,2);assert.equal(snapshot.documents.siteProfiles.p.mediaVersions.length,3);assert.equal(snapshot.documents.siteProfiles.p.fieldNotes.Name,'Keep');assert.equal(snapshot.documents.submissionRecords.original.status,'success');for(const [index,id]of ids.entries()){const item=store.get('mediaUpload:'+id);assert.equal(item.status,'confirmed');assert.equal(item.mime,imageFormatFixtures[index].mime);assert.equal(snapshot.documents.siteProfiles.p.mediaVersions[index+1].assetId,id);assert.equal(snapshot.documents.siteProfiles.p.mediaVersions[index+1].sha256,sha(imageFormatFixtures[index].bytes));}assert.equal(snapshot.documents.siteProfiles.p.media.logo,'cloud-media://'+ids[1]);assert.equal(store.get('paused'),true);
 }finally{store.close();assert.ok(resolve(home).startsWith(resolve(tmpdir())+sep)&&home.includes('el-original-format-recovery-'));await rm(home,{recursive:true,force:true});}
});
