import test from'node:test';import assert from'node:assert/strict';import{Store}from'../executor/src/store.mjs';import{libraryMutation,libraryMutationSatisfied}from'../core/library-mutation.mjs';
test('clear annotation matches original aliases, preserves learned form knowledge, leaves unrelated metadata and receipt intact',()=>{
 const knowledge={fields:{website:'#website'}},annotation={status:'deleted',note:'old',library:{favorite:true,groups:['high_quality']},formKnowledge:knowledge};const docs={siteAnnotations:{'target.example/form':annotation,'target.example':annotation,'other.example':{note:'keep'}},deletedSubmissionKeys:['target.example/form','other.example'],submissionRecords:{receipt:{status:'success'}}},operation={type:'clear_annotation',url:'https://target.example/form',id:'clear',at:'now'},next=libraryMutation(docs,operation);
 assert.deepEqual(next.data['target.example/form'].formKnowledge,knowledge);assert.deepEqual(next.data['target.example'],next.data['target.example/form']);assert.equal(next.data['target.example/form'].library,undefined);assert.equal(next.data['other.example'].note,'keep');assert.equal(docs.submissionRecords.receipt.status,'success');assert.equal(docs.siteAnnotations['target.example'].status,'deleted');assert.equal(libraryMutationSatisfied({...docs,siteAnnotations:next.data},operation),true);assert.equal(libraryMutationSatisfied(docs,operation),false);
 const deletion=libraryMutation(docs,{...operation,type:'clear_deleted'});assert.deepEqual(deletion.data,['other.example']);
});
test('actual transitions retain paged logs after outbox acknowledgement and isolate workspace and run filters',()=>{
 const store=new Store(':memory:');try{store.set('pair',{endpoint:'https://cloud.example',workspaceId:'one'});const task={id:'task',runId:'run',profileId:'p',url:'https://target.example',status:'pending'};const event=store.transition(task,'prepared');store.ack(event.id);assert.equal(store.pendingCount(),0);let result=store.logs({scope:'https://cloud.example|one',runId:'run'});assert.equal(result.entries[0].type,'prepared');assert.equal(result.entries[0].taskId,'task');assert.equal(store.logs({scope:'https://cloud.example|two'}).entries.length,0);assert.equal(store.logs({scope:'https://cloud.example|one',runId:'other'}).entries.length,0);
 for(let n=0;n<501;n++)store.appendLog({taskId:'task',runId:'run',message:'step '+n});result=store.logs({scope:'https://cloud.example|one'});assert.equal(result.entries.length,500);assert.ok(result.next);const remaining=store.logs({scope:'https://cloud.example|one',after:result.next});assert.equal(remaining.entries.length,2);assert.equal(remaining.next,null);assert.equal(remaining.entries[1].message,'step 500');assert.throws(()=>store.logs({scope:'scope',after:-1}),/游标/);
 }finally{store.close();}
});
