import test from 'node:test';import assert from 'node:assert/strict';import {Store} from '../executor/src/store.mjs';import {closeAcceptanceTask} from '../executor/src/acceptance-cleanup.mjs';import {mkdtemp,writeFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
test('fixed blocker cleanup persists recovery evidence before closing only registered task pages',async()=>{
 const home=await mkdtemp(join(tmpdir(),'el-cleanup-')),screenshot=join(home,'page.png');await writeFile(screenshot,'fixture evidence');const store=new Store(':memory:');
 store.set('acceptance:fixed',{combinations:[{identity:'site::p',existingTaskId:'t'}]});const task={id:'t',url:'https://site.example/submit',acceptanceId:'fixed',targetId:'owned',browserInstance:'browser',status:'needs_manual',attentionType:'human_verification',screenshot};store.set('task:t',task);
 const closed=[];const page=id=>({isClosed:()=>false,url:()=>id==='owned'?'https://site.example/submit':'https://other.example',async close(){assert.ok(store.get('task:t').recoveryCheckpoint.screenshotSha256);closed.push(id);}});const owned=page('owned'),other=page('other');
 const runtime={store,host:{startedAt:'browser'},findPage:async()=>owned,update(t,p){Object.assign(t,p);store.set('task:'+t.id,t);},context:{pages:()=>[owned,other],async newCDPSession(p){return{send:async()=>({targetInfo:{targetId:p===owned?'owned':'other'}}),detach:async()=>{}};}}};
 try{await closeAcceptanceTask(runtime,task);assert.deepEqual(closed,['owned']);assert.equal(task.recoveryCheckpoint.stage,'human_verification');assert.ok(task.tabClosedAt);}finally{store.close();await rm(home,{recursive:true,force:true});}
});
test('unknown submission retains its original page even when cleanup is requested',async()=>{
 await closeAcceptanceTask({findPage(){throw Error('must not close');}},{acceptanceId:'fixed',targetId:'t',attemptBoundary:'sent',status:'submitted_unconfirmed'});
});

test('dead-end cleanup closes original standalone run pages after a durable checkpoint and protects late evidence and shared pages',async()=>{
 for(const mode of ['normal','late-unknown','foreign-controller','shared-manual','browser-restarted','user-pause']){
  const home=await mkdtemp(join(tmpdir(),'el-deadend-cleanup-')),screenshot=join(home,'page.png');await writeFile(screenshot,'original dead-end evidence');const store=new Store(':memory:');
  const task={id:'original',runId:'original-run',profileId:'p',profileSnapshot:{id:'p'},url:'https://site.example/submit',targetId:'owned',browserInstance:'browser',version:1,controller:'executor',status:'err',attentionType:'destination_dead_end',reason:'Cannot submit',screenshot,originalDestinationDisposition:{kind:'dead_end'}};store.set('task:original',task);store.set('run:original-run',{id:'original-run',profileId:'p',tasks:['original']});store.set('paused',false);
  if(mode==='shared-manual')store.set('task:other',{id:'other',status:'needs_manual',targetId:'owned',browserInstance:'browser'});
  let closed=0;const owned={url:()=>task.url,isClosed:()=>false,close:async()=>{assert.equal(store.get('task:original').recoveryCheckpoint.stage,'destination_dead_end');closed++;}};
  const runtime={store,host:{startedAt:mode==='browser-restarted'?'new-browser':'browser'},findPage:async()=>owned,update(t,p,type){Object.assign(t,p);store.transition(t,type);},context:{pages:()=>[owned],newCDPSession:async()=>({detach:async()=>{},send:async()=>{if(mode==='late-unknown')store.set('task:original',{...store.get('task:original'),attemptBoundary:'late-boundary',status:'submitted_unconfirmed'});if(mode==='foreign-controller')store.set('task:original',{...store.get('task:original'),controller:'supervisor'});if(mode==='user-pause')store.set('paused',true);return{targetInfo:{targetId:'owned'}};}})}};
  try{if(mode==='normal'){await closeAcceptanceTask(runtime,task);assert.equal(closed,1);assert.equal(store.get('task:original').closeReason,'原任务未投稿阻塞，恢复点已持久保存');assert.ok(task.tabClosedAt);}else{await assert.rejects(()=>closeAcceptanceTask(runtime,task));assert.equal(closed,0);assert.equal(store.get('task:original').tabClosedAt,undefined);if(mode==='late-unknown')assert.equal(store.get('task:original').attemptBoundary,'late-boundary');}}finally{store.close();const {resolve,sep}=await import('node:path');const absolute=resolve(home);assert.ok(absolute.startsWith(resolve(tmpdir())+sep));await rm(absolute,{recursive:true,force:true});}
 }
});


test('original run receipt cleanup rechecks receipt, fields, verification, ownership and run membership after page awaits',async()=>{
 for(const mode of ['normal','receipt','fields','verification','confirmation','ownership','run','shared']){
  const home=await mkdtemp(join(tmpdir(),'el-run-receipt-cleanup-')),screenshot=join(home,'proof.png');await writeFile(screenshot,'original receipt proof');const store=new Store(':memory:');
  const task={id:'original',runId:'original-run',profileId:'p',profileSnapshot:{id:'p'},url:'https://site.example/submit',targetId:'owned',browserInstance:'browser',version:1,controller:'executor',status:'finished',screenshot,receipt:{evidence:'Original site receipt',confirmedBy:'manual'},manualConfirmation:{status:'confirmed'},actualSubmission:{fields:[]},cloudVerified:true};store.set('task:original',task);store.set('run:original-run',{id:'original-run',profileId:'p',tasks:['original']});store.set('paused',false);let closed=0;
  if(mode==='shared')store.set('task:other',{id:'other',status:'needs_manual',targetId:'owned',browserInstance:'browser'});
  const page={url:()=>task.url,isClosed:()=>false,close:async()=>{assert.ok(store.get('task:original').recoveryCheckpoint.screenshotSha256);closed++;}},runtime={store,host:{startedAt:'browser'},findPage:async()=>page,update(t,patch,type){Object.assign(t,patch);store.transition(t,type);},context:{pages:()=>[page],newCDPSession:async()=>({detach:async()=>{},send:async()=>{const current=store.get('task:original');if(mode==='run')store.set('run:original-run',{id:'original-run',profileId:'p',tasks:[]});else if(!['normal','shared'].includes(mode))store.set('task:original',{...current,...({receipt:{receipt:{evidence:'Changed receipt',confirmedBy:'manual'}},fields:{actualSubmission:{fields:[{name:'Name',value:'Changed'}]}},verification:{cloudVerified:false},confirmation:{manualConfirmation:{status:'pending_sync'}},ownership:{pageOwnership:'manual'}})[mode]});return{targetInfo:{targetId:'owned'}};}})}};
  try{if(mode==='normal'){await closeAcceptanceTask(runtime,task);assert.equal(closed,1);assert.ok(task.tabClosedAt);}else{await assert.rejects(()=>closeAcceptanceTask(runtime,task));assert.equal(closed,0);assert.equal(store.get('task:original').tabClosedAt,undefined);}}finally{store.close();const {resolve,sep}=await import('node:path');assert.ok(resolve(home).startsWith(resolve(tmpdir())+sep)&&home.includes('el-run-receipt-cleanup-'));await rm(home,{recursive:true,force:true});}
 }
});
