import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {PGlite} from '../executor/node_modules/@electric-sql/pglite/dist/index.js';import {aiCloudFixture} from '../executor/test/fixtures/ai-cloud.mjs';import {d1Executor} from '../cloud/worker/src/d1-executor.mjs';import {executorApi} from '../cloud/worker/src/executor-api.mjs';
for(const backend of ['d1','neon'])test('authenticated '+backend+' saves original inline logo bytes while preserving public URL, media history and other documents',async()=>{
 const profile={id:'p',name:'Original',fields:{Name:'Original',Url:'https://product.fixture.invalid',LOGO:'https://media.fixture.invalid/logo.png'},logoUrl:'https://media.fixture.invalid/logo.png',mediaVersions:[{assetId:'old',ref:'cloud-media://old'}]},documents={siteProfiles:{p:profile},submissionRecords:{keep:{status:'success',evidence:'Original receipt'}},siteAnnotations:{keep:{library:{favorite:true}}}},bytes=Buffer.from('<svg xmlns="http://www.w3.org/2000/svg"><rect width="1" height="1"/></svg>'),logoDataUrl='data:image/svg+xml;base64,'+bytes.toString('base64');let db,fixture,request,snapshot;
 try{
  if(backend==='d1'){fixture=aiCloudFixture();for(const[key,value]of Object.entries(documents))await fixture.ledger.putDocument(key,value,0);request=value=>d1Executor(value,fixture.env,'default',async()=>{throw Error('No model calls');});snapshot=async()=>{const documents={},revisions={};for(const key of ['siteProfiles','submissionRecords','siteAnnotations']){const row=await fixture.ledger.document(key);documents[key]=row.data;revisions[key]=row.revision;}return{documents,revisions};};}
  else{db=new PGlite();await db.exec(await readFile(new URL('../cloud/worker/schema.sql',import.meta.url),'utf8'));const sql=(strings,...params)=>{const query=strings.reduce((value,part,index)=>value+part+(index<params.length?'$'+(index+1):''),'');return{query,params,then:(resolve,reject)=>db.query(query,params).then(value=>value.rows).then(resolve,reject)};};sql.transaction=queries=>db.transaction(async tx=>{const rows=[];for(const query of queries)rows.push((await tx.query(query.query,query.params)).rows);return rows;});await sql`insert into externallink_workspaces(workspace_id) values('default')`;for(const[key,value]of Object.entries(documents))await sql`insert into externallink_workspace_documents(workspace_id,document_key,data) values('default',${key},${JSON.stringify(value)}::jsonb)`;snapshot=async()=>{const rows=await sql`select document_key,data,revision from externallink_workspace_documents where workspace_id='default'`;return{documents:Object.fromEntries(rows.map(row=>[row.document_key,row.data])),revisions:Object.fromEntries(rows.map(row=>[row.document_key,Number(row.revision)]))};};request=value=>executorApi(value,{APP_ACCESS_TOKEN:'fixture-admin'},sql,'default',{recordEvent:async()=>{},listSnapshot:snapshot});}
  const base='https://cloud.fixture.invalid/'+(backend==='d1'?'v2':'v1')+'/executor/',enrollment=await request(new Request(base+'devices?workspace=default',{method:'POST',headers:{Authorization:'Bearer fixture-admin'},body:'{}'}));assert.equal(enrollment.status,200);const device=await enrollment.json(),before=await snapshot(),input={profileId:'p',revision:before.revisions.siteProfiles,profile:{id:'p',logoDataUrl}},call=token=>request(new Request(base+'profile?workspace=default',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify(input)}));assert.equal((await call('wrong-token')).status,401);const response=await call(device.deviceToken);assert.equal(response.status,200,await response.clone().text());const after=await snapshot();assert.equal(after.documents.siteProfiles.p.logoDataUrl,logoDataUrl);assert.equal(after.documents.siteProfiles.p.logoUrl,profile.logoUrl);assert.deepEqual(after.documents.siteProfiles.p.mediaVersions,profile.mediaVersions);for(const key of ['submissionRecords','siteAnnotations']){assert.deepEqual(after.documents[key],before.documents[key]);assert.equal(after.revisions[key],before.revisions[key]);}
 }finally{fixture?.sqlite.close();await db?.close();}
});
