import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,readFile,rm} from 'node:fs/promises';import {join,resolve,sep} from 'node:path';import {tmpdir} from 'node:os';import {spawn} from 'node:child_process';import {once} from 'node:events';import {Store} from '../executor/src/store.mjs';import {workbenchScope} from '../executor/src/workbench-sync.mjs';
test('actual executor and workbench accept a two MiB original logo via authenticated profile HTTP and retain offline bytes after SQLite reopen',{timeout:45000},async()=>{
 const home=await mkdtemp(join(tmpdir(),'el-original-logo-http-')),services=[],pair={endpoint:'http://127.0.0.1:1',workspaceId:'fixture',storageBackend:'d1',deviceId:'fixture-device',deviceToken:'eld_fixture',localToken:'fixture-local'},profile={id:'p',name:'Original',fields:{Name:'Original',Url:'https://original.fixture.invalid'},mediaVersions:[{assetId:'old',ref:'cloud-media://old'}]},receipt={status:'success',evidence:'Original receipt'},prefix='<svg xmlns="http://www.w3.org/2000/svg">',suffix='</svg>',dataUrl='data:image/svg+xml;base64,'+Buffer.from(prefix+' '.repeat(2*1024*1024-prefix.length-suffix.length)+suffix).toString('base64');let store;
 try{
  store=new Store(join(home,'outbox.sqlite'));store.set('pair',pair);store.set('paused',true);store.set('acceptanceBatch',{status:'paused',cursor:13,count:30});store.set('applicationSnapshot',{scope:workbenchScope(pair),snapshot:{documents:{siteProfiles:{p:profile},submissionRecords:{keep:receipt}},revisions:{siteProfiles:1}}});store.close();store=null;
  for(const name of ['server.mjs','workbench-server.mjs']){const child=spawn(process.execPath,[resolve('executor/src/'+name)],{windowsHide:true,env:{...process.env,EXTERNALLINK_HOME:home,EXTERNALLINK_PORT:'0',EXTERNALLINK_WEB_PORT:'0'},stdio:['ignore','pipe','pipe']});let stderr='';child.stdout.resume();child.stderr.on('data',part=>stderr+=part);const service={child};services.push(service);for(let n=0;n<100;n++){if(child.exitCode!==null)throw Error(stderr);try{const info=JSON.parse(await readFile(join(home,name==='server.mjs'?'server.json':'workbench.json'),'utf8'));if(info.pid===child.pid){service.endpoint=info.endpoint;break;}}catch{}await new Promise(done=>setTimeout(done,50));}assert.ok(service.endpoint,'service startup');}
  for(const service of services){const response=await fetch(service.endpoint+'/profile',{method:'POST',signal:AbortSignal.timeout(12000),headers:{Authorization:'Bearer fixture-local','Content-Type':'application/json'},body:JSON.stringify({profileId:'p',revision:1,profile:{id:'p',logoDataUrl:dataUrl}})}),body=await response.json();assert.equal(response.status,200,JSON.stringify(body));assert.ok(body.pending>0);assert.equal(body.profile.logoDataUrl,dataUrl);assert.deepEqual(body.profile.mediaVersions,profile.mediaVersions);}
  for(const service of services.reverse())if(service.child.exitCode===null&&service.child.signalCode===null){const stopped=once(service.child,'exit');service.child.kill();await stopped;}
  store=new Store(join(home,'outbox.sqlite'),{readOnly:true});const pending=store.values('appMutation:').filter(item=>item.status!=='confirmed');assert.ok(pending.length);assert.ok(pending.every(item=>item.operation.profile.logoDataUrl===dataUrl));assert.deepEqual(store.get('applicationSnapshot').snapshot.documents.submissionRecords,{keep:receipt});assert.equal(store.get('paused'),true);assert.equal(store.get('acceptanceBatch').cursor,13);
 }finally{store?.close();for(const service of services)if(service.child.exitCode===null&&service.child.signalCode===null){const stopped=once(service.child,'exit');service.child.kill();await stopped;}assert.ok(resolve(home).startsWith(resolve(tmpdir())+sep)&&home.includes('el-original-logo-http-'));await rm(home,{recursive:true,force:true});}
});
