import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join,resolve,sep} from 'node:path';
import {Store} from '../executor/src/store.mjs';import {queue} from '../executor/src/shared.mjs';import {workbenchScope} from '../executor/src/workbench-sync.mjs';
import {originalCommentState,captureOriginalCommentState,restoreOriginalCommentState} from '../executor/src/original-comment-state.mjs';
import {originalSnapshotRestoreTransition} from './helpers/original-comment-restore.mjs';
const owner={profileId:'p',pageUrl:'https://article.fixture.invalid/post'},pair={endpoint:'https://cloud.fixture.invalid',workspaceId:'one'},legacyKey='commentHistory:p::'+queue.normalizeDestinationKey(owner.pageUrl);
const current=(text='原输入',tone='professional')=>({text,tone,selected:1,drafts:[{text:'第一候选',angle:'务实',chars:4},{text:'第二候选',angle:'提问',chars:4}]});
const flatten=version=>({id:version.id,at:version.at,label:version.label,...version.payload});
const normalize=version=>({label:version.label,selected:version.selected??-1,text:version.text||'',tone:version.tone,drafts:version.drafts});
const active=value=>({text:value.text,tone:value.tone,selected:value.selected,drafts:value.drafts});
function fixture(count=8){const store=new Store(':memory:');store.set('pair',pair);store.set('paused',true);const versions=Array.from({length:count},(_,index)=>({id:'old-'+index,at:'2026-10-10T00:00:00.000Z',label:'上一版',payload:current('历史 '+index)})),legacy={scope:workbenchScope(pair),profileId:owner.profileId,pageUrl:owner.pageUrl,versions};store.set(legacyKey,legacy);return{store,runtime:{store},legacy,versions};}
for(const count of [1,7,8,9])for(const mode of ['changed','same','empty','whitespace','selection_metadata_only','tone_changed'])test('original restoration transition matches complete frozen function: '+count+' stored versions / '+mode,()=>{
 const f=fixture(count);try{const versions=f.versions.slice(0,8),index=Math.min(2,versions.length-1),target=versions[index].payload;let now=current();if(mode==='same')now=structuredClone(target);if(mode==='empty')now={text:'',tone:'professional',selected:-1,drafts:[]};if(mode==='whitespace')now={text:'  ',tone:'professional',selected:-1,drafts:[]};if(mode==='selection_metadata_only')now={...structuredClone(target),selected:0};if(mode==='tone_changed')now={...structuredClone(target),tone:'casual'};
 const reference=originalSnapshotRestoreTransition(now,versions.map(flatten),index),result=restoreOriginalCommentState(f.runtime,{...owner,current:now,versionId:versions[index].id});assert.deepEqual(result.versions.map(v=>normalize(flatten(v))),reference.history.map(normalize));assert.deepEqual(active(result.active),reference.active);assert.deepEqual(result.legacyArchive,f.legacy);assert.deepEqual(f.store.get(legacyKey),f.legacy);assert.equal(f.store.get('paused'),true);if(mode==='same'||mode==='selection_metadata_only')assert.deepEqual(result.versions,versions);if(mode==='changed')assert.equal(result.versions.some(v=>v.id===versions[index].id),false);
 }finally{f.store.close();}
});
test('captures retain eight snapshots separately from active text and original comparison ignores candidate selection metadata',()=>{const f=fixture(0);try{for(let i=0;i<12;i++)captureOriginalCommentState(f.runtime,{...owner,current:current('编辑 '+i),label:'切换候选前'});const before=originalCommentState(f.runtime,owner);assert.equal(before.versions.length,8);assert.equal(before.active.text,'编辑 11');captureOriginalCommentState(f.runtime,{...owner,current:{...current('编辑 11'),selected:0},label:'切换候选前'});const after=originalCommentState(f.runtime,owner);assert.deepEqual(after.versions,before.versions);assert.equal(after.active.selected,0);captureOriginalCommentState(f.runtime,{...owner,current:current('仅当前草稿'),capture:false});assert.deepEqual(originalCommentState(f.runtime,owner).versions,before.versions);}finally{f.store.close();}});
test('raw empty text falls back only to the restored selected candidate',()=>{const f=fixture(1);try{f.legacy.versions[0].payload={...current(''),selected:1};f.store.set(legacyKey,f.legacy);const result=restoreOriginalCommentState(f.runtime,{...owner,current:current('当前编辑'),versionId:'old-0'});assert.equal(result.active.text,'第二候选');assert.equal(result.versions[0].payload.text,'当前编辑');}finally{f.store.close();}});
test('invalid or missing snapshot and failed state write leave legacy and canonical histories untouched',()=>{const f=fixture();try{const before=originalCommentState(f.runtime,owner);for(const versionId of ['',null,'missing'])assert.throws(()=>restoreOriginalCommentState(f.runtime,{...owner,current:current(),versionId}));assert.deepEqual(originalCommentState(f.runtime,owner),before);const set=f.store.set.bind(f.store);f.store.set=(id,value)=>{if(id.startsWith('originalCommentState:'))throw Error('Fixture storage failure');return set(id,value);};assert.throws(()=>restoreOriginalCommentState(f.runtime,{...owner,current:current(),versionId:'old-0'}),/storage failure/);assert.deepEqual(originalCommentState(f.runtime,owner),before);assert.deepEqual(f.store.get(legacyKey),f.legacy);}finally{f.store.close();}});
test('canonical state preserves all nine archived legacy versions and scopes through SQLite reopen',async()=>{const home=await mkdtemp(join(tmpdir(),'el-original-comment-state-')),file=join(home,'state.sqlite');let store=new Store(file);try{store.set('pair',pair);const runtime={store},legacy={scope:workbenchScope(pair),versions:Array.from({length:9},(_,i)=>({id:'v'+i,at:'2026-10-10T00:00:00Z',label:'上一版',payload:current('旧版 '+i)}))};store.set(legacyKey,legacy);restoreOriginalCommentState(runtime,{...owner,current:current('原未保存编辑'),versionId:'v3'});const before=originalCommentState(runtime,owner);assert.equal(before.legacyArchive.versions.length,9);store.close();store=new Store(file);runtime.store=store;assert.deepEqual(originalCommentState(runtime,owner),before);assert.deepEqual(store.get(legacyKey),legacy);store.set('pair',{...pair,workspaceId:'two'});assert.equal(originalCommentState(runtime,owner).versions.length,0);captureOriginalCommentState(runtime,{...owner,current:current('其他工作区')});store.set('pair',pair);assert.deepEqual(originalCommentState(runtime,owner),before);assert.equal(originalCommentState(runtime,{...owner,profileId:'q'}).versions.length,0);assert.equal(originalCommentState(runtime,{...owner,pageUrl:'https://other.fixture.invalid/post'}).versions.length,0);}finally{store.close();assert.ok(resolve(home).startsWith(resolve(tmpdir())+sep)&&home.includes('el-original-comment-state-'));await rm(home,{recursive:true,force:true});}});
