import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve,sep} from 'node:path';
import {Store} from '../executor/src/store.mjs';
import {Runtime} from '../executor/src/runtime.mjs';
import {queue} from '../executor/src/shared.mjs';
import {workbenchScope} from '../executor/src/workbench-sync.mjs';
import {freezeBatchConfig,initializeBatchPolicy} from '../executor/src/workbench-batch-policy.mjs';
import {batchJson,batchScopeRows,batchManifest} from '../core/workbench-batch-recovery.mjs';
import {freezeAcceptance} from '../executor/src/acceptance-freeze.mjs';
import {originalAgentUnavailableError,originalUnavailableReason,skipOriginalUnavailableTask,attachOriginalGroupPage,navigateOriginalGroupPage,retainOriginalUnavailablePage} from '../executor/src/original-agent-unavailable.mjs';
const hash=value=>createHash('sha256').update(batchJson(value)).digest('hex');

function fixture({offline=true,file=':memory:'}={}){
 const store=new Store(file);store.set('pair',{endpoint:'https://fixture.example',workspaceId:'original'});store.set('paused',false);store.set('offlineMode',{enabled:offline});
 const tasks=Array.from({length:4},(_,n)=>({id:'t'+n,runId:'r'+n,profileId:'p'+n,url:n<3?'https://same.example/submit':'https://other.example/submit',status:n===0?'filling':'pending',version:1,controller:'executor',workbenchBatchId:'b',profileRevision:7,profileSnapshot:{id:'p'+n,fields:{Name:'Original '+n,Url:'https://product'+n+'.example'}}}));
 Object.assign(tasks[0],{targetId:'original-target',browserInstance:'original-browser',aiTakeover:{id:'original-ai'}});
 for(const task of tasks){task.destinationKey=queue.normalizeDestinationKey(task.url);store.set('task:'+task.id,task);}
 const batch=initializeBatchPolicy({id:'b',scope:workbenchScope(store.get('pair')),...freezeBatchConfig({}, {unattended:true}),count:tasks.length,cursor:0,status:'running',cloudRecoveryVersion:1,cloudCheckpointRevision:1,items:tasks.map(task=>({identity:task.destinationKey+'::'+task.profileId,taskId:task.id,runId:task.runId,profileId:task.profileId,url:task.url,destinationKey:task.destinationKey,profileRevision:task.profileRevision,profile:task.profileSnapshot,status:task.id==='t0'?'running':'registered'}))});
 batch.configSha256=hash(batch.config);batch.scopeSha256=hash(batchScopeRows(batch));batch.unattendedState.taskBudgetUsed=1;batch.unattendedState.modelCallsUsed=4;batch.unattendedState.manualTodoIds=['t0'];batch.cloudManifest=batchManifest(batch);store.set('workbenchBatch:b',batch);
 let url=tasks[0].url;const page={url:()=>url,isClosed:()=>false,reloads:0,navigations:[],async reload(){this.reloads++;},async goto(value){url=value;this.navigations.push(value);}};
 const remote=new Map(tasks.map(task=>[task.id,structuredClone(task)])),calls=[];
 const runtime={store,controllerId:'original-controller',activeTaskIds:new Set(),host:{startedAt:'original-browser'},context:{async newCDPSession(){return{send:async()=>({targetInfo:{targetId:'original-target'}}),detach:async()=>{}};}},update:Runtime.prototype.update,findPage:async()=>page,
  cloud:{async flush(){for(const event of store.pending()){remote.set(event.taskId,structuredClone(store.get('task:'+event.taskId)));store.ack(event.id);}},async request(route,input){calls.push({route,input});if(route.startsWith('runs?runId='))return{tasks:[structuredClone([...remote.values()].find(task=>task.runId===decodeURIComponent(route.split('=')[1])))]};if(route==='lease'){const task=remote.get(input.taskId);assert.equal(task.version,input.version);task.version++;task.controllerId=input.controllerId;return{version:task.version};}throw Error('Unexpected '+route);}}};
 return{store,tasks,task:tasks[0],runtime,batch,page,remote,calls};
}
const skip=(f,assertCurrent=async()=>{})=>skipOriginalUnavailableTask(f.runtime,{task:f.task,page:f.page,result:{originalAgentUnavailable:true,reason:'Cloud worker failed'},assertCurrent});

test('unavailable reason and current-product-only skip match the actual original functions',async()=>{
 const source=execFileSync('git',['show','bd916b2944a577b160a6afcb8a7d73d263044c0c:extension/background.js'],{encoding:'utf8',maxBuffer:4*1024*1024});
 const advances=[],sandbox=vm.createContext({bumpEntryRunId(){},clearManualWaitTimer(){},clearEntryTimeout(){},log(){},broadcastTaskUpdate(){},chrome:{tabs:{sendMessage:async()=>{}}},advanceDestinationGroup:async(tab,task)=>advances.push({tab,id:task.id}),closeTab(){}});
 vm.runInContext(source.slice(source.indexOf('function skipTaskWithReason('),source.indexOf('function cancelRemainingDestinationTasks(')),sandbox);
 for(const message of ['云端失败','CLOUD unavailable','Worker overloaded','fetch failed','HTTP 503','DOM changed',''])assert.equal(originalAgentUnavailableError(Error(message)),sandbox.isAgentUnavailableError(Error(message)));
 const original={id:'t0',status:'filling'},entry={};sandbox.skipTaskWithReason(12,original,entry,originalUnavailableReason);await new Promise(resolve=>setImmediate(resolve));assert.equal(original.status,'skip');assert.equal(original.skipReason,originalUnavailableReason);assert.deepEqual(advances,[{tab:12,id:'t0'}]);assert.equal(entry.agentDone,true);
 for(const patch of [{originalTaskSyncFailure:true},{status:409},{staleTask:true},{batchPaused:true},{unattendedBudget:true}])assert.equal(originalAgentUnavailableError(Object.assign(Error('cloud failed'),patch)),false);
 const f=fixture();try{await skip(f);assert.equal(f.task.status,original.status);assert.equal(f.task.reason,original.skipReason);assert.equal(f.task.siteAutomaticObservation,undefined);assert.equal(f.task.originalGroupAdvance.nextTaskId,'t1');assert.equal(retainOriginalUnavailablePage(f.runtime,f.task),true);assert.equal(f.store.get('task:t1').status,'pending');assert.equal(f.store.get('task:t2').status,'pending');assert.equal(f.store.get('task:t3').status,'pending');const batch=f.store.get('workbenchBatch:b');assert.equal(batch.count,4);assert.equal(batch.unattendedState.taskBudgetUsed,1);assert.equal(batch.unattendedState.modelCallsUsed,4);assert.equal(batch.unattendedState.consecutiveFailures,0);assert.deepEqual(batch.unattendedState.manualTodoIds,[]);const pending=f.store.pendingCount();await skip(f);assert.equal(f.store.pendingCount(),pending);}finally{f.store.close();}
});

test('late skip cannot overwrite changed product, scope, task or unrelated batch progress',async()=>{
 for(const change of ['task','scope','profile','other-progress']){const f=fixture();let checked=0;try{const apply=()=>skip(f,async()=>{if(++checked!==2)return;if(change==='task')f.store.set('task:t0',{...f.task,status:'submitted_unconfirmed',attemptBoundary:'unknown'});if(change==='scope')f.store.set('pair',{endpoint:'https://different.example',workspaceId:'other'});if(change==='profile'){const batch=f.store.get('workbenchBatch:b');batch.items[1].profile.fields.Name='Changed';f.store.set('workbenchBatch:b',batch);}if(change==='other-progress'){const batch=f.store.get('workbenchBatch:b');batch.items[3].result='received';batch.items[3].status='complete';batch.unattendedState.modelCallsUsed=9;f.store.set('workbenchBatch:b',batch);}});if(change==='other-progress'){await apply();assert.equal(f.store.get('workbenchBatch:b').items[3].result,'received');assert.equal(f.store.get('workbenchBatch:b').unattendedState.modelCallsUsed,9);}else{await assert.rejects(apply);assert.equal(f.store.get('task:t1').status,'pending');assert.equal(f.store.pendingCount(),0);}}finally{f.store.close();}}
});

test('same frozen group takes exact original page after cloud source read and lease then reloads it',async()=>{
 const f=fixture({offline:false});try{await skip(f);const next=f.store.get('task:t1');await attachOriginalGroupPage(f.runtime,next);assert.deepEqual(f.calls.map(call=>call.route),['runs?runId=r0','lease']);assert.equal(f.store.get('task:t0').originalGroupAdvance.status,'transferred');assert.equal(next.targetId,f.task.targetId);assert.equal(next.originalGroupPage.status,'assigned');assert.equal(next.profileSnapshot.fields.Url,'https://product1.example');await navigateOriginalGroupPage(f.runtime,next,f.page,{active:()=>true});assert.equal(f.page.reloads,1);assert.equal(next.originalGroupPage.status,'ready');assert.equal(await attachOriginalGroupPage(f.runtime,next),true);assert.equal(f.store.get('workbenchBatch:b').unattendedState.taskBudgetUsed,1);assert.equal(f.store.pendingCount(),1);}finally{f.store.close();}
});

test('source or next unknown, controller, identity, scope, host and concurrent changes prevent page transfer',async()=>{
 for(const change of ['unknown-source','unknown-next','controller','profile','profile-snapshot','host','scope','active','remote-unknown','lease-race','shared-page']){const f=fixture({offline:false});try{await skip(f);await f.runtime.cloud.flush();const next=f.store.get('task:t1');if(change==='unknown-source')f.store.set('task:t0',{...f.store.get('task:t0'),attemptBoundary:'unknown'});if(change==='unknown-next'){next.attemptBoundary='unknown';f.store.set('task:t1',next);}if(change==='controller'){next.controller='supervisor';f.store.set('task:t1',next);}if(change==='profile'){next.profileId='foreign';f.store.set('task:t1',next);}if(change==='profile-snapshot'){next.profileSnapshot={fields:{Name:'Other product',Url:'https://wrong.example'}};f.store.set('task:t1',next);}if(change==='host')f.runtime.host.startedAt='replacement';if(change==='scope')f.store.set('pair',{endpoint:'https://other.example',workspaceId:'other'});if(change==='active')f.runtime.activeTaskIds.add('t0');if(change==='remote-unknown')f.remote.get('t0').attemptBoundary='remote-unknown';if(change==='lease-race'){const request=f.runtime.cloud.request;f.runtime.cloud.request=async(route,input)=>{const result=await request(route,input);if(route==='lease')f.store.set('task:t1',{...next,controller:'supervisor'});return result;};}if(change==='shared-page')f.store.set('task:foreign',{id:'foreign',targetId:f.task.targetId,browserInstance:f.task.browserInstance,status:'filling'});await assert.rejects(()=>attachOriginalGroupPage(f.runtime,next),undefined,change);assert.equal(f.store.get('task:t0').originalGroupAdvance.status,'awaiting_next');assert.equal(f.page.reloads,0);}finally{f.store.close();}}
});

test('SQLite atomic page transfer survives reopen and rolls back source, destination, outbox and checkpoint together',async()=>{
 const home=mkdtempSync(join(tmpdir(),'el-group-transfer-')),file=join(home,'state.sqlite'),f=fixture({file});try{await skip(f);await f.runtime.cloud.flush();const next=f.store.get('task:t1'),before=structuredClone(f.store.get('workbenchBatch:b')),log=f.store.appendLog.bind(f.store);f.store.appendLog=entry=>{if(entry.taskId==='t1')throw Error('disk failed');return log(entry);};await assert.rejects(()=>attachOriginalGroupPage(f.runtime,next),/disk failed/);f.store.appendLog=log;assert.equal(f.store.get('task:t0').originalGroupAdvance.status,'awaiting_next');assert.equal(f.store.get('task:t1').targetId,undefined);assert.equal(f.store.pendingCount(),0);assert.deepEqual(f.store.get('workbenchBatch:b'),before);await attachOriginalGroupPage(f.runtime,next);f.store.close();const reopened=new Store(file);try{f.runtime.store=reopened;const recovered=reopened.get('task:t1');assert.equal(await attachOriginalGroupPage(f.runtime,recovered),true);assert.equal(recovered.targetId,'original-target');reopened.set('pair',{endpoint:'https://other.example',workspaceId:'foreign'});await assert.rejects(()=>attachOriginalGroupPage(f.runtime,recovered));}finally{reopened.close();}}finally{try{f.store.close();}catch{}assert.ok(resolve(home).startsWith(resolve(tmpdir())+sep));rmSync(home,{recursive:true,force:true});}
});

test('lost transfer acknowledgment reuses durable assignment; navigation failure and missing page never create substitute tabs',async()=>{
 for(const mode of ['readback','navigation','missing']){const f=fixture();try{await skip(f);await f.runtime.cloud.flush();const next=f.store.get('task:t1');if(mode==='missing'){f.runtime.findPage=async()=>{throw Error('original page missing');};assert.equal(await attachOriginalGroupPage(f.runtime,next),false);assert.equal(next.status,'needs_manual');assert.equal(next.originalGroupPage.status,'original_page_missing');continue;}const flush=f.runtime.cloud.flush;if(mode==='readback')f.runtime.cloud.flush=async()=>{throw Error('cloud readback unavailable');};if(mode==='readback'){await assert.rejects(()=>attachOriginalGroupPage(f.runtime,next),/readback/);assert.equal(f.store.get('task:t0').originalGroupAdvance.status,'transferred');f.runtime.cloud.flush=flush;await flush();assert.equal(await attachOriginalGroupPage(f.runtime,next),true);}else await attachOriginalGroupPage(f.runtime,next);if(mode==='navigation'){f.page.reload=async()=>{throw Error('navigation failed');};assert.equal(await navigateOriginalGroupPage(f.runtime,next,f.page,{active:()=>true}),false);assert.equal(next.status,'needs_manual');assert.equal(next.reason,'无法重新进入提交入口: navigation failed');assert.equal(next.originalGroupPage.status,'navigation_failed');}assert.equal(f.store.get('workbenchBatch:b').unattendedState.taskBudgetUsed,1);}finally{f.store.close();}}
});

test('navigation boundary pauses and changed source page use goto only under original document ownership',async()=>{
 for(const mode of ['pause','goto']){const f=fixture();try{await skip(f);const next=f.store.get('task:t1');await attachOriginalGroupPage(f.runtime,next);if(mode==='pause'){const flush=f.runtime.cloud.flush;f.runtime.cloud.flush=async()=>{await flush();f.store.set('paused',true);};await assert.rejects(()=>navigateOriginalGroupPage(f.runtime,next,f.page,{active:()=>f.store.get('paused')===false}));assert.equal(f.page.reloads,0);assert.equal(next.originalGroupPage.status,'navigating');}else{await f.page.goto('https://same.example/login');await navigateOriginalGroupPage(f.runtime,next,f.page,{active:()=>true});assert.deepEqual(f.page.navigations,['https://same.example/login',next.url]);assert.equal(f.page.reloads,0);}}finally{f.store.close();}}
});

test('fixed acceptance and standalone run retain original group order and denominator without wrapping',async()=>{
 for(const mode of ['fixed','run']){const f=fixture();try{for(const task of f.tasks){delete task.workbenchBatchId;if(mode==='run'){task.runId='original';task.profileId='p0';task.profileSnapshot=structuredClone(f.task.profileSnapshot);}else task.acceptanceId='fixed';f.store.set('task:'+task.id,task);}if(mode==='run')f.store.set('run:original',{id:'original',profileId:'p0',profile:f.task.profileSnapshot,tasks:f.tasks.map(task=>task.id)});else{const frozen=freezeAcceptance(f.store,{id:'fixed',products:Object.fromEntries(f.tasks.slice(0,3).map(task=>[task.profileId,task.profileSnapshot])),profileRevision:7,sites:[f.task.url],count:3}),items={};frozen.combinations.forEach((combo,n)=>items[combo.identity]={taskId:'t'+n,runId:'r'+n});f.store.set('acceptanceExecution:fixed',{scopeSha256:frozen.sha256,items});f.store.set('acceptanceBatch',{id:'fixed',scopeSha256:frozen.sha256,count:3,cursor:0,attempts:{}});}await skip(f);assert.equal(f.task.originalGroupAdvance.nextTaskId,'t1');const next=f.store.get('task:t1');await attachOriginalGroupPage(f.runtime,next);assert.equal(next.profileId,mode==='fixed'?'p1':'p0');f.task=f.store.get('task:t2');f.task.status='filling';f.task.targetId='last-target';f.task.browserInstance='original-browser';f.store.set('task:t2',f.task);await skip(f);assert.equal(f.task.originalGroupAdvance.status,'complete');assert.equal(f.task.originalGroupAdvance.nextTaskId,null);assert.equal(f.store.get('task:t1').status,'pending');if(mode==='fixed')assert.equal(f.store.get('acceptanceBatch').count,3);}finally{f.store.close();}}
});

test('a newly received next product stays untouched while the next pending product receives the original page',async()=>{
 const f=fixture();try{await skip(f);f.store.set('task:t1',{...f.store.get('task:t1'),status:'finished',receipt:{evidence:'Independent real-site receipt'}});const next=f.store.get('task:t2');await attachOriginalGroupPage(f.runtime,next);assert.equal(next.targetId,'original-target');assert.equal(f.store.get('task:t0').originalGroupAdvance.nextTaskId,'t2');assert.equal(f.store.get('task:t1').receipt.evidence,'Independent real-site receipt');assert.equal(f.store.get('workbenchBatch:b').count,4);}finally{f.store.close();}
});

test('recovered assignment revalidates cloud source and refuses a newer unknown source without opening another page',async()=>{
 const f=fixture({offline:false});try{await skip(f);const next=f.store.get('task:t1');await attachOriginalGroupPage(f.runtime,next);f.remote.get('t0').attemptBoundary='late-cloud-unknown';await assert.rejects(()=>attachOriginalGroupPage(f.runtime,next),/云端原页来源/);assert.equal(next.targetId,'original-target');assert.equal(f.page.reloads,0);}finally{f.store.close();}
});

test('late cloud lease reply cannot overwrite a newly protected local task or switched workspace',async()=>{
 for(const mode of ['unknown','scope']){const f=fixture();try{const leaseTask=f.store.get('task:t1');f.runtime.cloud.request=async()=>{if(mode==='unknown')f.store.set('task:t1',{...leaseTask,status:'submitted_unconfirmed',attemptBoundary:'late-original-boundary'});else f.store.set('pair',{endpoint:'https://other.example',workspaceId:'other'});return{version:2};};await assert.rejects(()=>Runtime.prototype.lease.call(f.runtime,leaseTask,{online:true}),/领取期间/);assert.equal(f.store.get('task:t1').version,1);if(mode==='unknown')assert.equal(f.store.get('task:t1').attemptBoundary,'late-original-boundary');}finally{f.store.close();}}
});
