import test from 'node:test';import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';import {readFileSync} from 'node:fs';
import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join,resolve,sep} from 'node:path';import {createServer} from 'node:http';
import {Store} from '../executor/src/store.mjs';import {Cloud} from '../executor/src/cloud.mjs';import {D1Store} from '../cloud/worker/src/d1-store.mjs';import {d1Executor} from '../cloud/worker/src/d1-executor.mjs';
import {localRecoverySources,previewLocalRecovery,recoverLocalDocuments} from '../executor/src/local-recovery.mjs';import {workbenchScope} from '../executor/src/workbench-sync.mjs';
import {backupKeys} from '../core/application-backup.mjs';
test('original local documents recover through real HTTP, device authentication, D1 CAS and independent readback with a dropped write response',async()=>{
 const home=await mkdtemp(join(tmpdir(),'el-recovery-http-')),sql=new DatabaseSync(':memory:');let local,server;
 try{
 for(const file of ['0001_d1_storage.sql','0002_d1_executor.sql'])sql.exec(readFileSync(new URL('../cloud/worker/migrations/'+file,import.meta.url),'utf8'));
 const db={prepare(text){let args=[];return{bind(...values){args=values;return this;},first:async()=>sql.prepare(text).get(...args)||null,all:async()=>({results:sql.prepare(text).all(...args)}),run:async()=>{const q=sql.prepare(text);return q.columns().length?{results:q.all(...args),meta:{changes:0}}:{results:[],meta:{changes:q.run(...args).changes}};}};},async batch(statements){sql.exec('BEGIN');try{const values=[];for(const statement of statements)values.push(await statement.run());sql.exec('COMMIT');return values;}catch(error){sql.exec('ROLLBACK');throw error;}}};
 const objects=new Map(),bucket={head:async key=>objects.has(key)?{}:null,put:async(key,value,meta)=>objects.set(key,{bytes:new Uint8Array(value),meta}),get:async key=>{const value=objects.get(key);return value?{arrayBuffer:async()=>value.bytes.slice().buffer,httpMetadata:value.meta?.httpMetadata}:null;}};
 const env={LEDGER_DB:db,MEDIA_BUCKET:bucket,APP_ACCESS_TOKEN:'fixture-admin'},remote=new D1Store(db,bucket,'default'),receipt={taskId:'original-task',profileId:'p',status:'success',evidence:'Original receipt'};
 for(const [key,value]of Object.entries({siteProfiles:{p:{id:'p',name:'Cloud P',fields:{Name:'Cloud P'}}},siteAnnotations:{},submissionRecords:{'protected.example::p':receipt}}))await remote.putDocument(key,value,0);
 let dropped=false;const writes=[];
 server=createServer(async(req,res)=>{let body='';for await(const bytes of req)body+=bytes;const url=new URL(req.url,'http://cloud.test'),input=body?JSON.parse(body):null,write=url.pathname.endsWith('/library');if(write)writes.push(input.operation.id);const response=await d1Executor(new Request(url,{method:req.method,headers:req.headers,body:req.method==='GET'?undefined:body}),env,'default',async()=>({}));const output=await response.text();if(write&&!dropped&&response.ok){dropped=true;req.socket.destroy();return;}res.writeHead(response.status,{'Content-Type':'application/json'});res.end(output);});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 const endpoint='http://127.0.0.1:'+server.address().port,enrollment=await fetch(endpoint+'/v2/executor/devices',{method:'POST',headers:{Authorization:'Bearer fixture-admin','Content-Type':'application/json'},body:JSON.stringify({name:'isolated recovery'})});assert.equal(enrollment.status,200);const device=await enrollment.json(),pair={endpoint,workspaceId:'default',storageBackend:'d1',deviceToken:device.deviceToken};
 const backupRoot=join(home,'backups'),folder=join(backupRoot,'original-local');await mkdir(folder,{recursive:true});local=new Store(join(home,'outbox.sqlite'));local.set('pair',pair);local.set('paused',true);local.set('acceptanceBatch',{status:'paused',cursor:13,count:30});
 const documents={siteProfiles:{p:{id:'p',name:'Original P',fields:{Name:'Original P'},learnedFieldMappings:{name:'Name'}}},siteAnnotations:{'target.example':{library:{favorite:true,groups:['high_quality']},formKnowledge:{name:'#name'}}},submissionRecords:{'protected.example::p':{status:'failed'},'old.example::p':{profileId:'p',status:'success',evidence:'Older receipt'}},cfgName:'Original contact',cfgEmail:'owner@example.com',cfgCommentTemplate:'Original comment',urlList:'https://target.example/submit',activeSiteId:'p',selectedSiteIds:['p'],deletedSubmissionKeys:['removed.example'],sheetTableData:{entries:[{link:'https://target.example/submit',metrics:{dr:88}}]},domainBlacklist:['blocked.example'],targetFilters:{minDr:60},domainMetricsCache:{'target.example':{ageMonths:20}},linkMonitorResults:{},linkMonitorSchedule:{enabled:false,intervalHours:24},autoSubmitStandardWpComments:false,autoSubmitDirectoryListings:false,submissionSchemaVersion:2,timelineSchemaVersion:2,submissionTimeline:{'old.example::p':[{id:'original-event',destinationKey:'old.example',profileId:'p',occurredAt:'2026-09-30T00:00:00Z',type:'note',note:'Original history'}]}};assert.deepEqual(Object.keys(documents).sort(),[...backupKeys].sort());await writeFile(join(folder,'snapshot.json'),JSON.stringify({scope:workbenchScope(pair),documents}));
 const runtime={home,backupRoot,store:local,cloud:new Cloud(pair),status:()=>({tasks:[],paused:true,busy:false,pendingEvents:0})},listing=await localRecoverySources(runtime),preview=await previewLocalRecovery(runtime,{sourceId:listing.sources.find(s=>s.id).id}),input={id:preview.preview.id,confirmation:'恢复所选本机资料'};
 let result=await recoverLocalDocuments(runtime,input);assert.ok(result.remaining);assert.match(result.error,/云端连接失败/);const originalPlan=local.get('localRecoveryPlan:'+input.id).applicationPlanId,ids=local.get('applicationPlan:'+originalPlan).items.map(i=>i.id);
 local.close();local=new Store(join(home,'outbox.sqlite'));runtime.store=local;result=await recoverLocalDocuments(runtime,input);assert.equal(result.remaining,0);assert.deepEqual(local.get('applicationPlan:'+originalPlan).items.map(i=>i.id),ids);assert.equal(writes.length,new Set(writes).size);
 const proof=await runtime.cloud.request('snapshot');assert.deepEqual(proof.documents.submissionRecords['protected.example::p'],receipt);assert.equal(proof.documents.siteAnnotations['target.example'].library.favorite,true);assert.equal(proof.documents.siteProfiles.p.learnedFieldMappings.name,'Name');assert.equal(proof.documents.cfgName,'Original contact');assert.equal(local.get('acceptanceBatch').cursor,13);assert.equal(sql.prepare('SELECT count(*) n FROM executor_runs').get().n,0);assert.equal(sql.prepare('SELECT count(*) n FROM recovery_objects').get().n,writes.length*2);
 for(const key of backupKeys.filter(key=>!['submissionRecords','submissionTimeline'].includes(key)))assert.deepEqual(proof.documents[key],documents[key],key);assert.equal(proof.documents.submissionTimeline['old.example::p'][0].note,'Original history');assert.equal(local.get('applicationPlan:'+originalPlan).items.length,21);
 }finally{local?.close();if(server?.listening)await new Promise(resolve=>server.close(resolve));sql.close();assert.ok(resolve(home).startsWith(resolve(tmpdir())+sep)&&home.includes('el-recovery-http-'));await rm(home,{recursive:true,force:true});}
});
