import test from 'node:test';import assert from 'node:assert/strict';import{mkdtemp,rm}from'node:fs/promises';import{tmpdir}from'node:os';import{join,resolve,sep}from'node:path';
import{Store}from'../executor/src/store.mjs';import{Runtime}from'../executor/src/runtime.mjs';import{workbenchScope}from'../executor/src/workbench-sync.mjs';
import{prepareIndexNotification,notifyIndexNow}from'../executor/src/index-notification.mjs';
import{libraryMutation}from'../core/library-mutation.mjs';import{applicationSettingKeys}from'../core/application-preferences.mjs';import{localRecoveryDocuments}from'../core/local-recovery.mjs';import{exportApplicationBackup,mergeApplicationBackup,applicationBackupFragment,validateApplicationBackup}from'../core/application-backup.mjs';
function fixture(store=new Store(':memory:'),enabled=true){store.set('pair',{endpoint:'https://cloud.example',workspaceId:'original'});store.set('paused',true);store.set('acceptanceBatch',{status:'paused',cursor:13,count:30});const scope=workbenchScope(store.get('pair'));store.set('applicationSnapshot',{scope,snapshot:{documents:{cfgPingIndex:enabled},revisions:{}}});const runtime={store,update(task,patch,type){Object.assign(task,patch);store.transition(task,type);}},task={id:'original-task',runId:'original-run',url:'https://target.example/submit?q=one%20two',profileId:'p',status:'finished',cloudVerified:true,receipt:{evidence:'Original receipt',publicationStatus:'pending_moderation'}};task.indexNowNotification=prepareIndexNotification(runtime,task);store.set('task:'+task.id,task);return{runtime,task,store};}
test('original IndexNow preference survives settings, backup fragments, merge, export and local recovery',()=>{
 const source={siteProfiles:{p:{id:'p',name:'P'}},submissionRecords:{},cfgPingIndex:false},raw={format:'externallink-submission-backup',...source};assert.ok(applicationSettingKeys.includes('cfgPingIndex'));assert.equal(libraryMutation(source,{type:'settings',key:'cfgPingIndex',value:true,id:'change',at:'2026-10-05T00:00:00Z'}).data,true);assert.equal(exportApplicationBackup(source).cfgPingIndex,false);assert.equal(mergeApplicationBackup({},raw).cfgPingIndex,false);assert.equal(applicationBackupFragment(raw,'cfgPingIndex').cfgPingIndex,false);assert.equal(localRecoveryDocuments(source).cfgPingIndex,false);
 for(const value of ['false',1,null,{},[]]){assert.throws(()=>libraryMutation(source,{type:'settings',key:'cfgPingIndex',value,id:'bad',at:'now'}),/设置/);assert.throws(()=>validateApplicationBackup({...raw,cfgPingIndex:value}),/设置/);assert.throws(()=>localRecoveryDocuments({...source,cfgPingIndex:value}),/设置|格式/);}
});
test('a confirmed new receipt notifies the original URL once, saves intent first and survives SQLite restart',async()=>{
 const home=await mkdtemp(join(tmpdir(),'el-index-notification-')),file=join(home,'outbox.sqlite');let store=new Store(file);const f=fixture(store);let calls=0;const before=structuredClone(f.task.receipt);
 try{f.runtime.indexNowFetch=async value=>{calls++;const url=new URL(value);assert.equal(url.origin,'https://www.bing.com');assert.equal(url.pathname,'/indexnow');assert.equal(url.searchParams.get('url'),f.task.url);assert.equal(url.searchParams.get('key'),'ea4b5c1e2f3a4b5c6d7e8f9a0b1c2d3e');assert.equal(store.get('task:original-task').indexNowNotification.status,'sending');return new Response(null,{status:200});};await notifyIndexNow(f.runtime,f.task);assert.equal(f.task.indexNowNotification.status,'received');assert.equal(calls,1);assert.deepEqual(f.task.receipt,before);store.close();store=new Store(file);f.runtime.store=store;await notifyIndexNow(f.runtime,store.get('task:original-task'));assert.equal(calls,1);assert.equal(store.get('acceptanceBatch').cursor,13);assert.equal(store.get('paused'),true);}
 finally{store.close();assert.ok(resolve(home).startsWith(resolve(tmpdir())+sep)&&home.includes('el-index-notification-'));await rm(home,{recursive:true,force:true});}
});
test('disabled, old historical receipts and unconfirmed receipts do not notify',async()=>{
 const f=fixture(undefined,false);try{let calls=0;f.runtime.indexNowFetch=async()=>{calls++;return new Response(null,{status:200});};await notifyIndexNow(f.runtime,f.task);assert.equal(f.task.indexNowNotification.status,'disabled');delete f.task.indexNowNotification;f.store.set('task:'+f.task.id,f.task);await notifyIndexNow(f.runtime,f.task);const cached=f.store.get('applicationSnapshot');cached.snapshot.documents.cfgPingIndex=true;f.store.set('applicationSnapshot',cached);f.task.indexNowNotification=prepareIndexNotification(f.runtime,f.task);f.task.cloudVerified=false;f.store.set('task:'+f.task.id,f.task);await notifyIndexNow(f.runtime,f.task);assert.equal(f.task.indexNowNotification.status,'pending');assert.equal(calls,0);}finally{f.store.close();}
});
test('IndexNow validation, rejection and uncertain responses never alter receipts or report publication',async()=>{
 for(const [reply,status]of [[202,'validation_pending'],[403,'rejected'],[429,'rejected'],['lost','uncertain']]){const f=fixture();try{let calls=0;f.runtime.indexNowFetch=async()=>{calls++;if(reply==='lost')throw Error('network response lost');return new Response(null,{status:reply});};await notifyIndexNow(f.runtime,f.task);assert.equal(f.task.indexNowNotification.status,status);await notifyIndexNow(f.runtime,f.task);assert.equal(calls,1);assert.equal(f.task.receipt.publicationStatus,'pending_moderation');assert.equal(f.task.receipt.evidence,'Original receipt');}finally{f.store.close();}}
});
test('a persisted sending state is uncertain after restart and concurrent requests share the same notification',async()=>{
 const f=fixture();try{let release,calls=0;f.runtime.indexNowFetch=async()=>{calls++;await new Promise(resolve=>release=resolve);return new Response(null,{status:200});};const first=notifyIndexNow(f.runtime,f.task);while(!release)await new Promise(resolve=>setTimeout(resolve,1));const second=notifyIndexNow(f.runtime,f.task);release();await Promise.all([first,second]);assert.equal(calls,1);f.task.indexNowNotification.status='sending';f.store.set('task:'+f.task.id,f.task);await notifyIndexNow(f.runtime,f.task);assert.equal(f.task.indexNowNotification.status,'uncertain');assert.equal(calls,1);}finally{f.store.close();}
});
test('workspace and original URL identity changes cannot reuse the notification',async()=>{
 const f=fixture();try{let calls=0;f.runtime.indexNowFetch=async()=>{calls++;return new Response(null,{status:200});};f.store.set('pair',{endpoint:'https://cloud.example',workspaceId:'other'});await notifyIndexNow(f.runtime,f.task);assert.equal(calls,0);f.store.set('pair',{endpoint:'https://cloud.example',workspaceId:'original'});f.task.url='https://replacement.example';await notifyIndexNow(f.runtime,f.task);assert.equal(calls,0);}finally{f.store.close();}
});
test('production synchronization sends only a newly scheduled confirmed receipt and persists its event',async()=>{
 const f=fixture();try{const runtime=Object.assign(Object.create(Runtime.prototype),f.runtime);let requests=0,flushes=0;runtime.indexNowFetch=async()=>{requests++;return new Response(null,{status:202});};Object.defineProperty(runtime,'cloud',{value:{async request(route){assert.equal(route,'snapshot');return{documents:{cfgPingIndex:true}};},async flush(store){flushes++;for(const event of store.pending())store.ack(event.id);}}});await runtime.synchronize();assert.equal(requests,1);assert.equal(f.store.get('task:original-task').indexNowNotification.status,'validation_pending');assert.ok(flushes>=2);assert.equal(f.store.pendingCount(),0);assert.equal(f.store.get('paused'),true);}finally{f.store.close();}
});
test('the latest cloud disable setting overrides an older cached enabled setting before notification',async()=>{
 const f=fixture();try{const runtime=Object.assign(Object.create(Runtime.prototype),f.runtime);let calls=0;runtime.indexNowFetch=async()=>{calls++;return new Response(null,{status:200});};Object.defineProperty(runtime,'cloud',{value:{async request(){return{documents:{cfgPingIndex:false}};},async flush(store){for(const event of store.pending())store.ack(event.id);}}});await runtime.synchronize();assert.equal(calls,0);assert.equal(f.store.get('task:'+f.task.id).indexNowNotification.status,'disabled');assert.equal(f.store.get('task:'+f.task.id).receipt.evidence,'Original receipt');}finally{f.store.close();}
});
