import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {mkdtemp,rm} from 'node:fs/promises';
import {join,resolve,sep} from 'node:path';
import {tmpdir} from 'node:os';
import {Store} from '../executor/src/store.mjs';
import {Runtime} from '../executor/src/runtime.mjs';
import {workbenchScope} from '../executor/src/workbench-sync.mjs';
import {batchScopeRows} from '../core/workbench-batch-recovery.mjs';
import {parkedResumeIntent,selectParkedResume} from '../executor/src/parked-task-resume.mjs';
import {hasManualSubmissionConsent} from '../executor/src/submission-preferences.mjs';
import {nextWorkbenchTask} from '../executor/src/workbench-features.mjs';
import {requestExecutionPause,resumeExecution} from '../executor/src/execution-lifecycle.mjs';
import {freezeBatchConfig} from '../executor/src/workbench-batch-policy.mjs';
import {originalUnattended as U} from '../core/original-batch-config.mjs';

const hash=value=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
function fixture(file=':memory:'){
 const store=new Store(file),runtime=new Runtime(store,'unused-parked-test-home'),scope='https://cloud.example|original',profile={id:'p',name:'Original Product',fields:{Name:'Original Product',Url:'https://product.example'}},task={id:'original',runId:'original-run',workbenchBatchId:'b',profileId:'p',profileRevision:7,profileSnapshot:profile,targetId:'original-page',browserInstance:'original-browser',controller:'executor',status:'pending',url:'https://directory.example/submit',fillOnlyRun:true},batch={id:'b',scope,status:'running',count:1,cursor:1,config:{fillOnly:true},items:[{taskId:task.id,identity:'original-combination',url:task.url,status:'complete'}]};
 batch.scopeSha256=hash(batchScopeRows(batch));batch.configSha256=hash(batch.config);store.set('pair',{endpoint:'https://cloud.example',workspaceId:'original'});store.set('paused',false);store.set('activeWorkbenchBatch','b');store.set('workbenchBatch:b',batch);runtime.host={startedAt:'original-browser'};
 task.originalResume=parkedResumeIntent(task,{execution:{kind:'workbench',id:'b',scope,scopeSha256:batch.scopeSha256,configSha256:batch.configSha256},pageUrl:task.url,frameUrl:task.url,documentId:27,pauseAt:''});store.set('task:'+task.id,task);store.set('run:original-run',{id:'original-run',profile,tasks:[task.id],mediaManifest:[{asset_id:'original-logo',sha256:'original-sha'}]});store.set('task:unknown',{id:'unknown',status:'submitted_unconfirmed',attemptBoundary:'keep-original'});
 let pages=0,leases=0;runtime.findPage=async()=>{pages++;throw Error('Unexpected original page access');};runtime.lease=async()=>{leases++;};return{store,runtime,task,batch,profile,counts:()=>({pages,leases})};
}
test('original parked continuation and frozen media survive an atomic SQLite checkpoint and reopen',async()=>{
 const folder=await mkdtemp(join(tmpdir(),'el-parked-reopen-'));let store;try{const f=fixture(join(folder,'outbox.sqlite'));store=f.store;const request=structuredClone(f.task.originalResume),run=store.get('run:original-run');store.transition(f.task,'original_resume_queued');store.close();store=new Store(join(folder,'outbox.sqlite'));assert.deepEqual(store.get('task:original').originalResume,request);assert.deepEqual(store.get('run:original-run'),run);assert.equal(store.get('task:unknown').attemptBoundary,'keep-original');assert.equal(store.get('workbenchBatch:b').cursor,1);assert.equal(store.pending()[0].state.originalResume.id,request.id);}finally{store?.close();assert.ok(resolve(folder).startsWith(resolve(tmpdir())+sep)&&folder.includes('el-parked-reopen-'));await rm(folder,{recursive:true,force:true});}
});
test('stale workspace pause controller product receipt and batch configuration deny parked dispatch before page access',async()=>{
 for(const change of [f=>f.store.set('paused',true),f=>f.store.set('executionStopped',{at:'stopped'}),f=>f.store.set('executionPaused',{at:'new-user-pause'}),f=>f.store.set('pair',{endpoint:'https://other-cloud.example',workspaceId:'other'}),f=>f.task.controller='supervisor',f=>f.task.profileSnapshot.fields.Name='Changed Product',f=>f.task.attemptBoundary='unknown',f=>f.task.receipt={evidence:'keep-receipt'},f=>{f.batch.config.fillOnly=false;f.batch.configSha256=hash(f.batch.config);f.store.set('workbenchBatch:b',f.batch);}]){const f=fixture();try{change(f);f.store.set('task:original',f.task);const before=f.store.pendingCount();assert.equal(await selectParkedResume(f.runtime,f.store.get('workbenchBatch:b')),null);assert.deepEqual(f.counts(),{pages:0,leases:0});assert.equal(f.store.pendingCount(),before);assert.equal(f.store.get('task:unknown').attemptBoundary,'keep-original');}finally{f.store.close();}}
});
test('parallel manual permission is effective only for a dispatched original identity and unchanged scope',()=>{
 const f=fixture();try{f.task.originalResume.kind='manual';f.task.manualSubmissionConsent={scope:workbenchScope(f.store.get('pair')),...Object.fromEntries(['runId','profileId','targetId','browserInstance','profileRevision'].map(key=>[key,f.task[key]]))};for(const status of ['preparing','queued','dispatching']){f.task.originalResume.status=status;f.store.set('task:original',f.task);assert.equal(hasManualSubmissionConsent(f.runtime,f.task),false);}f.task.originalResume.status='dispatched';f.store.set('task:original',f.task);assert.equal(hasManualSubmissionConsent(f.runtime,f.task),true);f.task.profileSnapshot.fields.Name='Changed after dispatch';f.store.set('task:original',f.task);assert.equal(hasManualSubmissionConsent(f.runtime,f.task),false);assert.equal(f.store.get('singleTaskId'),null);}finally{f.store.close();}
});
test('a queued parked task locks its original destination while another destination remains dispatchable',async()=>{
 const f=fixture();try{const batch=f.store.get('workbenchBatch:b');batch.items.push({taskId:'same-destination',identity:'next-product',url:f.task.url,status:'registered'},{taskId:'other',identity:'other-destination',url:'https://other-directory.example/submit',status:'registered'},{taskId:'busy',identity:'current-worker',url:f.task.url,status:'running'});batch.count=4;batch.scopeSha256=hash(batchScopeRows(batch));f.task.originalResume.execution.scopeSha256=batch.scopeSha256;f.store.set('task:original',f.task);f.store.set('workbenchBatch:b',batch);for(const id of ['same-destination','other']){const item=batch.items.find(item=>item.taskId===id);f.store.set('task:'+id,{id,runId:'run-'+id,profileId:'p',workbenchBatchId:'b',url:item.url,status:'pending',controller:'executor',profileSnapshot:f.profile});}f.runtime.activeTaskIds=new Set(['busy']);f.runtime.context={};const selected=await nextWorkbenchTask(f.runtime,{single:false});assert.equal(selected.id,'other');assert.equal(f.counts().pages,0);assert.equal(f.store.get('task:original').originalResume.status,'queued');assert.equal(f.store.get('workbenchBatch:b').items[1].status,'registered');assert.equal(f.store.get('workbenchBatch:b').count,4);assert.equal(f.store.get('singleTaskId'),null);}finally{f.store.close();}
});

test('a pending manual skip denies original parked dispatch before page access and retains the original request',async()=>{
 const f=fixture();try{const request=structuredClone(f.task.originalResume);f.store.set('manualSkipPending:original',{id:'original-skip',scope:f.batch.scope,batchId:'b',taskId:f.task.id,runId:f.task.runId,stage:'requested'});assert.equal(await selectParkedResume(f.runtime,f.batch),null);assert.deepEqual(f.counts(),{pages:0,leases:0});assert.deepEqual(f.store.get('task:original').originalResume,request);assert.equal(f.store.get('task:unknown').attemptBoundary,'keep-original');}finally{f.store.close();}
});

test('the original frozen product identity survives JSONB key order without accepting changed content',()=>{
 const f=fixture();try{f.task.originalResume.kind='manual';f.task.originalResume.status='dispatched';f.task.manualSubmissionConsent={scope:f.batch.scope,...Object.fromEntries(['runId','profileId','targetId','browserInstance','profileRevision'].map(key=>[key,f.task[key]]))};f.task.profileSnapshot=Object.fromEntries(Object.entries(f.task.profileSnapshot).reverse().map(([key,value])=>[key,key==='fields'?Object.fromEntries(Object.entries(value).reverse()):value]));f.store.set('task:original',f.task);assert.equal(hasManualSubmissionConsent(f.runtime,f.task),true);f.task.profileSnapshot.fields.Url='https://changed.example';f.store.set('task:original',f.task);assert.equal(hasManualSubmissionConsent(f.runtime,f.task),false);}finally{f.store.close();}
});

test('explicit user resume keeps a previously queued original task with a full unattended budget and does not revive changed requests',async()=>{
 for(const changed of [false,true]){const f=fixture();try{Object.assign(f.batch,freezeBatchConfig({unattendedPreferences:{enabled:true,hours:1,tasks:1,manualTabs:20}},{unattended:true}));f.batch.unattendedState=U.createCheckpoint(f.batch.config,Date.now(),{taskBudgetUsed:1,modelCallsUsed:7});f.batch.items.push({taskId:'next',identity:'unstarted',url:'https://next.example',status:'registered'});f.batch.count=2;f.batch.scopeSha256=hash(batchScopeRows(f.batch));Object.assign(f.task.originalResume.execution,{scopeSha256:f.batch.scopeSha256,configSha256:f.batch.configSha256});f.store.set('task:original',f.task);f.store.set('workbenchBatch:b',f.batch);const before=structuredClone(f.batch.unattendedState),originalRequest=f.task.originalResume.id;requestExecutionPause(f.runtime);assert.deepEqual(f.store.get('workbenchBatch:b').pausedParkedResumes,[{taskId:f.task.id,requestId:originalRequest}]);if(changed){f.task.originalResume.id='replacement';f.store.set('task:original',f.task);}f.runtime.tick=()=>{};f.runtime.synchronize=async()=>{for(const event of f.store.pending())f.store.ack(event.id);};Object.defineProperty(f.runtime,'cloud',{value:{flush:f.runtime.synchronize}});if(changed){await assert.rejects(resumeExecution(f.runtime,{expectedBatchId:'b'}),/预算/);assert.equal(f.store.get('paused'),true);}else{await resumeExecution(f.runtime,{expectedBatchId:'b'});assert.equal(f.store.get('paused'),false);assert.equal(f.store.get('task:original').originalResume.id,originalRequest);assert.equal(f.store.get('task:original').originalResume.pauseAt,f.store.get('executionPaused').at);assert.equal(f.store.get('singleTaskId'),null);}const current=f.store.get('workbenchBatch:b').unattendedState;for(const key of ['taskBudgetUsed','modelCallsUsed','runDeadlineAt'])assert.equal(current[key],before[key]);assert.equal(f.store.get('task:unknown').attemptBoundary,'keep-original');assert.equal(f.store.get('workbenchBatch:b').count,2);}finally{f.store.close();}}
});
