import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join,resolve,sep} from 'node:path';
import {applicationMutation,applicationMutationSatisfied} from '../core/application-mutation.mjs';import {applicationModel} from '../core/application-model.mjs';import {applicationData} from '../executor/src/application-data.mjs';import {Store} from '../executor/src/store.mjs';import {workbenchScope} from '../executor/src/workbench-sync.mjs';import {enqueueLibraryMutation,flushApplicationMutations,overlayApplication} from '../executor/src/application-mutations.mjs';import {exportApplicationBackup,mergeApplicationBackup} from '../core/application-backup.mjs';
const original=()=>({siteProfiles:{p:{id:'p',name:'First',sortIndex:0,url:'https://first.example',fields:{Name:'First',Url:'https://first.example'}},q:{id:'q',name:'Second',sortIndex:1,url:'https://second.example',fields:{Name:'Second',Url:'https://second.example'},mediaVersions:[{assetId:'original'}]},old:{id:'old',archived:true,sortIndex:2}},activeSiteId:'q',selectedSiteIds:['q','p'],submissionRecords:{keep:{profileId:'p',status:'success',evidence:'Original receipt'}}});
const operation=(key,value)=>({type:'profile_selection',key,value,id:'original-selection-'+key,at:'2026-10-06T00:00:00Z'});
test('original current site and batch choices reach application readback without rewriting raw documents',async()=>{
 const documents=original(),before=structuredClone(documents),store=new Store(':memory:'),pair={endpoint:'https://fixture.invalid',workspaceId:'original'};
 try{store.set('pair',pair);store.set('applicationSnapshot',{scope:workbenchScope(pair),snapshot:{documents,revisions:{siteProfiles:1,activeSiteId:4,selectedSiteIds:5}}});const runtime={store,status:()=>({tasks:[],paused:true,busy:false,pendingEvents:0})},data=await applicationData(runtime);assert.deepEqual(data.model.profileSelection,{activeSiteId:'q',selectedSiteIds:['q','p']});assert.deepEqual(documents,before);assert.equal(store.get('applicationSnapshot').snapshot.documents.activeSiteId,'q');}finally{store.close();}
});
test('original selection fallback uses saved site order and excludes missing or archived identities without deleting historical selections',()=>{
 const docs=original();docs.activeSiteId='missing';docs.selectedSiteIds=['missing','old'];const before=structuredClone(docs);assert.deepEqual(applicationModel({documents:docs}).profileSelection,{activeSiteId:'p',selectedSiteIds:['p']});assert.deepEqual(docs,before);docs.activeSiteId='q';docs.selectedSiteIds=[];assert.deepEqual(applicationModel({documents:docs}).profileSelection,{activeSiteId:'q',selectedSiteIds:['q']});docs.siteProfiles={};assert.deepEqual(applicationModel({documents:docs}).profileSelection,{activeSiteId:'',selectedSiteIds:[]});
});
test('changing original selection writes only its own document and confirms empty batch choice without altering profiles or receipts',()=>{
 const docs=original(),before=structuredClone(docs);for(const [key,value]of [['activeSiteId','p'],['selectedSiteIds',['p']],['selectedSiteIds',[]]]){const op=operation(key,value),change=applicationMutation(docs,op);assert.equal(change.key,key);assert.deepEqual(change.data,value);assert.ok(applicationMutationSatisfied({...docs,[key]:change.data},op));}assert.deepEqual(docs,before);
});
test('selection rejects unowned archived duplicate or unsafe product identities and unsupported document keys',()=>{
 const docs=original();for(const [key,value]of [['activeSiteId','missing'],['activeSiteId','old'],['activeSiteId','constructor'],['activeSiteId',7],['activeSiteId',''],['selectedSiteIds',['q','q']],['selectedSiteIds',['missing']],['selectedSiteIds',['old']],['selectedSiteIds','q'],['siteProfiles',['q']]])assert.throws(()=>applicationMutation(docs,operation(key,value)),e=>e.status===400);
});
test('offline selections survive SQLite restart and lost replies using original IDs with the original pause and receipt',async()=>{
 const home=await mkdtemp(join(tmpdir(),'el-original-selection-')),path=join(home,'outbox.sqlite'),pair={endpoint:'https://fixture.invalid',workspaceId:'original'},scope=workbenchScope(pair),snapshot={documents:original(),revisions:{siteProfiles:1,activeSiteId:4,selectedSiteIds:5}};let store=new Store(path),online=false,writes=0;
 const runtime={store,cloud:{async request(route,input){if(!online)throw Error('offline');if(route==='snapshot')return structuredClone(snapshot);assert.equal(route,'library');writes++;const change=applicationMutation(snapshot.documents,input.operation);snapshot.documents[change.key]=change.data;snapshot.revisions[change.key]++;throw Error('selection committed response lost');}}};
 try{store.set('pair',pair);store.set('paused',true);store.set('applicationSnapshot',{scope,snapshot});const active=await enqueueLibraryMutation(runtime,{operation:operation('activeSiteId','p')}),selected=await enqueueLibraryMutation(runtime,{operation:operation('selectedSiteIds',['p'])});assert.equal(writes,0);assert.equal(overlayApplication(runtime,snapshot).documents.activeSiteId,'p');store.close();store=new Store(path);runtime.store=store;online=true;for(let i=0;i<4;i++)await flushApplicationMutations(runtime);assert.equal(writes,2);for(const id of [active.id,selected.id])assert.equal(store.get('appMutation:'+id).status,'confirmed');assert.deepEqual(snapshot.documents.selectedSiteIds,['p']);assert.equal(snapshot.documents.activeSiteId,'p');assert.equal(snapshot.documents.submissionRecords.keep.evidence,'Original receipt');assert.deepEqual(snapshot.documents.siteProfiles,original().siteProfiles);assert.equal(store.get('paused'),true);}finally{store.close();assert.ok(resolve(home).startsWith(resolve(tmpdir())+sep)&&home.includes('el-original-selection-'));await rm(home,{recursive:true,force:true});}
});
test('restored original selection stays usable and concurrent selection edits preserve the original pending conflict',async()=>{
 const store=new Store(':memory:'),pair={endpoint:'https://fixture.invalid',workspaceId:'original'},docs=original(),restored=mergeApplicationBackup({},exportApplicationBackup(docs)),snapshot={documents:restored,revisions:{siteProfiles:1,activeSiteId:4,selectedSiteIds:5}};let online=false,writes=0;const runtime={store,cloud:{async request(route){if(!online)throw Error('offline');if(route==='snapshot')return structuredClone(snapshot);writes++;throw Error('must not overwrite remote selection');}}};
 try{assert.deepEqual(applicationModel({documents:restored}).profileSelection,{activeSiteId:'q',selectedSiteIds:['q','p']});store.set('pair',pair);store.set('applicationSnapshot',{scope:workbenchScope(pair),snapshot});const result=await enqueueLibraryMutation(runtime,{operation:operation('selectedSiteIds',['p'])});snapshot.documents.selectedSiteIds=[];snapshot.revisions.selectedSiteIds++;online=true;await flushApplicationMutations(runtime);assert.equal(writes,0);assert.equal(store.get('appMutation:'+result.id).status,'conflict');assert.deepEqual(snapshot.documents.selectedSiteIds,[]);}finally{store.close();}
});
