import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,writeFile,readFile,rm} from 'node:fs/promises';import {join,resolve,sep} from 'node:path';import {tmpdir} from 'node:os';import {createHash} from 'node:crypto';
import {Store} from '../executor/src/store.mjs';import {Runtime} from '../executor/src/runtime.mjs';import {freezeAcceptance} from '../executor/src/acceptance-freeze.mjs';import {originalRunMediaEvidence,originalTaskMediaEvidence} from '../executor/src/task-media-evidence.mjs';import {materializeTaskMedia} from '../executor/src/task-media.mjs';
async function fixture(){
 const home=await mkdtemp(join(tmpdir(),'el-original-media-proof-')),store=new Store(':memory:'),bytes=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/l9sAAAAASUVORK5CYII=','base64'),file=join(home,'original.png'),sha256=createHash('sha256').update(bytes).digest('hex'),ref='cloud-media://original.png',profile={id:'p',name:'Original',url:'https://product.example',fields:{'Cloud LOGO':ref}};
 await writeFile(file,bytes);const frozen=freezeAcceptance(store,{id:'scope',products:{p:profile},profileRevision:1,sites:['https://directory.example/submit'],count:1,mediaManifest:[{productId:'p',kind:'logo',ref,file,mime:'image/png',sha256,ok:true}]});
 const run={id:'run',acceptanceId:frozen.id,workspaceId:'one',profileId:'p',profile:structuredClone(profile),profileRevision:1,createdAt:new Date(Date.parse(frozen.at)+1000).toISOString(),tasks:['task'],mediaManifest:[{asset_id:'original.png',media_kind:'logo',file_name:'original.png',sha256:''}]},task={id:'task',runId:run.id,profileId:'p',profileSnapshot:structuredClone(profile),status:'pending'};store.set('pair',{workspaceId:'one'});store.set('run:'+run.id,run);store.set('task:'+task.id,task);store.set('paused',true);let requests=0;
 const runtime={store,home,cloud:{request:async()=>{requests++;throw Error('offline');}},update(t,patch){Object.assign(t,patch);store.set('task:'+t.id,t);}};runtime.bridge=(t,message)=>Runtime.prototype.bridge.call(runtime,t,message);
 return{store,home,bytes,file,sha256,ref,profile,frozen,run,task,runtime,get requests(){return requests;},async close(){store.close();assert.ok(resolve(home).startsWith(resolve(tmpdir())+sep)&&home.includes('el-original-media-proof-'));await rm(home,{recursive:true,force:true});}};
}
test('original native bridge reads verified pre-run backup without cloud calls or rewriting missing historical SHA',async()=>{
 const f=await fixture();try{const runBefore=f.store.get('run:run'),taskBefore=f.store.get('task:task'),scopeBefore=f.store.get('acceptance:scope'),media=await f.runtime.bridge(f.task,{action:'fetchCloudSubmissionMedia',ref:f.ref});assert.equal(media.sha256,f.sha256);assert.equal(media.source,'original_frozen_backup');assert.equal(media.recoveredOriginalChecksum,true);assert.deepEqual(Buffer.from(media.dataUrl.split(',')[1],'base64'),f.bytes);assert.equal(f.requests,0);assert.deepEqual(f.store.get('run:run'),runBefore);assert.deepEqual(f.store.get('task:task'),taskBefore);assert.deepEqual(f.store.get('acceptance:scope'),scopeBefore);assert.equal(f.store.get('paused'),true);}finally{await f.close();}
});
test('offline task attachment uses original proven bytes and records their source while preserving old run and attempt state',async()=>{
 const f=await fixture();try{const before=f.store.get('run:run'),file=await materializeTaskMedia(f.runtime,f.task,{logoUrl:f.ref},'logo');assert.deepEqual(await readFile(file),f.bytes);assert.equal(f.task.usedMedia[0].sha256,f.sha256);assert.equal(f.task.usedMedia[0].source,'original_frozen_backup');assert.equal(f.task.usedMedia[0].sourceScopeSha256,f.frozen.sha256);assert.equal(f.task.usedMedia[0].recoveredOriginalChecksum,true);assert.equal(f.task.attemptBoundary,undefined);assert.deepEqual(f.store.get('run:run'),before);assert.equal(f.requests,0);}finally{await f.close();}
});
test('changed backup bytes, scope or original product cannot silently fall back to current cloud media',async()=>{
 const f=await fixture();try{await writeFile(f.file,'changed image');await assert.rejects(f.runtime.bridge(f.task,{action:'fetchCloudSubmissionMedia',ref:f.ref}),/字节校验/);await writeFile(f.file,f.bytes);const changed=structuredClone(f.frozen);changed.combinations[0].profile.name='Wrong product';f.store.set('acceptance:scope',changed);await assert.rejects(originalTaskMediaEvidence(f.runtime,f.task,f.ref),/范围校验/);f.store.set('acceptance:scope',f.frozen);f.store.set('run:run',{...f.run,profile:{...f.profile,name:'Different snapshot'}});assert.equal(await originalRunMediaEvidence(f.runtime,'run',f.ref),null);assert.equal(f.requests,0);}finally{await f.close();}
});
test('later backups, wrong task or workspace and disabled or unselected images cannot authorize original attachments',async()=>{
 const f=await fixture();try{await assert.rejects(originalTaskMediaEvidence(f.runtime,{...f.task,id:'other-task'},f.ref),/身份/);await assert.rejects(originalTaskMediaEvidence(f.runtime,{...f.task,profileId:'q'},f.ref),/身份/);await assert.rejects(originalTaskMediaEvidence(f.runtime,{...f.task,profileSnapshot:{...f.profile,mediaDisabled:{logo:true}}},f.ref),/选定/);await assert.rejects(originalTaskMediaEvidence(f.runtime,f.task,'cloud-media://unselected'),/选定/);f.store.set('pair',{workspaceId:'other'});await assert.rejects(originalTaskMediaEvidence(f.runtime,f.task,f.ref),/工作区/);f.store.set('pair',{workspaceId:'one'});f.store.set('run:run',{...f.run,createdAt:new Date(Date.parse(f.frozen.at)-1000).toISOString()});await assert.rejects(originalTaskMediaEvidence(f.runtime,f.task,f.ref),/晚于/);assert.equal(f.requests,0);}finally{await f.close();}
});
test('already frozen SHA keeps its original meaning and unknown task identifiers cannot be sent by the engine',async()=>{
 const f=await fixture();try{f.store.set('run:run',{...f.run,mediaManifest:[{...f.run.mediaManifest[0],sha256:'0'.repeat(64)}]});await assert.rejects(originalTaskMediaEvidence(f.runtime,f.task,f.ref),/不一致/);f.store.set('run:run',{...f.run,acceptanceId:null,mediaManifest:[{...f.run.mediaManifest[0],sha256:f.sha256}]});let sent;f.runtime.cloud.request=async(route,body)=>{sent={route,body};return{ok:true};};await f.runtime.bridge(f.task,{action:'fetchCloudSubmissionMedia',ref:f.ref,taskId:'foreign-task'});assert.equal(sent.route,'media');assert.equal(sent.body.taskId,f.task.id);assert.equal(sent.body.ref,f.ref);}finally{await f.close();}
});
