import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
import {applicationModel} from '../core/application-model.mjs';
import {pendingSubmissionQueue,originalNavigationQueue} from '../core/submission-queue.mjs';
import {originalLibraryCatalog,originalLibraryPreferences,originalLibraryQuickOpen,originalNavigationState,originalLibraryBatchQueue} from './helpers/original-library-catalog.mjs';
import {canonicalLibraryDestination} from '../core/library-records.mjs';
import {submissionQueue} from '../executor/src/submission-queue.mjs';
import {Store} from '../executor/src/store.mjs';
import {workbenchScope} from '../executor/src/workbench-sync.mjs';
import {applicationMutation,applicationMutationSatisfied} from '../core/application-mutation.mjs';
import {enqueueLibraryMutation,flushApplicationMutations,pendingApplication} from '../executor/src/application-mutations.mjs';
import {quickOpenLibrary} from '../executor/src/quick-open.mjs';
const Timeline=globalThis.ExtLinkSubmissionTimeline;
const profiles={p:{id:'p',name:'原产品甲',sortIndex:0,url:'https://product.example'},q:{id:'q',name:'原产品乙',sortIndex:1,url:'https://other.example'}};
const record=(url,profileId='p',extra={})=>({destinationUrl:url,destinationKey:globalThis.ExtLinkQueue.normalizeDestinationKey(url),profileId,status:'success',confirmedBy:'manual',evidence:'Original concrete receipt',publicationStatus:'published',submittedAt:'2026-09-20T00:00:00Z',...extra});
function fixture(urls){return{documents:{siteProfiles:structuredClone(profiles),sheetTableData:{entries:urls.map(link=>({link,metrics:{dr:70,da:55}}))},submissionSchemaVersion:2,submissionRecords:{},submissionTimeline:{},linkMonitorResults:{}}};}
function summary(item){const progress=item.progress||Timeline.deriveLibraryProgress(item);return{url:item.url,events:item.events.map(e=>e.id).sort(),profiles:item.profileStatuses.map(p=>({profileId:p.profileId,success:p.success,publicationStatus:p.publicationStatus,submittedAt:p.submittedAt})).sort((a,b)=>a.profileId.localeCompare(b.profileId)),monitorStatus:item.monitorStatus,quality:item.quality.score,progress};}
async function compare(snapshot){const before=structuredClone(snapshot),expected=await originalLibraryCatalog(snapshot),model=applicationModel(snapshot);for(const item of expected.items){const actual=model.library.find(r=>r.url===item.url);assert.ok(actual);assert.deepEqual(summary(actual),summary(item),item.url);}assert.deepEqual(snapshot,before);return model;}
test('library facts isolate unrelated paths on one host, including monitoring and quality',async()=>{
 const a='https://articles.example/one',b='https://articles.example/two',snapshot=fixture([a,b]);snapshot.documents.submissionRecords['articles.example/one::p']=record(a);snapshot.documents.submissionTimeline['articles.example/two::q']=[{id:'other-article',profileId:'q',destinationUrl:b,type:'rejected',note:'Other article only',occurredAt:'2026-10-02T00:00:00Z'}];snapshot.documents.linkMonitorResults['articles.example/one::p']={status:'live'};await compare(snapshot);
});
test('old success flags without a receipt remain original action history rather than received submissions',async()=>{
 const url='https://legacy.example/form',snapshot=fixture([url]);snapshot.documents.submissionRecords['legacy.example/form::p']=record(url,'p',{confirmedBy:'legacy_import',evidence:'Table.xlsx submitted seed',publicationStatus:'submitted'});const model=await compare(snapshot);assert.equal(model.library[0].progress.hasSubmitted,false);
});
test('later ordinary notes fall back to the original record publication state',async()=>{
 const url='https://notes.example/form',snapshot=fixture([url]);snapshot.documents.submissionRecords['notes.example/form::p']=record(url,'p',{publicationStatus:'pending_moderation'});snapshot.documents.submissionTimeline['notes.example/form::p']=[{id:'old-published',profileId:'p',destinationUrl:url,type:'published',occurredAt:'2026-09-21T00:00:00Z'},{id:'latest-note',profileId:'p',destinationUrl:url,type:'note',note:'Only a note',occurredAt:'2026-10-03T00:00:00Z'}];await compare(snapshot);
});
test('record display uses the latest matching original row rather than insertion order',async()=>{
 const url='https://records.example/form',snapshot=fixture([url]);snapshot.documents.submissionRecords.old=record(url);snapshot.documents.submissionRecords.new=record(url,'p',{submittedAt:'2026-10-01T00:00:00Z',publicationStatus:'pending_moderation'});await compare(snapshot);
});
test('all original display aliases read the same original submission and timeline evidence',async()=>{
 for(const domain of ['startupstash.com','startupcollections.com','aisuperhub.io','launchpedia.co','tipseason.com','library.phygital.plus','aisotools.com','producthunt.com','aitools.neilpatel.com']){const url='https://'+domain,receiptUrl=url+'/submit',snapshot=fixture([url]);snapshot.documents.submissionRecords[domain+'/submit::p']=record(receiptUrl);snapshot.documents.submissionTimeline[domain+'/submit::p']=[{id:'alias-note',profileId:'p',destinationUrl:receiptUrl,type:'note',note:'Original alias note',occurredAt:'2026-10-01T00:00:00Z'}];await compare(snapshot);}
});
test('latest activity uses original submitted/history time instead of a later synchronization timestamp',async()=>{
 const url='https://times.example/form',snapshot=fixture([url]);snapshot.documents.sheetTableData.entries[0].time='2026年9月19日';snapshot.documents.submissionRecords['times.example/form::p']=record(url,'p',{updatedAt:'2026-10-06T00:00:00Z'});const model=await compare(snapshot);assert.equal(model.library[0].lastActivityAt,model.library[0].progress.historyAt);
});
test('local task receipts remain visible only on their original destination and do not rewrite the ledger',()=>{
 const a='https://task.example/one',b='https://task.example/two',snapshot=fixture([a,b]),before=structuredClone(snapshot),model=applicationModel(snapshot,[{id:'original-task',profileId:'p',url:a,status:'finished',receipt:{evidence:'Local concrete receipt',publicationStatus:'pending_moderation'},updatedAt:'2026-10-01T00:00:00Z'}]);assert.equal(model.library.find(r=>r.url===a).progress.hasSubmitted,true);assert.equal(model.library.find(r=>r.url===b).progress.hasSubmitted,false);assert.deepEqual(snapshot,before);
});
test('original display aliases appear once, retain raw source rows, and produce one queued job per product',async()=>{
 const home='https://tipseason.com',submit=home+'/submit',other='https://ordinary.example/form',snapshot=fixture([home,submit,other]);snapshot.documents.siteAnnotations={'tipseason.com':{status:'can_submit',library:{groups:['high_quality']}},'tipseason.com/submit':{status:'paid'}};const before=structuredClone(snapshot),model=await compare(snapshot);assert.equal(model.library.length,2);assert.equal(model.inventoryTotal,3);const alias=model.library.find(r=>r.url===home);assert.equal(alias.annotation.status,'can_submit');assert.deepEqual(alias.aliases.map(a=>a.url),[home,submit]);assert.deepEqual(snapshot,before);
 const unmarked=structuredClone(snapshot);delete unmarked.documents.siteAnnotations['tipseason.com/submit'];const queue=pendingSubmissionQueue(unmarked,{selectedSiteIds:['p','q']}),group=queue.groups.find(g=>g.domain==='tipseason.com');assert.equal(queue.groups.length,2);assert.equal(group.jobs.length,2);assert.deepEqual(group.jobs.map(j=>j.profileId).sort(),['p','q']);assert.ok(group.quality);assert.equal(group.category,model.library.find(r=>r.url===home).category);
});
test('saved queue cursor and explicit URL retain the exact frozen original alias route',async()=>{
 const home='https://tipseason.com',submit=home+'/submit',snapshot=fixture(['https://ordinary.example/form',home,submit]),store=new Store(':memory:');try{snapshot.documents.sheetTableData.entries[0].metrics={dr:100,da:100};const pair={endpoint:'https://fixture.invalid',workspaceId:'alias-cursor'},scope=workbenchScope(pair),page={targetId:'original-tab',browserInstance:'original-browser'};store.set('pair',pair);store.set('paused',true);store.set('submissionQueue',{scope,key:'tipseason.com/submit',index:0,selectedSiteIds:['p'],page});const runtime={store,cloud:{async request(route){assert.equal(route,'snapshot');return structuredClone(snapshot);}}};let expected=await originalNavigationState(snapshot,{cursor:{key:'tipseason.com/submit',index:0}}),result=await submissionQueue(runtime);assert.equal(result.task.key,expected.cursor.key);assert.deepEqual(store.get('submissionQueue').page,page);expected=await originalNavigationState(snapshot,{input:{url:submit},cursor:expected.cursor});result=await submissionQueue(runtime,{url:submit});assert.equal(result.task.key,expected.cursor.key);assert.equal(store.get('paused'),true);}finally{store.close();}
});
test('automatic visit queue alignment resolves the original concrete alias within the complete original source range',async()=>{
 const source=readFileSync(new URL('../executor/src/browser-assistant.mjs',import.meta.url),'utf8'),body=source.slice(source.indexOf('function recordVisitQueue('),source.indexOf('function frozenConfig(')),snapshot=fixture(['https://tipseason.com','https://tipseason.com/submit']),store=new Store(':memory:');try{store.set('pair',{endpoint:'https://fixture.invalid',workspaceId:'auto-alias'});store.set('paused',true);const runtime={store},context=vm.createContext({runtime,snapshot,workbenchScope,pendingSubmissionQueue,originalNavigationQueue,canonicalLibraryDestination});const result=vm.runInContext(body+"\nrecordVisitQueue(runtime,snapshot,'p',{destinationKey:'tipseason.com/submit'})",context);const expected=await originalLibraryBatchQueue(snapshot,{profileIds:['p']});assert.equal(result.queueTotal,expected.groups.length);assert.equal(store.get('submissionQueue').key,'tipseason.com');assert.equal(store.get('paused'),true);assert.equal(store.values('task:').length,0);}finally{store.close();}
});
test('alias preferences save at the original catalog key and can be read and acknowledged there',async()=>{
 for(const domain of ['tipseason.com','library.phygital.plus','ordinary.example']){const url='https://'+domain+'/submit',snapshot=fixture([url]),key=canonicalLibraryDestination(url),rawKey=globalThis.ExtLinkQueue.normalizeDestinationKey(url);snapshot.documents.siteAnnotations={[key]:{status:'can_submit',note:'Original canonical note',library:{favorite:false,groups:['high_quality'],custom:'keep'}}};if(key!==rawKey)snapshot.documents.siteAnnotations[rawKey]={note:'Unrelated old route marker',library:{groups:[],favorite:false}};const patch={favorite:true,groups:['free_submit'],profileIds:['p']},original=await originalLibraryPreferences(snapshot.documents,{url,...patch}),operation={type:'preferences',url,preferences:patch,id:'original-alias-preferences',at:'2026-10-06T00:00:00Z'},change=applicationMutation(snapshot.documents,operation),documents={...snapshot.documents,[change.key]:change.data};assert.equal(original.result.key,key);assert.deepEqual(change.data[key].library.groups,original.documents.siteAnnotations[key].library.groups);assert.equal(change.data[key].library.favorite,true);assert.equal(change.data[key].note,'Original canonical note');assert.equal(change.data[key].library.custom,'keep');assert.equal(applicationMutationSatisfied(documents,operation),true);assert.equal(applicationModel({documents}).library[0].preferences.favorite,true);if(key!==rawKey)assert.deepEqual(change.data[rawKey],snapshot.documents.siteAnnotations[rawKey]);}
});
test('unknown alias preference response is confirmed by the original mutation ID without a second write',async()=>{
 const url='https://library.phygital.plus/tool-submission',snapshot=fixture([url]),store=new Store(':memory:'),before=structuredClone(snapshot.documents.submissionRecords);try{snapshot.revisions={siteAnnotations:1};store.set('pair',{endpoint:'https://fixture.invalid',workspaceId:'alias-save'});store.set('paused',true);store.set('applicationSnapshot',{scope:workbenchScope(store.get('pair')),snapshot:structuredClone(snapshot)});let writes=0;const runtime={store,cloud:{async request(route,input){if(route==='snapshot')return structuredClone(snapshot);assert.equal(route,'library');writes++;const change=applicationMutation(snapshot.documents,input.operation);snapshot.documents[change.key]=change.data;snapshot.revisions[change.key]++;throw Error('lost original response');}}};await enqueueLibraryMutation(runtime,{operation:{type:'preferences',url,preferences:{favorite:true,groups:['high_quality']}}});const id=store.values('appMutation:')[0].id;await flushApplicationMutations(runtime);assert.equal(writes,1);assert.equal(pendingApplication(runtime).length,0);assert.equal(store.values('appMutation:')[0].id,id);assert.equal(store.values('appMutation:')[0].status,'confirmed');assert.equal(applicationModel(snapshot).library[0].preferences.favorite,true);assert.deepEqual(snapshot.documents.submissionRecords,before);assert.equal(store.get('paused'),true);}finally{store.close();}
});
test('quick open resolves original display aliases, deduplicates and retains ordinary path scope',async()=>{
 for(const domain of ['startupstash.com','startupcollections.com','aisuperhub.io','launchpedia.co','tipseason.com','library.phygital.plus','aisotools.com','producthunt.com','aitools.neilpatel.com']){
  const home='https://'+domain,snapshot=fixture([home,home+'/submit','https://ordinary.example/one']),input={urls:[home+'/submit',home+'/another','https://ordinary.example/two','https://ordinary.example/one','javascript:void(0)'],batchSize:5,intervalMs:100},expected=await originalLibraryQuickOpen(snapshot,input),store=new Store(':memory:'),visited=[];
  try{store.set('pair',{endpoint:'https://fixture.invalid',workspaceId:'alias-open'});store.set('paused',true);const runtime={store,cloud:{async request(route){assert.equal(route,'snapshot');return structuredClone(snapshot);}},context:{async newPage(){return{isClosed:()=>false,async goto(url){visited.push(url);}};},async newCDPSession(){return{async send(){return{targetInfo:{targetId:'original-'+visited.length}};},async detach(){}};}}};const result=await quickOpenLibrary(runtime,input);await runtime.quickOpenJob;assert.deepEqual(visited,expected,domain);assert.equal(store.get('quickOpenJob:'+result.job.id).status,'completed');assert.equal(store.get('paused'),true);assert.equal(store.pendingCount(),0);assert.equal(store.values('task:').length,0);assert.deepEqual(snapshot,fixture([home,home+'/submit','https://ordinary.example/one']));}finally{store.close();}
 }
});
