import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join,resolve,sep} from 'node:path';
import {Store} from '../executor/src/store.mjs';import {applicationAi,fillCommentDraft} from '../executor/src/workbench-features.mjs';import {saveCommentVersion,commentHistory} from '../executor/src/comment-history.mjs';
const input={profileId:'p',pageUrl:'https://article.example/post',pageText:'Original article excerpt',allowLink:true,tone:'professional',language:'zh'},drafts=[{text:'First',angle:'务实建议',anchorText:'Original',placement:'末尾',chars:5},{text:'Second',angle:'补充经验',anchorText:'',placement:'正文',chars:6},{text:'Third',angle:'提问',anchorText:'Original',placement:'末尾',chars:5}];
function fixture(filters={}){const store=new Store(':memory:'),snapshot={documents:{targetFilters:filters,siteProfiles:{p:{id:'p',name:'Original',fields:{Name:'Original',Url:'https://product.example'},blogRules:{tone:'helpful'}}}},revisions:{siteProfiles:1}},calls=[];let response={ok:true,status:'ok',drafts},onAi=()=>{};store.set('pair',{endpoint:'https://cloud.invalid',workspaceId:'original'});store.set('paused',true);const runtime={store,cloud:{async request(route,payload){if(route==='snapshot')return structuredClone(snapshot);assert.equal(route,'ai/comment');calls.push(structuredClone(payload));onAi();return structuredClone(response);}}};return{runtime,snapshot,calls,set response(value){response=value;},set onAi(value){onAi=value;}};}
test('original disabled AI comment preference prevents model calls and leaves all draft history intact',async()=>{
 const f=fixture({aiComments:false});try{await assert.rejects(applicationAi(f.runtime,'commentDrafts',input),/关闭/);assert.equal(f.calls.length,0);assert.equal(f.runtime.store.values('commentDraft:').length,0);assert.equal(f.runtime.store.values('commentHistory:').length,0);}finally{f.runtime.store.close();}
});
test('original promotion-link switch overrides request defaults and generated history records the effective preference',async()=>{
 for(const [filters,requested,expected]of [[{aiCommentAllowLink:false},true,false],[{},undefined,true],[{},false,false]]){const f=fixture(filters);try{await applicationAi(f.runtime,'commentDrafts',{...input,allowLink:requested});assert.equal(f.calls[0].allowLink,expected);assert.equal(commentHistory(f.runtime,input).versions[0].payload.allowLink,expected);assert.equal(f.calls[0].config.blogRules.tone,'professional');}finally{f.runtime.store.close();}}
});
test('comment versions preserve the original copyCommentDraft metadata and accept partial candidate sets',()=>{
 const source=readFileSync(new URL('../extension/sidepanel.js',import.meta.url),'utf8'),copy=vm.runInNewContext('('+source.slice(source.indexOf('function copyCommentDraft('),source.indexOf('function makeCommentSnapshot('))+')'),f=fixture();
 try{for(const selected of [drafts.slice(0,1),drafts.slice(0,2),drafts]){saveCommentVersion(f.runtime,{...input,drafts:selected});const result=commentHistory(f.runtime,input).versions[0].payload.drafts;assert.deepEqual(result,JSON.parse(JSON.stringify(selected.map(copy))));}assert.throws(()=>saveCommentVersion(f.runtime,{...input,drafts:[]}),/候选/);assert.throws(()=>saveCommentVersion(f.runtime,{...input,drafts:[{text:4}]}),/候选/);}finally{f.runtime.store.close();}
});
test('one-candidate original fallback and original one-to-five request counts save valid candidates',async()=>{
 const f=fixture();try{f.response={ok:true,status:'ok',drafts:drafts.slice(0,1)};const result=await applicationAi(f.runtime,'commentDrafts',{...input,count:1});assert.equal(f.calls[0].count,1);assert.equal(result.drafts.length,1);assert.equal(commentHistory(f.runtime,input).versions[0].payload.drafts.length,1);f.response={ok:true,status:'ok',drafts:Array.from({length:5},(_,i)=>({text:'Candidate '+i}))};await applicationAi(f.runtime,'commentDrafts',{...input,count:9});assert.equal(f.calls[1].count,5);assert.equal(commentHistory(f.runtime,input).versions[0].payload.drafts.length,5);}finally{f.runtime.store.close();}
});
test('empty or rejected model results do not replace the previous valid draft or history',async()=>{
 const f=fixture();try{await applicationAi(f.runtime,'commentDrafts',input);const oldDrafts=f.runtime.store.values('commentDraft:'),oldHistory=f.runtime.store.values('commentHistory:');for(const response of [{ok:false,status:'rejected',drafts:[]},{ok:true,status:'ok',drafts:[{text:'  '}]}]){f.response=response;await assert.rejects(applicationAi(f.runtime,'commentDrafts',{...input,refresh:true}),/评论/);assert.deepEqual(f.runtime.store.values('commentDraft:'),oldDrafts);assert.deepEqual(f.runtime.store.values('commentHistory:'),oldHistory);}}finally{f.runtime.store.close();}
});
test('workspace switches during model generation abandon old results instead of attributing them to the new workspace',async()=>{
 const f=fixture();try{f.onAi=()=>f.runtime.store.set('pair',{endpoint:'https://cloud.invalid',workspaceId:'changed'});await assert.rejects(applicationAi(f.runtime,'commentDrafts',input),/工作区/);assert.equal(f.runtime.store.values('commentDraft:').length,0);assert.equal(f.runtime.store.values('commentHistory:').length,0);assert.equal(f.runtime.store.get('paused'),true);}finally{f.runtime.store.close();}
});
test('same-host article navigation or a different product refuses old comment filling before any lease or field action',async()=>{
 const f=fixture();f.runtime.store.set('task:original',{id:'original',profileId:'p',status:'pending',url:input.pageUrl});f.runtime.context={};f.runtime.findPage=async()=>({url:()=> 'https://article.example/another-post'});f.runtime.lease=async()=>{throw Error('must not lease');};try{await assert.rejects(fillCommentDraft(f.runtime,{taskId:'original',profileId:'other',pageUrl:input.pageUrl,text:'Original comment'}),/产品/);await assert.rejects(fillCommentDraft(f.runtime,{taskId:'original',profileId:'p',pageUrl:input.pageUrl,text:'Original comment'}),/文章页面/);assert.equal(f.calls.length,0);assert.equal(f.runtime.store.get('paused'),true);}finally{f.runtime.store.close();}
});
test('article navigation while cloud snapshot is pending refuses the old draft before leasing or filling',async()=>{
 const f=fixture();let current=input.pageUrl,leases=0;f.runtime.store.set('task:original',{id:'original',profileId:'p',status:'pending',url:input.pageUrl});f.runtime.context={};f.runtime.findPage=async()=>({url:()=>current,frames:()=>[]});f.runtime.lease=async()=>{leases++;};f.runtime.cloud.request=async()=>{current='https://article.example/new-article';return structuredClone(f.snapshot);};try{await assert.rejects(fillCommentDraft(f.runtime,{taskId:'original',profileId:'p',pageUrl:input.pageUrl,text:'Original comment'}),/文章页面/);assert.equal(leases,0);assert.equal(f.runtime.store.get('task:original').selectedComment,undefined);}finally{f.runtime.store.close();}
});
test('single-candidate metadata and distinct edited history survive a real SQLite close and reopen',async()=>{
 const home=await mkdtemp(join(tmpdir(),'el-original-comment-')),path=join(home,'outbox.sqlite');let store=new Store(path);
 try{store.set('pair',{endpoint:'https://fixture.invalid',workspaceId:'original'});store.set('paused',true);const runtime={store},original={...input,drafts:[drafts[0]]};saveCommentVersion(runtime,original);saveCommentVersion(runtime,{...original,drafts:[{...drafts[0],text:'Edited original candidate'}]});const before=commentHistory(runtime,input);store.close();store=new Store(path);runtime.store=store;assert.deepEqual(commentHistory(runtime,input),before);assert.equal(before.versions[0].payload.drafts[0].angle,'务实建议');assert.equal(before.versions[1].payload.drafts[0].text,'First');assert.equal(store.get('paused'),true);}finally{store.close();assert.ok(resolve(home).startsWith(resolve(tmpdir())+sep));await rm(home,{recursive:true,force:true});}
});
