import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {execFileSync} from 'node:child_process';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join,resolve,sep} from 'node:path';
import {Store} from '../executor/src/store.mjs';import {Runtime} from '../executor/src/runtime.mjs';import {runExports} from '../executor/src/run-exports.mjs';
const source=execFileSync('git',['show','bd916b2944a577b160a6afcb8a7d73d263044c0c:extension/background.js'],{encoding:'utf8',maxBuffer:4*1024*1024}),original=source.match(/^function log\([^]*?^\}/m)?.[0];assert.ok(original);
function reference(message){let entry;const context=vm.createContext({Date,Math,state:{runId:'original-run'},console:{log(){},warn(){},error(){}},persistBatchLogEntry:value=>entry=structuredClone(value),chrome:{runtime:{sendMessage:async()=>({})}}});vm.runInContext(original,context);context.log(message.msg,message.cls,{event:message.event||'content_step',taskIndex:7,taskId:'original',domain:'target.example',profileId:'p'});return entry;}
test('native content log and export retain original event severity class domain and task context after SQLite reopen',{timeout:15000},async()=>{
 const home=await mkdtemp(join(tmpdir(),'el-content-log-')),file=join(home,'outbox.sqlite');let store=new Store(file);const runtime=new Runtime(store,home),pair={endpoint:'https://cloud.example',workspaceId:'original'},scope=pair.endpoint+'|'+pair.workspaceId,task={id:'original',runId:'original-run',profileId:'p',index:7,url:'https://www.target.example/form',status:'needs_manual'};store.set('pair',pair);store.set('paused',true);store.set('task:'+task.id,task);store.set('acceptanceBatch',{status:'paused',cursor:13,count:30});store.set('workbenchBatch:batch',{id:'batch',scope,status:'paused',count:1,cursor:0,items:[{identity:'original-combination',taskId:task.id,runId:task.runId,profileId:'p',profile:{name:'Original'},url:task.url,status:'registered'}]});
 try{const expected=[];for(const cls of ['err','warn','ok',undefined,'custom']){const message={action:'log',msg:'Original Unicode message 🙂\nSecond line',cls,event:'original_content_event'};await runtime.bridge(task,message);expected.push(reference(message));}
  const result=await runtime.control('getBatchLog',{runId:task.runId,taskId:task.id});assert.equal(result.entries.length,expected.length);const keys=['message','level','cls','event','runId','taskId','taskIndex','domain','profileId'];for(let i=0;i<expected.length;i++)for(const key of keys)assert.equal(result.entries[i][key],expected[i][key],key+' '+i);
  const exported=JSON.parse(runExports(runtime,'exportAutomationRun',{sourceId:'workbench:batch'}).content);for(let i=0;i<expected.length;i++)for(const key of keys)assert.equal(exported.events[i][key],expected[i][key],'export '+key+' '+i);
  assert.deepEqual(store.get('task:'+task.id),task);assert.equal(store.pendingCount(),0);assert.equal(store.get('acceptanceBatch').cursor,13);assert.equal(store.logs({scope:'https://cloud.example|other'}).entries.length,0);
  store.close();store=new Store(file,{readOnly:true});assert.deepEqual(store.logs({scope,runId:task.runId,taskId:task.id}).entries,result.entries);assert.deepEqual(store.get('task:'+task.id),task);assert.equal(store.pendingCount(),0);
 }finally{store.close();assert.ok(resolve(home).startsWith(resolve(tmpdir())+sep)&&home.includes('el-content-log-'));await rm(home,{recursive:true,force:true});}
});
