import test from'node:test';import assert from'node:assert/strict';import{applicationMutation,applicationMutationSatisfied}from'../core/application-mutation.mjs';
import{Store}from'../executor/src/store.mjs';import{enqueueProfileMutation,flushApplicationMutations,pendingApplication}from'../executor/src/application-mutations.mjs';import{workbenchScope}from'../executor/src/workbench-sync.mjs';
test('original Chinese product language and manually configured integer comment link limits survive editing without rewriting history',()=>{
 const receipt={taskId:'original-task',profileId:'p',status:'success'},media={assetId:'original-media',sha256:'original'},docs={siteProfiles:{p:{id:'p',name:'Original',language:'zh',fields:{Name:'Original'},blogRules:{tone:'professional',preferredAnchor:'brand',maxLinksPerDraft:10},mediaVersions:[media]}},submissionRecords:{'site.example::p':receipt}};
 for(const maxLinksPerDraft of [0,1,5,6,10,100]){const result=applicationMutation(docs,{type:'profile',profileId:'p',at:'now',profile:{id:'p',language:'zh',fields:{Name:'Edited'},blogRules:{...docs.siteProfiles.p.blogRules,maxLinksPerDraft}}});assert.equal(result.data.p.language,'zh');assert.equal(result.data.p.blogRules.maxLinksPerDraft,maxLinksPerDraft);assert.deepEqual(result.data.p.mediaVersions,[media]);assert.deepEqual(docs.submissionRecords['site.example::p'],receipt);}
 for(const value of [-1,1.5,'10',null,Infinity,Number.MAX_SAFE_INTEGER+1])assert.throws(()=>applicationMutation(docs,{type:'profile',profileId:'p',at:'now',profile:{id:'p',blogRules:{maxLinksPerDraft:value}}}),/评论规则/);
});
test('original per-field notes update partially, retain blank and unedited notes, and confirm the same patch after a lost response',()=>{
 const docs={siteProfiles:{p:{id:'p',fields:{Name:'Original',Title:'Original title'},fieldNotes:{Name:'Old name note',Title:'Preserve other note'},mediaVersions:[{assetId:'original'}]}}},operation={type:'profile',profileId:'p',at:'now',profile:{id:'p',fieldNotes:{Name:'  New name note  '}}};
 const result=applicationMutation(docs,operation);assert.deepEqual(result.data.p.fieldNotes,{Name:'New name note',Title:'Preserve other note'});assert.deepEqual(result.data.p.mediaVersions,docs.siteProfiles.p.mediaVersions);assert.equal(applicationMutationSatisfied({siteProfiles:result.data},operation),true);
 const blank={...operation,profile:{id:'p',fieldNotes:{Name:'  '}}};assert.deepEqual(applicationMutation(docs,blank).data.p.fieldNotes,docs.siteProfiles.p.fieldNotes);assert.equal(applicationMutationSatisfied(docs,blank),true);
});
test('field note changes reject invalid values and unsafe keys before changing product data',()=>{
 const docs={siteProfiles:{p:{id:'p',fields:{Name:'Original'}}}};for(const fieldNotes of [null,[],{Name:123},{Name:'x'.repeat(100001)},JSON.parse('{"__proto__":"unsafe"}'),{constructor:'unsafe'}])assert.throws(()=>applicationMutation(docs,{type:'profile',profileId:'p',at:'now',profile:{id:'p',fieldNotes}}),error=>error.status===400&&/字段备注/.test(error.message));assert.equal(docs.siteProfiles.p.fieldNotes,undefined);
});
test('a committed partial field note patch with a lost reply is confirmed from cloud without resending or dropping other notes',async()=>{
 const store=new Store(':memory:'),pair={endpoint:'https://cloud.fixture.invalid',workspaceId:'original'},snapshot={documents:{siteProfiles:{p:{id:'p',language:'zh',fields:{Name:'Original'},fieldNotes:{Name:'Old',Title:'Keep'}}}},revisions:{siteProfiles:1}};let writes=0;
 store.set('pair',pair);store.set('paused',true);store.set('applicationSnapshot',{scope:workbenchScope(pair),snapshot});const runtime={store,cloud:{async request(route,input){if(route==='snapshot')return structuredClone(snapshot);assert.equal(route,'profile');const original=pendingApplication(runtime)[0];assert.ok(original.id);writes++;snapshot.documents.siteProfiles=applicationMutation(snapshot.documents,original.operation).data;snapshot.revisions.siteProfiles++;throw Error('reply lost after commit');}}};
 try{const result=await enqueueProfileMutation(runtime,{profileId:'p',revision:1,profile:{id:'p',fieldNotes:{Name:' Updated '}}}),id=result.id;assert.equal(result.pending,1);assert.equal(store.get('appMutation:'+id).status,'pending');assert.equal((await flushApplicationMutations(runtime)).pending,0);assert.equal(store.get('appMutation:'+id).status,'confirmed');assert.equal(writes,1);assert.deepEqual(snapshot.documents.siteProfiles.p.fieldNotes,{Name:'Updated',Title:'Keep'});assert.equal(snapshot.documents.siteProfiles.p.language,'zh');assert.equal(store.get('paused'),true);}finally{store.close();}
});
