import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve,sep} from 'node:path';
import vm from 'node:vm';
import {Store} from '../executor/src/store.mjs';
import {Runtime} from '../executor/src/runtime.mjs';
import {originalBatchConfig,originalUnattended as U} from '../core/original-batch-config.mjs';
import {applicationMutation} from '../core/application-mutation.mjs';
import {exportApplicationBackup,mergeApplicationBackup} from '../core/application-backup.mjs';
import {localRecoveryOriginalDocuments} from '../core/local-recovery.mjs';
import {previewWorkbenchBatch,startWorkbenchBatch,nextWorkbenchTask,finishWorkbenchTask} from '../executor/src/workbench-features.mjs';
import {freezeBatchConfig,initializeBatchPolicy,watchBatchDeadline,batchActionAllowed,finalizeBatchDeadline,reserveBatchModelCall,retainBatchManualPage} from '../executor/src/workbench-batch-policy.mjs';

function fixture(file=':memory:',options={}){
 const store=new Store(file),profile={id:'p',name:'Original P',fields:{Name:'Original P',Url:'https://product.example'}},documents={siteProfiles:{p:profile},sheetTableData:{entries:Array.from({length:6},(_,n)=>({link:'https://site'+n+'.example/submit'}))},submissionRecords:{},cfgConcurrency:'4',unattendedPreferences:{enabled:true,hours:8,tasks:100,manualTabs:20}},runtime=new Runtime(store,'isolated-unused');store.set('pair',{endpoint:'https://cloud.example',workspaceId:'default'});store.set('paused',true);runtime.tick=()=>{};runtime.lease=async()=>{};
 const items=Array.from({length:6},(_,n)=>({identity:'original-'+n,profileId:'p',url:'https://site'+n+'.example/submit',taskId:'t'+n,runId:'r'+n,profile,profileRevision:1,status:'registered'}));
 const batch=initializeBatchPolicy({id:'b',scope:'https://cloud.example|default',...freezeBatchConfig(documents,options),count:6,cursor:0,status:'running',items});store.set('workbenchBatch:b',batch);store.set('activeWorkbenchBatch','b');store.set('paused',false);for(const item of items){store.set('task:'+item.taskId,{id:item.taskId,runId:item.runId,profileId:'p',url:item.url,status:'pending',profileRevision:1,profileSnapshot:profile});store.set('run:'+item.runId,{id:item.runId,profile,profileId:'p',tasks:[{id:item.taskId,url:item.url}]});}
 return{runtime,store,documents,batch};
}
test('batch pure helpers and unattended module match the original pre-refactor sources and clamp through the same UI helper',()=>{
 const hashes={'sidepanel-model':'3bef9545ce27176dc9a767243c3e66b947672ce5300085470fe6505a27f257f3',unattended:'f605333d0270254463c60a0e686fb386c409e865d203ad8f131a0973053066cb'},sandbox={self:{}};vm.createContext(sandbox);for(const [name,hash]of Object.entries(hashes)){const source=readFileSync(new URL('../core/'+name+'.js',import.meta.url),'utf8').replace(/\r\n/g,'\n');assert.equal(createHash('sha256').update(source).digest('hex'),hash);vm.runInContext(source,sandbox);}
 for(const concurrency of ['4.8','bad','0','9999',-2])for(const hours of ['',99,'bad',2.5]){const options={concurrency,pingIndex:false,fillOnly:true,unattended:true,unattendedMaxHours:hours,unattendedMaxTasks:0,unattendedMaxManualTabs:999};const reference=JSON.parse(JSON.stringify(sandbox.self.ExtLinkSidepanel.buildBatchConfig(options)));assert.deepEqual(originalBatchConfig({},options),reference);}
});
test('original saved concurrency and unattended preferences roundtrip through mutations, backup and local recovery without resetting unrelated fields',()=>{
 const documents={siteProfiles:{p:{id:'p',name:'P'}},cfgConcurrency:'4 old',unattendedPreferences:{enabled:true,hours:8,tasks:100,manualTabs:20},submissionRecords:{original:{status:'success',taskId:'old'}}};const imported=exportApplicationBackup(documents);assert.equal(imported.cfgConcurrency,'4 old');assert.deepEqual(mergeApplicationBackup({},imported).unattendedPreferences,documents.unattendedPreferences);const original=localRecoveryOriginalDocuments({documents});assert.equal(original.cfgConcurrency,'4 old');assert.deepEqual(original.unattendedPreferences,documents.unattendedPreferences);const patch=applicationMutation(documents,{id:'original-change',at:'2026-10-07T00:00:00Z',type:'settings',key:'unattendedPreferences',value:{manualTabs:999}});assert.deepEqual(patch.data,{enabled:true,hours:8,tasks:100,manualTabs:100});assert.deepEqual(documents.submissionRecords.original,{status:'success',taskId:'old'});assert.throws(()=>applicationMutation(documents,{id:'invalid-change',at:'2026-10-07T00:00:00Z',type:'settings',key:'unattendedPreferences',value:{enabled:'true'}}),/格式/);
});
test('batch preview freezes original mode and settings, is scope bound and refuses changed config before registration',async()=>{
 const {runtime,store,documents}=fixture();try{store.set('activeWorkbenchBatch',null);store.set('paused',true);Object.defineProperty(runtime,'cloud',{value:{request:async route=>route==='snapshot'?{documents,revisions:{siteProfiles:1}}:{tasks:[],runs:[]}}});const result=await previewWorkbenchBatch(runtime,{profileIds:['p'],urls:['https://site0.example/submit'],config:{fillOnly:true,unattendedMaxHours:99,unattendedMaxTasks:2}});assert.equal(result.batch.config.fillOnly,true);assert.equal(result.batch.config.concurrency,4);assert.equal(result.batch.config.unattendedMaxHours,12);assert.equal(result.batch.config.unattendedMaxTasks,2);assert.equal(result.batch.scope,'https://cloud.example|default');const before=store.pendingCount();store.set('workbenchBatch:'+result.batch.id,{...result.batch,config:{...result.batch.config,fillOnly:false}});await assert.rejects(()=>startWorkbenchBatch(runtime,{batchId:result.batch.id,ordinaryPermissionsAuthorized:true}),/参数校验/);assert.equal(store.pendingCount(),before);}finally{store.close();}
});
test('fill-only release applies to every original task, preserves profile identities and does not release unrelated pending work',async()=>{
 const {runtime,store}=fixture(':memory:',{fillOnly:true});try{store.set('task:unrelated',{id:'unrelated',status:'pending'});for(let n=0;n<6;n++){const task=await nextWorkbenchTask(runtime);assert.equal(task.id,'t'+n);assert.equal(task.fillOnlyRun,true);assert.equal(task.unattendedBatchId,'b');runtime.update(task,{status:'needs_manual',attentionType:'fill_only',fillOnlyPrepared:true},'fixture_filled');assert.equal(finishWorkbenchTask(runtime,task.id),true);store.set('singleTaskId',null);}await nextWorkbenchTask(runtime);assert.equal(store.get('workbenchBatch:b').unattendedState.taskBudgetUsed,6);assert.equal(store.get('workbenchBatch:b').count,6);assert.equal(store.get('task:unrelated').status,'pending');}finally{store.close();}
});
test('excluded leading combinations do not reset the original cursor when a task lease completes',async()=>{
 const {runtime,store}=fixture();try{const batch=store.get('workbenchBatch:b');batch.items[0].status='excluded';store.set('workbenchBatch:b',batch);const task=await nextWorkbenchTask(runtime);assert.equal(task.id,'t1');assert.equal(store.get('workbenchBatch:b').cursor,1);assert.equal(store.get('workbenchBatch:b').items[0].status,'excluded');assert.equal(store.get('workbenchBatch:b').items[1].status,'running');}finally{store.close();}
});
test('task budget stops at original count and retains unprocessed tasks and denominator',async()=>{
 const {runtime,store}=fixture(':memory:',{unattendedMaxTasks:2});try{for(let n=0;n<2;n++){const task=await nextWorkbenchTask(runtime);runtime.update(task,{status:'needs_manual',attentionType:'fill_only'},'fixture_manual');finishWorkbenchTask(runtime,task.id);store.set('singleTaskId',null);}assert.equal(await nextWorkbenchTask(runtime),null);const batch=store.get('workbenchBatch:b');assert.equal(batch.status,'paused');assert.equal(batch.unattendedState.taskBudgetUsed,2);assert.equal(batch.count,6);assert.equal(batch.cursor,2);assert.equal(store.get('task:t2').status,'pending');assert.equal(store.get('paused'),true);}finally{store.close();}
});
test('atomic task claim rolls back budget, task flag and outbox if task persistence fails',async()=>{
 const {runtime,store}=fixture();try{const set=store.set.bind(store);store.set=(key,value)=>{if(key==='task:t0')throw Error('claim disk failure');return set(key,value);};await assert.rejects(()=>nextWorkbenchTask(runtime),/claim disk failure/);store.set=set;assert.equal(store.get('workbenchBatch:b').unattendedState.taskBudgetUsed,0);assert.equal(store.get('task:t0').unattendedClaimed,undefined);assert.equal(store.pendingCount(),0);}finally{store.close();}
});
test('manual capacity keeps prepared pages and waits without shrinking the batch; closed original pages release capacity',async()=>{
 const {runtime,store}=fixture(':memory:',{unattendedMaxManualTabs:1,fillOnly:true});try{const task=await nextWorkbenchTask(runtime);runtime.update(task,{status:'needs_manual',attentionType:'fill_only',targetId:'retained-original-target',browserInstance:'original-browser'},'fixture_manual');assert.equal(retainBatchManualPage(runtime,task),true);finishWorkbenchTask(runtime,task.id);store.set('singleTaskId',null);assert.equal(await nextWorkbenchTask(runtime),null);assert.equal(store.get('workbenchBatch:b').unattendedState.waitReason,'manual_capacity');assert.equal(store.get('paused'),false);assert.equal(store.get('task:t1').status,'pending');runtime.update(task,{tabClosedAt:'user-closed-original'},'fixture_page_closed');const next=await nextWorkbenchTask(runtime);assert.equal(next.id,'t1');assert.equal(store.get('workbenchBatch:b').unattendedState.waitReason,'');assert.equal(store.get('workbenchBatch:b').count,6);}finally{store.close();}
});
test('model calls reserve original budget before network and exhausted budget retains unknown attempts',async()=>{
 const {runtime,store}=fixture();try{const task=await nextWorkbenchTask(runtime);let calls=0;Object.defineProperty(runtime,'cloud',{value:{request:async()=>{calls++;return{ok:true};}}});const batch=store.get('workbenchBatch:b');batch.unattendedState.modelCallsUsed=199;store.set('workbenchBatch:b',batch);await runtime.batchModelRequest(task,'plan',{});assert.equal(calls,1);assert.equal(store.get('workbenchBatch:b').unattendedState.modelCallsUsed,200);runtime.update(task,{status:'submitting',attemptBoundary:'original-attempt'},'fixture_boundary');await assert.rejects(()=>runtime.batchModelRequest(task,'plan',{}),/模型调用预算/);assert.equal(calls,1);finalizeBatchDeadline(runtime,task);assert.equal(store.get('task:t0').status,'submitted_unconfirmed');assert.equal(store.get('task:t0').attemptBoundary,'original-attempt');assert.equal(store.get('workbenchBatch:b').count,6);}finally{store.close();}
});
test('original watchdog parks a timed-out task for verification and continues other targets without globally pausing',async()=>{
 const {runtime,store}=fixture();try{const task=await nextWorkbenchTask(runtime);runtime.update(task,{status:'submitting',attemptBoundary:'original-boundary',taskDeadlineAt:Date.now()-1},'fixture_boundary');runtime.activeTaskId=task.id;watchBatchDeadline(runtime);assert.equal(store.get('paused'),false);assert.equal(batchActionAllowed(runtime,task),false);finalizeBatchDeadline(runtime,task);assert.equal(store.get('task:t0').status,'submitted_unconfirmed');assert.equal(store.get('task:t0').attemptBoundary,'original-boundary');assert.equal(retainBatchManualPage(runtime,store.get('task:t0')),true);finishWorkbenchTask(runtime,task.id);store.set('singleTaskId',null);assert.equal(store.get('workbenchBatch:b').unattendedState.consecutiveFailures,1);assert.equal((await nextWorkbenchTask(runtime)).id,'t1');}finally{store.close();}
});
test('manual consent on a paused fill-only task preserves the original model budget and run deadline without opening the rest of its batch',async()=>{
 const {runtime,store}=fixture(':memory:',{fillOnly:true});try{const task=await nextWorkbenchTask(runtime);const identity={runId:task.runId,profileId:'p',profileRevision:1,targetId:'target',browserInstance:'browser'};runtime.update(task,{...identity,status:'pending',fillOnlyRun:false,manualSubmissionConsent:{scope:'https://cloud.example|default',...identity}},'fixture_explicit_manual');const batch=store.get('workbenchBatch:b');batch.status='paused';store.set('workbenchBatch:b',batch);assert.equal(batchActionAllowed(runtime,task),true);reserveBatchModelCall(runtime,task);assert.equal(store.get('workbenchBatch:b').unattendedState.modelCallsUsed,1);const expired=store.get('workbenchBatch:b');expired.unattendedState.runDeadlineAt=Date.now()-1;store.set('workbenchBatch:b',expired);assert.equal(batchActionAllowed(runtime,task),false);assert.throws(()=>reserveBatchModelCall(runtime,task),/截止时间/);assert.equal(store.get('workbenchBatch:b').unattendedState.modelCallsUsed,1);assert.equal(store.get('task:t1').status,'pending');assert.equal(store.get('workbenchBatch:b').status,'paused');assert.equal(store.get('paused'),true);}finally{store.close();}
});
test('consecutive failures pause at original threshold without clearing the other combinations',async()=>{
 const {runtime,store}=fixture();try{for(let n=0;n<5;n++){const task=await nextWorkbenchTask(runtime);runtime.update(task,{status:'needs_manual',attentionType:'site_unavailable',reason:'fixture site failure'},'fixture_failure');finishWorkbenchTask(runtime,task.id);store.set('singleTaskId',null);}const batch=store.get('workbenchBatch:b');assert.equal(batch.status,'paused');assert.equal(batch.unattendedState.consecutiveFailures,5);assert.equal(batch.count,6);assert.equal(store.get('task:t5').status,'pending');}finally{store.close();}
});
test('disk reopen retains original deadline, consumed task budget and claim identity rather than restarting them',async()=>{
 const home=await mkdtemp(join(tmpdir(),'el-batch-policy-')),file=join(home,'outbox.sqlite');let fixtureState;
 try{fixtureState=fixture(file);const task=await nextWorkbenchTask(fixtureState.runtime),original=fixtureState.store.get('workbenchBatch:b');fixtureState.store.close();const store=new Store(file),runtime=new Runtime(store,home);fixtureState={store,runtime};const saved=store.get('workbenchBatch:b');initializeBatchPolicy(saved);assert.equal(saved.unattendedState.runDeadlineAt,original.unattendedState.runDeadlineAt);assert.equal(saved.unattendedState.taskBudgetUsed,1);assert.equal(store.get('task:'+task.id).unattendedBatchId,'b');assert.equal(store.get('task:'+task.id).unattendedClaimed,true);assert.equal(store.get('paused'),true);}finally{fixtureState?.store.close();const absolute=resolve(home);assert.ok(absolute.startsWith(resolve(tmpdir())+sep)&&absolute.split(sep).at(-1).startsWith('el-batch-policy-'));await rm(absolute,{recursive:true,force:true});}
});

test('unattended capacity includes preserved manual pages from an earlier batch in the same workspace and counts distinct targets',async()=>{
 const {runtime,store}=fixture(':memory:',{unattendedMaxManualTabs:1});try{store.set('workbenchBatch:previous',{id:'previous',scope:'https://cloud.example|default',status:'waiting_manual'});store.set('task:old',{id:'old',workbenchBatchId:'previous',status:'needs_manual',targetId:'previous-human-page'});assert.equal(await nextWorkbenchTask(runtime),null);assert.equal(store.get('workbenchBatch:b').unattendedState.manualTabCount,1);assert.equal(store.get('task:t0').status,'pending');store.set('task:old',{...store.get('task:old'),tabClosedAt:'human-closed'});assert.equal((await nextWorkbenchTask(runtime)).id,'t0');}finally{store.close();}
});

test('batch runtime deadline pauses every active original task and keeps all pending combinations',async()=>{
 const {runtime,store}=fixture();try{const task=await nextWorkbenchTask(runtime);runtime.update(task,{status:'filling'},'fixture_filling');const batch=store.get('workbenchBatch:b');batch.unattendedState.runDeadlineAt=Date.now()-1;store.set('workbenchBatch:b',batch);runtime.activeTaskIds=new Set([task.id]);watchBatchDeadline(runtime);assert.equal(store.get('paused'),true);assert.equal(store.get('workbenchBatch:b').pauseReasonCode,'deadline');finalizeBatchDeadline(runtime,task);assert.equal(store.get('task:t0').status,'needs_manual');assert.equal(store.get('task:t1').status,'pending');assert.equal(store.get('workbenchBatch:b').count,6);}finally{store.close();}
});

test('native restart parks original in-flight batch tasks using the historical interrupted-status helper and preserves consumed budgets',()=>{
 const {runtime,store}=fixture();try{const batch=store.get('workbenchBatch:b');batch.unattendedState.taskBudgetUsed=2;batch.items[0].status='running';batch.items[1].status='running';store.set('workbenchBatch:b',batch);store.set('task:t0',{...store.get('task:t0'),status:'filling',workbenchBatchId:'b',targetId:'original-form'});store.set('task:t1',{...store.get('task:t1'),status:'submitting',workbenchBatchId:'b',targetId:'original-unknown',attemptBoundary:'original-post-boundary'});const deadline=batch.unattendedState.runDeadlineAt;new Runtime(store,'isolated-reopen');assert.equal(store.get('task:t0').status,U.interruptedTaskStatus({status:'running'}).status);assert.equal(store.get('task:t1').status,U.interruptedTaskStatus({status:'running',submissionAttempted:true}).status);assert.equal(store.get('task:t1').attemptBoundary,'original-post-boundary');assert.equal(store.get('task:t1').targetId,'original-unknown');assert.equal(store.get('workbenchBatch:b').unattendedState.taskBudgetUsed,2);assert.equal(store.get('workbenchBatch:b').unattendedState.runDeadlineAt,deadline);assert.equal(store.get('workbenchBatch:b').items[0].taskId,'t0');assert.equal(store.get('workbenchBatch:b').cursor,2);assert.equal(store.get('task:t2').status,'pending');}finally{store.close();}
});
