import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join,resolve,basename} from 'node:path';
import {Store} from '../executor/src/store.mjs';import {captureFillLearning,flushFillLearning} from '../executor/src/fill-learning.mjs';import {workbenchScope} from '../executor/src/workbench-sync.mjs';
import {libraryMutation} from '../core/library-mutation.mjs';import {destinationFormSchema,applyDestinationFormKnowledge,fillLearningMappings} from '../core/form-knowledge.mjs';
const pair={endpoint:'https://cloud.example',workspaceId:'learning'},profile={id:'p',name:'Original Product',fields:{Name:'Original Product',Url:'https://product.example'}};
const message={profileId:'p',pageUrl:'https://directory.example/form?token=never-remember',identity:{name:'Original Product',url:'https://product.example'},mappings:{title:{profileKey:'Name',value:'Original Product',label:'Product name',hint:'name'},chat:{profileKey:'Discord',value:'https://discord.gg/own-product',label:'Discord invite',hint:'Discord'}},schema:{url:'https://directory.example/form?token=never-remember',forms:[{method:'POST',action:'secret',values:['answers']}],fields:[{name:'title',label:'Product name',type:'text',value:'Original Product',required:true,options:[{value:'option-enum',text:'Option',selected:true,disabled:false}]}],body:'answers',domHash:'answers'}};
const binding={profileId:'p',profile,taskId:'original-task',targetId:'original-target',browserInstance:'original-browser',profileRevision:2};
const documents=()=>({siteProfiles:{p:structuredClone(profile)},siteAnnotations:{'directory.example':{note:'Original note',library:{favorite:true,groups:['high_quality']}}},submissionRecords:{old:{status:'success',taskId:'protected-task',evidence:'Original receipt'}}});
test('destination memory retains field semantics across products and strips answers, URL tokens and selected choices',()=>{
 const docs=documents(),learning=libraryMutation(docs,{id:'one',at:'now',type:'form_learning',profileId:'p',url:message.pageUrl,identity:message.identity,mappings:message.mappings});docs[learning.key]=learning.data;assert.equal(docs.siteProfiles.p.fields.Discord,'https://discord.gg/own-product');assert.equal(docs.siteProfiles.p.fieldNotes.Discord,'填表学习');
 const memory=libraryMutation(docs,{id:'two',at:'now',type:'form_knowledge',url:message.pageUrl,mappings:message.mappings,schema:message.schema});docs[memory.key]=memory.data;const annotation=docs.siteAnnotations['directory.example'];assert.equal(annotation.library.favorite,true);assert.deepEqual(annotation.library.groups,['high_quality']);assert.equal(annotation.note,'Original note');assert.equal(annotation.formKnowledge.mappings.title.value,undefined);assert.equal(annotation.formKnowledge.mappings.title.shared,true);assert.equal(JSON.stringify(annotation.formKnowledge).includes('Original Product'),false);assert.equal(JSON.stringify(annotation.formKnowledge).includes('never-remember'),false);assert.equal(JSON.stringify(annotation.formKnowledge).includes('selected'),false);
 const another=applyDestinationFormKnowledge(docs,{projectKey:'q',brandName:'Another Product',targetDomain:'https://another.example',projectFields:{Name:'Another Product'}},'https://directory.example/form');assert.equal(another.projectFields.Name,'Another Product');assert.equal(another.learnedFieldMappings['directory.example'].title.value,undefined);assert.equal(another.learnedFieldMappings['directory.example'].title.profileKey,'Name');assert.equal(another.destinationFormSchema.url,'https://directory.example/form');assert.deepEqual(docs.submissionRecords.old,{status:'success',taskId:'protected-task',evidence:'Original receipt'});
 const own=applyDestinationFormKnowledge(docs,{learnedFieldMappings:docs.siteProfiles.p.learnedFieldMappings},message.pageUrl);assert.equal(own.learnedFieldMappings['directory.example'].title.value,'Original Product');
 docs.siteProfiles.legacy={learnedFieldMappings:{'directory.example':{unusable:null,valid:{profileKey:'Pricing',label:'Pricing',value:'Free'}}}};const legacy=applyDestinationFormKnowledge(docs,{},message.pageUrl);assert.equal(legacy.learnedFieldMappings['directory.example'].valid.profileKey,'Pricing');assert.equal(legacy.learnedFieldMappings['directory.example'].unusable,undefined);
 const repeated=libraryMutation(docs,{id:'repeat',at:'later',type:'form_knowledge',url:message.pageUrl,mappings:message.mappings,schema:{...message.schema,url:'https://directory.example/form?token=another',fields:message.schema.fields.map(f=>({...f,value:'Changed answer'}))}});assert.equal(repeated.data['directory.example'].formKnowledge.stages.length,1);docs.siteAnnotations=repeated.data;
 for(let index=0;index<14;index++){const next=libraryMutation(docs,{id:'stage'+index,at:'later',type:'form_knowledge',url:message.pageUrl,mappings:{},schema:{url:message.schema.url,fields:[{name:'stage'+index,type:'text'}]}});docs.siteAnnotations=next.data;}assert.equal(docs.siteAnnotations['directory.example'].formKnowledge.stages.length,12);assert.equal(docs.siteAnnotations['directory.example'].formKnowledge.stages.at(-1).fields[0].name,'stage13');assert.equal(docs.siteAnnotations['directory.example'].library.favorite,true);
});
test('field learning cannot replace existing answers, remember credentials or accept invalid profile identity',()=>{
 const docs=documents();docs.siteProfiles.p.fields.Discord='https://discord.gg/kept';const op={id:'one',at:'now',type:'form_learning',profileId:'p',url:message.pageUrl,identity:message.identity,mappings:message.mappings};assert.equal(libraryMutation(docs,op).data.p.fields.Discord,'https://discord.gg/kept');assert.throws(()=>libraryMutation(docs,{...op,identity:{}}),/身份/);assert.throws(()=>libraryMutation(docs,{...op,identity:{...op.identity,name:'Other Product'}}),/身份/);assert.deepEqual(fillLearningMappings({password:{profileKey:'Name',value:'private',label:'Password'}}),{});assert.throws(()=>fillLearningMappings(JSON.parse('{"__proto__":{"profileKey":"Name","value":"private"}}')),/无效/);assert.throws(()=>destinationFormSchema({url:'chrome://extensions',fields:[]}),/网址/);
});
test('offline field learning survives SQLite reopening and lost write acknowledgement resumes the same plan without replay',async()=>{
 const root=await mkdtemp(join(tmpdir(),'externallink-learning-test-'));let store=new Store(join(root,'outbox.sqlite'));try{
  store.set('pair',pair);store.set('paused',true);store.set('acceptanceBatch',{id:'frozen',cursor:13,count:30,status:'paused'});let snapshot={documents:documents(),revisions:{siteProfiles:2,siteAnnotations:1}},online=false,lost=false,writes=[];
  const runtime=()=>({store,cloud:{async request(route,input){assert.ok(store.values('fillLearning:').length);if(!online)throw Error('Offline');if(route==='snapshot')return structuredClone(snapshot);assert.equal(route,'library');const key=input.operation.type==='form_learning'?'siteProfiles':'siteAnnotations';assert.equal(input.revision,snapshot.revisions[key]);const change=libraryMutation(snapshot.documents,input.operation);snapshot.documents[change.key]=change.data;snapshot.revisions[change.key]++;writes.push(input.operation.id);if(lost){lost=false;throw Error('Lost response after write');}return{ok:true};}}});
  const saved=captureFillLearning(runtime(),binding,message);assert.equal(saved.persisted,true);await flushFillLearning(runtime());assert.match(store.get('fillLearning:'+saved.id).error,/Offline/);assert.equal(writes.length,0);
  online=true;lost=true;await flushFillLearning(runtime());const first=store.get('fillLearning:'+saved.id);assert.ok(first.applicationPlanId);const ids=store.get('applicationPlan:'+first.applicationPlanId).items.map(i=>i.id);assert.equal(writes.length,1);store.close();store=new Store(join(root,'outbox.sqlite'));const after=await flushFillLearning(runtime());assert.equal(after.pending,0);assert.deepEqual(writes,ids);assert.equal(store.get('fillLearning:'+saved.id).applicationPlanId,first.applicationPlanId);assert.equal(store.get('fillLearning:'+saved.id).status,'confirmed');assert.equal(snapshot.documents.siteProfiles.p.fields.Discord,'https://discord.gg/own-product');assert.equal(store.get('paused'),true);assert.deepEqual(store.get('acceptanceBatch'),{id:'frozen',cursor:13,count:30,status:'paused'});assert.equal(captureFillLearning(runtime(),binding,message).id,saved.id);assert.equal(writes.length,2);
 }finally{store.close();const target=resolve(root);assert.equal(resolve(tmpdir()),resolve(join(target,'..')));assert.ok(basename(target).startsWith('externallink-learning-test-'));await rm(target,{recursive:true,force:true});}
});
test('renamed products preserve pending original answers and record the excluded profile while sharing semantics',async()=>{
 const store=new Store(':memory:');try{store.set('pair',pair);let snapshot={documents:documents(),revisions:{siteProfiles:2,siteAnnotations:1}};snapshot.documents.siteProfiles.p.name='Renamed Product';snapshot.documents.siteProfiles.p.fields.Name='Renamed Product';let writes=0;const runtime={store,cloud:{async request(route,input){if(route==='snapshot')return structuredClone(snapshot);writes++;assert.equal(input.operation.type,'form_knowledge');const change=libraryMutation(snapshot.documents,input.operation);snapshot.documents[change.key]=change.data;snapshot.revisions[change.key]++;return{ok:true};}}};const saved=captureFillLearning(runtime,binding,message);await flushFillLearning(runtime);assert.equal(store.get('fillLearning:'+saved.id).status,'completed_with_exclusions');assert.equal(store.get('fillLearning:'+saved.id).excludedProfile,true);assert.equal(snapshot.documents.siteProfiles.p.name,'Renamed Product');assert.equal(snapshot.documents.siteProfiles.p.learnedFieldMappings,undefined);assert.equal(writes,1);
 }finally{store.close();}
});
test('workspace switch while flushing cannot write learning or relabel the old cached snapshot',async()=>{
 const store=new Store(':memory:');try{store.set('pair',pair);const scope=workbenchScope(pair),snapshot={documents:documents(),revisions:{siteProfiles:2,siteAnnotations:1}};store.set('applicationSnapshot',{scope,snapshot});let writes=0;const runtime={store,cloud:{async request(route){if(route!=='snapshot'){writes++;return;}store.set('pair',{...pair,workspaceId:'another'});return snapshot;}}};const saved=captureFillLearning(runtime,binding,message);await flushFillLearning(runtime);assert.equal(writes,0);assert.equal(store.get('fillLearning:'+saved.id).scope,scope);assert.equal(store.get('applicationSnapshot').scope,scope);assert.equal(store.get('fillLearning:'+saved.id).status,'pending');
 }finally{store.close();}
});
