import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import worker from '../cloud/worker/src/index.mjs';import {putDeviceMedia} from '../cloud/worker/src/device-media.mjs';import {listOriginalD1Media,resolveOriginalCloudMediaDefaults} from '../core/original-cloud-media.mjs';
const bytes=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jf9sAAAAASUVORK5CYII=','base64'),sha=createHash('sha256').update(bytes).digest('hex');
function fixture(){const objects=new Map();let writes=0;const bucket={head:async key=>objects.get(key)||null,get:async key=>{const o=objects.get(key);return o?{...o,arrayBuffer:async()=>o.bytes.slice().buffer}:null;},put:async(key,value,metadata)=>{if(metadata.onlyIf&&objects.has(key))return null;writes++;objects.set(key,{key,bytes:value instanceof ArrayBuffer?new Uint8Array(value):Uint8Array.from(value),size:value.byteLength,...metadata});},list:async({prefix})=>({objects:[...objects.values()].filter(o=>o.key.startsWith(prefix)),truncated:false})};const env={APP_ACCESS_TOKEN:'test-admin',LEDGER_DB:{},MEDIA_BUCKET:bucket,STATE_BACKEND:'d1'};
 const call=(path,method='GET',headers={},body)=>worker.fetch(new Request('https://fixture.invalid/'+path+'?workspace=default',{method,headers:{Authorization:'Bearer test-admin',...headers},...(body?{body}: {})}),env);return{objects,bucket,call,writes:()=>writes};}
test('same-byte legacy uploads restore zero-based and null original metadata without changing content or unrelated metadata',async()=>{
 const f=fixture();for(const [id,kind,index]of [['logo','logo',null],['cover','featured',null],['screen0','screenshot',0],['screen3','screenshot',3]]){
  const key='workspaces/default/media/'+id;await f.bucket.put(key,bytes,{httpMetadata:{contentType:'image/png',cacheControl:'private'},customMetadata:{retained:'original'}});
  const headers={'Content-Type':'image/png','X-Asset-Sha256':sha,'X-Profile-Id':'JevPlay','X-Media-Kind':kind,'X-Asset-Name':id+'.png',...(index===null?{}:{'X-Media-Index':String(index)})};
  assert.equal((await f.call('v1/media/'+id,'PUT',headers,bytes)).status,200);assert.deepEqual(Buffer.from(f.objects.get(key).bytes),bytes);assert.equal(f.objects.get(key).customMetadata.retained,'original');assert.equal(f.objects.get(key).httpMetadata.cacheControl,'private');
 }
 const assets=(await(await f.call('v2/media')).json()).assets;assert.deepEqual(assets.map(a=>[a.asset_id,a.profile_id,a.media_kind,a.media_index]),[['logo','JevPlay','logo',null],['cover','JevPlay','featured',null],['screen0','JevPlay','screenshot',0],['screen3','JevPlay','screenshot',3]]);
 const defaults=await resolveOriginalCloudMediaDefaults({id:'JevPlay'},()=>listOriginalD1Media(f.bucket,'default'));assert.deepEqual(defaults.originalMediaDefaults.screenshots,['cloud-media://screen0','cloud-media://screen3']);
 const before=f.writes();assert.equal((await f.call('v2/media/screen0','PUT',{'Content-Type':'image/png','X-Asset-Sha256':sha,'X-Media-Index':'1.2'},bytes)).status,400);assert.equal(f.writes(),before);
 assert.equal((await f.call('v2/media/screen0','PUT',{'Content-Type':'image/png','X-Asset-Sha256':'0'.repeat(64)},bytes)).status,400);assert.equal(f.writes(),before);
 const changed=Buffer.from(bytes);changed[changed.length-1]^=1;assert.equal((await f.call('v2/media/screen0','PUT',{'Content-Type':'image/png','X-Asset-Sha256':createHash('sha256').update(changed).digest('hex')},changed)).status,409);assert.equal(f.writes(),before);assert.deepEqual(Buffer.from(f.objects.get('workspaces/default/media/screen0').bytes),bytes);
});
test('device uploads preserve all four screenshot slot indices in catalogue and frozen original defaults',async()=>{
 const f=fixture();for(let index=1;index<=4;index++)await putDeviceMedia(f.bucket,'default',{assetId:'asset-11111111-1111-4111-8111-11111111111'+index,profileId:'JevPlay',kind:'screenshot'+index,mime:'image/png',dataUrl:'data:image/png;base64,'+bytes.toString('base64'),sha256:sha,fileName:'screen'+index+'.png'},{JevPlay:{id:'JevPlay'}});
 const assets=(await(await f.call('v2/media')).json()).assets;assert.deepEqual(assets.map(row=>row.media_index),[1,2,3,4]);const defaults=await resolveOriginalCloudMediaDefaults({id:'JevPlay'},()=>listOriginalD1Media(f.bucket,'default'));assert.deepEqual(defaults.originalMediaDefaults.screenshots,assets.map(row=>'cloud-media://'+row.asset_id));
});
