import test from 'node:test';
import assert from 'node:assert/strict';
import {lookupDomainMetrics,authoritativeRdapUrls} from '../cloud/worker/src/rdap-domain-metrics.mjs';
const now=Date.parse('2026-10-09T00:00:00Z'),data={events:[{eventAction:'registration',eventDate:'2000-01-01T00:00:00Z'},{eventAction:'expiration',eventDate:'2030-01-01T00:00:00Z'}]},bootstrap={services:[[['com'],['https://registry.example/com/v1/']],[['tools'],['https://tools.example/rdap/']]]};
test('a working original RDAP service retains original dates and age calculation without bootstrap requests',async()=>{const calls=[],rows=await lookupDomainMetrics(['producthunt.com'],{now,fetchImpl:async url=>{calls.push(url);return Response.json(data);}});assert.deepEqual(calls,['https://rdap.org/domain/producthunt.com']);assert.equal(rows[0].createdAt,data.events[0].eventDate);assert.equal(rows[0].expiresAt,data.events[1].eventDate);assert.equal(rows[0].ageDays,Math.floor((now-Date.parse(data.events[0].eventDate))/86400000));assert.equal(rows[0].ageMonths,Math.floor(rows[0].ageDays/30.4375));});
test('a failed public redirector uses one IANA bootstrap for distinct registries and preserves the original batch result order',async()=>{const calls=[],rows=await lookupDomainMetrics(['producthunt.com','bai.tools'],{now,fetchImpl:async url=>{calls.push(url);if(url.startsWith('https://rdap.org/'))return new Response('Forbidden',{status:403});if(url==='https://data.iana.org/rdap/dns.json')return Response.json(bootstrap);return Response.json(data);}});assert.equal(calls.filter(url=>url==='https://data.iana.org/rdap/dns.json').length,1);assert.ok(calls.includes('https://registry.example/com/v1/domain/producthunt.com'));assert.ok(calls.includes('https://tools.example/rdap/domain/bai.tools'));assert.deepEqual(rows.map(row=>[row.domain,row.status]),[['producthunt.com','ok'],['bai.tools','ok']]);});
test('authoritative service discovery uses the longest label suffix and rejects non-HTTPS credential and query endpoints',()=>{assert.deepEqual(authoritativeRdapUrls('tool.co.uk',{services:[[['uk'],['https://short.example/']],[['co.uk'],['http://insecure.example/','https://user:pass@bad.example/','https://query.example/?url=','https://long.example/api/']],[['eviluk'],['https://wrong.example/']]]}),['https://long.example/api/domain/tool.co.uk']);assert.deepEqual(authoritativeRdapUrls('tool.invalid',bootstrap),[]);});
test('a missing service or registry failure remains unknown and retries the next IANA service without guessing an age',async()=>{const calls=[],rows=await lookupDomainMetrics(['tool.com','tool.invalid'],{now,fetchImpl:async url=>{calls.push(url);if(url==='https://data.iana.org/rdap/dns.json')return Response.json({services:[[['com'],['https://first.example/','https://second.example/']]]});if(url.startsWith('https://second.example/'))return Response.json(data);return new Response('',{status:503});}});assert.equal(rows[0].status,'ok');assert.equal(rows[1].status,'unknown');assert.equal(rows[1].ageMonths,undefined);assert.ok(calls.includes('https://second.example/domain/tool.com'));assert.match(rows[1].message,/IANA/);});
test('timeouts malformed bootstrap and malformed registry JSON never become successful domain ages',async()=>{for(const kind of ['timeout','bootstrap-json','registry-json']){const rows=await lookupDomainMetrics(['tool.com'],{now,fetchImpl:async url=>{if(url.startsWith('https://rdap.org/'))throw Error('Timeout');if(url==='https://data.iana.org/rdap/dns.json'){if(kind==='timeout')throw Error('Bootstrap timeout');return Response.json(kind==='bootstrap-json'?{}:bootstrap);}return new Response('Not JSON');}});assert.equal(rows[0].status,'unknown');assert.equal(rows[0].ageMonths,undefined);}});
