// Thin operator client. All decisions and durable state stay in the one server.
import { readFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { Store } from './store.mjs';
const home=process.env.EXTERNALLINK_HOME || path.join(os.homedir(),'.externallink-executor');
const [action='status',inputFile]=process.argv.slice(2);
const allowed=new Set(['status','catalog','profile','preview','start','pause','resume','runOne','sync','takeover','verify','review','annotate','prepareRetry','retryRejected','retryAfterLogin','correctReceiptStatus','connectHost','attachPage','openEntry','googleLogin','retryNoAction','closeTaskTab']);
allowed.add('observeTask');
allowed.add('closeObservation');
allowed.add('claimTask');
allowed.add('authorizeMarketing');
allowed.add('registerAccount');
allowed.add('verifyRegistration');
allowed.add('retryPrefillOnly');
allowed.add('finishProductPreview');
allowed.add('annotateObservation');
allowed.add('advancePlan');
allowed.add('inspectCookiePreferences');
allowed.add('verifyPlanStage');
allowed.add('enableFunctionalCookies');
allowed.add('acceptAuthorizedCookies');
allowed.add('recoverToolScoutLogout');
allowed.add('continueUnsubmitted');
allowed.add('finishCommunityVisit');
allowed.add('requestLoginLink','restoreLostPreparation');
allowed.add('startLibrary');
allowed.add('basicGoogleLogin');
if(!allowed.has(action))throw new Error('不支持的业务操作');
const store=new Store(path.join(home,'outbox.sqlite'),{readOnly:true});const pair=store.get('pair');store.close();
if(!pair)throw new Error('请先在原插件中配对');
const server=JSON.parse(await readFile(path.join(home,'server.json'),'utf8'));
const body=['status','catalog'].includes(action)?undefined:inputFile?JSON.parse(await readFile(inputFile,'utf8')):{};
const response=await fetch(server.endpoint+'/'+action,{method:body?'POST':'GET',headers:{Authorization:`Bearer ${pair.localToken}`,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(120000)});
const data=await response.json();if(!response.ok)throw new Error(data.error);console.log(JSON.stringify(data,null,2));
