import assert from 'node:assert/strict';
import http from 'node:http';
import {mkdtemp,readFile,rm} from 'node:fs/promises';
import {join,resolve,sep} from 'node:path';
import {tmpdir} from 'node:os';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
import {chromium} from 'playwright';
import {Store} from '../src/store.mjs';
import {workbenchScope} from '../src/workbench-sync.mjs';
import Worker from '../../cloud/worker/src/index.mjs';
import {aiCloudFixture} from './fixtures/ai-cloud.mjs';
const home=await mkdtemp(join(tmpdir(),'el-ai-browser-')),f=aiCloudFixture(),realFetch=globalThis.fetch;
let backend,web,browser,store,releaseModel,external=0;
globalThis.fetch=(url,options)=>new URL(typeof url==='string'?url:url.url).hostname==='127.0.0.1'?realFetch(url,options):f.fetch(url,options);
const cloud=http.createServer(async(req,res)=>{try{const body=[];for await(const chunk of req)body.push(chunk);const response=await Worker.fetch(new Request('https://worker.fixture.invalid'+req.url,{method:req.method,headers:req.headers,...(!['GET','HEAD'].includes(req.method)?{body:Buffer.concat(body)}:{})}),f.env);res.writeHead(response.status,{'Content-Type':'application/json'});res.end(await response.text());}catch(error){res.writeHead(500,{'Content-Type':'application/json'});res.end(JSON.stringify({ok:false,error:error.message}));}});
await new Promise(done=>cloud.listen(0,'127.0.0.1',done));const endpoint='http://127.0.0.1:'+cloud.address().port;
const remote=async(route,token,body)=>{const response=await fetch(endpoint+'/v2/executor/'+route+'?workspace=default',{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});assert.equal(response.status,200);return response.json();};
const local=async(route,body)=>{const response=await fetch(backend.endpoint+route,{method:'POST',headers:{Authorization:'Bearer fixture-local','Content-Type':'application/json'},body:JSON.stringify(body)});return{status:response.status,data:await response.json()};};
async function start(name){const child=spawn(process.execPath,[resolve(import.meta.dirname,'../src/'+name)],{windowsHide:true,env:{...process.env,EXTERNALLINK_HOME:home,EXTERNALLINK_PORT:'0',EXTERNALLINK_WEB_PORT:'0'},stdio:['ignore','pipe','pipe']});let errors='';child.stderr.on('data',part=>errors+=part);child.stdout.resume();const service={child};if(name==='server.mjs')backend=service;else web=service;for(let n=0;n<100;n++){if(child.exitCode!==null)throw Error('fixture service exited: '+errors);try{const state=JSON.parse(await readFile(join(home,name==='server.mjs'?'server.json':'workbench.json'),'utf8'));if(state.pid===child.pid){service.endpoint=state.endpoint;return;}}catch{}await new Promise(done=>setTimeout(done,50));}throw Error('fixture service startup exceeded observation budget');}
async function stop(service){if(service?.child.exitCode===null&&service.child.signalCode===null){const ended=once(service.child,'exit');service.child.kill();await ended;}}
const protectedNative=s=>JSON.stringify([s.valuesByInsertion('task:'),s.get('acceptanceBatch'),s.get('workbenchBatch:original'),s.pending(),s.logs({scope:workbenchScope(s.get('pair'))})]);
const protectedCloud=()=>JSON.stringify(f.sqlite.prepare('SELECT * FROM documents ORDER BY key').all());
try{
 const docs={siteProfiles:{p:{id:'p',name:'原产品',fields:{Name:'原产品',Url:'https://product.fixture.invalid',Title:'原宣传标题'},fieldNotes:{Name:'Original note'},media:{screenshots:[]}}},activeSiteId:'p',selectedSiteIds:['p'],urlList:'https://article.fixture.invalid/post',siteAnnotations:{},targetFilters:{aiComments:true,aiCommentAllowLink:false},submissionRecords:{original:{status:'success',evidence:'Original receipt'}},linkMonitorSchedule:{enabled:false,minutes:1440}};
 for(const [key,data]of Object.entries(docs))await f.ledger.putDocument(key,data,0);
 const enrolled=await remote('devices','fixture-admin',{}),pair={endpoint,storageBackend:'d1',...enrolled,localToken:'fixture-local'},scope=workbenchScope(pair);
 const registered=await remote('runs',pair.deviceToken,{run:{id:'original-run',profileId:'p',profileRevision:1,createdAt:'2026-10-07T00:00:00Z',mode:'single_page_preparation',authorization:'fill_only',feeLimit:0,tasks:[{id:'original-task',url:'https://article.fixture.invalid/post',destinationKey:'article.fixture.invalid/post'}]}});
 store=new Store(join(home,'outbox.sqlite'));store.set('pair',pair);store.set('paused',true);store.set('applicationSnapshot',{scope,snapshot:await remote('snapshot',pair.deviceToken)});store.set('run:original-run',registered.run);store.set('task:original-task',{...registered.tasks[0],status:'submitted_unconfirmed',attemptBoundary:'original-boundary',profileSnapshot:docs.siteProfiles.p});store.set('acceptanceBatch',{id:'original-fixed',status:'paused',cursor:13,count:30});store.set('workbenchBatch:original',{id:'original',status:'paused',cursor:13,usedTasks:13,usedAiActions:4,items:[{taskId:'original-task'}]});const before=protectedNative(store),cloudBefore=protectedCloud();store.close();store=null;
 await start('server.mjs');await start('workbench-server.mjs');
 const input={profileId:'p',pageUrl:'https://article.fixture.invalid/post',count:3,pageText:'Supplied original article',language:'zh'},first=await local('/commentDrafts',input);assert.equal(first.status,200);let count=f.state.modelCalls;const cached=await local('/commentDrafts',input);assert.equal(cached.data.cached,true);assert.equal(f.state.modelCalls,count);const forced=await local('/commentDrafts',{...input,refresh:true});assert.equal(forced.status,200);assert.equal(f.state.modelCalls,count+1);assert.notEqual(forced.data.drafts[0].text,first.data.drafts[0].text);
 const originalHistory=(await local('/commentHistory',input)).data;f.state.status=402;const failed=await local('/commentDrafts',{...input,refresh:true});assert.equal(failed.status,503);assert.match(failed.data.error,/额度|余额/);assert.deepEqual((await local('/commentHistory',input)).data,originalHistory);f.state.status=200;
 browser=await chromium.launch({channel:'chrome',headless:true,args:['--disable-extensions']});const context=await browser.newContext(),page=await context.newPage(),errors=[];page.on('pageerror',error=>errors.push(error.message));await context.route('**/*',async route=>{if(new URL(route.request().url()).origin!==web.endpoint){external++;await route.abort();return;}await route.continue();});
 await page.goto(web.endpoint+'/#access=fixture-local');await page.getByRole('button',{name:'AI 评论',exact:true}).click();await page.getByLabel('评论页面网址',{exact:true}).fill(input.pageUrl);await page.getByLabel('文章内容',{exact:true}).fill(input.pageText);await page.getByRole('button',{name:'生成 3 条评论',exact:true}).click();await page.getByText('评论已生成并保存在本机。',{exact:true}).waitFor();const firstText=await page.getByLabel('评论候选 1',{exact:true}).inputValue();await page.getByLabel('评论候选 1',{exact:true}).fill('Edited original candidate');await page.getByRole('button',{name:'保存编辑后的草稿',exact:true}).click();await page.getByText('编辑后的草稿已保存。',{exact:true}).waitFor();count=f.state.modelCalls;
 await page.getByRole('button',{name:'生成 3 条评论',exact:true}).click();await page.waitForFunction(previous=>document.querySelector('[aria-label="评论候选 1"]')?.value!==previous,'Edited original candidate');assert.notEqual(await page.getByLabel('评论候选 1',{exact:true}).inputValue(),firstText);assert.equal(f.state.modelCalls,count+1);
 await page.getByRole('button',{name:'恢复上一版',exact:true}).click();await page.getByText('上一版已恢复，当前版本仍在历史记录中。',{exact:true}).waitFor();assert.equal(await page.getByLabel('评论候选 1',{exact:true}).inputValue(),'Edited original candidate');
 await page.getByRole('button',{name:'我的网站',exact:true}).click();await page.getByRole('button',{name:'资料与媒体',exact:true}).click();f.state.hold=new Promise(done=>releaseModel=done);count=f.state.modelCalls;await page.getByRole('button',{name:'从网站提取资料',exact:true}).click();for(let n=0;n<100&&f.state.modelCalls===count;n++)await new Promise(done=>setTimeout(done,20));assert.equal(f.state.modelCalls,count+1);await page.getByLabel('产品名称',{exact:true}).fill('Typed during extraction');releaseModel();f.state.hold=null;await page.getByText('网站资料已提取并填入表单，请检查后保存。',{exact:true}).waitFor();assert.equal(await page.getByLabel('产品名称',{exact:true}).inputValue(),'Typed during extraction');assert.match(await page.getByLabel('宣传标题',{exact:true}).inputValue(),/^Generated title /);await page.getByRole('button',{name:'AI 补全产品资料',exact:true}).click();await page.getByText('资料草稿已补全，请检查后保存。',{exact:true}).waitFor();
 assert.deepEqual(errors,[]);assert.equal(external,0);await browser.close();browser=null;await stop(web);await stop(backend);store=new Store(join(home,'outbox.sqlite'));assert.equal(protectedNative(store),before);assert.equal(protectedCloud(),cloudBefore);assert.ok(store.values('commentHistory:')[0].versions.some(version=>version.payload.drafts[0].text==='Edited original candidate'));assert.equal(f.sqlite.prepare('SELECT count(*) n FROM executor_runs').get().n,1);assert.equal(f.sqlite.prepare('SELECT count(*) n FROM executor_events').get().n,0);
 console.log(JSON.stringify({ok:true,kind:'actual_worker_native_services_and_chrome_original_ai',cacheHitSkipsProvider:true,explicitGenerationRefreshes:true,failedGenerationRetainsHistory:true,editedPreviousVersionRestored:true,lateTypedExtractionPreserved:true,profileGenerationDraftOnly:true,originalDocumentsTasksAndFrozenBudgetUnchanged:true,fixtureModelCalls:f.state.modelCalls,fixturePageReads:f.state.pageReads,newRuntimeRuns:0,cloudEvents:0,browserExternalRequests:external,realProviderRequests:0,newRealSubmissions:0}));
}finally{releaseModel?.();f.state.hold=null;store?.close();await browser?.close();await stop(web);await stop(backend);await new Promise(done=>cloud.close(done));globalThis.fetch=realFetch;f.sqlite.close();const target=resolve(home);assert.ok(target.startsWith(resolve(tmpdir())+sep)&&target.split(sep).at(-1).startsWith('el-ai-browser-'));await rm(target,{recursive:true,force:true});}
console.log(JSON.stringify({fixtureCleanupCompleted:true}));
