import assert from 'node:assert/strict';import http from 'node:http';import {readFile} from 'node:fs/promises';import {chromium} from 'playwright';
const products=[{id:'p',name:'Actual Product',url:'https://product.example',fields:{Name:'Actual Product',Url:'https://product.example','Business mail':'owner@example.com','Long description':'Actual description'}},{id:'q',name:'Second Product',fields:{Name:'Second Product'}}];
const tasks=[{id:'t',profileId:'p',url:'https://site0.example/submit',status:'finished',receipt:{evidence:'Received',publicationStatus:'pending_moderation'},syncStatus:'confirmed'}];
const snapshot={ok:true,at:new Date().toISOString(),cached:true,revisions:{siteProfiles:2},model:{products,total:45,library:Array.from({length:45},(_,i)=>({site:'site'+i+'.example',url:'https://site'+i+'.example/submit',source:'cloud.urlList',annotation:{}})),combinations:[{site:'site0.example',profileId:'p',taskIds:['t'],records:[],submission:'received',execution:'finished',review:'pending',reply:'unknown',publication:'unknown',sync:'confirmed'}]},runtime:{paused:true,busy:false,pendingEvents:0},tasks,acceptances:[]};
const writes=[];const server=http.createServer(async(req,res)=>{const pathname=new URL(req.url,'http://localhost').pathname;let input='';for await(const chunk of req)input+=chunk;
 if(['/', '/application.js','/application.css'].includes(pathname)){const file=pathname==='/'?'application.html':pathname.slice(1);res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(await readFile(new URL('../web/'+file,import.meta.url)));return;}
 res.setHeader('Content-Type','application/json');if(pathname==='/appData')res.end(JSON.stringify(snapshot));else if(pathname==='/connection')res.end('{"ok":true}');else if(pathname==='/profile'){const body=JSON.parse(input);writes.push(body);Object.assign(products[0].fields,body.profile.fields);res.end('{"ok":true}');}else if(pathname==='/taskDetails')res.end(JSON.stringify({ok:true,task:tasks[0]}));else res.end('{"ok":false,"error":"Unexpected request"}');
});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const browser=await chromium.launch({channel:'chrome',headless:true,args:['--disable-extensions']});
try{const page=await browser.newPage();const errors=[];page.on('pageerror',error=>errors.push(error.message));await page.goto('http://127.0.0.1:'+server.address().port+'/#access=fixture');await page.getByRole('heading',{name:'Actual Product',exact:true}).waitFor();
 assert.equal(await page.locator('nav button').count(),4);assert.equal(await page.evaluate(()=>typeof chrome.runtime),'undefined');assert.equal(await page.evaluate(()=>location.hash),'');
 await page.getByRole('button',{name:'外链库',exact:true}).click();assert.equal(await page.locator('tbody tr').count(),40);await page.getByRole('button',{name:'下一页',exact:true}).click();assert.equal(await page.locator('tbody tr').count(),5);
 await page.getByRole('button',{name:'提交总览',exact:true}).click();await page.getByRole('button',{name:/已收件 审核/}).click();assert.match(await page.locator('dialog').innerText(),/site0.example/);await page.getByRole('button',{name:'关闭详情'}).click();
 await page.getByRole('button',{name:'我的网站',exact:true}).click();await page.getByRole('button',{name:'资料与媒体',exact:true}).first().click();await page.getByLabel('Long description',{exact:true}).fill('Revised actual description');await page.getByRole('button',{name:'保存资料',exact:true}).click();await page.getByText('已保存并回读云端；历史投稿保留旧版本。',{exact:true}).waitFor();assert.equal(writes.length,1);assert.equal(writes[0].profile.fields['Long description'],'Revised actual description');
 assert.deepEqual(errors,[]);console.log(JSON.stringify({ok:true,kind:'synthetic_ui_regression',pages:4,extensionInstalled:false,libraryPagination:true,profileSave:true}));
}finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
