import assert from'node:assert/strict';import{mkdtemp,rm}from'node:fs/promises';import{tmpdir}from'node:os';import{join,resolve,sep}from'node:path';import{chromium}from'playwright';
import{Store}from'../src/store.mjs';import{Runtime}from'../src/runtime.mjs';import{getTargetInfo}from'../src/browser-target.mjs';import{checkBrowserAssistant,stopBrowserAssistant}from'../src/browser-assistant.mjs';import{workbenchScope}from'../src/workbench-sync.mjs';import{applicationMutation}from'../../core/application-mutation.mjs';
const home=await mkdtemp(join(tmpdir(),'el-auto-visit-')),browser=await chromium.launch({channel:'chrome',headless:true,args:['--disable-extensions']}),context=await browser.newContext();let posts=0,external=0,registrations=0,lost=false,onSnapshot,store=new Store(join(home,'outbox.sqlite')),runtime;
const form='<form><label>Product name<input name="productName" id="name" required></label><label>Website<input name="website" id="website" type="url" required></label><label>Email<input name="email" id="email" type="email" required></label><label>Description<textarea name="description" id="description" required></textarea></label><button type="submit">Submit product</button></form>';
const profile={id:'p',name:'Original Product',fields:{Name:'Original Product',Url:'https://product.example','Business mail':'owner@example.com','Long description (250-500 words)':'A useful original product for checking automatic form recovery.'}},snapshot={documents:{siteProfiles:{p:profile},activeSiteId:'p',submissionRecords:{},sheetTableData:{entries:[]},autoFillOnVisit:false},revisions:{siteProfiles:2,sheetTableData:1,autoFillOnVisit:1}},runs=new Map(),remoteTasks=new Map();
await context.route('**/*',async route=>{const request=route.request(),url=new URL(request.url());if(!url.hostname.endsWith('.fixture.invalid'))external++;if(request.method()==='POST')posts++;let body=form;if(url.pathname==='/dynamic')body='<title>Directory loading</title><h1>Submit your product</h1>';if(url.pathname==='/iframe')body='<title>Embedded directory</title><iframe src="/inner"></iframe>';if(url.pathname==='/article')body='<title>Preserve original identities</title><article><h1>Preserve original identities</h1><p>Task recovery should not lose the original receipt.</p></article><form id="commentform"><textarea name="comment" id="comment"></textarea><input name="author"><input name="email"><input name="url"><button type="submit">Post Comment</button></form>';await route.fulfill({status:200,contentType:'text/html',body:'<!doctype html>'+body});});
const pair={endpoint:'https://cloud.fixture.invalid',workspaceId:'auto-visit'};store.set('pair',pair);store.set('paused',true);store.set('acceptanceBatch',{status:'paused',cursor:13,count:30});
const cloud={async request(route,input){if(route==='snapshot'){await onSnapshot?.();return structuredClone(snapshot);}if(route==='runs?view=inventory')return{runs:[...runs.values()],tasks:[...remoteTasks.values()]};if(route.startsWith('runs?runId=')){const id=decodeURIComponent(route.split('=')[1]);return{runs:runs.has(id)?[structuredClone(runs.get(id))]:[],tasks:[...remoteTasks.values()].filter(t=>t.runId===id)};}if(route.startsWith('tasks/'))return{task:structuredClone(remoteTasks.get(route.slice(6)))};if(route==='runs'){assert.ok(runtime.store.values('singlePagePlan:').some(plan=>plan.run.id===input.run.id&&plan.status==='registering'));registrations++;const run={...input.run,profile:structuredClone(snapshot.documents.siteProfiles.p)},task={...input.run.tasks[0],runId:run.id,profileId:'p',status:'needs_manual',version:1,attentionType:'fill_only'};assert.equal(run.authorization,'fill_only');runs.set(run.id,run);remoteTasks.set(task.id,task);if(lost){lost=false;throw Error('lost registration reply');}return{ok:true,run,tasks:[task]};}if(route==='library'){const change=applicationMutation(snapshot.documents,input.operation);snapshot.documents[change.key]=change.data;snapshot.revisions[change.key]=(snapshot.revisions[change.key]||0)+1;return{ok:true};}throw Error('Unexpected '+route);}};
function bind(){runtime=new Runtime(store,home);runtime.context=context;runtime.host={startedAt:'original-browser'};Object.defineProperty(runtime,'cloud',{value:cloud});runtime.lease=async()=>{};runtime.synchronize=async()=>{for(const event of store.pending()){remoteTasks.set(event.taskId,event.state);store.ack(event.id);}};runtime.tick=()=>{throw Error('Automatic visiting must only prepare');};runtime.dispatchControl=(action,input)=>runtime.control(action,input);runtime.findPage=async task=>{for(const page of context.pages())if((await getTargetInfo(context,page))?.targetId===task.targetId)return page;throw Error('Original target missing');};store.set('applicationSnapshot',{scope:workbenchScope(pair),snapshot:structuredClone(snapshot)});}
async function target(host,path='/submit'){const page=await context.newPage();await page.goto('https://'+host+'.fixture.invalid'+path);return page;}
function eligible(page){snapshot.documents.sheetTableData.entries.push({link:page.url(),indexPage:page.url(),name:'Original target'});snapshot.revisions.sheetTableData++;store.set('applicationSnapshot',{scope:workbenchScope(pair),snapshot:structuredClone(snapshot)});}
async function settled(){await checkBrowserAssistant(runtime);await new Promise(resolve=>setTimeout(resolve,25));}
try{
 bind();store.set('browserAssistantSettings',{scope:workbenchScope(pair),enabled:true,autoFillOnVisit:false,profileId:'p'});const page=await target('unregistered');eligible(page);await settled();assert.equal(await page.locator('#name').inputValue(),'');assert.equal(registrations,0);
 await runtime.control('saveAssistantSettings',{enabled:true,autoFillOnVisit:true,profileId:'p'});await settled();assert.equal(await page.locator('#name').inputValue(),'Original Product','enabling on an already connected page must match and prepare its unregistered pending target');assert.equal(await page.locator('#website').inputValue(),'https://product.example');assert.equal(registrations,1);assert.equal(posts,0);await settled();assert.equal(registrations,1);const first=store.values('task:')[0];assert.equal(first.attemptBoundary,undefined);assert.equal(first.profileRevision,2);assert.equal(store.get('submissionQueue').key,first.destinationKey);assert.equal(store.values('assistantFill:')[0].queueTotal,1);
 const later=await target('later-added');await settled();assert.equal(await later.locator('#name').inputValue(),'');const before=registrations;eligible(later);await settled();assert.equal(await later.locator('#name').inputValue(),'Original Product');assert.equal(registrations,before+1);
 const dynamic=await target('dynamic','/dynamic');eligible(dynamic);await settled();const beforeMount=registrations;assert.equal(beforeMount,before+1);await dynamic.evaluate(html=>document.body.insertAdjacentHTML('beforeend',html),form);await settled();assert.equal(await dynamic.locator('#name').inputValue(),'Original Product');assert.equal(registrations,beforeMount+1);
 const cancelledPage=await target('cancelled-then-enabled');eligible(cancelledPage);const cancelInfo=await getTargetInfo(context,cancelledPage),cancelPanel=await runtime.control('sidepanelOpened',{profileId:'p',targetId:cancelInfo.targetId});await settled();assert.ok(runtime.sidepanelAutoTimers.size);await runtime.control('saveAssistantSettings',{enabled:true,autoFillOnVisit:false,profileId:'p'});assert.equal(runtime.sidepanelAutoTimers.size,0);const cancelledRecord=store.values('assistantFill:').find(f=>f.targetId===cancelInfo.targetId);assert.equal(cancelledRecord.status,'cancelled');await new Promise(resolve=>setTimeout(resolve,650));assert.equal(await cancelledPage.locator('#name').inputValue(),'');await runtime.control('saveAssistantSettings',{enabled:true,autoFillOnVisit:true,profileId:'p'});await settled();await new Promise(resolve=>setTimeout(resolve,750));assert.equal(await cancelledPage.locator('#name').inputValue(),'Original Product','turning back on must resume the cancelled original page');assert.equal(store.get(cancelledRecord.fillKey).status,'prepared');assert.ok(store.get(cancelledRecord.fillKey).history.some(h=>h.status==='cancelled'));await settled();assert.equal(store.values('task:').filter(t=>t.targetId===cancelInfo.targetId).length,1);await runtime.control('sidepanelClosed',{panelId:cancelPanel.panel.id});
 const embedded=await target('embedded','/iframe');eligible(embedded);await embedded.frameLocator('iframe').locator('#name').waitFor();await settled();assert.equal(await embedded.frameLocator('iframe').locator('#name').inputValue(),'Original Product');
 const other=await target('other-product');eligible(other);await other.locator('#name').fill('Other product');await other.locator('#website').fill('https://other-product.example');const guarded=registrations;await settled();assert.equal(await other.locator('#name').inputValue(),'Other product');assert.equal(registrations,guarded);
 const article=await target('article','/article');eligible(article);await settled();assert.equal(await article.locator('#comment').inputValue(),'');assert.equal(registrations,guarded);
 const unknown=await target('unknown-attempt');eligible(unknown);store.set('task:unknown',{id:'unknown',runId:'original-unknown-run',profileId:'p',url:unknown.url(),status:'submitted_unconfirmed',attemptBoundary:'original-boundary'});await settled();assert.equal(await unknown.locator('#name').inputValue(),'');assert.equal(registrations,guarded);assert.equal(store.get('task:unknown').attemptBoundary,'original-boundary');
 const parked=await target('parked-login');eligible(parked);remoteTasks.set('remote-login',{id:'remote-login',runId:'remote-login-run',profileId:'p',url:parked.url(),status:'needs_manual',attentionType:'login'});await settled();assert.equal(await parked.locator('#name').inputValue(),'');assert.equal(registrations,guarded);
 // A later same-host unknown attempt must also protect an already bound task.
 await page.locator('#name').fill('');store.set('task:other-unknown',{id:'other-unknown',profileId:'p',url:page.url().replace('/submit','/alternate'),status:'submitted_unconfirmed',attemptBoundary:'same-host-original-boundary'});const originalTarget=await getTargetInfo(context,page);await assert.rejects(runtime.control('fillAssistantTask',{taskId:first.id,profileId:'p',targetId:originalTarget.targetId,url:page.url()}),/同站|未知尝试/);assert.equal(await page.locator('#name').inputValue(),'');assert.equal(registrations,guarded);
 const stage=await target('stage-page','/actual-form');eligible(stage);snapshot.documents.sheetTableData.entries.at(-1).link=stage.url().replace('/actual-form','/submit');snapshot.documents.sheetTableData.entries.at(-1).indexPage=snapshot.documents.sheetTableData.entries.at(-1).link;store.set('applicationSnapshot',{scope:workbenchScope(pair),snapshot:structuredClone(snapshot)});await settled();assert.equal(await stage.locator('#name').inputValue(),'Original Product');assert.equal(store.values('task:').find(t=>t.targetId===store.values('assistantFill:').find(f=>f.url===stage.url()).targetId).url,stage.url().replace('/actual-form','/submit'));const originalSettings=store.get('browserAssistantSettings'),raced=await target('preference-race');eligible(raced);const racedInfo=await getTargetInfo(context,raced);runtime.lease=async()=>store.set('browserAssistantSettings',{...originalSettings,enabled:false});await assert.rejects(runtime.control('fillAssistantTask',{profileId:'p',targetId:racedInfo.targetId,url:raced.url()}),/设置/);assert.equal(await raced.locator('#name').inputValue(),'');runtime.lease=async()=>{};store.set('browserAssistantSettings',originalSettings);const afterLeaseRace=registrations;
 const scopePage=await target('scope-race');eligible(scopePage);const scopeInfo=await getTargetInfo(context,scopePage);onSnapshot=()=>store.set('pair',{...pair,workspaceId:'other-workspace'});await assert.rejects(runtime.control('fillAssistantTask',{profileId:'p',targetId:scopeInfo.targetId,url:scopePage.url()}),/工作区/);assert.equal(await scopePage.locator('#name').inputValue(),'');assert.equal(registrations,afterLeaseRace);onSnapshot=null;store.set('pair',pair);const closedPanel=await runtime.control('sidepanelOpened',{profileId:'p',targetId:scopeInfo.targetId});await runtime.control('sidepanelClosed',{panelId:closedPanel.panel.id});await assert.rejects(runtime.control('fillAssistantTask',{profileId:'p',targetId:scopeInfo.targetId,url:scopePage.url(),panelId:closedPanel.panel.id,panelGeneration:closedPanel.panel.generation}),/面板/);assert.equal(registrations,afterLeaseRace);await raced.close();await scopePage.close();const beforeRecovery=registrations;
 const recovery=await target('lost-reply');eligible(recovery);lost=true;await settled();assert.equal(await recovery.locator('#name').inputValue(),'');assert.equal(registrations,beforeRecovery+1);const plan=store.values('singlePagePlan:').find(item=>item.status==='registration_unknown'),originalId=plan.run.tasks[0].id,targetInfo=await getTargetInfo(context,recovery);assert.ok(originalId);await stopBrowserAssistant(runtime);store.close();store=new Store(join(home,'outbox.sqlite'));snapshot.documents.siteProfiles.p={...profile,fields:{...profile.fields,Name:'New cloud name'}};snapshot.revisions.siteProfiles=7;bind();const resumed=await runtime.control('fillAssistantTask',{targetId:targetInfo.targetId,url:recovery.url(),profileId:'p'});assert.equal(resumed.submitted,false);assert.equal(resumed.taskId,originalId);assert.equal(registrations,beforeRecovery+1);assert.equal(await recovery.locator('#name').inputValue(),'Original Product');assert.equal(store.get('task:'+originalId).profileRevision,2);
 assert.equal(posts,0);assert.equal(external,0);assert.equal(store.get('paused'),true);assert.equal(store.get('acceptanceBatch').cursor,13);console.log(JSON.stringify({ok:true,kind:'isolated_original_auto_visit_browser',alreadyConnectedPreferenceChange:true,unregisteredLibraryTarget:true,liveLibraryAddition:true,dynamicFormMount:true,iframePrepared:true,differentProductGuard:true,articleExcluded:true,unknownAttemptPreserved:true,lostRegistrationReplyAndSqliteRestart:true,originalTaskAndProfileRetained:true,originalQueuePosition:true,cancelledOriginalPageResumesOnReenable:true,stageUrlKeepsLibraryDestination:true,remoteLoginGatePreserved:true,boundTaskSameHostUnknownPreserved:true,disabledDuringLeaseStopsFill:true,scopeChangeAndClosedPanelStopFill:true,posts,externalRequests:external,fixedBatchPaused:true}));
}finally{await stopBrowserAssistant(runtime);store.close();await browser.close();assert.ok(resolve(home).startsWith(resolve(tmpdir())+sep)&&home.includes('el-auto-visit-'));await rm(home,{recursive:true,force:true});}
