import assert from 'node:assert/strict';import http from 'node:http';import {readFile} from 'node:fs/promises';import {chromium} from 'playwright';import {Store} from '../src/store.mjs';import {applicationData} from '../src/application-data.mjs';import {applicationAi} from '../src/workbench-features.mjs';import {saveCommentVersion} from '../src/comment-history.mjs';import {originalCommentState,captureOriginalCommentState,restoreOriginalCommentState} from '../src/original-comment-state.mjs';const commentHistory=(runtime,input)=>({ok:true,versions:originalCommentState(runtime,input).versions});
const pageUrl='https://article.example/post',snapshot={documents:{siteProfiles:{p:{id:'p',name:'Original P',url:'https://product.example'},q:{id:'q',name:'Original Q',url:'https://q.example'}},activeSiteId:'p',targetFilters:{aiCommentAllowLink:false},submissionRecords:{original:{profileId:'p',status:'success',evidence:'Original receipt',destinationUrl:'https://receipt.example'}}},revisions:{siteProfiles:1,targetFilters:1}},original=structuredClone(snapshot),store=new Store(':memory:'),calls=[],requests=[],errors=[];
store.set('pair',{endpoint:'https://fixture.invalid',workspaceId:'comment-drafts'});store.set('paused',true);store.set('acceptanceBatch',{status:'paused',cursor:13,count:30});
let response={ok:true,status:'ok',drafts:[{text:'First candidate',angle:'务实建议',anchorText:'Original',placement:'末尾',chars:15},{text:'Second candidate',angle:'提问'},{text:'Third candidate',angle:'补充'}]},gate=null;
const runtime={store,status:()=>({tasks:[],paused:true,busy:false,pendingEvents:0}),cloud:{async request(route,input){if(route==='snapshot')return structuredClone(snapshot);assert.equal(route,'ai/comment');calls.push(structuredClone(input));const captured=structuredClone(response);if(gate){const waiting=gate;waiting.started();await waiting.promise;}return captured;}}};
const hold=()=>{let release,started;const began=new Promise(resolve=>started=resolve);gate={promise:new Promise(resolve=>release=resolve),started};const resume=()=>{gate=null;release();};resume.started=began;return resume;};
const server=http.createServer(async(req,res)=>{try{const path=new URL(req.url,'http://localhost').pathname,files={'/':'../web/application.html','/profiles-core.js':'../../core/profiles.js','/target-filters-core.js':'../../core/target-filters.js','/timeline-core.js':'../../core/submission-timeline.js'};if(files[path]||['/application.js','/comment-studio.js','/setup.js','/application.css','/activity-time.js'].includes(path)){res.setHeader('Content-Type',path.endsWith('.js')?'text/javascript':path.endsWith('.css')?'text/css':'text/html');res.end(await readFile(new URL(files[path]||'../web'+path,import.meta.url)));return;}let raw='';for await(const chunk of req)raw+=chunk;const input=raw?JSON.parse(raw):{};let result;if(path==='/connection')result={ok:true};else if(path==='/appData')result=await applicationData(runtime,input);else if(path==='/commentDrafts'){requests.push({path,input});result=await applicationAi(runtime,'commentDrafts',input);}else if(path==='/captureOriginalCommentState'||path==='/restoreOriginalCommentState'){requests.push({path,input});result=path==='/captureOriginalCommentState'?captureOriginalCommentState(runtime,input):restoreOriginalCommentState(runtime,input);}else if(path==='/originalCommentState')result=originalCommentState(runtime,input);else throw Error('Unexpected route '+path);res.setHeader('Content-Type','application/json');res.end(JSON.stringify(result));}catch(error){res.writeHead(error.status||500,{'Content-Type':'application/json'});res.end(JSON.stringify({ok:false,error:error.message}));}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const origin='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({channel:'chrome',headless:true,args:['--disable-extensions']});
try{
 const page=await browser.newPage();page.on('pageerror',error=>errors.push(error.message));await page.route('**/*',route=>route.request().url().startsWith(origin)?route.continue():route.abort());await page.goto(origin);await page.getByRole('button',{name:'AI 评论',exact:true}).click();
 const field=name=>page.getByLabel(name,{exact:true}),button=name=>page.getByRole('button',{name,exact:true}),generated=async()=>{await button('生成 3 条评论').click();await page.getByText('评论已生成并保存在本机。',{exact:true}).waitFor();},settled=()=>page.waitForFunction(()=>[...document.querySelectorAll('button')].some(node=>node.textContent==='生成 3 条评论'&&!node.disabled));
 await field('评论页面网址').fill(pageUrl);await field('文章内容').fill('Original real article excerpt');await field('评论语气').selectOption('professional');await field('评论语言').selectOption('zh');await field('允许草稿包含推广链接').check();const firstSuccessfulResponse=structuredClone(response);response={ok:false,status:'rejected',drafts:[]};await button('生成 3 条评论').click();await settled();assert.equal(await field('评论候选 1').count(),0);await button('载入最近草稿').click();await settled();assert.match(await page.locator('#connection-status').innerText(),/尚无草稿/);response=firstSuccessfulResponse;await generated();assert.equal(calls[0].allowLink,false);assert.equal(calls[0].config.blogRules.tone,'professional');assert.equal(await field('允许草稿包含推广链接').isChecked(),false);await page.getByRole('heading',{name:'候选 1 · 务实建议',exact:true}).waitFor();
 await button('保存编辑后的草稿').click();await page.getByText('编辑后的草稿已保存。',{exact:true}).waitFor();const originalSavedId=commentHistory(runtime,{profileId:'p',pageUrl}).versions[0].id;
 await field('评论候选 1').fill('Edited candidate');await button('保存编辑后的草稿').click();await page.getByText('编辑后的草稿已保存。',{exact:true}).waitFor();let versions=commentHistory(runtime,{profileId:'p',pageUrl}).versions;assert.equal(versions[0].payload.drafts[0].angle,'务实建议');assert.equal(versions[0].payload.drafts[0].anchorText,'Original');assert.equal(versions[0].payload.drafts[0].placement,'末尾');assert.equal(versions[0].payload.drafts[0].chars,'Edited candidate'.length);
 await page.locator('[data-comment-history-id="'+originalSavedId+'"]').click();await page.getByText('历史草稿已载入，未填表或发布。',{exact:true}).waitFor();assert.equal(await field('评论候选 1').inputValue(),'First candidate');assert.equal(await field('评论语言').inputValue(),'zh');
 response={ok:true,status:'ok',drafts:[{text:'One fallback candidate',angle:'页面兜底'}]};const releaseEdit=hold(),waiting=page.waitForResponse(r=>r.url()===origin+'/commentDrafts');await button('生成 3 条评论').click();await releaseEdit.started;await field('评论候选 1').fill('Edited while generation waits');releaseEdit();await waiting;await settled();assert.equal(await field('评论候选 1').inputValue(),'One fallback candidate');assert.equal(await field('评论候选 2').count(),0);versions=commentHistory(runtime,{profileId:'p',pageUrl}).versions;assert.equal(originalCommentState(runtime,{profileId:'p',pageUrl}).active.drafts[0].text,'One fallback candidate');assert.ok(versions.some(v=>v.payload.drafts[0].text==='Edited while generation waits'));
 const releaseProduct=hold(),productResponse=page.waitForResponse(r=>r.url()===origin+'/commentDrafts');await button('生成 3 条评论').click();await releaseProduct.started;await field('评论推广产品').selectOption('q');releaseProduct();await productResponse;await settled();assert.equal(await field('评论推广产品').inputValue(),'q');assert.equal(await field('评论候选 1').count(),0);assert.equal(commentHistory(runtime,{profileId:'q',pageUrl}).versions.length,0);
 await field('评论推广产品').selectOption('p');const releaseUrl=hold(),urlResponse=page.waitForResponse(r=>r.url()===origin+'/commentDrafts');await button('生成 3 条评论').click();await releaseUrl.started;await field('评论页面网址').fill('https://article.example/another');releaseUrl();await urlResponse;await settled();assert.equal(await field('评论候选 1').count(),0);assert.equal(commentHistory(runtime,{profileId:'p',pageUrl:'https://article.example/another'}).versions.length,0);
 await field('评论页面网址').fill(pageUrl);const releaseLeave=hold(),leaveResponse=page.waitForResponse(r=>r.url()===origin+'/commentDrafts');await button('生成 3 条评论').click();await releaseLeave.started;await button('我的网站').click();releaseLeave();await leaveResponse;await button('AI 评论').click();assert.equal(await field('评论候选 1').count(),0);await field('评论页面网址').fill(pageUrl);await button('载入最近草稿').click();await field('评论候选 1').waitFor();assert.equal(await field('评论候选 1').inputValue(),'One fallback candidate');
 const beforeFailure=store.values('commentHistory:');response={ok:false,status:'rejected',drafts:[]};await button('生成 3 条评论').click();await settled();assert.equal(await field('评论候选 1').inputValue(),'One fallback candidate');assert.deepEqual(store.values('commentHistory:'),beforeFailure);response={ok:true,status:'ok',drafts:[{text:'Retry candidate',angle:'重试'}]};await generated();assert.equal(await field('评论候选 1').inputValue(),'Retry candidate');
 snapshot.documents.targetFilters.aiComments=false;const countBefore=calls.length;await button('生成 3 条评论').click();await settled();assert.equal(calls.length,countBefore);assert.equal(await field('评论候选 1').inputValue(),'Retry candidate');assert.deepEqual(snapshot.documents.submissionRecords,original.documents.submissionRecords);assert.deepEqual(store.get('acceptanceBatch'),{status:'paused',cursor:13,count:30});assert.equal(store.get('paused'),true);assert.deepEqual(errors,[]);
 console.log(JSON.stringify({passed:true,firstFailedGenerationIsNotALoadableDraft:true,productionAiAndHistory:true,effectiveOriginalPreferences:true,candidateMetadataSaveRestore:true,oneCandidateFallback:true,inFlightEditsRetainedInHistory:true,productAndArticleChangesDiscardOldResults:true,navigationDisposesOldStudio:true,failurePreservesDraftAndRetry:true,originalReceiptAndPausedBatchPreserved:true,newRealSubmissions:0}));
}finally{await browser.close();await new Promise(resolve=>server.close(resolve));store.close();}
