import assert from 'node:assert/strict';import http from 'node:http';import {chromium} from 'playwright';import {Store} from '../src/store.mjs';import {Runtime} from '../src/runtime.mjs';
let posts=0;const form='<title>Original article</title><article>This article explains how an original task keeps the same evidence during recovery.</article><form id="commentform" method="POST"><label>Name<input id="author" name="author" required></label><label>Email<input id="email" name="email" type="email" required></label><label>Website<input id="url" name="url" type="url"></label><label>Comment<textarea id="comment" name="comment" required maxlength="2000"></textarea></label><button id="submit" type="submit">Post Comment</button></form>';
const server=http.createServer((req,res)=>{if(req.method==='POST')posts++;res.setHeader('Content-Type','text/html');res.end(req.url==='/outer'?'<title>Original article frame</title><iframe src="/inner"></iframe>':form);});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--disable-extensions']}),context=await browser.newContext(),page=await context.newPage(),store=new Store(':memory:'),runtime=new Runtime(store,'unused-comment-test-home'),base='http://127.0.0.1:'+server.address().port;
try{
 const profile={id:'p',name:'Original product',url:'https://product.example',fields:{Name:'Original product',Url:'https://product.example','Business mail':'owner@example.com'}},snapshot={documents:{siteProfiles:{p:profile},submissionRecords:{receipt:{profileId:'p',status:'success',destinationUrl:'https://receipt.example',evidence:'Original receipt'}}},revisions:{siteProfiles:1}};store.set('pair',{endpoint:'https://cloud.invalid',workspaceId:'comment-fill'});store.set('paused',true);store.set('acceptanceBatch',{status:'paused',cursor:13,count:30});runtime.context=context;runtime.findPage=async()=>page;let leases=0;runtime.lease=async()=>{leases++;};runtime.tick=()=>{throw Error('must not submit');};runtime.synchronize=async()=>{for(const event of store.pending())store.ack(event.id);};Object.defineProperty(runtime,'cloud',{value:{request:async route=>{assert.equal(route,'snapshot');return structuredClone(snapshot);}}});
 for(const route of ['/article','/outer']){await page.goto(base+route);const text='Original draft for '+route,task={id:'original',profileId:'p',url:page.url(),status:'pending',profileSnapshot:profile};store.set('task:original',task);const result=await runtime.control('fillCommentDraft',{taskId:'original',profileId:'p',pageUrl:page.url(),text});assert.equal(result.filled,true);assert.equal(result.submitted,false);const frame=route==='/outer'?page.frames().find(frame=>frame.url()===base+'/inner'):page;assert.equal(await frame.locator('#comment').inputValue(),text);assert.equal(store.get('task:original').selectedComment,text);assert.equal(store.get('task:original').attemptBoundary,undefined);assert.equal(store.get('task:original').receipt,undefined);assert.equal(posts,0);}
 const oldUrl=page.url(),oldLeases=leases;await page.goto(base+'/another-article');await assert.rejects(runtime.control('fillCommentDraft',{taskId:'original',profileId:'p',pageUrl:oldUrl,text:'Old article comment'}),/文章页面/);assert.equal(leases,oldLeases);assert.equal(await page.locator('#comment').inputValue(),'');assert.equal(posts,0);assert.equal(store.get('paused'),true);assert.deepEqual(store.get('acceptanceBatch'),{status:'paused',cursor:13,count:30});assert.equal(snapshot.documents.submissionRecords.receipt.evidence,'Original receipt');console.log(JSON.stringify({passed:true,productionRuntimeAndActualCommentFields:true,iframe:true,sameHostArticleChangeRejectedBeforeLease:true,originalTaskAndReceiptPreserved:true,posts:0,newRealSubmissions:0}));
}finally{store.close();await browser.close();await new Promise(resolve=>server.close(resolve));}
