import assert from 'node:assert/strict';
import http from 'node:http';
import {readFile} from 'node:fs/promises';
import {chromium} from 'playwright';
import {originalLibraryCatalog} from '../../tests/helpers/original-library-catalog.mjs';
import {applicationModel} from '../../core/application-model.mjs';
import {applicationMutation} from '../../core/application-mutation.mjs';
import {Store} from '../src/store.mjs';
import {applicationData} from '../src/application-data.mjs';
import {enqueueLibraryMutation,pendingApplication} from '../src/application-mutations.mjs';
const a='https://articles.example/one',b='https://articles.example/two',legacy='https://legacy.example/form',alias='https://tipseason.com',preferenceAlias='https://library.phygital.plus/tool-submission';
const receipt=(url,extra={})=>({destinationUrl:url,destinationKey:globalThis.ExtLinkQueue.normalizeDestinationKey(url),profileId:'p',status:'success',confirmedBy:'manual',evidence:'Original concrete receipt',submittedAt:'2026-09-20T00:00:00Z',publicationStatus:'published',...extra});
const snapshot={documents:{siteProfiles:{p:{id:'p',sortIndex:0,name:'原产品甲',url:'https://product.example'},q:{id:'q',sortIndex:1,name:'原产品乙',url:'https://other.example'}},sheetTableData:{entries:[{link:a,name:'第一篇文章',time:'2026年9月19日',record:'导入记录第一行\n第二行',detail:'原详情',note:'原补充备注',projects:['p'],metrics:{dr:70}},{link:b,name:'第二篇文章',metrics:{dr:70}},{link:legacy,name:'旧导入标记'},{link:alias,name:'原平台主页'},{link:preferenceAlias,name:'原分组别名'}]},siteAnnotations:{'library.phygital.plus':{library:{groups:['high_quality']}},'library.phygital.plus/tool-submission':{note:'Old route preference',library:{groups:[]}}},submissionSchemaVersion:2,
 submissionRecords:{'articles.example/one::p':receipt(a,{updatedAt:'2026-10-06T00:00:00Z'}),'legacy.example/form::p':receipt(legacy,{confirmedBy:'legacy_import',evidence:'Table.xlsx submitted seed',publicationStatus:'submitted'}),'tipseason.com/submit::p':receipt(alias+'/submit')},
 submissionTimeline:{'articles.example/one::p':[{id:'own-note',profileId:'p',destinationUrl:a,type:'note',note:'第一篇原备注',source:'manual',occurredAt:'2026-10-01T00:00:00Z'}],'articles.example/two::q':[{id:'other-follow',profileId:'q',destinationUrl:b,type:'needs_follow_up',note:'第二篇的专属跟进',source:'manual',occurredAt:'2026-10-02T00:00:00Z'}]},linkMonitorResults:{'articles.example/one::p':{status:'live'}}},revisions:{siteProfiles:1,sheetTableData:1,submissionRecords:1,submissionTimeline:1}};
const original=structuredClone(snapshot),store=new Store(':memory:'),requests=[],writes=[],errors=[];store.set('pair',{endpoint:'https://fixture.invalid',workspaceId:'library-records'});store.set('paused',true);store.set('acceptanceBatch',{id:'original-fixed',status:'paused',cursor:13,count:30});
const runtime={store,status:()=>({tasks:[],paused:true,busy:false,pendingEvents:0}),cloud:{async request(route,input){if(route==='snapshot')return structuredClone(snapshot);if(route==='runs?view=inventory')return{runs:[],tasks:[]};assert.equal(route,'library');const mutation=applicationMutation(snapshot.documents,input.operation);assert.equal(input.revision,snapshot.revisions[mutation.key]||0);writes.push(structuredClone(input));snapshot.documents[mutation.key]=mutation.data;snapshot.revisions[mutation.key]=(snapshot.revisions[mutation.key]||0)+1;return{ok:true};}}};
const server=http.createServer(async(req,res)=>{try{const path=new URL(req.url,'http://localhost').pathname,files={'/':'../web/application.html','/profiles-core.js':'../../core/profiles.js','/target-filters-core.js':'../../core/target-filters.js','/timeline-core.js':'../../core/submission-timeline.js'};if(files[path]||['/application.js','/comment-studio.js','/setup.js','/application.css','/activity-time.js'].includes(path)){res.setHeader('Content-Type',path.endsWith('.js')?'text/javascript':path.endsWith('.css')?'text/css':'text/html');res.end(await readFile(new URL(files[path]||'../web'+path,import.meta.url)));return;}let raw='';for await(const chunk of req)raw+=chunk;const input=raw?JSON.parse(raw):{};let result;if(path==='/connection')result={ok:true};else if(path==='/appData')result=await applicationData(runtime,input);else if(path==='/libraryMutation'){requests.push(structuredClone(input));result=await enqueueLibraryMutation(runtime,input);}else throw Error('Unexpected route '+path);res.setHeader('Content-Type','application/json');res.end(JSON.stringify(result));}catch(error){res.writeHead(error.status||500,{'Content-Type':'application/json'});res.end(JSON.stringify({ok:false,error:error.message}));}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const origin='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({channel:'chrome',headless:true,args:['--disable-extensions']});
try{
 const page=await browser.newPage();page.on('pageerror',error=>errors.push(error.message));page.on('dialog',dialog=>dialog.accept());await page.route('**/*',route=>route.request().url().startsWith(origin)?route.continue():route.abort());await page.goto(origin);await page.getByRole('button',{name:'外链库',exact:true}).click();await page.getByLabel('站点状态',{exact:true}).waitFor();
 const row=url=>page.locator('#content tbody tr').filter({has:page.locator('a[href="'+url+'"]')}),field=name=>page.getByLabel(name,{exact:true});
 const reference=await originalLibraryCatalog(snapshot),model=applicationModel(snapshot);
 for(const item of reference.items){const actual=model.library.find(r=>r.url===item.url);assert.equal(actual.monitorStatus,item.monitorStatus);assert.equal(actual.quality.score,item.quality.score);assert.equal(actual.progress.hasSubmitted,globalThis.ExtLinkSubmissionTimeline.deriveLibraryProgress(item).hasSubmitted);}
 assert.match(await row(a).innerText(),/提交时间：2026.*9.*20/);assert.match(await row(a).innerText(),/最近动态：2026.*10.*1/);assert.match(await row(a).innerText(),/原记录时间：2026.*9.*19/);assert.doesNotMatch(await row(a).innerText(),/需要跟进/);assert.match(await row(b).innerText(),/需要跟进/);
 await field('提交进度').selectOption('submitted');assert.equal(await row(legacy).count(),0);assert.equal(await row(a).count(),1);assert.equal(await row(alias).count(),1);await field('提交进度').selectOption('');
 await row(a).getByRole('button',{name:'时间线',exact:true}).click();await page.getByRole('heading',{name:'第一篇文章 · 提交进度',exact:true}).waitFor();const detail=page.locator('#detail-content');assert.match(await detail.innerText(),/导入记录第一行\n第二行/);assert.match(await detail.innerText(),/原记录对应产品：原产品甲/);assert.match(await detail.innerText(),/原详情/);assert.match(await detail.innerText(),/原补充备注/);assert.doesNotMatch(await detail.innerText(),/第二篇的专属跟进/);assert.equal(await detail.locator('.record-detail').first().evaluate(node=>getComputedStyle(node).whiteSpace),'pre-wrap');
 await detail.locator('.timeline-event').filter({hasText:'第一篇原备注'}).getByRole('button',{name:'编辑动态',exact:true}).click();await field('动态说明').fill('第一篇修改后的备注');const read=page.waitForResponse(response=>response.url()===origin+'/appData');await page.getByRole('button',{name:'保存动态',exact:true}).click();await read;assert.equal(requests.at(-1).operation.eventId,'own-note');assert.equal(globalThis.ExtLinkSubmissionTimeline.normalizeTimeline(snapshot.documents.submissionTimeline)['articles.example/one::p'].find(e=>e.id==='own-note').note,'第一篇修改后的备注');
 await page.getByRole('button',{name:'关闭详情',exact:true}).click();await row(a).getByRole('button',{name:'时间线',exact:true}).click();await detail.getByText('第一篇修改后的备注',{exact:true}).waitFor();assert.doesNotMatch(await detail.innerText(),/第二篇的专属跟进/);const deleted=page.waitForResponse(response=>response.url()===origin+'/appData');await detail.locator('.timeline-event').filter({hasText:'第一篇修改后的备注'}).getByRole('button',{name:'删除动态',exact:true}).click();await deleted;await page.getByRole('heading',{name:'第一篇文章 · 提交进度',exact:true}).waitFor();assert.doesNotMatch(await detail.innerText(),/第一篇修改后的备注/);assert.equal(globalThis.ExtLinkSubmissionTimeline.normalizeTimeline(snapshot.documents.submissionTimeline)['articles.example/two::q'][0].id,'other-follow');
 await page.getByRole('button',{name:'关闭详情',exact:true}).click();await row(preferenceAlias).getByRole('button',{name:'编辑',exact:true}).click();await field('高质量优先').uncheck();await field('免费可提交').check();const preferenceRead=page.waitForResponse(response=>response.url()===origin+'/appData');await page.getByRole('button',{name:'保存收藏与分组',exact:true}).click();await preferenceRead;assert.deepEqual(snapshot.documents.siteAnnotations['library.phygital.plus'].library.groups,['free_submit']);assert.deepEqual(snapshot.documents.siteAnnotations['library.phygital.plus/tool-submission'],original.documents.siteAnnotations['library.phygital.plus/tool-submission']);await page.getByRole('button',{name:'关闭详情',exact:true}).click();await row(preferenceAlias).getByRole('button',{name:'编辑',exact:true}).click();assert.equal(await field('高质量优先').isChecked(),false);assert.equal(await field('免费可提交').isChecked(),true);
 await page.getByRole('button',{name:'关闭详情',exact:true}).click();await page.getByRole('button',{name:'提交总览',exact:true}).click();const legacyOverview=page.locator('#content tbody tr').filter({hasText:'legacy.example'}),strongOverview=page.locator('#content tbody tr').filter({hasText:'articles.example'}).filter({hasText:'原产品甲'});await legacyOverview.waitFor();assert.match(await legacyOverview.innerText(),/未投稿/);assert.doesNotMatch(await legacyOverview.innerText(),/已收件/);assert.match(await strongOverview.innerText(),/已收件/);
 assert.deepEqual(snapshot.documents.submissionRecords,original.documents.submissionRecords);assert.deepEqual(snapshot.documents.sheetTableData,original.documents.sheetTableData);assert.deepEqual(snapshot.documents.linkMonitorResults,original.documents.linkMonitorResults);assert.deepEqual(store.get('acceptanceBatch'),{id:'original-fixed',status:'paused',cursor:13,count:30});assert.equal(store.get('paused'),true);assert.equal(pendingApplication(runtime).length,0);assert.equal(writes.length,3);assert.deepEqual(errors,[]);
 console.log(JSON.stringify({passed:true,originalCatalogProjection:true,sameHostPathsIsolated:true,originalDisplayAlias:true,legacyFlagNotReceipt:true,originalTimesAndImportedDetails:true,editRemoveOriginalEventAndReadback:true,aliasPreferencesSaveAndReopen:true,otherPathAndReceiptPreserved:true,originalBatchPaused:true,newRealSubmissions:0}));
}finally{await browser.close();await new Promise(resolve=>server.close(resolve));store.close();}
