import assert from 'node:assert/strict';
import http from 'node:http';
import {readFile} from 'node:fs/promises';
import {chromium} from 'playwright';
import {Store} from '../src/store.mjs';
import {applicationData} from '../src/application-data.mjs';
import {applicationMutation} from '../../core/application-mutation.mjs';
import {enqueueLibraryMutation,pendingApplication} from '../src/application-mutations.mjs';
import {clearSiteAnnotation} from '../src/library-reset.mjs';
import {submissionQueue,removeFromSubmissionQueue} from '../src/submission-queue.mjs';
import {previewWorkbenchBatch} from '../src/workbench-features.mjs';
const url='https://tipseason.com/submit',domain='tipseason.com',routeKey=domain+'/submit',other='https://ordinary.example/form',snapshot={documents:{siteProfiles:{p:{id:'p',name:'原产品',fields:{Name:'原产品',Url:'https://product.example'}}},selectedSiteIds:['p'],sheetTableData:{entries:[{link:url,metrics:{dr:95,da:90}},{link:'https://'+domain},{link:other,metrics:{dr:10}}]},siteAnnotations:{[domain]:{status:'deleted',statuses:['deleted'],note:'原目录备注',library:{favorite:true,groups:['high_quality']},formKnowledge:{schema:{original:true}}},[routeKey]:{status:'can_submit',note:'旧路线备注',formKnowledge:{schema:{route:true}}}},deletedSubmissionKeys:[domain],submissionRecords:{protected:{profileId:'p',status:'success',confirmedBy:'manual',evidence:'Original concrete receipt',destinationUrl:'https://protected.example/form'}}},revisions:{siteProfiles:1,siteAnnotations:1,deletedSubmissionKeys:1,sheetTableData:1,submissionRecords:1}},original=structuredClone(snapshot),store=new Store(':memory:'),writes=[],previews=[],errors=[];
store.set('pair',{endpoint:'https://fixture.invalid',workspaceId:'library-actions-ui'});store.set('paused',true);store.set('acceptanceBatch',{id:'original-fixed',status:'paused',cursor:13,count:30});
const runtime={store,status:()=>({paused:true,busy:false,pendingEvents:0,tasks:[]}),cloud:{async request(route,input){if(route==='snapshot')return structuredClone(snapshot);if(route==='runs?view=inventory')return{runs:[],tasks:[]};assert.equal(route,'library');const change=applicationMutation(snapshot.documents,input.operation);assert.equal(input.revision,snapshot.revisions[change.key]||0);writes.push(input.operation);snapshot.documents[change.key]=change.data;snapshot.revisions[change.key]=(snapshot.revisions[change.key]||0)+1;return{ok:true};}}};
const server=http.createServer(async(req,res)=>{try{const path=new URL(req.url,'http://localhost').pathname,files={'/':'../web/application.html','/profiles-core.js':'../../core/profiles.js','/target-filters-core.js':'../../core/target-filters.js','/timeline-core.js':'../../core/submission-timeline.js'};if(files[path]||['/application.js','/comment-studio.js','/setup.js','/application.css','/activity-time.js'].includes(path)){res.setHeader('Content-Type',path.endsWith('.js')?'text/javascript':path.endsWith('.css')?'text/css':'text/html');res.end(await readFile(new URL(files[path]||'../web'+path,import.meta.url)));return;}let raw='';for await(const chunk of req)raw+=chunk;const input=raw?JSON.parse(raw):{};let result;if(path==='/connection')result={ok:true};else if(path==='/appData')result=await applicationData(runtime,input);else if(path==='/clearSiteAnnotation')result=await clearSiteAnnotation(runtime,input);else if(path==='/libraryMutation')result=await enqueueLibraryMutation(runtime,input);else if(path==='/getSubmissionQueue')result=await submissionQueue(runtime,input);else if(path==='/removeFromSubmissionQueue')result=await removeFromSubmissionQueue(runtime,input);else if(path==='/previewBatch'){result=await previewWorkbenchBatch(runtime,input);previews.push(result.batch.id);}else throw Error('Unexpected route '+path);res.setHeader('Content-Type','application/json');res.end(JSON.stringify(result));}catch(error){res.writeHead(error.status||500,{'Content-Type':'application/json'});res.end(JSON.stringify({ok:false,error:error.message}));}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const origin='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({channel:'chrome',headless:true,args:['--disable-extensions']});
try{
 const page=await browser.newPage();page.on('pageerror',error=>errors.push(error.message));await page.route('**/*',route=>route.request().url().startsWith(origin)?route.continue():route.abort());await page.goto(origin);await page.getByRole('button',{name:'外链库',exact:true}).click();const row=()=>page.locator('#content tbody tr').filter({has:page.locator('a[href="'+url+'"]')}),field=name=>page.getByLabel(name,{exact:true});await row().waitFor();assert.equal(await page.locator('#content tbody tr').count(),2);
 await row().getByRole('button',{name:'编辑',exact:true}).click();assert.equal(await field('收藏此网站').isChecked(),true);await page.getByRole('button',{name:'清除网站标记',exact:true}).click();await field('清除网站标记确认文字').fill('清除网站标记');await page.getByRole('button',{name:'确认清除网站标记',exact:true}).click();await page.getByText('网站标记已清除并回读云端。',{exact:true}).waitFor();assert.deepEqual(snapshot.documents.siteAnnotations[domain].formKnowledge,original.documents.siteAnnotations[domain].formKnowledge);assert.deepEqual(snapshot.documents.siteAnnotations[routeKey],original.documents.siteAnnotations[routeKey]);assert.equal(snapshot.documents.deletedSubmissionKeys.includes(domain),false);await page.getByRole('button',{name:'关闭详情',exact:true}).click();
 await page.getByRole('button',{name:'单站投稿队列',exact:true}).click();await page.getByRole('button',{name:'从待投稿队列移除',exact:true}).waitFor();assert.match(await page.locator('#detail-content').innerText(),/tipseason.com/);await page.getByRole('button',{name:'从待投稿队列移除',exact:true}).click();await page.getByText('已从待投稿队列移除，网站资料和历史收件保留。',{exact:true}).waitFor();assert.equal(snapshot.documents.siteAnnotations[domain].status,'deleted');assert.ok(snapshot.documents.deletedSubmissionKeys.includes(domain));assert.match(await page.locator('#detail-content').innerText(),/ordinary.example/);await page.getByRole('button',{name:'关闭详情',exact:true}).click();
 await row().getByRole('button',{name:'编辑',exact:true}).click();assert.equal(await field('已归档').isChecked(),true);await field('已归档').uncheck();await field('可以提交').check();await page.getByRole('button',{name:'保存提交条件',exact:true}).click();await page.getByText('提交条件已保存并回读云端',{exact:true}).waitFor();assert.equal(snapshot.documents.deletedSubmissionKeys.includes(domain),false);await page.getByRole('button',{name:'关闭详情',exact:true}).click();await field('选择 '+url).check();await page.getByRole('button',{name:'批量提交',exact:true}).click();await page.getByRole('button',{name:'预览批量提交',exact:true}).click();await page.getByRole('heading',{name:'批量提交范围确认',exact:true}).waitFor();const preview=store.get('workbenchBatch:'+previews.at(-1));assert.equal(preview.items.length,1);assert.equal(preview.items[0].status,'ready');assert.equal(preview.items[0].url,url);
 assert.deepEqual(snapshot.documents.submissionRecords,original.documents.submissionRecords);assert.deepEqual(snapshot.documents.sheetTableData,original.documents.sheetTableData);assert.deepEqual(snapshot.documents.siteAnnotations[routeKey],original.documents.siteAnnotations[routeKey]);assert.equal(store.get('paused'),true);assert.deepEqual(store.get('acceptanceBatch'),{id:'original-fixed',status:'paused',cursor:13,count:30});assert.equal(store.values('task:').length,0);assert.equal(pendingApplication(runtime).length,0);assert.equal(writes.length,6);assert.deepEqual(errors,[]);console.log(JSON.stringify({passed:true,productionClearRemoveRestoreAndPreview:true,canonicalKnowledgeAndOldRouteRetained:true,originalRecordsAndPausedBatchPreserved:true,newRealSubmissions:0}));
}finally{await browser.close();await new Promise(resolve=>server.close(resolve));store.close();}
