import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import Worker from '../../cloud/worker/src/index.mjs';
import {Cloud} from '../src/cloud.mjs';
import {neonCloudFixture} from './fixtures/neon-cloud.mjs';
import {mediaObjectKey,artifactObjectKey} from '../../cloud/worker/src/worker-core.mjs';
import {applicationMutationDependencies} from '../../core/application-mutation-dependencies.mjs';
const f=await neonCloudFixture(),realFetch=globalThis.fetch;
const calls=[];let losePart=false,loseCommit=false;
globalThis.fetch=async(url,options)=>{
 const target=new URL(url instanceof URL?url:typeof url==='string'?url:url.url);
 if(target.hostname==='worker.fixture.invalid'){
  calls.push(target.pathname);const response=await Worker.fetch(new Request(url,options),f.env);
  if(losePart&&target.pathname.endsWith('/library-transfer/part')){losePart=false;throw Error('part response lost');}
  if(loseCommit&&target.pathname.endsWith('/library-transfer/commit')){loseCommit=false;throw Error('commit response lost');}
  return response;
 }
 return f.fetch(url,options);
};
const response=async(route,token,body,method=body?'POST':'GET',workspace='one')=>Worker.fetch(new Request('https://worker.fixture.invalid/v1/executor/'+route+(route.includes('?')?'&':'?')+'workspace='+workspace,{method,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},...(method==='POST'?{body:JSON.stringify(body)}:{})}),f.env);
const call=async(...args)=>{const r=await response(...args);return{status:r.status,data:await r.json()};};
let token,operations=0;
const mutate=async(operation,key,expected=200)=>{
 const snap=await f.snapshot();const result=await call('library',token,{operation:{id:'original-operation-'+(++operations),at:'2026-10-07T01:00:00Z',...operation},revision:snap.revisions[key]||0,revisions:snap.revisions});
 assert.equal(result.status,expected,JSON.stringify(result.data));return f.snapshot();
};
try{
 const enrolled=await call('devices','fixture-admin',{});assert.equal(enrolled.status,200);token=enrolled.data.deviceToken;
 const originalProfile={id:'p',name:'Original',url:'https://product.fixture.invalid',fields:{Name:'Original',Url:'https://product.fixture.invalid',Custom:'Old field'},fieldNotes:{Custom:'Original note'},media:{screenshots:[]},opaqueOriginal:{retain:true},mediaVersions:[]};
 const originalReceipt={status:'success',profileId:'p',destinationKey:'directory.fixture.invalid/submit',destinationUrl:'https://directory.fixture.invalid/submit',publicUrl:'https://directory.fixture.invalid/post',publicationStatus:'submitted',evidence:'Original receipt ABC123',taskId:'original-task'};
 const recordKey='directory.fixture.invalid/submit::p';
 for(const [key,data]of Object.entries({siteProfiles:{p:originalProfile},sheetTableData:{projects:{p:{original:'table project'}},entries:[{link:'https://directory.fixture.invalid/submit',name:'Old directory',opaqueOriginal:'retain'}]},siteAnnotations:{'directory.fixture.invalid/submit':{note:'Old note',originalExtra:{retain:true}}},submissionRecords:{[recordKey]:originalReceipt},cfgName:'Old default',urlList:'https://old.fixture.invalid/submit|directory'}))await f.seed(key,data);
 const receiptBefore=structuredClone((await f.snapshot()).documents.submissionRecords);
 let snap=await mutate({type:'profile_create',profileId:'q',profile:{id:'q',name:'新增官网',url:'https://new-product.fixture.invalid',fields:{Name:'新增官网',Url:'https://new-product.fixture.invalid'}}},'siteProfiles');assert.equal(snap.documents.siteProfiles.q.archived,false);assert.deepEqual(snap.documents.siteProfiles.p,originalProfile);
 const saved=await call('profile',token,{profileId:'p',profile:{id:'p',fields:{Title:'新宣传标题'},fieldNotes:{Title:'中文说明',Custom:''}},revision:snap.revisions.siteProfiles});assert.equal(saved.status,200,JSON.stringify(saved.data));snap=await f.snapshot();assert.equal(snap.documents.siteProfiles.p.fields.Custom,'Old field');assert.equal(snap.documents.siteProfiles.p.fieldNotes.Custom,'Original note');assert.equal(snap.documents.siteProfiles.p.fieldNotes.Title,'中文说明');assert.deepEqual(snap.documents.siteProfiles.p.opaqueOriginal,{retain:true});
 for(const patch of [{evil:'not allowed'},{fields:{'API key':'secret'}},{mediaVersions:[]}, {url:'https://user:pass@product.fixture.invalid'}]){
  if(Object.hasOwn(patch,'mediaVersions'))continue;
  assert.equal((await call('profile',token,{profileId:'p',profile:{id:'p',...patch},revision:snap.revisions.siteProfiles})).status,400);
 }
 assert.equal((await call('profile',token,{profileId:'p',profile:{id:'p',name:'stale'},revision:1})).status,409);
 await mutate({type:'profile_selection',key:'activeSiteId',value:'q'},'activeSiteId');await mutate({type:'profile_selection',key:'selectedSiteIds',value:['p','q']},'selectedSiteIds');await mutate({type:'profile_order',profileIds:['q','p']},'siteProfiles');
 await mutate({type:'profile_archive',profileId:'q',archived:true},'siteProfiles');await mutate({type:'profile_selection',key:'activeSiteId',value:'q'},'activeSiteId',400);await mutate({type:'profile_archive',profileId:'q',archived:false},'siteProfiles');
 await mutate({type:'profile_create',profileId:'temporary',profile:{id:'temporary',name:'temporary'}},'siteProfiles');snap=await mutate({type:'profile_delete',profileId:'temporary'},'siteProfiles');assert.ok(!snap.documents.siteProfiles.temporary);assert.deepEqual(snap.documents.submissionRecords,receiptBefore);
 await mutate({type:'create',url:'https://new-directory.fixture.invalid/submit',fields:{name:'新增外链',category:'AI目录',dr:'80',note:'中文备注'}},'sheetTableData');await mutate({type:'import',urls:['https://new-directory.fixture.invalid/submit','https://import.fixture.invalid']},'sheetTableData');snap=await mutate({type:'edit',url:'https://directory.fixture.invalid/submit',fields:{dr:'75',note:'新备注'}},'sheetTableData');assert.equal(snap.documents.sheetTableData.entries[0].opaqueOriginal,'retain');assert.equal(snap.documents.sheetTableData.entries[0].metrics.dr,75);assert.equal(snap.documents.sheetTableData.entries.length,3);
 snap=await mutate({type:'preferences',url:'https://directory.fixture.invalid/submit',preferences:{favorite:true,groups:['high_quality'],profileIds:['p','q']}},'siteAnnotations');assert.equal(snap.documents.siteAnnotations['directory.fixture.invalid/submit'].library.favorite,true);assert.deepEqual(snap.documents.siteAnnotations['directory.fixture.invalid/submit'].library.groups,['high_quality']);assert.deepEqual(snap.documents.siteAnnotations['directory.fixture.invalid/submit'].originalExtra,{retain:true});
 await mutate({type:'mark',url:'https://directory.fixture.invalid/submit',statuses:['needs_login'],note:'需要登录'},'siteAnnotations');await mutate({type:'remove_queue',url:'https://directory.fixture.invalid/submit'},'siteAnnotations');await mutate({type:'set_deleted',url:'https://directory.fixture.invalid/submit'},'deletedSubmissionKeys');await mutate({type:'clear_deleted',url:'https://directory.fixture.invalid/submit'},'deletedSubmissionKeys');await mutate({type:'pin',url:'https://directory.fixture.invalid/submit'},'urlList');
 const mappings={description:{profileKey:'Discord',value:'https://discord.gg/original',label:'Discord',hint:''}};
 snap=await mutate({type:'form_learning',url:'https://directory.fixture.invalid/submit',profileId:'p',identity:{name:'Original',url:'https://product.fixture.invalid'},mappings},'siteProfiles');assert.equal(snap.documents.siteProfiles.p.fields.Discord,'https://discord.gg/original');
 await mutate({type:'form_knowledge',url:'https://directory.fixture.invalid/submit',mappings,schema:{url:'https://directory.fixture.invalid/submit?query=hidden',forms:[{method:'post'}],fields:[{name:'description',label:'详细介绍',type:'text'}]}},'siteAnnotations');snap=await mutate({type:'clear_annotation',url:'https://directory.fixture.invalid/submit'},'siteAnnotations');assert.ok(snap.documents.siteAnnotations['directory.fixture.invalid/submit'].formKnowledge);assert.equal(snap.documents.siteAnnotations['directory.fixture.invalid/submit'].statuses,undefined);
 await mutate({type:'submify_refs',items:[{id:'original-source',link:'https://directory.fixture.invalid/submit'}]},'sheetTableData');await mutate({type:'submify_import',items:[{id:'public-new',link:'https://public.fixture.invalid',name:'公共目录'}]},'sheetTableData');await mutate({type:'submify_gates',gates:[{url:'https://public.fixture.invalid',reason:'paid'}]},'siteAnnotations');
 await mutate({type:'domain_metrics',results:[{domain:'directory.fixture.invalid',status:'ok',ageMonths:50,ageDays:1500,fetchedAt:1}]},'domainMetricsCache');
 await mutate({type:'monitor_result',recordKey,jobId:'original-monitor',result:{status:'live',targetFound:true,targetHost:'product.fixture.invalid',inputUrl:originalReceipt.publicUrl,url:originalReceipt.publicUrl}},'linkMonitorResults');snap=await mutate({type:'monitor_publication',recordKey,jobId:'original-monitor'},'submissionRecords');assert.equal(snap.documents.submissionRecords[recordKey].publicationStatus,'published');assert.equal(snap.documents.submissionRecords[recordKey].evidence,originalReceipt.evidence);
 await mutate({type:'settings',key:'targetFilters',value:{minDr:70,aiComments:false}},'targetFilters');await mutate({type:'settings',key:'domainBlacklist',value:{add:['blocked.fixture.invalid']}},'domainBlacklist');await mutate({type:'settings',key:'unattendedPreferences',value:{tasks:20}},'unattendedPreferences');await mutate({type:'settings',key:'linkMonitorSchedule',value:{enabled:false,minutes:1440}},'linkMonitorSchedule');await mutate({type:'settings',key:'cfgName',value:'新默认名称'},'cfgName');
 await mutate({type:'backup_key_merge',key:'cfgEmail',backup:{format:'externallink-submission-backup',submissionRecords:{},siteProfiles:{},cfgEmail:'original@example.invalid'}},'cfgEmail');await mutate({type:'backup_merge',key:'cfgName',backup:{format:'externallink-submission-backup',submissionRecords:{},siteProfiles:{},cfgName:'备份默认名称'}},'cfgName');
 snap=await mutate({type:'recover_local',id:'original-recover',key:'cfgName',data:'本机完整名称'},'cfgName');const archives=(await f.db.query("SELECT archive_id,data FROM externallink_executor_recovery ORDER BY archive_id")).rows;assert.equal(archives.find(a=>a.archive_id==='local-source-original-recover').data.data,'本机完整名称');assert.equal(archives.find(a=>a.archive_id.startsWith('local-before-original-recover-')).data.data,'备份默认名称');
 const beforeArchiveConflict=structuredClone(snap);await mutate({type:'recover_local',id:'original-recover',key:'cfgName',data:'同编号不同内容'},'cfgName',409);assert.deepEqual(await f.snapshot(),beforeArchiveConflict);
 snap=await mutate({type:'backup_prepared_key',id:'original-prepared',key:'cfgName',patch:[{path:[],value:'准备合并名称'}]},'cfgName');assert.equal(snap.documents.cfgName,'准备合并名称');assert.equal((await f.db.query("SELECT count(*)::int n FROM externallink_executor_recovery")).rows[0].n,4);
 // A secondary product change between read and transaction must reject the
 // favorite allocation, including when the annotation revision is unchanged.
 const beforeConcurrent=await f.snapshot();f.state.beforeTransaction=async()=>{f.state.beforeTransaction=null;await f.seed('siteProfiles',{...beforeConcurrent.documents.siteProfiles,q:{...beforeConcurrent.documents.siteProfiles.q,archived:true}});};
 const conflict=await call('library',token,{operation:{type:'preferences',id:'race',at:'now',url:'https://directory.fixture.invalid/submit',preferences:{profileIds:['q']}},revision:beforeConcurrent.revisions.siteAnnotations});assert.equal(conflict.status,409,JSON.stringify(conflict.data));assert.deepEqual((await f.snapshot()).documents.siteAnnotations,beforeConcurrent.documents.siteAnnotations);
 const beforeFailed=await f.snapshot(),archiveCount=(await f.db.query('SELECT count(*)::int n FROM externallink_executor_recovery')).rows[0].n;f.state.failSql=/with written as/;
 await mutate({type:'recover_local',id:'rollback',key:'cfgName',data:'不得保存'},'cfgName',500);assert.deepEqual(await f.snapshot(),beforeFailed);assert.equal((await f.db.query('SELECT count(*)::int n FROM externallink_executor_recovery')).rows[0].n,archiveCount);
 // Native large transfer: immutable parts survive a lost reply and a recreated
 // Cloud client; commit keeps the original operation and version guard.
 const cloud=new Cloud({endpoint:'https://worker.fixture.invalid',workspaceId:'one',deviceToken:token,storageBackend:'neon'}),beforeLarge=await f.snapshot();
 const backup={format:'externallink-submission-backup',submissionRecords:{},siteProfiles:{huge:{id:'huge',fields:{Description:'原资料😀'.repeat(150000)}}}},body={operation:{type:'backup_merge',id:'original-large',at:'now',key:'siteProfiles',backup},revision:beforeLarge.revisions.siteProfiles};
 losePart=true;await assert.rejects(cloud.request('library',body),/连接失败/);assert.deepEqual(await f.snapshot(),beforeLarge);
 const id=createHash('sha256').update(JSON.stringify(body)).digest('hex'),other=(await call('devices','fixture-admin',{})).data.deviceToken;assert.equal((await call('library-transfer/status?id='+id,other)).status,404);
 loseCommit=true;await assert.rejects(new Cloud(cloud.config).request('library',body),/连接失败/);snap=await cloud.request('snapshot');assert.equal(snap.documents.siteProfiles.huge.fields.Description,backup.siteProfiles.huge.fields.Description);const afterLarge=await f.snapshot();
 await assert.rejects(new Cloud(cloud.config).request('library',body),/回读|更新/);assert.deepEqual(await f.snapshot(),afterLarge);assert.ok(calls.some(route=>route.endsWith('/library-transfer/start')));assert.deepEqual(afterLarge.documents.submissionRecords,beforeLarge.documents.submissionRecords);
 // Legacy SQL-only metadata remains readable. New immutable device uploads
 // are catalogued with the original screenshot kind/index representation.
 const png='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/l9sAAAAASUVORK5CYII=',bytes=Buffer.from(png.split(',')[1],'base64'),sha=createHash('sha256').update(bytes).digest('hex'),legacy='old-logo.png';
 await f.env.MEDIA_BUCKET.put(mediaObjectKey('one',legacy),bytes,{httpMetadata:{contentType:'image/png'}});await f.db.query("INSERT INTO externallink_media_assets(workspace_id,asset_id,profile_id,media_kind,object_key,file_name,content_type,byte_length,sha256) VALUES('one',$1,'p','logo',$2,'原图.png','image/png',$3,$4)",[legacy,mediaObjectKey('one',legacy),bytes.length,sha]);
 assert.equal((await call('media-assets/'+legacy,token)).data.asset.sha256,sha);const legacyRead=await response('workspace/media/'+legacy,token);assert.equal(legacyRead.status,200);assert.deepEqual(Buffer.from(await legacyRead.arrayBuffer()),bytes);
 const media={assetId:'asset-11111111-1111-4111-8111-111111111111',profileId:'p',kind:'screenshot2',dataUrl:png,mime:'image/png',sha256:sha,fileName:'screen.png'};const upload=await call('media-upload',token,media);assert.equal(upload.status,200,JSON.stringify(upload.data));const puts=f.state.puts;assert.equal((await call('media-upload',token,media)).status,200);assert.equal(f.state.puts,puts);assert.equal((await call('media-upload',token,{...media,profileId:'huge'})).status,409);assert.equal(f.state.puts,puts);
 const catalog=(await call('workspace/media',token)).data.assets;assert.equal(catalog.length,2);assert.equal(catalog.find(asset=>asset.asset_id===media.assetId).media_index,2);assert.equal(catalog.find(asset=>asset.asset_id===media.assetId).media_kind,'screenshot');
 const interruptedMedia={...media,assetId:'asset-22222222-2222-4222-8222-222222222222',kind:'logo'};f.state.failSql=/insert into externallink_media_assets/;
 assert.equal((await call('media-upload',token,interruptedMedia)).status,500);assert.equal((await call('media-assets/'+interruptedMedia.assetId,token)).status,404);
 const interruptedPuts=f.state.puts;assert.equal((await call('media-upload',token,interruptedMedia)).status,200);assert.equal(f.state.puts,interruptedPuts);assert.equal((await call('media-assets/'+interruptedMedia.assetId,token)).data.asset.sha256,sha);
 const mediaBefore=await f.snapshot();await mutate({type:'profile',profileId:'p',profile:{id:'p',media:{screenshots:['','cloud-media://'+media.assetId]},mediaVersions:[{assetId:media.assetId,ref:'cloud-media://'+media.assetId,kind:'screenshot2',sha256:sha}]}},'siteProfiles');await mutate({type:'profile_media',profileId:'p',kind:'screenshot2',action:'disable'},'siteProfiles');snap=await mutate({type:'profile_media',profileId:'p',kind:'screenshot2',action:'restore',assetId:media.assetId},'siteProfiles');assert.equal(snap.documents.siteProfiles.p.fields['Screenshot 2'],'cloud-media://'+media.assetId);assert.deepEqual(snap.documents.submissionRecords,mediaBefore.documents.submissionRecords);
 assert.equal((await call('profile',token,{profileId:'p',profile:{id:'p',mediaVersions:[]},revision:snap.revisions.siteProfiles})).status,400);
 await f.env.MEDIA_BUCKET.put(artifactObjectKey('one','old-proof'),bytes,{httpMetadata:{contentType:'image/png'},customMetadata:{sha256:sha}});assert.equal((await response('workspace/automation/artifacts/old-proof',token)).status,200);assert.equal((await response('workspace/automation/artifacts/missing',token)).status,404);
 assert.equal((await call('workspace/media',token,{},'POST')).status,403);assert.equal((await call('workspace/admin',token)).status,403);assert.equal((await call('library',token,{operation:{type:'settings',key:'credentials',id:'deny',at:'now',value:'secret'},revision:0})).status,403);assert.equal((await call('library',token,{operation:{type:'unsupported'},revision:0})).status,400);
 assert.deepEqual((await call('workspace/submission-tasks',token)).data.tasks,[]);assert.deepEqual((await call('revisions',token)).data.revisions,(await f.snapshot()).revisions);
 assert.equal((await call('library',token,{operation:{type:'backup_key_merge',key:'credentials',id:'deny-backup-key',at:'now'},revision:0})).status,403);
 const beforeDenied=await f.snapshot();assert.equal((await call('library','fixture-admin',{operation:{type:'profile_delete',profileId:'p'},revision:beforeDenied.revisions.siteProfiles})).status,401);assert.equal((await call('revisions',token,undefined,'GET','other')).status,403);assert.equal((await call('revoke','fixture-admin',{deviceId:enrolled.data.deviceId})).status,200);assert.equal((await call('media-upload',token,media)).status,401);assert.deepEqual(await f.snapshot(),beforeDenied);
 for(const table of ['externallink_executor_runs','externallink_executor_tasks','externallink_executor_events'])assert.equal((await f.db.query('SELECT count(*)::int n FROM '+table)).rows[0].n,0);
 assert.equal(applicationMutationDependencies({type:'form_learning'}).at(0),'siteProfiles');
 console.log(JSON.stringify({ok:true,kind:'actual_worker_neon_http_driver_original_library_and_media',operations,allOriginalMutationFamiliesRouted:true,originalFieldsNotesAndReceiptsPreserved:true,secondaryVersionConflictAtomic:true,recoverySourceAndBeforeImmutable:true,recoveryWriteFailureRollsBackArchives:true,nativeLargeTransferLostPartAndCommit:true,legacyMediaAndNewScreenshotCatalog:true,mediaImmutableAcrossProducts:true,workspaceReadAndMethodScopes:true,revokedDeviceRejected:true,queries:f.state.queries,transactions:f.state.transactions,newRuntimeRuns:0,newRealSubmissions:0,realProviderRequests:0,productionNeonRequests:0}));
}finally{globalThis.fetch=realFetch;await f.close();}
