import assert from 'node:assert/strict';import http from 'node:http';import {readFile} from 'node:fs/promises';import {execFileSync} from 'node:child_process';import {createHash} from 'node:crypto';import {chromium} from 'playwright';
import {Runtime} from '../src/runtime.mjs';import {Store} from '../src/store.mjs';import {applicationModel} from '../../core/application-model.mjs';import {getTargetInfo} from '../src/browser-target.mjs';import {singlePagePanel} from '../src/single-page.mjs';
const original=execFileSync('git',['show','bd916b2944a577b160a6afcb8a7d73d263044c0c:extension/content.js'],{encoding:'utf8',maxBuffer:4*1024*1024}),current=await readFile(new URL('../../core/form-engine.js',import.meta.url),'utf8');
const fn=source=>source.match(/^  function prescanPage\([^]*?^  \}/m)?.[0].replace(/\r\n/g,'\n');assert.ok(fn(original));assert.equal(fn(original),fn(current));
const store=new Store(':memory:'),runtime=new Runtime(store,'unused-prescan-fixture'),snapshot={documents:{siteProfiles:{p:{id:'p',name:'Original product',fields:{Name:'Original product',Url:'https://product.example'}}},submissionRecords:{kept:{status:'success',evidence:'original receipt'}},siteAnnotations:{}},revisions:{siteProfiles:2}};
store.set('pair',{endpoint:'https://cloud.example',workspaceId:'prescan'});store.set('paused',true);store.set('acceptanceBatch',{status:'paused',cursor:13,count:30});let posts=0,externalRequests=0,subjectInfo,subject;
Object.defineProperty(runtime,'cloud',{value:{async request(route){assert.equal(route,'snapshot');return structuredClone(snapshot);}}});
const article='Original article discusses directory submissions and feedback, existing evidence and links. '.repeat(10);
const form='<form id="commentform" method="POST"><label>Name<input name="author" id="author"></label><label>Website<input name="url" id="url" type="url"></label><label>Comment<textarea name="comment" id="comment" maxlength="700"></textarea></label><button type="submit">Post Comment</button></form>';
const server=http.createServer(async(req,res)=>{try{const path=new URL(req.url,'http://localhost').pathname;if(path==='/article'){if(req.method==='POST')posts++;res.setHeader('Content-Type','text/html');res.end('<title>Original link scan</title><meta name="robots" content="noindex, follow"><meta name="description" content="Original article description"><meta name="keywords" content="original, links"><article><h1>Original heading</h1>'+article+'</article><div class="comments"><a href="https://a.example" rel="nofollow ugc">A</a><a href="https://b.example">B</a><a href="https://c.example">C</a></div><a href="https://d.example" rel="nofollow sponsored">D</a><a href="https://e.example" rel="nofollow">E</a><a href="https://f.example" rel="nofollow">F</a><a href="https://g.example">G</a><a href="/internal">Internal</a>'+form);return;}
const files={'/':'../web/application.html','/profiles-core.js':'../../core/profiles.js','/target-filters-core.js':'../../core/target-filters.js','/timeline-core.js':'../../core/submission-timeline.js'};if(path in files||['/application.js','/comment-studio.js','/setup.js','/application.css','/activity-time.js'].includes(path)){res.setHeader('Content-Type',path.endsWith('.js')?'text/javascript':path.endsWith('.css')?'text/css':'text/html');res.end(await readFile(new URL(files[path]||'../web'+path,import.meta.url)));return;}
let raw='';for await(const chunk of req)raw+=chunk;const input=raw?JSON.parse(raw):{};let result;if(path==='/connection')result={ok:true};else if(path==='/appData')result={ok:true,model:applicationModel(snapshot),tasks:[],runtime:{paused:true,busy:false,pendingEvents:0},assistant:{settings:{}},settings:{},pendingEdits:[]};else if(path==='/browserLibraryPages')result={ok:true,pages:[{targetId:subjectInfo.targetId,url:subject.url(),title:'Original article'}]};else if(path==='/sidepanelState')result={ok:true,panel:singlePagePanel(runtime)};else if(['/sidepanelOpened','/sidepanelClosed','/sidepanelDetect'].includes(path))result=await runtime.control(path.slice(1),input);else throw Error('Unexpected fixture route '+path);res.setHeader('Content-Type','application/json');res.end(JSON.stringify(result));}catch(error){res.writeHead(500,{'Content-Type':'application/json'});res.end(JSON.stringify({ok:false,error:error.message}));}});
await new Promise(done=>server.listen(0,'127.0.0.1',done));const base='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({channel:'chrome',headless:true,args:['--disable-extensions']});
try{const context=await browser.newContext();runtime.context=context;runtime.host={startedAt:'prescan-browser'};await context.route('**/*',route=>{if(new URL(route.request().url()).origin===base)return route.continue();externalRequests++;return route.abort();});subject=await context.newPage();await subject.goto(base+'/article');subjectInfo=await getTargetInfo(context,subject);const page=await context.newPage();page.setDefaultTimeout(7000);await page.goto(base);await page.getByRole('button',{name:'外链库',exact:true}).click();await page.getByRole('button',{name:'当前网页填写',exact:true}).click();const response=page.waitForResponse(reply=>reply.url().endsWith('/sidepanelDetect'));await page.getByRole('button',{name:'检测所选网页',exact:true}).click();const result=await(await response).json();assert.equal(result.ok,true,result.error);assert.equal(result.frames.length,1);const scan=result.frames[0].prescan;assert.ok(scan,'Original prescan results are absent from the current detection response');
assert.deepEqual(Object.fromEntries(['externalLinks','externalNofollow','userContentNofollow','nofollowRatio','commentExternalLinks','commentNofollow','dofollowLikely','indexable','commentMaxLength'].map(key=>[key,scan[key]])),{externalLinks:7,externalNofollow:4,userContentNofollow:2,nofollowRatio:0.571,commentExternalLinks:3,commentNofollow:1,dofollowLikely:true,indexable:false,commentMaxLength:700});assert.equal(scan.title,'Original link scan');assert.equal(scan.description,'Original article description');assert.equal(scan.keywords,'original, links');assert.equal(scan.h1,'Original heading');assert.ok(scan.articleChars>600);assert.equal(scan.hasCommentForm,true);
await page.getByText('页面预扫描',{exact:true}).waitFor();await page.getByText('外链 7 条，其中 nofollow 4 条；评论区外链 3 条，其中 nofollow 1 条。',{exact:true}).waitFor();await page.getByText('可跟踪链接：较可能（根据现有链接估计） · 搜索引擎索引：页面禁止索引 · 评论上限：700 字',{exact:true}).waitFor();
await subject.evaluate(()=>{document.querySelectorAll('.comments a').forEach(link=>link.rel='nofollow');document.querySelector('meta[name=robots]').content='index, follow';});const params={panelId:singlePagePanel(runtime).id,targetId:subjectInfo.targetId,profileId:'p',expectedUrl:subject.url()};const second=await runtime.control('sidepanelDetect',params);assert.equal(second.frames[0].prescan.dofollowLikely,false);assert.equal(second.frames[0].prescan.indexable,true);
await subject.evaluate(()=>{document.querySelectorAll('a').forEach(link=>link.remove());document.querySelector('#comment').removeAttribute('maxlength');});const third=await runtime.control('sidepanelDetect',params);assert.equal(third.frames[0].prescan.dofollowLikely,null);assert.equal(third.frames[0].prescan.nofollowRatio,null);assert.equal(third.frames[0].prescan.commentMaxLength,null);
assert.equal(await subject.locator('#comment').inputValue(),'');assert.equal(store.values('task:').length,0);assert.equal(store.pendingCount(),0);assert.equal(store.get('acceptanceBatch').cursor,13);assert.equal(posts,0);assert.equal(externalRequests,0);await page.getByRole('button',{name:'关闭详情',exact:true}).click();console.log(JSON.stringify({ok:true,originalCompletePrescanFunctionSourceUnchanged:true,originalFunctionSha256:createHash('sha256').update(fn(original)).digest('hex'),actualUiEntryAndNativeDetectionUsed:true,originalPrescanProperties:20,commentLinksTakePriority:true,indexableFalseAndTrueVerified:true,insufficientLinksRemainUnknown:true,commentMaxAndUnlimitedVerified:true,fieldsLeftBlank:true,originalReceiptsAndPausedBatchPreserved:true,taskRegistrations:0,posts,externalRequests,productionWrites:0}));
}finally{await browser.close();await new Promise(done=>server.close(done));store.close();}
