import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {chromium} from 'playwright';import {Store} from '../src/store.mjs';import {Runtime} from '../src/runtime.mjs';import {runProductHuntWorkflow} from '../src/product-hunt.mjs';import {manualSubmit} from '../src/manual-controls.mjs';import {getTargetInfo} from '../src/browser-target.mjs';import {profiles,plain} from '../src/shared.mjs';
import {sidepanelOpened,sidepanelFill} from '../src/single-page.mjs';import {queue} from '../src/shared.mjs';
import {fillAssistantTask} from '../src/browser-assistant.mjs';import {workbenchScope} from '../src/workbench-sync.mjs';
const html=String.raw`<!doctype html><title>Isolated launch fixture</title><style>body{font:16px sans-serif}input,textarea,select,button{display:block;margin:8px}input[type=checkbox]{display:inline}</style><main id=stage></main><script>
window.created=0;window.trusted=false;window.visited=[];window.captured={};window.uploads=[];
const panes=[
 '<h1>My products</h1><p>Frozen Product draft</p><button onclick="render(1)">Continue editing</button>',
 '<h1>Main info</h1><label>Product name<input name="name" required></label><label>Website<input name="website" type="url" required></label><label>Tagline<input name="tagline" required></label><label>Product description<textarea name="description" required></textarea></label><button onclick="capture();render(2)">Next step: Images and media</button>',
 '<h1>Images and media</h1><label>Logo<input name="thumbnailImageUuid" type="file" accept="image/png" required onchange="preview(this)"></label><label>Gallery<input name="media" type="file" accept="image/png" multiple required onchange="preview(this)"></label><button onclick="render(3)">Next step: Makers</button>',
 '<h1>Makers</h1><label><input type="checkbox" name="isMaker" id="isMaker">I worked on this product</label><label><input type="checkbox" name="soloMaker" id="soloMaker">Solo maker</label><button onclick="capture();render(4)">Next step: Company info</button>',
 '<h1>Company info</h1><label><input type="checkbox" name="bootstrapped" id="bootstrapped">Bootstrapped</label><label>Team size<select name="teamSize"><option value="1" selected>1</option></select></label><label>Crunchbase URL<input name="crunchbaseUrl" type="url"></label><button onclick="capture();render(5)">Next step: Shoutouts</button>',
 '<h1>Shoutouts</h1><label>First comment<textarea name="commentBody"></textarea></label><button onclick="capture();render(6)">Next step: Extras</button>',
 '<h1>Extras</h1><label>Pricing<select name="pricingType"><option value="">Choose</option><option value="free">Free</option></select></label><button onclick="capture();render(7)">Next step: Connect with investors</button>',
 '<h1>Investors</h1><button onclick="render(8)">Next step: Launch checklist</button>',
 '<h1>Launch checklist</h1><div role="progressbar" aria-valuenow="100">All steps complete</div><button id="create" onclick="window.trusted=event.isTrusted;window.created++;document.querySelector(\x27main\x27).innerHTML=\x27<h1>Frozen Product</h1><p>Draft created</p>\x27">Create draft</button>'
];
window.capture=()=>document.querySelectorAll('input,textarea,select').forEach(e=>window.captured[e.name]=e.type==='checkbox'?e.checked:e.value);
window.preview=async input=>{const files=await Promise.all([...input.files].map(async file=>({name:file.name,type:file.type,bytes:[...new Uint8Array(await file.arrayBuffer())]})));window.uploads.push({input:input.name,files});for(const file of input.files){const image=document.createElement('img');image.alt=input.name==='media'?'Media':'preview';image.width=30;image.height=30;image.src=URL.createObjectURL(file);input.parentElement.append(image);}};
window.render=index=>{window.visited.push(index);document.querySelector('main').innerHTML=panes[index];};render(0);
</script>`;
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--disable-extensions']}),context=await browser.newContext(),store=new Store(':memory:');let requests=0,posts=0;
let mediaBytes;const mediaRefs=['cloud-media://fixture/logo','cloud-media://fixture/gallery-1','cloud-media://fixture/gallery-2'],mediaReads=[];
await context.route('**/*',route=>{requests++;if(route.request().method()==='POST')posts++;return route.fulfill({status:200,contentType:'text/html',body:html});});
try{
 const page=await context.newPage();await page.goto('https://www.producthunt.com/posts/new');const info=await getTargetInfo(context,page),profile={id:'p',name:'Frozen Product',fields:{Name:'Frozen Product',Url:'https://product.example','Short description(20-30 words)':'A factual launch fixture tagline','Long description (250-500 words)':'Original product description for an isolated launch test.','Solo Maker':'Yes',Funding:'Bootstrapped','Team size':'1','Crunchbase URL':'https://www.crunchbase.com/organization/fixture','Product Hunt First Comment':'A factual comment supplied by this fixture.',Pricing:'Free'}};
 profile.media={logo:mediaRefs[0],screenshots:mediaRefs.slice(1)};
 mediaBytes=Buffer.from((await page.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=canvas.height=32;const ctx=canvas.getContext('2d');ctx.fillStyle='#126abc';ctx.fillRect(0,0,32,32);return canvas.toDataURL('image/png');})).split(',')[1],'base64');
 const task={id:'original-ph',runId:'original-run',profileId:'p',url:page.url(),targetId:info.targetId,browserInstance:'fixture-browser',profileRevision:2,profileSnapshot:profile,status:'needs_manual',controller:'executor'};store.set('pair',{endpoint:'https://cloud.example',workspaceId:'fixture'});store.set('paused',true);store.set('task:'+task.id,task);store.set('run:'+task.runId,{id:task.runId,profile});
 task.destinationKey=queue.normalizeDestinationKey(page.url());task.targetId='previous-target';delete task.profileSnapshot;store.set('task:'+task.id,task);store.set('run:'+task.runId,{id:task.runId,profileId:'p',profileRevision:2,profile});
 let flushes=0,accepted=0;const runtime={store,context,host:{startedAt:'fixture-browser'},job:null,lease:async()=>{},findPage:async()=>page,tick:()=>{},bridge:async()=>({ok:true}),update(t,patch,type){Object.assign(t,patch);store.transition(t,type);},cloud:{request:async()=>({documents:{siteProfiles:{p:profile},submissionRecords:{}},revisions:{siteProfiles:2}}),flush:async()=>{assert.ok(store.get('task:'+task.id).attemptBoundary);assert.equal(await page.evaluate(()=>window.created),0);await page.evaluate(()=>{const create=document.getElementById('create'),rect=create.getBoundingClientRect(),decoy=document.createElement('button');decoy.textContent='Next step: Extras';decoy.style.cssText='position:fixed;left:'+rect.left+'px;top:'+rect.top+'px;width:'+rect.width+'px;height:'+rect.height+'px';decoy.onclick=()=>window.staleClicks=(window.staleClicks||0)+1;document.querySelector('main').append(decoy);create.style.marginLeft='320px';});flushes++;}},synchronize:async()=>{for(const event of store.pending())store.ack(event.id);},accept:async(t,p,result)=>{assert.ok(t.attemptBoundary);accepted++;runtime.update(t,{status:'finished',receipt:{evidence:result.evidence,publicationStatus:result.publicationStatus}},'fixture_receipt');}};
 const requestSnapshot=runtime.cloud.request;runtime.cloud.request=async(route,input)=>{if(route==='runs?view=inventory')return{tasks:[store.get('task:'+task.id)],runs:[store.get('run:'+task.runId)]};if(route==='snapshot'){const snapshot=await requestSnapshot(route,input);snapshot.documents.siteProfiles.p={...profile,name:'Latest Different Name',fields:{...profile.fields,Name:'Latest Different Name'}};snapshot.revisions.siteProfiles=5;return snapshot;}if(route!=='media')throw Error('Unexpected cloud route '+route);assert.equal(input.taskId,task.id);assert.ok(mediaRefs.includes(input.ref));mediaReads.push(input.ref);return{ok:true,name:input.ref.split('/').at(-1)+'.png',dataUrl:'data:image/png;base64,'+mediaBytes.toString('base64')};};runtime.bridge=(task,message)=>Runtime.prototype.bridge.call(runtime,task,message);
 runtime.prepareWithAi=async()=>{throw Error('Fixture fields must fill without AI: '+JSON.stringify({mediaReads,uploads:await page.evaluate(()=>window.uploads),history:task.productHunt.history.slice(-3)}));};
 const config=plain(profiles.buildAgentConfigFromProfile(profile)),opened=sidepanelOpened(runtime,{profileId:'p',targetId:info.targetId}),panelInput={panelId:opened.panel.id,profileId:'p',targetId:info.targetId,expectedUrl:page.url(),mode:'form'};const fill=await sidepanelFill(runtime,panelInput);Object.assign(task,store.get('task:'+task.id));let prepared=fill.fill;assert.equal(fill.taskId,'original-ph');assert.equal(fill.runId,'original-run');assert.deepEqual(task.profileSnapshot,profile);assert.equal(task.profileRevision,2);assert.equal(task.pageHistory[0].targetId,'previous-target');assert.equal(task.productHuntCreationConsent,null);assert.equal(prepared.ready_to_create,true);assert.equal(await page.evaluate(()=>window.created),0);assert.equal(task.attemptBoundary,undefined);assert.deepEqual(await page.evaluate(()=>window.visited),[0,1,2,3,4,5,6,7,8]);const actual=await page.evaluate(()=>window.captured);assert.equal(actual.name,'Frozen Product');assert.equal(actual.website,'https://product.example');assert.equal(actual.soloMaker,true);assert.equal(actual.bootstrapped,true);assert.equal(actual.pricingType,'free');
 const uploads=await page.evaluate(()=>window.uploads);assert.deepEqual(uploads.map(u=>[u.input,u.files.length]),[['thumbnailImageUuid',1],['media',2]]);assert.deepEqual(mediaReads,mediaRefs);for(const file of uploads.flatMap(u=>u.files)){assert.equal(file.type,'image/png');assert.deepEqual(Buffer.from(file.bytes),mediaBytes);}assert.equal(task.productHunt.history.find(s=>s.stage==='images').actualPreparation.fields.filter(f=>f.type==='file').length,2);
 assert.ok(task.actualSubmission.fields.some(f=>f.stage==='main_info'&&f.name==='name'&&f.value==='Frozen Product'));assert.equal(task.actualSubmission.attachments.length,3);for(const file of task.actualSubmission.attachments){assert.equal(file.sha256,createHash('sha256').update(mediaBytes).digest('hex'));assert.equal(file.stage,'images');}
 assert.ok(store.values('fillLearning:').some(item=>item.taskId===task.id&&Object.values(item.mappings).some(m=>m.profileKey==='Name'&&m.value==='Frozen Product')));assert.ok(store.values('fillLearning:').every(item=>!JSON.stringify(item.schema).includes('Frozen Product')));
 const snapshotRequest=runtime.cloud.request;runtime.cloud.request=async(route,input)=>{const value=await snapshotRequest(route,input);if(route==='snapshot')value.documents.sheetTableData={entries:[{link:page.url(),name:'Product Hunt'}]};return value;};const scope=workbenchScope(store.get('pair'));store.set('applicationSnapshot',{scope,snapshot:await runtime.cloud.request('snapshot')});store.set('browserAssistantSettings',{scope,enabled:true,autoFillOnVisit:true,profileId:'p'});const assistant=await fillAssistantTask(runtime,{taskId:task.id,targetId:task.targetId,url:page.url(),panelId:opened.panel.id,panelGeneration:opened.panel.generation});assert.equal(assistant.platform,'product_hunt');assert.equal(assistant.readyToCreate,true);assert.equal(assistant.submitted,false);assert.equal(await page.evaluate(()=>window.created),0);assert.equal(store.get('task:'+task.id).attemptBoundary,undefined);Object.assign(task,store.get('task:'+task.id));store.set('browserAssistantSettings',{scope,enabled:false,autoFillOnVisit:false,profileId:'p'});
 await page.evaluate(()=>{const label=document.createElement('label');label.innerHTML='<input type="checkbox" name="acceptTerms" required>Accept terms';document.querySelector('main').append(label);});const gate=await runProductHuntWorkflow(runtime,task,page,config,{active:()=>true});assert.equal(gate.needs_manual,true);assert.equal(await page.evaluate(()=>window.created),0);assert.equal(task.attemptBoundary,undefined);await page.evaluate(()=>render(8));prepared=await runProductHuntWorkflow(runtime,task,page,config,{active:()=>true});assert.equal(prepared.ready_to_create,true);
 await manualSubmit(runtime,{taskId:task.id,expectedRunId:task.runId,expectedTargetId:task.targetId,ordinaryPermissionsAuthorized:true,confirmProductHuntCreate:true});assert.equal(store.get('task:'+task.id).productHuntCreationConsent.targetId,task.targetId);Object.assign(task,store.get('task:'+task.id));const result=await runProductHuntWorkflow(runtime,task,page,config,{confirmCreate:true});assert.equal(result.matched,true);assert.equal(await page.evaluate(()=>window.created),1);assert.equal(await page.evaluate(()=>window.trusted),true);assert.equal(flushes,1);assert.equal(accepted,1);await assert.rejects(runProductHuntWorkflow(runtime,task,page,config,{confirmCreate:true}),/必须先核验/);assert.equal(await page.evaluate(()=>window.created),1);assert.equal(posts,0);
 assert.equal(await page.evaluate(()=>window.staleClicks||0),0);assert.equal(mediaReads.length,3);
 console.log(JSON.stringify({ok:true,kind:'synthetic_producthunt_launch',originalStages:9,sidepanelOriginalTask:true,frozenProfileAcrossCloudChanges:true,previousPagePreserved:true,actualFieldsVerified:true,cloudMediaBridge:true,actualFileInputs:true,logoFiles:1,galleryFiles:2,fileBytesVerified:true,defaultWaitsForConfirmation:true,legalGatePreserved:true,originalConsentBinding:true,durableBoundaryBeforeTrustedClick:true,freshButtonPosition:true,oneTrustedCreateClick:true,newDraftEvidence:true,noRepeat:true,networkPosts:posts,interceptedRequests:requests}));
}finally{store.close();await browser.close();}
