import assert from 'node:assert/strict';import {chromium} from 'playwright';import {Store} from '../src/store.mjs';import {runProductHuntWorkflow} from '../src/product-hunt.mjs';import {manualSubmit} from '../src/manual-controls.mjs';import {getTargetInfo} from '../src/browser-target.mjs';import {profiles,plain} from '../src/shared.mjs';
const html=String.raw`<!doctype html><title>Isolated launch fixture</title><style>body{font:16px sans-serif}input,textarea,select,button{display:block;margin:8px}input[type=checkbox]{display:inline}</style><main id=stage></main><script>
window.created=0;window.trusted=false;window.visited=[];window.captured={};
const panes=[
 '<h1>My products</h1><p>Frozen Product draft</p><button onclick="render(1)">Continue editing</button>',
 '<h1>Main info</h1><label>Product name<input name="name" required></label><label>Website<input name="website" type="url" required></label><label>Tagline<input name="tagline" required></label><label>Product description<textarea name="description" required></textarea></label><button onclick="capture();render(2)">Next step: Images and media</button>',
 '<h1>Images and media</h1><button onclick="render(3)">Next step: Makers</button>',
 '<h1>Makers</h1><label><input type="checkbox" name="isMaker" id="isMaker">I worked on this product</label><label><input type="checkbox" name="soloMaker" id="soloMaker">Solo maker</label><button onclick="capture();render(4)">Next step: Company info</button>',
 '<h1>Company info</h1><label><input type="checkbox" name="bootstrapped" id="bootstrapped">Bootstrapped</label><label>Team size<select name="teamSize"><option value="1" selected>1</option></select></label><label>Crunchbase URL<input name="crunchbaseUrl" type="url"></label><button onclick="capture();render(5)">Next step: Shoutouts</button>',
 '<h1>Shoutouts</h1><label>First comment<textarea name="commentBody"></textarea></label><button onclick="capture();render(6)">Next step: Extras</button>',
 '<h1>Extras</h1><label>Pricing<select name="pricingType"><option value="">Choose</option><option value="free">Free</option></select></label><button onclick="capture();render(7)">Next step: Connect with investors</button>',
 '<h1>Investors</h1><button onclick="render(8)">Next step: Launch checklist</button>',
 '<h1>Launch checklist</h1><div role="progressbar" aria-valuenow="100">All steps complete</div><button id="create" onclick="window.trusted=event.isTrusted;window.created++;document.querySelector(\x27main\x27).innerHTML=\x27<h1>Frozen Product</h1><p>Draft created</p>\x27">Create draft</button>'
];
window.capture=()=>document.querySelectorAll('input,textarea,select').forEach(e=>window.captured[e.name]=e.type==='checkbox'?e.checked:e.value);
window.render=index=>{window.visited.push(index);document.querySelector('main').innerHTML=panes[index];};render(0);
</script>`;
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--disable-extensions']}),context=await browser.newContext(),store=new Store(':memory:');let requests=0,posts=0;
await context.route('**/*',route=>{requests++;if(route.request().method()==='POST')posts++;return route.fulfill({status:200,contentType:'text/html',body:html});});
try{
 const page=await context.newPage();await page.goto('https://www.producthunt.com/posts/new');const info=await getTargetInfo(context,page),profile={id:'p',name:'Frozen Product',fields:{Name:'Frozen Product',Url:'https://product.example','Short description(20-30 words)':'A factual launch fixture tagline','Long description (250-500 words)':'Original product description for an isolated launch test.','Solo Maker':'Yes',Funding:'Bootstrapped','Team size':'1','Crunchbase URL':'https://www.crunchbase.com/organization/fixture','Product Hunt First Comment':'A factual comment supplied by this fixture.',Pricing:'Free'}};
 const task={id:'original-ph',runId:'original-run',profileId:'p',url:page.url(),targetId:info.targetId,browserInstance:'fixture-browser',profileRevision:2,profileSnapshot:profile,status:'needs_manual',controller:'executor'};store.set('pair',{endpoint:'https://cloud.example',workspaceId:'fixture'});store.set('paused',true);store.set('task:'+task.id,task);store.set('run:'+task.runId,{id:task.runId,profile});
 let flushes=0,accepted=0;const runtime={store,context,host:{startedAt:'fixture-browser'},job:null,lease:async()=>{},findPage:async()=>page,tick:()=>{},bridge:async()=>({ok:true}),update(t,patch,type){Object.assign(t,patch);store.transition(t,type);},cloud:{request:async()=>({documents:{siteProfiles:{p:profile},submissionRecords:{}},revisions:{siteProfiles:2}}),flush:async()=>{assert.ok(store.get('task:'+task.id).attemptBoundary);assert.equal(await page.evaluate(()=>window.created),0);await page.evaluate(()=>{const create=document.getElementById('create'),rect=create.getBoundingClientRect(),decoy=document.createElement('button');decoy.textContent='Next step: Extras';decoy.style.cssText='position:fixed;left:'+rect.left+'px;top:'+rect.top+'px;width:'+rect.width+'px;height:'+rect.height+'px';decoy.onclick=()=>window.staleClicks=(window.staleClicks||0)+1;document.querySelector('main').append(decoy);create.style.marginLeft='320px';});flushes++;}},synchronize:async()=>{for(const event of store.pending())store.ack(event.id);},accept:async(t,p,result)=>{assert.ok(t.attemptBoundary);accepted++;runtime.update(t,{status:'finished',receipt:{evidence:result.evidence,publicationStatus:result.publicationStatus}},'fixture_receipt');}};
 const config=plain(profiles.buildAgentConfigFromProfile(profile));let prepared=await runProductHuntWorkflow(runtime,task,page,config,{active:()=>true});assert.equal(prepared.ready_to_create,true);assert.equal(await page.evaluate(()=>window.created),0);assert.equal(task.attemptBoundary,undefined);assert.deepEqual(await page.evaluate(()=>window.visited),[0,1,2,3,4,5,6,7,8]);const actual=await page.evaluate(()=>window.captured);assert.equal(actual.name,'Frozen Product');assert.equal(actual.website,'https://product.example');assert.equal(actual.soloMaker,true);assert.equal(actual.bootstrapped,true);assert.equal(actual.pricingType,'free');
 await page.evaluate(()=>{const label=document.createElement('label');label.innerHTML='<input type="checkbox" name="acceptTerms" required>Accept terms';document.querySelector('main').append(label);});const gate=await runProductHuntWorkflow(runtime,task,page,config,{active:()=>true});assert.equal(gate.needs_manual,true);assert.equal(await page.evaluate(()=>window.created),0);assert.equal(task.attemptBoundary,undefined);await page.evaluate(()=>render(8));prepared=await runProductHuntWorkflow(runtime,task,page,config,{active:()=>true});assert.equal(prepared.ready_to_create,true);
 await manualSubmit(runtime,{taskId:task.id,expectedRunId:task.runId,expectedTargetId:task.targetId,ordinaryPermissionsAuthorized:true,confirmProductHuntCreate:true});assert.equal(store.get('task:'+task.id).productHuntCreationConsent.targetId,task.targetId);Object.assign(task,store.get('task:'+task.id));const result=await runProductHuntWorkflow(runtime,task,page,config,{confirmCreate:true});assert.equal(result.matched,true);assert.equal(await page.evaluate(()=>window.created),1);assert.equal(await page.evaluate(()=>window.trusted),true);assert.equal(flushes,1);assert.equal(accepted,1);await assert.rejects(runProductHuntWorkflow(runtime,task,page,config,{confirmCreate:true}),/必须先核验/);assert.equal(await page.evaluate(()=>window.created),1);assert.equal(posts,0);
 console.log(JSON.stringify({ok:true,kind:'synthetic_producthunt_launch',originalStages:9,actualFieldsVerified:true,defaultWaitsForConfirmation:true,legalGatePreserved:true,originalConsentBinding:true,durableBoundaryBeforeTrustedClick:true,oneTrustedCreateClick:true,newDraftEvidence:true,noRepeat:true,networkPosts:posts,interceptedRequests:requests}));
}finally{store.close();await browser.close();}
