import assert from 'node:assert/strict';import http from 'node:http';import {readFile} from 'node:fs/promises';import {chromium} from 'playwright';import {applicationModel} from '../../core/application-model.mjs';import {applicationMutation} from '../../core/application-mutation.mjs';import {Store} from '../src/store.mjs';import {workbenchScope} from '../src/workbench-sync.mjs';import {enqueueProfileMutation} from '../src/application-mutations.mjs';import {imageFormatFixtures} from './image-format-fixtures.mjs';
const image=imageFormatFixtures[0],docs={siteProfiles:{p:{id:'p',name:'Original Product',url:'https://original.example',fields:{Name:'Original Product',Url:'https://original.example',Title:'Original title','Cloud LOGO':'cloud-media://old-logo'},media:{logo:'cloud-media://old-logo'},mediaVersions:[{assetId:'old-logo',ref:'cloud-media://old-logo',kind:'logo',mime:image.mime,sha256:'0000000000000000000000000000000000000000000000000000000000000000',fileName:image.name}]}},activeSiteId:'p',selectedSiteIds:['p'],submissionRecords:{keep:{profileId:'p',status:'success',evidence:'Original receipt'}}},receipt=structuredClone(docs.submissionRecords),revisions={siteProfiles:1},writes=[],errors=[],store=new Store(':memory:'),pair={endpoint:'https://fixture.invalid',workspaceId:'editor'};let holdSave=false,saveHeld,releaseSave,uploads=0,concurrentMedia=false;
const runtime={store,cloud:{async request(route,input){if(route==='snapshot')return{documents:structuredClone(docs),revisions:structuredClone(revisions)};assert.equal(route,'profile');const change=applicationMutation(docs,{type:'profile',profileId:input.profileId,profile:input.profile,at:new Date().toISOString()});assert.equal(input.revision,revisions.siteProfiles);docs[change.key]=change.data;revisions.siteProfiles++;return{ok:true};}}};store.set('pair',pair);store.set('paused',true);
const cache=()=>store.set('applicationSnapshot',{scope:workbenchScope(pair),snapshot:{documents:structuredClone(docs),revisions:structuredClone(revisions)}});cache();
const server=http.createServer(async(req,res)=>{const path=new URL(req.url,'http://localhost').pathname;let raw='';for await(const chunk of req)raw+=chunk;const input=raw?JSON.parse(raw):{};
 try{
  if(['/', '/application.js','/comment-studio.js','/setup.js','/application.css','/activity-time.js','/timeline-core.js','/profiles-core.js','/target-filters-core.js'].includes(path)){const name=path==='/'?'application.html':path.slice(1),file=name==='timeline-core.js'?'../../core/submission-timeline.js':name==='profiles-core.js'?'../../core/profiles.js':name==='target-filters-core.js'?'../../core/target-filters.js':'../web/'+name;res.setHeader('Content-Type',name.endsWith('.js')?'text/javascript':name.endsWith('.css')?'text/css':'text/html');res.end(await readFile(new URL(file,import.meta.url)));return;}
  if(path.startsWith('/cloud/workspace/media/')){res.setHeader('Content-Type',image.mime);res.end(image.bytes);return;}
  writes.push({route:path,...structuredClone(input)});let result;
  if(path==='/connection')result={ok:true};
  else if(path==='/appData'){cache();result={ok:true,at:new Date().toISOString(),model:applicationModel({documents:docs}),revisions:structuredClone(revisions),runtime:{paused:true,busy:false,pendingEvents:0},tasks:[],acceptances:[],pendingEdits:[],workbenchBatches:[],settings:{},assistant:{settings:{enabled:false},fills:[]}};}
  else if(path==='/profile'){result=await enqueueProfileMutation(runtime,input);if(holdSave){holdSave=false;saveHeld?.();await new Promise(resolve=>releaseSave=resolve);}}
  else if(path==='/libraryMutation'){const change=applicationMutation(docs,{...input.operation,id:'editor-media',at:new Date().toISOString()});docs[change.key]=change.data;revisions.siteProfiles++;cache();result={ok:true};}
  else if(path==='/mediaUpload'){const current=docs.siteProfiles.p,kind=input.kind,assetId=++uploads===1?'new-logo':'new-'+kind+'-'+uploads,ref='cloud-media://'+assetId,media={...current.media},fields={};if(kind==='logo'){media.logo=ref;fields['Cloud LOGO']=ref;}else if(kind==='featured'){media.featured=ref;fields['Cloud Featured image']=ref;}else{media.screenshots=[...(media.screenshots||[])];media.screenshots[Number(kind.slice(10))-1]=ref;fields['Screenshot '+kind.slice(10)]=ref;}const change=applicationMutation(docs,{type:'profile',profileId:'p',profile:{id:'p',fields,media,mediaVersions:[...current.mediaVersions,{assetId,ref,kind,mime:image.mime,sha256:'0000000000000000000000000000000000000000000000000000000000000000',fileName:image.name}]},at:new Date().toISOString()});docs[change.key]=change.data;if(concurrentMedia)docs.siteProfiles.p.fields.Title='Concurrent during media';revisions.siteProfiles++;cache();result={ok:true,assetId,pending:0};}
  else throw Error('Unexpected route '+path);
  res.setHeader('Content-Type','application/json');res.end(JSON.stringify(result));
 }catch(error){res.writeHead(error.status||500,{'Content-Type':'application/json'});res.end(JSON.stringify({ok:false,error:error.message}));}
});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const browser=await chromium.launch({channel:'chrome',headless:true,args:['--disable-extensions']});
try{
 const context=await browser.newContext(),page=await context.newPage();page.on('pageerror',error=>errors.push(error.message));await page.route('**/*',route=>new URL(route.request().url()).hostname==='127.0.0.1'?route.continue():route.abort());await page.goto('http://127.0.0.1:'+server.address().port+'/#access=fixture');await page.getByRole('button',{name:'编辑当前网站',exact:true}).waitFor();await page.getByRole('button',{name:'编辑当前网站',exact:true}).click();await page.getByLabel('产品名称',{exact:true}).fill('Unsaved draft');page.once('dialog',dialog=>dialog.dismiss());await page.getByRole('button',{name:'关闭详情'}).click();assert.equal(await page.locator('dialog').evaluate(node=>node.open),true,'Closing a product editor must preserve an unconfirmed draft');assert.equal(await page.getByLabel('产品名称',{exact:true}).inputValue(),'Unsaved draft');
 page.once('dialog',dialog=>dialog.dismiss());await page.keyboard.press('Escape');assert.equal(await page.locator('dialog').evaluate(node=>node.open),true);assert.equal(docs.siteProfiles.p.name,'Original Product');
 const held=new Promise(resolve=>saveHeld=resolve);holdSave=true;await page.getByRole('button',{name:'保存资料',exact:true}).click();await held;assert.equal(docs.siteProfiles.p.name,'Unsaved draft');await page.getByLabel('产品名称',{exact:true}).fill('Edited during save');await page.getByRole('button',{name:'关闭详情'}).click();assert.equal(await page.locator('dialog').evaluate(node=>node.open),true,'Save in flight must retain its owning editor');releaseSave();releaseSave=null;await page.getByText('本次资料已保存；表单还有新的修改，请再次保存。',{exact:true}).waitFor();page.once('dialog',dialog=>dialog.dismiss());await page.getByRole('button',{name:'关闭详情'}).click();assert.equal(await page.getByLabel('产品名称',{exact:true}).inputValue(),'Edited during save');await page.getByRole('button',{name:'保存资料',exact:true}).click();await page.getByText('已保存并回读云端；历史投稿保留旧版本。',{exact:true}).waitFor();assert.equal(docs.siteProfiles.p.name,'Edited during save');await page.getByRole('button',{name:'关闭详情'}).click();
 await page.getByRole('button',{name:'编辑当前网站',exact:true}).click();await page.getByLabel('产品名称',{exact:true}).fill('Local stale draft');const oldRevision=revisions.siteProfiles;docs.siteProfiles.p.fields.Title='Concurrent remote title';revisions.siteProfiles++;const refreshed=page.waitForResponse(response=>response.url().endsWith('/appData'));await page.getByRole('button',{name:'刷新云端',exact:true}).evaluate(node=>node.click());await refreshed;assert.equal(await page.getByLabel('产品名称',{exact:true}).inputValue(),'Local stale draft');await page.getByRole('button',{name:'保存资料',exact:true}).click();await page.getByText('尚未确认，编辑内容保留：资料版本已变化，请回读后重试',{exact:true}).waitFor();assert.equal(writes.findLast(item=>item.route==='/profile').revision,oldRevision);assert.equal(docs.siteProfiles.p.name,'Edited during save');assert.equal(docs.siteProfiles.p.fields.Title,'Concurrent remote title');assert.equal(await page.getByLabel('产品名称',{exact:true}).inputValue(),'Local stale draft');page.once('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'关闭详情'}).click();
 await page.getByRole('button',{name:'编辑当前网站',exact:true}).click();await page.getByLabel('产品名称',{exact:true}).fill('Draft preserved across upload');await page.getByLabel('上传新媒体版本',{exact:true}).setInputFiles({name:image.name,mimeType:image.mime,buffer:image.bytes});await page.getByText('新媒体版本已上传并回读',{exact:true}).waitFor();assert.equal(await page.getByLabel('产品名称',{exact:true}).inputValue(),'Draft preserved across upload');await page.getByRole('button',{name:'保存资料',exact:true}).click();await page.getByText('已保存并回读云端；历史投稿保留旧版本。',{exact:true}).waitFor();assert.equal(docs.siteProfiles.p.name,'Draft preserved across upload');assert.equal(docs.siteProfiles.p.fields['Cloud LOGO'],'cloud-media://new-logo');assert.equal(docs.siteProfiles.p.media.logo,'cloud-media://new-logo');assert.equal(docs.siteProfiles.p.mediaVersions.length,2);assert.deepEqual(docs.submissionRecords,receipt);assert.equal(store.get('paused'),true);assert.deepEqual(errors,[]);
 await page.getByRole('button',{name:'关闭详情'}).click();await page.getByRole('button',{name:'编辑当前网站',exact:true}).click();await page.getByLabel('产品名称',{exact:true}).fill('Draft across all media');
 for(const kind of ['featured','screenshot1','screenshot2','screenshot3','screenshot4']){await page.getByLabel('上传媒体类型').selectOption(kind);await page.getByLabel('上传新媒体版本').setInputFiles({name:image.name,mimeType:image.mime,buffer:image.bytes});await page.getByText('新媒体版本已上传并回读',{exact:true}).waitFor();assert.equal(await page.getByLabel('上传媒体类型').inputValue(),kind);assert.equal(await page.getByLabel('产品名称',{exact:true}).inputValue(),'Draft across all media');}
 await page.getByRole('button',{name:'停用此类媒体',exact:true}).click();await page.getByText('停用已保存，历史素材保留。',{exact:true}).waitFor();assert.equal(docs.siteProfiles.p.mediaDisabled.screenshot4,true);await page.getByRole('button',{name:'使用这个版本',exact:true}).last().click();await page.getByText('媒体版本选择已保存。',{exact:true}).waitFor();assert.equal(docs.siteProfiles.p.mediaDisabled.screenshot4,false);assert.equal(await page.getByLabel('产品名称',{exact:true}).inputValue(),'Draft across all media');const retainedMedia=structuredClone(docs.siteProfiles.p.media),retainedVersions=structuredClone(docs.siteProfiles.p.mediaVersions);await page.getByRole('button',{name:'保存资料',exact:true}).click();await page.getByText('已保存并回读云端；历史投稿保留旧版本。',{exact:true}).waitFor();assert.deepEqual(docs.siteProfiles.p.media,retainedMedia);assert.deepEqual(docs.siteProfiles.p.mediaVersions,retainedVersions);await page.getByRole('button',{name:'关闭详情'}).click();
 await page.getByRole('button',{name:'编辑当前网站',exact:true}).click();await page.getByLabel('产品名称',{exact:true}).fill('Draft during concurrent media');concurrentMedia=true;await page.getByLabel('上传媒体类型').selectOption('logo');await page.getByLabel('上传新媒体版本').setInputFiles({name:image.name,mimeType:image.mime,buffer:image.bytes});await page.getByText('媒体更新已记录；资料有其他变化，原编辑保留，请重新核对。',{exact:true}).waitFor();await page.getByRole('button',{name:'保存资料',exact:true}).click();await page.getByText('尚未确认，编辑内容保留：资料版本已变化，请回读后重试',{exact:true}).waitFor();assert.equal(docs.siteProfiles.p.fields.Title,'Concurrent during media');assert.equal(docs.siteProfiles.p.name,'Draft across all media');assert.equal(await page.getByLabel('产品名称',{exact:true}).inputValue(),'Draft during concurrent media');
 const unload=page.waitForEvent('dialog');const close=page.close({runBeforeUnload:true});const prompt=await unload;assert.equal(prompt.type(),'beforeunload');await prompt.dismiss();await close;assert.equal(page.isClosed(),false);assert.equal(await page.getByLabel('产品名称',{exact:true}).inputValue(),'Draft during concurrent media');assert.deepEqual(docs.submissionRecords,receipt);assert.deepEqual(errors,[]);
 console.log('Original dirty editor close, Escape and tab exit, in-flight edits, frozen revision after pull, all six media kinds preserving draft, disable and restore, and concurrent media protection passed; real submissions 0');
}finally{releaseSave?.();await browser.close();await new Promise(resolve=>server.close(resolve));store.close();}
