import assert from 'node:assert/strict';
import http from 'node:http';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
import {mkdtemp,readFile,rm} from 'node:fs/promises';
import {join,resolve,sep} from 'node:path';
import {tmpdir} from 'node:os';
import {chromium} from 'playwright';
import {Store} from '../src/store.mjs';

const home=await mkdtemp(join(tmpdir(),'el-run-export-ui-')),cloudCalls=[];
const documents={siteProfiles:{p:{id:'p',name:'原产品',fields:{Name:'原产品',Url:'https://product.example'}}},sheetTableData:{entries:[]},submissionRecords:{},submissionTimeline:{}};
const cloud=http.createServer((req,res)=>{cloudCalls.push({method:req.method,url:req.url});res.setHeader('Content-Type','application/json');if(req.method==='GET'&&req.url.startsWith('/v2/executor/snapshot'))res.end(JSON.stringify({ok:true,documents,revisions:{siteProfiles:1}}));else{res.writeHead(400);res.end(JSON.stringify({ok:false,error:'fixture rejects unrequested cloud actions'}));}});
await new Promise(resolve=>cloud.listen(0,'127.0.0.1',resolve));const cloudEndpoint='http://127.0.0.1:'+cloud.address().port,scope=cloudEndpoint+'|default';
let backend,web,browser,store;const serviceLogs=[];
async function start(file){const child=spawn(process.execPath,[resolve(import.meta.dirname,'../src/'+file)],{windowsHide:true,env:{...process.env,EXTERNALLINK_HOME:home,EXTERNALLINK_PORT:'0',EXTERNALLINK_WEB_PORT:'0'},stdio:['ignore','pipe','pipe']});child.stdout.on('data',data=>serviceLogs.push(String(data)));child.stderr.on('data',data=>serviceLogs.push(String(data)));for(let n=0;n<100;n++){if(child.exitCode!==null)throw Error('isolated service exited '+child.exitCode);try{const saved=JSON.parse(await readFile(join(home,file==='server.mjs'?'server.json':'workbench.json'),'utf8'));if(saved.pid===child.pid)return{child,endpoint:saved.endpoint};}catch{}await new Promise(resolve=>setTimeout(resolve,50));}throw Error('isolated service startup timed out');}
async function stop(service){if(!service||service.child.exitCode!==null)return;const finished=once(service.child,'exit');service.child.kill();await finished;}
try{
 store=new Store(join(home,'outbox.sqlite'));store.set('pair',{endpoint:cloudEndpoint,workspaceId:'default',localToken:'isolated-export-local',deviceToken:'isolated-device-secret',storageBackend:'d1'});store.set('paused',true);store.set('applicationSnapshot',{scope,snapshot:{documents,revisions:{siteProfiles:1}},at:'2026-10-01T00:00:00Z'});
 const items=Array.from({length:3},(_,n)=>({identity:'original-'+n,taskId:'original-task-'+n,runId:'original-run',profileId:'p',profile:{name:'原产品'},url:'https://site'+n+'.example/submit',status:'registered'}));
 const states=[{status:'finished',receipt:{evidence:'站方明确确认',publicationStatus:'pending_moderation',evidenceUrl:'https://site0.example/receipt'}},{status:'submitted_unconfirmed',attemptBoundary:{id:'original-boundary'},reason:'原响应丢失'},{status:'pending'}];
 for(const [index,item]of items.entries())store.set('task:'+item.taskId,{id:item.taskId,runId:item.runId,profileId:'p',url:item.url,...states[index]});
 store.set('workbenchBatch:original-batch',{id:'original-batch',scope,count:3,cursor:2,status:'paused',items,createdAt:'2026-10-01T00:00:00Z'});store.set('activeWorkbenchBatch','original-batch');
 const originalRun={runId:'old-run-ID',status:'failed',startedAt:'2020-01-01',taskTotal:1,tasks:{'old-task':{taskId:'old-task',status:'failed',artifactRef:'original-artifact'}},events:[{id:'original-event',at:'2020-01-01',result:'旧执行结果'}]};
 store.set('originalRunHistory:old',{id:'old',scope,activeBatchRun:{runId:'old-batch-ID',status:'paused',tasks:[{index:1,profileName:'旧产品',url:'https://old.example/submit',status:'err',skipReason:'原失败'}]},automationRunLedger:{schemaVersion:1,order:['old-run-ID'],runs:{'old-run-ID':originalRun}}});
 for(let n=0;n<1205;n++)store.appendLog({id:'original-log-'+n,runId:'original-run',taskId:'original-task-1',message:'原日志 '+n});store.close();store=null;
 backend=await start('server.mjs');web=await start('workbench-server.mjs');
 const api=async(endpoint,route,body={})=>{const response=await fetch(endpoint+route,{method:'POST',headers:{Authorization:'Bearer isolated-export-local','Content-Type':'application/json'},body:JSON.stringify(body)});return{status:response.status,data:await response.json()};};
 for(const endpoint of [backend.endpoint,web.endpoint]){assert.equal((await fetch(endpoint+'/runExportSources',{method:'POST',body:'{}'})).status,401);assert.equal((await api(endpoint,'/runExportSources')).status,200);assert.equal((await api(endpoint,'/exportBatchReport',{sourceId:'workbench:missing'})).status,400);const record=await api(endpoint,'/exportAutomationRun',{sourceId:'workbench:original-batch'});assert.equal(record.status,200);const body=JSON.parse(record.data.content);assert.equal(body.events.length,1205);assert.equal(body.tasks['original-task-1'].attemptBoundary.id,'original-boundary');assert.equal(body.frozenCombinations.length,3);}
 browser=await chromium.launch({channel:'chrome',headless:true,args:['--disable-extensions']});const page=await browser.newPage({acceptDownloads:true}),errors=[];page.on('pageerror',error=>errors.push(error.message));await page.goto(web.endpoint+'/#access=isolated-export-local');await page.getByRole('heading',{name:'原产品',exact:true}).waitFor();await page.getByRole('button',{name:'运行任务',exact:true}).click();
 async function download(button){const pending=page.waitForEvent('download');await page.getByRole('button',{name:button,exact:true}).click();const file=await pending;assert.equal(await file.failure(),null);return{name:file.suggestedFilename(),content:await readFile(await file.path(),'utf8')};}
 await page.getByRole('button',{name:'导出本轮报告',exact:true}).click();await page.getByLabel('选择导出原记录').waitFor();assert.equal(await page.getByLabel('选择导出原记录').inputValue(),'original-batch:old');let file=await download('下载本轮报告');assert.equal(file.name,'externallink-old-batch-ID-本轮报告.md');assert.match(file.content,/原失败/);assert.match(file.content,/原固定范围：1/);
 await page.getByLabel('选择导出原记录').selectOption('workbench:original-batch');file=await download('下载本轮报告');assert.match(file.content,/取得回执（1）/);assert.match(file.content,/待人工 \/ 待核验（1）/);assert.match(file.content,/剩余（1）/);assert.match(file.content,/原响应丢失/);assert.match(file.content,/处理游标：2/);assert.match(file.content,/等待审核/);assert.ok(file.content.includes('\n| 原产品 |'));await page.getByRole('button',{name:'关闭详情',exact:true}).click();
 await page.getByRole('button',{name:'导出执行记录',exact:true}).click();await page.getByLabel('选择导出原记录').waitFor();assert.equal(await page.getByLabel('选择导出原记录').inputValue(),'original-run:old:old-run-ID');file=await download('下载执行记录');assert.deepEqual(JSON.parse(file.content),originalRun);assert.equal(file.name,'externallink-old-run-ID-执行记录.json');
 await page.getByLabel('选择导出原记录').selectOption('workbench:original-batch');file=await download('下载执行记录');let record=JSON.parse(file.content);assert.equal(record.events.length,1205);assert.equal(record.events.at(-1).id,'original-log-1204');assert.equal(record.frozenCombinations.length,3);assert.doesNotMatch(file.content,/isolated-device-secret|isolated-export-local/);
 // A late response must not download a record after the user chooses another source.
 let release;const held=new Promise(resolve=>release=resolve);let enteredResolve;const entered=new Promise(resolve=>enteredResolve=resolve);await page.route('**/exportAutomationRun',async route=>{const response=await route.fetch();enteredResolve();await held;await route.fulfill({response});});let lateDownloads=0;const late=()=>lateDownloads++;page.on('download',late);await page.getByRole('button',{name:'下载执行记录',exact:true}).click();await entered;await page.getByLabel('选择导出原记录').selectOption('original-run:old:old-run-ID');release();await page.getByText('选择已变化，旧记录没有下载；请下载当前选择的记录。',{exact:true}).waitFor();assert.equal(lateDownloads,0);page.off('download',late);await page.unroute('**/exportAutomationRun');
 await page.route('**/exportAutomationRun',route=>route.fulfill({status:400,contentType:'application/json',body:JSON.stringify({ok:false,error:'原记录核验失败'})}));await page.getByRole('button',{name:'下载执行记录',exact:true}).click();await page.getByText('导出失败，原记录仍保留：原记录核验失败',{exact:true}).waitFor();await page.unroute('**/exportAutomationRun');await page.getByRole('button',{name:'关闭详情',exact:true}).click();
 await page.route('**/runExportSources',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({ok:true,sources:[]})}));await page.getByRole('button',{name:'导出本轮报告',exact:true}).click();await page.getByText('当前没有可导出的原批次或执行记录。',{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'下载本轮报告',exact:true}).count(),0);await page.unroute('**/runExportSources');
 await page.getByRole('button',{name:'关闭详情',exact:true}).click();await page.getByRole('button',{name:'恢复原执行历史',exact:true}).click();const restoredRun={runId:'restored-original',status:'stopped',tasks:{'retained-task':{taskId:'retained-task',status:'needs_manual',artifactRef:'retained-artifact'}},events:[{id:'retained-event',at:'2020-01-01',result:'保留原执行结果'}]};await page.getByLabel('原执行历史JSON文件').setInputFiles({name:'original-run.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(restoredRun))});await page.getByText('1 份原执行记录、1 条原事件。确认后保存供查看与导出。',{exact:true}).waitFor();await page.getByRole('button',{name:'确认保存原执行历史',exact:true}).click();await page.getByText('原执行历史已保存，原任务和事件编号保留。',{exact:true}).waitFor();await page.getByRole('button',{name:'确认保存原执行历史',exact:true}).click();await page.getByText('这份原历史已保存，没有重复导入。',{exact:true}).waitFor();await page.getByRole('button',{name:'查看原执行记录',exact:true}).first().click();await page.getByLabel('选择导出原记录').waitFor();file=await download('下载执行记录');assert.deepEqual(JSON.parse(file.content),restoredRun);
 await page.getByRole('button',{name:'关闭详情',exact:true}).click();const largeLedger={schemaVersion:1,order:[],runs:{}};for(let r=0;r<20;r++){const runId='large-original-'+r;largeLedger.order.push(runId);largeLedger.runs[runId]={runId,status:'paused',tasks:{},events:Array.from({length:600},(_,n)=>({id:'large-event-'+r+'-'+n,at:'2020-01-01',result:'原历史 '+('A'.repeat(1000))}))};}const largeBytes=Buffer.from(JSON.stringify(largeLedger));assert.ok(largeBytes.length>8*1024*1024);const partCalls=[];let dropFirstPart=true;await page.route('**/runHistoryUploadPart',async route=>{const body=route.request().postDataJSON();partCalls.push(body.index);const response=await route.fetch();if(dropFirstPart){dropFirstPart=false;await route.fulfill({status:502,contentType:'application/json',body:JSON.stringify({ok:false,error:'已保存分段响应丢失'})});}else await route.fulfill({response});});await page.getByRole('button',{name:'恢复原执行历史',exact:true}).click();await page.getByLabel('原执行历史JSON文件').setInputFiles({name:'large-original-ledger.json',mimeType:'application/json',buffer:largeBytes});await page.getByText('原历史预览失败：已保存分段响应丢失',{exact:true}).waitFor();await stop(web);await stop(backend);backend=await start('server.mjs');web=await start('workbench-server.mjs');await page.goto(web.endpoint+'/#access=isolated-export-local');await page.getByRole('heading',{name:'原产品',exact:true}).waitFor();await page.getByRole('button',{name:'运行任务',exact:true}).click();await page.getByRole('button',{name:'恢复原执行历史',exact:true}).click();await page.getByLabel('原执行历史JSON文件').setInputFiles({name:'large-original-ledger.json',mimeType:'application/json',buffer:largeBytes});await page.getByText('20 份原执行记录、12000 条原事件。确认后保存供查看与导出。',{exact:true}).waitFor();assert.equal(partCalls.filter(index=>index===0).length,1);await page.getByRole('button',{name:'确认保存原执行历史',exact:true}).click();await page.getByText('原执行历史已保存，原任务和事件编号保留。',{exact:true}).waitFor();await page.getByRole('button',{name:'查看原执行记录',exact:true}).click();await page.getByLabel('选择导出原记录').waitFor();file=await download('下载执行记录');assert.deepEqual(JSON.parse(file.content),largeLedger.runs['large-original-0']);await page.unroute('**/runHistoryUploadPart');
 assert.deepEqual(errors,[]);assert.equal(cloudCalls.filter(call=>call.method!=='GET').length,0);store=new Store(join(home,'outbox.sqlite'),{readOnly:true});assert.equal(store.get('paused'),true);assert.equal(store.get('workbenchBatch:original-batch').cursor,2);assert.equal(store.pendingCount(),0);assert.equal(store.exportLogs({scope,taskIds:items.map(item=>item.taskId),runIds:['original-run']}).entries.length,1205);assert.deepEqual(store.get('originalRunHistory:old').automationRunLedger.runs['old-run-ID'],originalRun);assert.equal(store.values('originalRunHistory:').length,3);const largeHistory=store.values('originalRunHistory:').find(item=>item.automationRunLedger.order.length===20);assert.deepEqual(largeHistory.automationRunLedger,largeLedger);assert.equal(store.get('task:retained-task'),null);assert.equal(store.get('activeBatchRun'),null);store.close();store=null;
 console.log(JSON.stringify({ok:true,kind:'original_report_exports_actual_services_and_downloads',executorAndWorkbenchAuthenticatedRoutes:true,originalPackedReportDownload:true,originalLedgerExactPayload:true,originalHistoryFilePreviewRestoreAndExactDownload:true,idempotentHistoryDoesNotActivateTasks:true,largeHistoryBytes:largeBytes.length,largeHistoryRuns:20,largeHistoryEvents:12000,serviceRestartAndLostPartReplyResume:true,alreadySavedPartNotResent:true,nativeFrozenCount:3,fullPersistedEvents:1205,unknownAttemptRetained:true,lateSelectionDownloadPrevented:true,errorsAndEmptyRecordsVisible:true,businessHistoryAndPendingPreserved:true,externalRequests:0,newRealSubmissions:0}));
}catch(error){console.error(serviceLogs.join('').slice(-3000));throw error;}finally{store?.close();await browser?.close();await stop(web);await stop(backend);await new Promise(resolve=>cloud.close(resolve));const absolute=resolve(home);assert.ok(absolute.startsWith(resolve(tmpdir())+sep)&&absolute.split(sep).at(-1).startsWith('el-run-export-ui-'));await rm(absolute,{recursive:true,force:true});}
