import assert from 'node:assert/strict';import http from 'node:http';
import {chromium} from 'playwright';
import {Store} from '../src/store.mjs';import {Runtime} from '../src/runtime.mjs';
import {getTargetInfo} from '../src/browser-target.mjs';
import {checkBrowserAssistant,stopBrowserAssistant} from '../src/browser-assistant.mjs';
import {workbenchScope} from '../src/workbench-sync.mjs';
let posts=0,registrations=0,lostRegistrationReply=false;
const form='<form method="POST"><label>Product name<input name="name" id="name" required></label><label>Website<input name="website" id="website" type="url" required></label><label>Email<input name="email" id="email" type="email" required></label><label>Description<textarea id="description" name="description" required></textarea></label><button type="submit">Submit Tool</button></form>';
const server=http.createServer((req,res)=>{if(req.method==='POST')posts++;res.setHeader('Content-Type','text/html');res.end(req.url==='/outer'?'<title>Iframe directory</title><iframe src="/inner"></iframe>':form);});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--disable-extensions']}),context=await browser.newContext(),page=await context.newPage(),store=new Store(':memory:'),runtime=new Runtime(store,'unused-test-home');
try{
 const profile={id:'p',name:'Original Product',url:'https://product.example',promoUrl:'https://product.example/original-promotion',fields:{Name:'Original Product',Url:'https://product.example','Business mail':'owner@example.com','Long description (250-500 words)':'A useful product for testing original form migration.'}};
 const snapshot={documents:{siteProfiles:{p:profile},cfgEmail:'owner@example.com',submissionRecords:{}},revisions:{siteProfiles:2}},runs=new Map(),remoteTasks=new Map();
 store.set('paused',true);store.set('pair',{endpoint:'https://cloud.example',workspaceId:'single-page-test'});runtime.context=context;runtime.host={startedAt:'synthetic-browser'};
 Object.defineProperty(runtime,'cloud',{value:{async request(route,input){if(route==='snapshot')return structuredClone(snapshot);if(route==='runs?view=inventory')return{runs:[...runs.values()],tasks:[...remoteTasks.values()]};if(route.startsWith('runs?runId=')){const id=decodeURIComponent(route.split('=')[1]);return{runs:runs.has(id)?[structuredClone(runs.get(id))]:[],tasks:[...remoteTasks.values()].filter(t=>t.runId===id)};}if(route.startsWith('tasks/'))return{task:structuredClone(remoteTasks.get(route.slice(6)))};if(route==='runs'&&input){assert.ok(store.values('singlePagePlan:').some(p=>p.run.id===input.run.id&&p.status==='registering'));registrations++;const run={...input.run,profile:structuredClone(snapshot.documents.siteProfiles[input.run.profileId]),mediaManifest:[]},task={...input.run.tasks[0],runId:run.id,profileId:'p',version:1,status:'needs_manual',siteStatus:'not_submitted',attentionType:'fill_only'};runs.set(run.id,run);remoteTasks.set(task.id,task);if(lostRegistrationReply){lostRegistrationReply=false;throw Error('Synthetic lost registration response');}return{ok:true,run,tasks:[task]};}throw Error('Unexpected cloud route '+route);}}});
 runtime.lease=async()=>{};runtime.synchronize=async()=>{for(const event of store.pending()){remoteTasks.set(event.taskId,event.state);store.ack(event.id);}};runtime.tick=()=>{throw Error('Fill-only panel must not start submission');};
 runtime.findPage=async task=>{for(const candidate of context.pages())if((await getTargetInfo(context,candidate))?.targetId===task.targetId)return candidate;throw Error('Original page missing');};
 const base='http://127.0.0.1:'+server.address().port;await page.goto(base+'/outer');const info=await getTargetInfo(context,page),opened=await runtime.control('sidepanelOpened',{profileId:'p',targetId:info.targetId}),input={panelId:opened.panel.id,profileId:'p',targetId:info.targetId,expectedUrl:page.url()};
 const detected=await runtime.control('sidepanelDetect',input);assert.equal(detected.frames.filter(f=>f.operable).length,1);assert.equal(registrations,0);const inner=page.frames().find(f=>f.url().endsWith('/inner'));assert.equal(await inner.locator('#name').inputValue(),'');
 const filled=await runtime.control('sidepanelFill',input);assert.equal(filled.submitted,false);assert.equal(await inner.locator('#name').inputValue(),'Original Product');assert.equal(await inner.locator('#website').inputValue(),'https://product.example/original-promotion');assert.equal(await inner.locator('#email').inputValue(),'owner@example.com');assert.match(await inner.locator('#description').inputValue(),/useful product/);assert.equal(posts,0);assert.equal(registrations,1);const task=store.get('task:'+filled.taskId);assert.equal(task.attemptBoundary,undefined);assert.equal(task.pageOwnership,'manual');assert.ok(task.actualPreparation.fields.length>=4);assert.equal(task.profileRevision,2);
 await runtime.control('sidepanelFill',input);assert.equal(registrations,1);assert.equal(posts,0);await assert.rejects(runtime.control('sidepanelFill',{...input,expectedUrl:base+'/changed'}),/跳转/);assert.equal(posts,0);
 const later=context.newPage();const second=await later;await second.goto(base+'/new-form');const target=await getTargetInfo(context,second);const secondInput={...input,targetId:target.targetId,expectedUrl:second.url()};lostRegistrationReply=true;await assert.rejects(runtime.control('sidepanelFill',secondInput),/lost registration/);const count=registrations,unknownPlan=store.values('singlePagePlan:').find(p=>p.status==='registration_unknown');assert.ok(unknownPlan);
 snapshot.documents.siteProfiles.p={...profile,name:'Changed cloud product',promoUrl:'https://product.example/new-promotion',fields:{...profile.fields,Name:'Changed cloud product'}};snapshot.revisions.siteProfiles=7;
 const recovered=await runtime.control('sidepanelFill',secondInput);assert.equal(recovered.submitted,false);assert.equal(registrations,count);assert.equal(await second.locator('#name').inputValue(),'Original Product');assert.equal(store.get('task:'+recovered.taskId).profileRevision,2);assert.deepEqual(store.get('task:'+recovered.taskId).profileSnapshot,profile);assert.equal(store.get('singlePagePlan:'+unknownPlan.id).status,'registered');assert.equal(recovered.runId,unknownPlan.run.id);assert.equal(posts,0);
 assert.equal(await second.locator('#website').inputValue(),'https://product.example/original-promotion');
 const third=await context.newPage();await third.goto(base+'/new-promotional-form');const thirdTarget=await getTargetInfo(context,third),newFill=await runtime.control('sidepanelFill',{...input,targetId:thirdTarget.targetId,expectedUrl:third.url()});assert.equal(newFill.submitted,false);assert.equal(await third.locator('#website').inputValue(),'https://product.example/new-promotion');assert.equal(await third.locator('#name').inputValue(),'Changed cloud product');assert.equal(store.get('task:'+newFill.taskId).profileRevision,7);assert.equal(registrations,count+1);assert.equal(profile.fields.Url,'https://product.example');assert.equal(posts,0);
 const scope=workbenchScope(store.get('pair'));store.set('applicationSnapshot',{scope,snapshot});store.set('browserAssistantSettings',{scope,enabled:true,autoFillOnVisit:true,profileId:'p'});const dispatched=[];runtime.dispatchControl=async(action,input)=>{dispatched.push(action);return runtime.control(action,input);};await checkBrowserAssistant(runtime);assert.ok(runtime.sidepanelAutoTimers?.size>0);await runtime.control('sidepanelClosed',{panelId:opened.panel.id});assert.equal(runtime.sidepanelAutoTimers.size,0);await new Promise(resolve=>setTimeout(resolve,700));assert.equal(dispatched.includes('fillAssistantTask'),false);assert.equal(store.values('assistantFill:').filter(f=>f.status==='cancelled').length,1);await stopBrowserAssistant(runtime);await assert.rejects(runtime.control('sidepanelFill',input),/关闭/);assert.equal(store.get('singlePagePanel').open,false);console.log(JSON.stringify({ok:true,kind:'synthetic_single_page_form',readOnlyDetection:true,iframeFilled:true,originalProfileFrozen:true,originalPromotionFilled:true,newPromotionOnlyInNewTasks:true,noSubmission:true,sameRegistrationRecovered:true,staleUrlRejected:true,panelClosedTimersCleared:true}));
}finally{store.close();await browser.close();await new Promise(resolve=>server.close(resolve));}
