// Isolated PostgreSQL engine acceptance. Install the fixture dependency with:
// npm install --prefix executor/test-output/timeline-pg @electric-sql/pglite@0.5.8 --ignore-scripts --no-audit --no-fund
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '../test-output/timeline-pg/node_modules/@electric-sql/pglite/dist/index.js';
import {executorApi} from '../../cloud/worker/src/executor-api.mjs';
import {timelineDocumentKeys} from '../../core/original-timeline-mutation.mjs';
const db=new PGlite();let transactions=0,beforeTransaction;
const parameter=value=>Array.isArray(value)?'{'+value.map(item=>JSON.stringify(String(item))).join(',')+'}':value;
const sql=(strings,...values)=>{const text=strings.reduce((out,string,index)=>out+(index?'$'+index:'')+string,''),params=values.map(parameter);return{text,params,then(resolve,reject){return db.query(text,params).then(result=>result.rows).then(resolve,reject);}};};
sql.transaction=async queries=>{transactions++;await beforeTransaction?.();return db.transaction(async tx=>{const result=[];for(const query of queries)result.push((await tx.query(query.text,query.params)).rows);return result;});};
const helpers={async listSnapshot(){const rows=await sql`select document_key,data,revision from externallink_workspace_documents where workspace_id='one'`;return{documents:Object.fromEntries(rows.map(row=>[row.document_key,row.data])),revisions:Object.fromEntries(rows.map(row=>[row.document_key,Number(row.revision)]))};}};
const env={APP_ACCESS_TOKEN:'fixture-admin'},call=async(route,token,body,workspace='one')=>{const r=await executorApi(new Request('https://fixture.example/v1/executor/'+route,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})}),env,sql,workspace,helpers);return{status:r.status,data:await r.json()};};
try{
 await db.exec(await readFile(new URL('../../cloud/worker/schema.sql',import.meta.url),'utf8'));await sql`insert into externallink_workspaces(workspace_id) values('one'),('other')`;
 const enrollment=await call('devices','fixture-admin',{});assert.equal(enrollment.status,200);const token=enrollment.data.deviceToken;
 assert.equal((await call('workspace/timeline','wrong',{event:{}})).status,401);assert.equal((await call('workspace/journal-documents',token,undefined,'other')).status,401);
 const docs={siteProfiles:{p:{id:'p',name:'原产品'},q:{id:'q',name:'新产品'}},submissionRecords:{original:{status:'success',evidence:'保留原收件',taskId:'original-task'}},submissionTimeline:{}};
 for(const [key,data]of Object.entries(docs))await sql`insert into externallink_workspace_documents(workspace_id,document_key,data) values('one',${key},${JSON.stringify(data)}::jsonb)`;
 const event={id:'original-event',profileId:'p',profileName:'原产品',destinationKey:'directory.example/submit',destinationUrl:'https://directory.example/submit',type:'submitted',status:'submitted',note:'收到站方回执 ABC123',occurredAt:'2026-10-07T00:00:00.000Z',source:'manual',confirmedBy:'manual'};
 assert.equal((await call('workspace/timeline',token,{event})).status,200);let snap=(await call('workspace/journal-documents',token)).data;assert.equal(snap.documents.submissionRecords['directory.example/submit::p'].evidence,event.note);assert.equal(snap.documents.timelineSchemaVersion,1);assert.equal(snap.documents.submissionSchemaVersion,2);
 const firstRevisions=structuredClone(snap.revisions),firstAudit=Number((await sql`select count(*) n from externallink_timeline_revisions`)[0].n);assert.equal((await call('workspace/timeline',token,{event})).status,200);snap=(await call('workspace/journal-documents',token)).data;assert.deepEqual(snap.revisions,firstRevisions);assert.equal(Number((await sql`select count(*) n from externallink_timeline_revisions`)[0].n),firstAudit);
 assert.equal((await call('workspace/timeline',token,{event:{...event,note:'different'}})).status,409);
 const operation={type:'timeline',id:'move-original',at:'2026-10-07T01:00:00.000Z',action:'update',eventId:event.id,patch:{profileId:'q',profileName:'新产品',type:'published',status:'published',publicUrl:'https://directory.example/post',note:'人工确认上线'}};
 let result=await call('library',token,{operation,revision:snap.revisions.submissionTimeline,revisions:Object.fromEntries(timelineDocumentKeys.map(key=>[key,snap.revisions[key]||0]))});assert.equal(result.status,200,JSON.stringify(result.data));snap=(await call('workspace/journal-documents',token)).data;assert.equal(snap.documents.submissionTimeline['directory.example/submit::p'],undefined);assert.equal(snap.documents.submissionTimeline['directory.example/submit::q'][0].id,event.id);assert.equal(snap.documents.submissionRecords['directory.example/submit::p'].evidence,event.note);assert.equal(snap.documents.submissionRecords['directory.example/submit::q'].publicationStatus,'published');assert.deepEqual(snap.documents.submissionRecords.original,docs.submissionRecords.original);
 const before=structuredClone(snap);let injected=false;beforeTransaction=async()=>{if(injected)return;injected=true;await sql`update externallink_workspace_documents set data=data||' {"concurrent":{"evidence":"other client"}}'::jsonb,revision=revision+1 where workspace_id='one' and document_key='submissionRecords'`;};
 result=await call('library',token,{operation:{...operation,id:'concurrent-attempt',patch:{...operation.patch,note:'待修改'}},revision:before.revisions.submissionTimeline,revisions:Object.fromEntries(timelineDocumentKeys.map(key=>[key,before.revisions[key]||0]))});assert.equal(result.status,409,JSON.stringify(result.data));beforeTransaction=null;snap=(await call('workspace/journal-documents',token)).data;assert.deepEqual(snap.documents.submissionTimeline,before.documents.submissionTimeline);assert.equal(snap.documents.submissionRecords.concurrent.evidence,'other client');
 const records=structuredClone(snap.documents.submissionRecords);result=await call('library',token,{operation:{type:'timeline',id:'remove',at:'now',action:'remove',eventId:event.id},revision:snap.revisions.submissionTimeline,revisions:Object.fromEntries(timelineDocumentKeys.map(key=>[key,snap.revisions[key]||0]))});assert.equal(result.status,200);snap=(await call('workspace/journal-documents',token)).data;assert.deepEqual(snap.documents.submissionTimeline,{});assert.deepEqual(snap.documents.submissionRecords,records);assert.deepEqual((await sql`select operation from externallink_timeline_revisions order by revision_id`).map(row=>row.operation),['created','updated','deleted']);
 assert.equal((await call('workspace/timeline',token,{event:{...event,id:'common',profileId:'__destination__',type:'published',status:'published'}})).status,200);snap=(await call('workspace/journal-documents',token)).data;assert.deepEqual(snap.documents.submissionRecords,records);assert.ok(snap.documents.submissionTimeline['directory.example/submit::__destination__']);
 console.log(JSON.stringify({ok:true,kind:'authenticated_neon_api_with_isolated_postgresql_engine',originalProductMove:true,commonDestinationEvent:true,originalReceiptsPreserved:true,duplicateRevisionsAndAuditUnchanged:true,concurrentLedgerChangeRollsBackAllDocuments:true,removeRetainsLedgerAndAudit:true,unauthorizedAndOtherWorkspaceRejected:true,transactions,productionNeonRequests:0,newRealSubmissions:0}));
}finally{await db.close();}
